### ISSUE TITLE
no btrfs controller in Device Manager

### ISSUE THREAD

**Issue by kamilmirza** [maharmstone/btrfs#100]
installed successfully but shows no **_btrsfs controller_** under **_Storage Controllers_** 
btrfs.sys is present in drivers folder and in registry, tried reboot
have added DWORD(32) in btrfs/Mappings key with my user SID and UID(1000) 
can UAS be the problem? have btrfs in USB drive acting as USB Attach SCSI 
but no drive shows up in my computer and **_Disk Management_** show the drive without any letter

**Comment by kamilmirza** [comment]
have to reboot in TEST SIGNING MODE to use btrfs
in normal mode btrfs-controller showed up with yellow exclamation 
win10x64-1803 (UEFI)

**Comment by maharmstone** [comment]
Using the latest version of the driver? That shouldn't happen, it's
signed...

**Comment by kamilmirza** [comment]
yes but it says its say

> Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)
