### ISSUE TITLE
explorer quick access

### ISSUE THREAD

**Issue by Meltd** [maharmstone/btrfs#101]
It seems you can only add one folder from btrfs volume to win10 quick access panel. Adding folders from other volumes works fine.

**Comment by maharmstone** [comment]
I've not heard of the Quick Access panel before. Could you send me a
screenshot please?

**Comment by Meltd** [comment]
4 icon. If i delete pinned folder i can add another. And as i said folders from ntfs volumes work fine.
![q](https://user-images.githubusercontent.com/9748606/43326358-546e0370-91c1-11e8-94d1-2411771760ea.PNG)

**Comment by Atemu** [comment]
![It's this menu](https://user-images.githubusercontent.com/18599032/43328989-a4e5495a-91bf-11e8-8a97-1b3258efb11d.PNG)

You can drag and drop directories to it to pin them but when you drag a second BTRFS directory or subvol, nothing happens.

**Comment by Zero3K** [comment]
I hope that this issue is fixed soon.

**Comment by maharmstone** [comment]
Fixed in current master - most likely by https://github.com/maharmstone/btrfs/commit/825bd546247b5b5d16598c1217c73a1f3388e235.
