### ISSUE TITLE
Getting a partition mounted

### ISSUE THREAD

**Issue by elliotclee** [maharmstone/btrfs#108]
I installed WinBtrfs and successfully had it mounting a btrfs volume. Then I converted an ext4 partition to btrfs in Linux and changed it to MBR partition type 7, but that second partition didn't get mounted. It probably didn't help that ext2fsd was still trying to mount that partition, either.

I've turned off ext2fsd, and tried deleting the btrfs registry entries, etc. and reinstalling the windows btrfs driver, but now neither of my btrfs partitions get mounted. diskmgmt.msc doesn't help at all - it thinks the partitions are of type RAW.

How can I make Windows look again at the partitions and recognize them as btrfs?

**Comment by elliotclee** [comment]
I uninstalled WinBtrfs the proper way (see https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver ) and after installing WinBtrfs again, I was back to the original situation of having the one partition on E: but no drive letter for the other partition.

Even though the second partition shows up in diskmgmt it doesn't show up as having a drive letter. My solution was to use mountvol to try assigning drive letters to all the volumes that didn't have them, and eventually I found one of those that was the btrfs volume I was looking for.

**Comment by elliotclee** [comment]
I guess the two specific things I'm asking for here are:
* A user-friendly uninstall method (Control Panel -> Apps)
* A user-friendly way of assigning drive letters to winbtrfs volumes

**Comment by Zero3K** [comment]
I am able to get the BTRFS formatted VHD Image used by VirtualBox to show up with no issues when I mount it via Simple VHD Manager.

**Comment by maharmstone** [comment]
Closing old issues
