### ISSUE TITLE
zstd Support

### ISSUE THREAD

**Issue by HaoZeke** [maharmstone/btrfs#112]
I have a veracrypt encrypted btrfs storage device with zstd compression. However, after decrypting it, I am not able to acess it. What other logs should I provide?

Currently it simply shows:

> 'Drive Is Not Accessible. The Parameter Is Incorrect

**Comment by maharmstone** [comment]
Zstd isn't yet supported - it's only been in Linux for a few months. Veracrypt works otherwise though.

**Comment by Zero3K** [comment]
It looks like its been implemented as part of today's changes.

**Comment by maharmstone** [comment]
Zero's right - it'll be in the next version.
