### ISSUE TITLE
 Blue screen with SYSTEM_SERVICE_EXCEPTION

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#113]
When I am copying around 20 GB of files from a NTFS formatted drive to a 20 GB BTRFS formatted VHD, it crashes with a SYSTEM_SERVICE_EXCEPTION BSOD when 15-18 GB of the files are copied. A minidump compressed as a ZIP file is attached.

[092918-15625-01.zip](https://github.com/maharmstone/btrfs/files/2431018/092918-15625-01.zip)

**Comment by maharmstone** [comment]
Same issue as https://github.com/maharmstone/btrfs/issues/121
