### ISSUE TITLE
installation cannot be done on latest version of windows

### ISSUE THREAD

**Issue by mispp** [maharmstone/btrfs#114]
The following happens:

```
C:\Data\btrfs-1.0.2>Pnputil.exe -a btrfs.inf
Microsoft PnP Utility

Processing inf :            btrfs.inf
Adding the driver package failed : A problem was encountered while attempting to add the driver to the store.


Total attempted:              1
Number successfully imported: 0
```

Same happens with right-click -> install.

**Comment by zeg** [comment]
same error

`
Fault bucket , type 0
Event Name: PnPDriverImportError
Response: Not available
Cab Id: 0

Problem signature:
P1: x64
P2: E0000247
P3: btrfs.inf
P4: 33032e304608d6cd328b42cc9dfee076dd760551
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_x64_e0c2a48267b3cf3d7d19d395fa65a14a0c198c6_00000000_26574360

Analysis symbol: 
Rechecking for solution: 0
Report Id: 84a7e72d-24af-4ad3-86d0-d4087eff9d9a
Report Status: 4
Hashed bucket: 
`

**Comment by redman684** [comment]
Same issue here. Also the pnputil.exe and RUNDLL32.EXE approaches found in this issue board both fail.

I inspected the  publishers certificate and noticed it's valid until 11/08/2018 (I believe this is 11 August, not 8 November)

I set my system time to somewhere in May 2018 and the install finishes without the error.

**Comment by a-jacobo** [comment]
You can install the drivers by temporarily disabling the driver signature enforcement. To do it you have to go to Change Advanced Startup Options and then:
   Click Advanced options.
   Click Startup Settings.
   Click on Restart.
   On the Startup Settings screen press 7 or F7 to disable driver signature enforcement.

After it restarts you can install the drivers and restart again to re-enable the signature enforcement.

**Comment by mispp** [comment]
@a-jacobo thanks for the workaround!

but generally, can this be fixed, or there is some issue with signing of the driver? if i remember, there are some complications for issues certs to individuals, so companies have to sign them, but have no idea how it was done initially here.

**Comment by NatoBoram** [comment]
Personally, I get this error when I try to install it.

![image](https://user-images.githubusercontent.com/10495562/47952870-3422bb00-df4c-11e8-9ccb-69eefc5cb2a9.png)

**Comment by ServidoresJMG** [comment]
hello despite making the necessary arrangements so that the driver is installed does not mount the disks.
this is tested with 1.0, 1.0.1, and 1.0.2
any solution from the programmer?

**Comment by Atemu** [comment]
@ServidoresJMG have you tried it with [1.1](https://github.com/maharmstone/btrfs/releases/tag/v1.1)?

**Comment by SergeGautherie** [comment]
Duplicated by #116?
