### ISSUE TITLE
Not working on Current Win10 (1809 Pro/X64) : Installs but fails in all cases

### ISSUE THREAD

**Issue by dmiller423** [maharmstone/btrfs#117]
Microsoft Windows 10 Pro
10.0.17763 Build 17763  (1809)

Existing btrfs partitions aren't mounted. 
I've also tried formatting from windows: Set part type to ms data,  format with /fs:btrfs  or mkbtrfs  result is an _immediate_ success,  but isn't mounted and complains about formatting on access.

I've gone through everything I can find in existing issues etc,  there really isn't any error reporting to diagnose what is going that I can find.  The driver is clearly loaded or the userland binaries would fail, I would imagine.

**Comment by G-Bigo** [comment]
Should be solved in WinBTRFS v1.1. At least mkbtrfs on an external (eSATA) RAID volume worked for me. Volume is correctly mounted and R/W accessible.

**Comment by maharmstone** [comment]
Closing old issues
