### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by kika123** [maharmstone/btrfs#12]
Adding official ARM support for Winbtrfs, it works already after adding an ARM sln config

**Comment by maharmstone** [comment]
Really? Even if it compiles, I very much doubt it will work - the code does no endian-checking at all at the moment.

**Comment by kika123** [comment]
ARM supports both little and big-endian modes

**Comment by kika123** [comment]
Windows RT 8.1 is little-endian, by the way

**Comment by maharmstone** [comment]
That'd make things easier then! Thanks for telling me about this - let me do some testing with my Raspberry Pi, and if I don't have any problems I'll include an ARM binary with the next release.
