### ISSUE TITLE
Hiawatha 9.15 gives an error when ran

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#120]
Download URL: https://www.hiawatha-webserver.org/files/hiawatha-9/hiawatha-9.15.zip

When I try to run it after moving its folder to the root directory on a BTRFS formatted drive, it gives me an error stating "C:\Hiawatha\config: Not a directory".

**Comment by Zero3K** [comment]
Its being ran in ReactOS.

**Comment by maharmstone** [comment]
You probably want to log it with ReactOS, then - this is a Windows driver which ReactOS happens to use, not a ReactOS driver. I can only accept bugs which manifest on Windows and on a clean filesystem.
