### ISSUE TITLE
BSOD while extracting an archive larger than (or near) the remaining disk space on BTRFS

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#121]
When I try to do that by extracting a large archive file via 7-ZIP (one that is 500+ MB), the speed will slowly decrease when it reaches 100% until I get a BSOD mentioning IO BOOST. I used Windows 10 64-bit when it happened. When I use the latest master of ReactOS, I get a bunch of the following errors:

Btrfs ERR : insert_extent : alloc_chunk returned c00000e5
Btrfs ERR : do_write_file : insert_extent returned c00000e5
Btrfs ERR : write_file2 : do_write_file returned c00000e5
Btrfs ERR : write_file : write_file2 returned c00000e5
(/cc/copy.c:218) IoPageWrite failed, Status c00000e5
Freed dirty VACB

Followed by a (ULONG_PTR)Entry % POOL_BLOCK_SIZE == 0 BSOD.

**Comment by Zero3K** [comment]
I had a similar error occur when I did the following (but instead of an IO BOOST error, I get a SYSTEM_SERVICE_EXCEPTION error):

1. Create a 1 GB VHD file that is a fixed size.
2. Attach it via Disk Management.
3. Format it from RAW to BTRFS by cancelling the prompt asking to format and formatting via the command line with format DRIVE /fs:BTRFS.
4. Copy a 600-650 MB file to it.

A mini dump is attached in a ZIP archive.

[111118-16125-01.zip](https://github.com/maharmstone/btrfs/files/2569521/111118-16125-01.zip)

**Comment by Zero3K** [comment]
Is there anything else you need?

**Comment by maharmstone** [comment]
Thank you. There issues is that alloc_chunk is causing a BSOD when it fails at a certain point - it should be fixed by https://github.com/maharmstone/btrfs/commit/a3b4d349bf81ac43c9ba7083fd4aa948771c695d.

Fortunately both your minidumps are the same bug.

**Comment by Zero3K** [comment]
Thanks for fixing it. Can you please merge the changes you made recently and in the past few days to its source in ReactOS's source soon?

**Comment by maharmstone** [comment]
Nothing to do with me - you'll have to ask them.

**Comment by Zero3K** [comment]
Oh, okay.
