### ISSUE TITLE
Cannot mount BTRFS formatted VMWare Disk Image

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#124]
When I try to do so, it tells me that it can't read the volume information contained in it. I am using VMWare Workstation Player 15.

**Comment by maharmstone** [comment]
I'm afraid I can't do anything about any of your issues unless you post the output of `btrfs check` on Linux, as I've requested. Anything you post without that will be summarily closed in future. Sorry.

**Comment by Zero3K** [comment]
I don't use Linux. I use Windows.

**Comment by maharmstone** [comment]
http://www.knopper.net/knoppix/index-en.html

**Comment by Zero3K** [comment]
Its a VMWare Image. How do I mount it in Knoppix?

**Comment by Zero3K** [comment]
The VMWare Image is a fresh one with no corruption in the BTRFS file system.

**Comment by Zero3K** [comment]
The btrfs command is missing in Knoppix.

**Comment by Zero3K** [comment]
Can you please re-open it since I gave you the information you asked for? It'll be nice to get it working for people who use VMWare Workstation Player.
