### ISSUE TITLE
BSOD when trying to delete the BTRFS volume of a mounted VHD

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#125]
When I do that with Driver Verifier enabled, I get a BSOD mentioning IO VIOLATION. The analysis of the BSOD is available in the attached text file.

[btrfs_bsod_analysis.txt](https://github.com/maharmstone/btrfs/files/2592123/btrfs_bsod_analysis.txt)

**Comment by maharmstone** [comment]
Fairly sure this is the same issue as https://github.com/maharmstone/btrfs/issues/111.
