### ISSUE TITLE
Issue with creation of large file when 30-40% of BTRFS partition is in use

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#127]
When I try to make a 512 MB page file in ReactOS after applying the latest two changes you made that I made into a patch, I get a bunch of the following errors:

(tem/smss/pagefile.c:470) SMSS:PFILE: NtCreatePagingFile (\??\C:\pagefile.sys, 1F000000, 20000000) failed with C0000034
Btrfs ERR : alloc_chunk : not enough free space found (stripe_size == 0)
Btrfs ERR : insert_prealloc_extent : alloc_chunk returned c000007f
Btrfs ERR : extend_file : insert_prealloc_extent returned c000007f
Btrfs ERR : file_create2 : extend_file returned c000007f
Btrfs ERR : file_create : file_create2 returned c000007f

Even though I have plenty of free space according to the attached screenshot:

![virtualbox_reactos btrfs test _17_11_2018_17_48_02](https://user-images.githubusercontent.com/6194332/48666489-0469cc00-ea91-11e8-873c-c7c574bf4d83.png)

**Comment by maharmstone** [comment]
I've already told you, I'm not accepting bugs to do with ReactOS. How do I know the issue isn't with ReactOS?

**Comment by Zero3K** [comment]
I'll test it in Windows and see what happens. The File System is clean since I just installed ReactOS in it.

**Comment by Zero3K** [comment]
It would be nice if I could try helping you fix this bug by being given a link to a compiled build with the latest changes before the next version comes out.

**Comment by Zero3K** [comment]
I tried using AppVeyor on a fork of it. When using Visual Studio 2017 as the selected environment, I get the following:

https://ci.appveyor.com/project/Zero3K/btrfs/builds/20440709/messages

**Comment by Zero3K** [comment]
He won't do it though since its not an issue with the actual driver.
