### ISSUE TITLE
Issue with compiling it with Visual Studio 2015 Community Edition

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#128]
When I try using it, it gives an error of the "windowskernelmodedriver10" build tools missing even though I installed the Windows 10 Software and Driver Development Kits.

**Comment by Zero3K** [comment]
My question was valid though.

**Comment by maharmstone** [comment]
How to set up MSVC is not an issue with this project.

**Comment by Zero3K** [comment]
How else do I get help? I already tried searching Google (which didn't help).
