### ISSUE TITLE
Another BSOD happened when copying over a large file along with some smaller files

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#131]
I tried replicating the crash I had earlier on my PC (which is running Windows 10 x64 Version 1803) with one compiled from the latest source (I used a Windows 10 development VM provided by Microsoft). I didn't get that BSOD but I got another one instead. It was a RESOURCE_NOT_OWNED BSOD (also, before that, I got some errors mentioning that I needed more space in order to copy them over even though I was copying 800-900 MB of files to a 1 GB VHD formatted as BTRFS from a RAW drive while running Windows 10). I am attaching the Minidump compressed as a ZIP archive.

[112518-9359-01.zip](https://github.com/maharmstone/btrfs/files/2613199/112518-9359-01.zip)

**Comment by Zero3K** [comment]
@maharmstone are you able to replicate it or not?

**Comment by Zero3K** [comment]
Why the thumbs down emoji?

**Comment by Zero3K** [comment]
I was able to replicate it in a VM just a few minutes ago.

**Comment by Zero3K** [comment]
What else can I do to help get it fixed?

**Comment by Zero3K** [comment]
Has it been fixed yet?

**Comment by maharmstone** [comment]
Closing old issues
