### ISSUE TITLE
Another BSOD just happened

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#134]
It was a SYSTEM_SERVICE_EXCEPTION that just happened randomly (I was doing nothing with a BTRFS formatted drive when it happened). The mini dumps that were generated are attached as a ZIP archive.

[Minidumps.zip](https://github.com/maharmstone/btrfs/files/2623129/Minidumps.zip)

**Comment by Zero3K** [comment]
What else can I do to help get it fixed?

**Comment by Zero3K** [comment]
Has it been fixed?

**Comment by l33tlinuxh4x0r** [comment]
I have had that BSOD and the following BSOD "pfn list corrupt" I am using 1903 build of windows 10 and it is very unstable. It was working much better with older versions of windows however I'm not going to downgrade.

**Comment by Zero3K** [comment]
> 
> 
> It was a SYSTEM_SERVICE_EXCEPTION that just happened randomly (I was doing nothing with a BTRFS formatted drive when it happened). The mini dumps that were generated are attached as a ZIP archive.
> 
> [Minidumps.zip](https://github.com/maharmstone/btrfs/files/2623129/Minidumps.zip)

I haven't had it occur yet under Windows 7 when using v1.2.1 of it.

**Comment by l33tlinuxh4x0r** [comment]
I turned off XMP in my bios and things seem to be a lot more stable now.
