### ISSUE TITLE
external hdd save removing

### ISSUE THREAD

**Issue by rox4d** [maharmstone/btrfs#136]
After trying to remove external hdd (esata or usb2 no matter) by "USB Safely Remove" utility, hdd are not disappearing  from a system (and continues rotation, volume starts to be inaccessible),  windows (win7 amd64) are unable to shutdown PC after that.

**Comment by G-Bigo** [comment]
Confirmed. Simply disconnecting immediately causes BSOD. Only chance is shutting PC completely down and then switching off / disconnecting external device.

**Comment by maharmstone** [comment]
Closing old issues
