### ISSUE TITLE
Expose exclusive and shared disk usage to the user

### ISSUE THREAD

**Issue by Atemu** [maharmstone/btrfs#138]
Currently the user can see total uncompressed disk usage in the general tab after "size on disk" and compressed total usage in the btrfs properties tab after "size on disk" but not the shared or exclusive usage which `btrfs filesystem du` would show on Linux:

```
     Total   Exclusive  Set shared  Filename
  18.74GiB    18.74GiB       0.00B  /var/lib/machines/win10.img
```

Being able to see these values would be very helpful.

**Comment by maharmstone** [comment]
Closing old issues
