### ISSUE TITLE
Possible error in ubtrfs.c

### ISSUE THREAD

**Issue by ameisen** [maharmstone/btrfs#141]
I've been going through the codebase and cleaning it up (moving to a more modern version of C, and also moving some of it to C++, and making sure it compiles under MSVC and Clang).

I noticed in btrfs.c line 686:

` sblen = sizeof(sb);`

where 'sb' is:

`superblock* sb;`

I'm not 100% sure (since I didn't write this code), but I am fairly confident that that is intended to be:

`sblen = sizeof(*sb);`

as it seems unlikely that you wanted to get the size of a pointer.

I doubt that this causes any issues due to the lines thereafter:

`if (sblen & (sector_size - 1))
    sblen = (sblen & sector_size) + sector_size;`

... as sblen is being aligned to the sector_size, so it would only potentially cause a problem if sector_size were for some reason smaller than the size of a superblock object. Should still probably be fixed.

As far as my (sleep-deprived) brain can tell, the entire block can be rewritten without any branches:

`ULONG sblen = (sizeof(superblock) + (sector_size - 1)) & ~(sector_size - 1);`

**Comment by maharmstone** [comment]
Thank you, you're quite right. Fixed: https://github.com/maharmstone/btrfs/commit/a90bba724beed9c101a50a6ec2a5f6b3ddab4303

Could you please e-mail me the details of exactly what you're planning? I'm a bit wary of any large-scale refactorings at this stage, on the grounds that "it ain't broke". MSVC 2015 is what I use to compile, so there should be no issues there...

**Comment by ameisen** [comment]
There is a similar issue further down in the file at line 1007.

I can e-mail, though it's more for my personal use and tinkering. The changes to the actual design/behavior of the driver are minimal, it's is purely refactoring/modernization of the code. There are some changes in support between 2015 and 2017 (which is the current public version), though they both support the LLVM plugin which can be used as well via Clang (and works better than MinGW-GCC, generally). I wasn't planning on submitting a pull request with these changes simply because they'd be... difficult to go over. I was hoping just to see better code generation.

I can e-mail it to you or a link to the fork if you're just curious to look at it, though. I've migrated mkbtrfs to C++, ubtrfs is cleaned up to semi-modern C (MSVC's C support is lacking, so I can't really use C11), though I plan on changing that to C++. Haven't touched shellbtrfs yet, and have only lightly touched the driver itself. I'm wary of sweeping changes in the driver itself, and plan on only refactoring/migrating things that have fairly localized/obvious behavior.

When I'm done with the current finishing up in ubtrfs, I'm going to go over my changes and take account of any other issues that I may have noticed and at least submit them as fixes. I am unsure if a few things are bugs or not (is `BOOL` with a value that isn't `1` going to be handled currently by WinAPI?), though.

**Comment by ameisen** [comment]
Just a note that I found a few memory/resource leaks in the shell source files. I haven't gone over the driver itself, yet.

Since I found them during a refactoring... it's difficult for me to make a simple patch. I need to figure out the best approach there.

**Comment by SergeGautherie** [comment]
> Fixed: a90bba7

Shouldn't this issue be closed then?

> `ULONG sblen = (sizeof(superblock) + (sector_size - 1)) & ~(sector_size - 1);`

Please, submit a PR, if wanted.

> memory/resource leaks

If you can't submit PRs, then file issues, so someone else can look into them?

**Comment by ale5000-git** [comment]
@ameisen: Why not create a separate ticket for every memory/resorce leak?
