### ISSUE TITLE
GUI for viewing / managing BTRFS

### ISSUE THREAD

**Issue by G-Bigo** [maharmstone/btrfs#143]
Maybe it's a dummy question, however I haven't found anything on Google.

Cite from the WinBTRFS description:
»The DLL file **shellbtrfs.dll** provides the GUI interface«

But ... how do I get a running BTRFS GUI from this DLL?

As mentioned rundll32.exe can perform some actions at command line level, but even there without any useful feedback. Any Windows online partition manager I know of (including but not limited to Acronis Disk Director, O+O Partition Manager, EaseUS Partition Master) shows BTRFS volumes as 'unformated' and thus actually is rather dangerous than simply useless in this case (DON'T click the 'Format' button ...).

I'ld really love something like a GUI correctly showing (and if possible managing) BTRFS volumes from within a running Windows system.

If this question is stupid / answered elsewhere: Sorry! Anyway, I'll be glad for any hints.

**Comment by Foltik** [comment]
Not sure, but I think this is the menu shows up when you right click a drive and select properties, then go to the BTRFS tab in explorer.

**Comment by G-Bigo** [comment]
Here we go! Thanks, that was fast and exactly to the point.

**Comment by SergeGautherie** [comment]
@G-Bigo, can you close this answered issue? Thanks.

**Comment by G-Bigo** [comment]
Done. Sorry, didn’t notice the close button after my answer last year.

 

Von: Serge Gautherie <notifications@github.com> 
Gesendet: Mittwoch, 18. September 2019 18:08
An: maharmstone/btrfs <btrfs@noreply.github.com>
Cc: G-Bigo <it@art-promo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [maharmstone/btrfs] GUI for viewing / managing BTRFS (#143)

 

@G-Bigo <https://github.com/G-Bigo> , can you close this answered issue? Thanks.
