### ISSUE TITLE
What is the CompressType zstd?

### ISSUE THREAD

**Issue by gyurmogyuri** [maharmstone/btrfs#145]
### What is the CompressType zstd?

This is in  the **readme**:
`CompressType (DWORD): set this to 1 to prefer zlib compression, and 2 to prefer lzo compression. The default is 0, which uses lzo compression if the incompat flag is set, and zlib otherwise.`

I don't know how can I defined the zstd?   `CompressType 3`?

Thank's I wait for answer.

**Comment by theChaosCoder** [comment]
See https://github.com/maharmstone/btrfs/issues/72
It's on the todo list.

**Comment by gyurmogyuri** [comment]
Thanks
