### ISSUE TITLE
option to format BTRFS in windows

### ISSUE THREAD

**Issue by ServidoresJMG** [maharmstone/btrfs#146]
it would be interesting to be able to format from windows in BTRFS with the same as the options NTFS, Fat etc.

Some idea or solution for windows to format without having to go to format them by linux

**Comment by Atemu** [comment]
>* How do I format a partition as Btrfs?
>
>Use the included command line program mkbtrfs.exe. We can't add Btrfs to Windows' own dialog box, unfortunately, as its list of filesystems has been hardcoded. You can also run format /fs:btrfs, if you don't need to set any Btrfs-specific options.

https://github.com/maharmstone/btrfs/blob/master/README.md#troubleshooting

**Comment by ServidoresJMG** [comment]
understood, but it could be put it in the tab of utilities of BTRFS, in the properties of the disk as they put the other options.

**Comment by ale5000-git** [comment]
> You could probably make a GUI BTRFS formatting tool (maybe even as context menu entry when right clicking on a disk?)

This look like a very good idea.
