### ISSUE TITLE
Windows 7 64-bit problem with driver signature

### ISSUE THREAD

**Issue by rayshadowsun** [maharmstone/btrfs#147]
Using windows 7 x64 on old mobo so not secureboot. 
I can use the driver "winbtrfs 1.1" if I press F7 on boot and choose to disable signature enforcing but I can't make it permanent. I've tried using bcdedit, putting windows in test-mode but no luck.

**Comment by maharmstone** [comment]
If memory serves, support for the certificates in question wasn't in the initial version of Windows 7, and was patched in later by Microsoft. If you update Windows, does it fix the problem?

**Comment by rayshadowsun** [comment]
Thank you, I din't think to check haha. Did all kinds of commands and stuff lol. Well now it works. Thank you again! Great driver :D
