### ISSUE TITLE
UID GID MAPPING

### ISSUE THREAD

**Issue by itslog** [maharmstone/btrfs#148]
This is I suspect a request for clarification and not an actual problem. But I noticed when I was creating the registry entries to map some UIDs and GIDs that on the initial install the mapping for the example "S-1" = "Users" = "100" the actual number entered into modification field was "64" though it displays (100) beside the 64 in the RegEdit user interface. 
To illustrate more clearly this is what I get when I export of the Group Mapping Branch. But I am going to add #comments to label whats what

_Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\btrfs\GroupMappings]
"S-1"=dword:00000064
##^ OG entry present from install to Id all the Users as Users? as it displays (100) in the RegEditUI
"S-1-5-21-3770889400-2829634035-1529012777-1001"=dword:00000100
##^Me making sure my User was forsure a User - I simply entered 100 using Modify
"S-1-5-21-3770889400-2829634035-1529012777-500"=dword:00000000
##^Here I was planning map Administrator as root cause
"S-1-1-0"=dword:00065534
##^Here I was planning map Everyone to nobody_

I am guessing 64=100 as the result of some maths that I hav+e been blissfully ignorant of until now, if this is obvious I apologize if this is a dumb question -- but 

**Q1:** Should I be doing some sort of number conversion to get the correct number to input into the DWORD entry to get the correct result that I'm seeing in the RegEdit UI?
**Q2:** Mapping the Administrator to root and Everyone to nobody is kosher and correct? (just on the non-breaking btrfs level - not  super security I just want any admin user to be able to get at everything on btrfs & any thing public to remain public)

**Comment by maharmstone** [comment]
64 in hex is 100 in decimal... I can't say for certain, but the fact that the numbers in the REG file are eight-digits long strongly implies that they are hex.

The "Everyone" mapping is redundant, as it uses 65534 if it doesn't know what else to do. You probably want to map your normal Windows user to your Linux uid, which is probably 1000.

**Comment by mateMathieu** [comment]
> You probably want to map your normal Windows user to your Linux uid, which is probably 1000.

Hi,
How do we do this?
Thank you

**Comment by rgcv** [comment]
Hey, sorry to bump this, but I might as well add some info to this.

> How do we do this?

You can create a `DWORD` key in `HKLM\SYSTEM\CurrentControlSet\Services\btrfs\Mappings` with your user's SID.

```reg
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\btrfs\Mappings]
"<user-sid-here>"=dword:000003e8 ; 1000
```

You can use the (deprecated) `wmic` utility to easily discover which SID corresponds to your user
```cmd
> wmic useraccount get name,sid
<USERNAME> <SID>
```

You could also change the existing `GroupMappings` key for your Windows user's group to map it to your linux box user's GID too, if it isn't already.  Once again, using `wmic`, you can check which it is to make sure.

```cmd
> wmic group get name,sid
<GROUPNAME> <SID>
```

---

This is what I've done.  I tested creating a file in a `btrfs` partition on windows and checked its ownership on linux.  Seemed to work just fine :+1:

**Comment by maharmstone** [comment]
Closing old issues

**Comment by typorian** [comment]
> Hey, sorry for bumping this, but I might as well add some info.
> 
> > How do we do this?
> 
> You can create a `DWORD` key in `HKLM\SYSTEM\CurrentControlSet\Services\btrfs\Mappings` with your user's SID.
> 
> ```reg
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\btrfs\Mappings]
> "<user-sid-here>"=dword:000003e8 ; 1000
> ```
> 
> You can use the (deprecated) `wmic` utility to easily discover which SID corresponds to your user
> 
> ```batchfile
> > wmic useraccount get name,sid
> <USERNAME> <SID>
> ```
> 
> You could also change the existing `GroupMappings` key for your Windows user's group to map it to your linux box user's GID too, if it isn't already. Once again, using `wmic`, you can check which it is to make sure.
> 
> ```batchfile
> > wmic group get name,sid
> <GROUPNAME> <SID>
> ```
> 
> This is what I've done. I tested creating a file in a `btrfs` partition on windows and checked its ownership on linux. Seemed to work just fine 👍

just to make sure, does this mean the name of the dword is created by wirting "<user-sid>;<linux uid>" in the name field? I'm at a loss because I don't know windows

**Comment by rgcv** [comment]
> the name of the dword is created by writing "user-sid;linux uid"
No no, sorry! :p The extra `; 1000` is just a comment that `000003e8` is the hex value for 1000.

What is being created is a key whose name is your user SID that equals the value `dword:<linux uid in hex>`, `dword` being the type of the value, and the UID the.. well, value.

**Comment by typorian** [comment]
@rgcv Thank you so much for taking the time to respond, it makes a lot of sense when you put it like that. I think windows may not like changes to these dwords somehow, after deleting everything I did and putting it in again the way you explained it, it now works. Great! Thanks again.
