### ISSUE TITLE
Ignoring device mount option on boot.

### ISSUE THREAD

**Issue by halvors** [maharmstone/btrfs#150]
Editing the Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\btrfs\__UUID__\Mounted and set it to "0" does get ignored and set back to "1" on reboot.

**Comment by maharmstone** [comment]
By design. That's not an option, that's something the driver sets to say the FS is mounted.

**Comment by jf352** [comment]
So how do we set the driver to tell it not to mount a specific drive at boot?

**Comment by maharmstone** [comment]
Try creating a DWORD called "Ignore" and set it to 1.

**Comment by jf352** [comment]
> Try creating a DWORD called "Ignore" and set it to 1.

Wow, thanks. Feel like an idiot - read the README multiple times and completely forgot about it. Thanks for the great driver!
