### ISSUE TITLE
Issue with running a game in ReactOS on a BTRFS formatted drive

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#152]
When running Melty Blood: Actress Again - Current Code in ReactOS (latest master) on a BTRFS formatted drive, it crashes ReactOS with a memory error being reported in the debug log. It and more info can be found at https://jira.reactos.org/browse/CORE-15950.

**Comment by maharmstone** [comment]
I have told you before that I am not willing to accept bug reports regarding ReactOS. You seem to have forgotten.

**Comment by Zero3K** [comment]
* <btrfs.sys:18d02 (drivers/filesystems/btrfs/create.c:154 (find_file_in_dir))>
* <btrfs.sys:1b91a (drivers/filesystems/btrfs/create.c:1316 (open_fileref_child))>
* <btrfs.sys:1c34f (drivers/filesystems/btrfs/create.c:1524 (open_fileref))>
* <btrfs.sys:1f46e (drivers/filesystems/btrfs/create.c:3205 (drv_create))>
