### ISSUE TITLE
Error: Unable to access file - it is busy by other process.

### ISSUE THREAD

**Issue by rox4d** [maharmstone/btrfs#154]
With this release (1.2) there are seems to be issue with creating files with certain symbols in filename (win7 amd64). For example file cpu-z_1.83-en.zip can't be copyed (from ntfs), but same file named as cpu-z-1.83-en.zip are. Issue are not limited presense "_" in filename as file with name InsD2018.msi can't be copyed while a same file named as insD2018.msi are ok.
p.s. error message (in header) possible may be slightly different with EN locale (it is my translation).

**Comment by maharmstone** [comment]
If you reboot, does it still happen with the same files? If Explorer can't access a file on an NTFS volume, it's probably not a btrfs issue...

**Comment by rox4d** [comment]
I was supposing it is unhappy about destination, as it is possible to copy these files to other location at ntfs, but strange things:
1. unable copy cpu-z_1.83-en.zip
2. copy cpu-z_1.83-en.zip to cpu-z-1.83-en.zip on ntfs
3. successfuly copyed cpu-z-1.83-en.zip to btrfs
4. rename cpu-z-1.83-en.zip to cpu-z_1.83-en.zip
6. successfuly copyed cpu_z-1.83-en.zip  to btrfs
I can'`t see stranges in these file permissions  (in file properties)
p.s. reboot does not help.

**Comment by theChaosCoder** [comment]
I can confirm it. I installed v1.2 today and noticed that some files can't be copied because they are "in use". I synced my Steam folder via FreeFileSync. 

**It is not limited to files with a "_" in filename.** 

Copying to a ntfs drive of these files works. To the btrfs drive not.

I made a reboot, didn't help. The same files are "locked" if I try copy them to the btrfs partition.

My System: Win Pro 64bit (1903), Same SSD drive with 2 partitions.

**Comment by rox4d** [comment]
It is possible to copy these files through a intermediate fat32 medium.
p.s. I suppose that i saw the same behaviour with 1.1, but it was a one file created in wine and then copyed to ntfs by ntfs-3g (a much different config).

**Comment by theChaosCoder** [comment]
I think I found the problem. The file(s) has a "security bit" set (You know the evil downloaded file flag). After unchecking it no more problems.
![flag](https://user-images.githubusercontent.com/3579830/57227015-a5811a80-7010-11e9-886c-9b22d17f67f1.PNG)

**Comment by rox4d** [comment]
I can't test- there are no such file properties in windows7 (it is not means that ntfs itself has no such ability).

**Comment by maharmstone** [comment]
Thanks Chaos - it looks like you're right. I'll look into it.

**Comment by rox4d** [comment]
ops,  i missed that it exists for files with this bit set. It helps, but how to make that for large directory?

**Comment by theChaosCoder** [comment]
@rox4d This is something would also like to know. You can't even select multiple files...  -__-

**Comment by maharmstone** [comment]
Right, I tracked the problem back to https://github.com/maharmstone/btrfs/commit/3e9ba3df1ed321940cd1853fba2f3abc028a2513 from ReactOS. I've just released v1.2.1, which fixes this issue.

**Comment by rox4d** [comment]
Yes it fixed now, thanks.
