### ISSUE TITLE
FileRenameInformationEx not supported (Word can't save)

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [maharmstone/btrfs#155]
Microsoft Word 2019 cannot save to btrfs, it gives the following error.

AUTOSAVE FAILED  We have not been able to save your recent changes. Please save to a different file in order to keep all of your changes.

This happens when both updating a existing file and when creating a new file... Nothing is saved to the drive... Microsoft Excel can save files however.

I have also noticed that Godot game engine could not save to btrfs either... Every other program that I have tried seems to work correctly.

**Comment by maharmstone** [comment]
Thanks. Looks like Word is sending us a FileRenameInformationEx request, which we don't know how to handle.

**Comment by l33tlinuxh4x0r** [comment]
When you say "we" do you mean the current driver or do you mean that the developers don't know how to fix it?

**Comment by maharmstone** [comment]
I mean the current driver. It's a new thing in Windows 10.

**Comment by l33tlinuxh4x0r** [comment]
Sounds good... I look forward to a fix :)

**Comment by maharmstone** [comment]
Should be fixed by 0977f9dbd294fcefa2de66499007b9529ec46083.

**Comment by Zero3K** [comment]
Can anyone confirm that it has been fixed?

**Comment by l33tlinuxh4x0r** [comment]
There hasn't been another binary release yet. I cannot confirm as I haven't been able to test the new build yet. The fix is there but you would have to build the driver yourself or wait for a release, (I'm waiting for a release).

**Comment by mistguy** [comment]
I cannot save anything with Word, Excel or Powerpoint 2019.

**Comment by ale5000-git** [comment]
Have you tried with version 1.3?

**Comment by mistguy** [comment]
Yeah, I confirm my issue is fixed. Thank you.

**Comment by Zero3K** [comment]
That's nice. This issue should be closed since it has been fixed.
