### ISSUE TITLE
Windows is reporting no free space available

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#156]
When I attached a VHD containing a partition formatted as BTRFS, the drive that contains it is shown as NTFS with no free space available. I am using v1.2.1 of the BTRFS driver under Windows 7 SP1.

EDIT: The drive was formatted using ReactOS' setup procedure. The version of it used was 0.4.13-dev-258-g8aeb6a9.

**Comment by SergeGautherie** [comment]
I don't know about Windows behavior.
With regard to some ReactOS usecases, read some details at
https://jira.reactos.org/browse/CORE-16021

**Comment by Zero3K** [comment]
I think that it has something to do with formatting the partition as BTRFS.

**Comment by maharmstone** [comment]
I can't reproduce this on Windows 10 Pro.

**Comment by Zero3K** [comment]
So its a ReactOS issue then?

**Comment by maharmstone** [comment]
You said you were using Windows 7 - where does ReactOS come into it?

**Comment by Zero3K** [comment]
Well, the drive was formatted as BTRFS with ReactOS's setup interface.

**Comment by maharmstone** [comment]
That won't make a difference.

**Comment by Zero3K** [comment]
Then why aren't you able to reproduce it?

**Comment by Zero3K** [comment]
@maharmstone Try copying files to a drive formatted as BTRFS.

**Comment by rsw0x** [comment]
Seeing a similar issue on Windows 10 after I enabled compression.

**Comment by Zero3K** [comment]
Okay. I hope that its easy to fix.

**Comment by archeYR** [comment]
Installed ReactOS on a 2 GB VHD with Btrfs filesystem, could reproduce the issue:
![Btrfs_ReactOS](https://user-images.githubusercontent.com/32551254/58216781-2bcf7900-7d00-11e9-9ed3-7f49758ae525.png)
Then attached that VHD with ReactOS installation to a Windows Server 2019 VM, and tried to access it using WinBtrfs 1.2.1, issue still persisted:
![Btrfs_Windows](https://user-images.githubusercontent.com/32551254/58217084-73a2d000-7d01-11e9-846e-85e5b0f42a65.png)
Tried to format the another 2 GB VHD from the same Server 2019 VM, looks fine
![VirtualBox_Windows Server 2019_23_05_2019_02_05_54](https://user-images.githubusercontent.com/32551254/58217159-c54b5a80-7d01-11e9-959e-78241defc75a.png)
Both VMs have 512 MB of allocated system memory.

**Comment by binarymaster** [comment]
> Tried to format the another 2 GB VHD from the same Server 2019 VM, looks fine

@archeYR what happens if you backup all files before formatting, and after formatting copy them to Btrfs volume?

**Comment by archeYR** [comment]
@binarymaster After doing so, I noticed another weird thing...
![VirtualBox_Windows Server 2019_23_05_2019_03_05_00](https://user-images.githubusercontent.com/32551254/58218561-99cb6e80-7d07-11e9-9301-799f6bfa0585.png)

**Comment by Zero3K** [comment]
That is weird indeed.

**Comment by theChaosCoder** [comment]
My btrfs drives shows also the wrong used or free space. I copied ~500gb to it, but it shows that only less then 100gb is used. I used zstd compression. And no it was not compressed down to 100gb, zstd saved about 80gb   :-)

**Comment by SergeGautherie** [comment]
@Zero3K, could you report detailed steps to reproduce this issue on Windows? That means not using ReactOS at all. Thanks.

@archeYR, it seems your first comment belongs to the ReactOS issue, rather than here.

Please, move other misbehaviors, like "used space too low", to separates issues.

**Comment by Zero3K** [comment]
I don't know how to reproduce it on Windows since formatting a drive under it doesn't cause the same issue and I can't format it as BTRFS.

**Comment by andrewtheshiny** [comment]
I have a dual boot system. Windows 10 and Ubuntu 19.04. 

Yesterday , under Ubuntu I created a btrfs filesystem on a WD Blue 1TB drive (sudo mkfs.btrfs -f /dev/sdb) and then re-booted into Windows. I installed winbtrfs per instruction, re-booted and copied some files onto the disk. It seemed okay. 

This morning I rebooted into Windows and after a few minutes I got a popup from Windows  reporting low disk space on D (btrfs) drive. It shows 0% free. A while later Windows crashed and hung showing btrfs.sys had failed.

I've now disabled D drive with disk manager but Windows is still reporting low disk space.

Any thoughts would be appreciated.

Maybe I'll try creating another btrfs drive under Windows first. My system has two identical WD Blues.

…Andrew
![Screencap_d-drive](https://user-images.githubusercontent.com/40549794/58561575-669c4a00-81f5-11e9-8c83-02ca8387a29b.png)

**Comment by Zero3K** [comment]
So its not a ReactOS only issue then. That's not good.

**Comment by andrewtheshiny** [comment]
I started over this afternoon and formatted the disk again under U19.04 and voila, it's working fine. 

Shows up in windows. I added a disk (in windows) to make it RAID0, copied data (in windows and U1904), viewed properties, booted into U19.04 and back to Windows. No issues.

I don't what I did wrong but it seems to be okay now. 

I'm continuing to run some performance tests to see how it goes. And use it for a while.

**Comment by andrewtheshiny** [comment]
![image](https://user-images.githubusercontent.com/40549794/58587250-ea245e00-822a-11e9-852d-618c5459ba43.png)

**Comment by SergeGautherie** [comment]
> I don't what I did wrong

Guess: maybe the different sizes?
Note that, on ReactOS case, the issue seems to happen for 1/2/4/20 GiB, not 40 GiB partition/disk...

**Comment by ale5000-git** [comment]
@Zero3K
@SergeGautherie
Have you tried with version 1.3?

**Comment by Zero3K** [comment]
> 
> 
> @Zero3K
> @SergeGautherie
> Have you tried with version 1.3?

It has been fixed (for me) in v1.3. I formatted a partition as BTRFS in ReactOS (which was compiled using the source code that contains v1.3's source code) using its setup procedure and checked the free space in ReactOS. It didn't report as 0 bytes.

**Comment by SergeGautherie** [comment]
> Have you tried with version 1.3?

I confirm https://jira.reactos.org/browse/CORE-16021 is fixed.

**Comment by Zero3K** [comment]
Could this issue be closed then?

**Comment by Zero3K** [comment]
I'm going to close it since its been fixed.
