### ISSUE TITLE
Used Space is being incorrectly shown

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#157]
@binarymaster After doing so, I noticed another weird thing...
![VirtualBox_Windows Server 2019_23_05_2019_03_05_00](https://user-images.githubusercontent.com/32551254/58218561-99cb6e80-7d07-11e9-9301-799f6bfa0585.png)

_Originally posted by @archeYR in https://github.com/maharmstone/btrfs/issues/156#issuecomment-495030216_

**Comment by Zero3K** [comment]
I also noticed this issue occurring in Windows 7. A screenshot of it is as follows:

![Used Space Difference](https://user-images.githubusercontent.com/6194332/58396911-a78d3680-801c-11e9-9199-95dc5ca5f559.png)

**Comment by ROCKNROLLKID** [comment]
Does either of these issues still happen with lastest nightly of ReactOS and 1.3 update?

**Comment by Zero3K** [comment]
When using v1.3 in ReactOS:

1. The drive shows up as BTRFS.
2. The used space is still being shown incorrectly (it states 241 MB when there is more than that actually being used).

**Comment by maharmstone** [comment]
@ROCKNROLLKID - ReactOS is an unsupported operating system. We don't accept bug reports unless they show up on Windows.

@Zero3K - the difference will be sparse files or shared data. The pie chart represents what's physically on the disk, while the Properties box is all of the logical file sizes added together.

**Comment by ale5000-git** [comment]
@Zero3K: To note that ReactOS have updated only the driver to 1.3 (not the shell extension).

**Comment by Zero3K** [comment]
@maharmstone Is the pie chart reflecting the compressing of the data that is occurring?

**Comment by Zero3K** [comment]
Well?

**Comment by maharmstone** [comment]
I'm not going to waste my time looking into this if you address me like that. Closed.

**Comment by Zero3K** [comment]
Address you like what? I just wanted to know the answer to my question.
