### ISSUE TITLE
BTRFS formatted partition is showing up as NTFS formatted

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#158]
In Windows 7 when using v1.2.1 of the BTRFS driver, a BTRFS formatted partition is showing up as NTFS formatted.

**Comment by maharmstone** [comment]
Only in certain places. This is deliberate, as there's certain functions that Windows will refuse to do unless it thinks it's on NTFS.

**Comment by Zero3K** [comment]
I forgot to mention that its being reported in the drive's properties as NTFS when in the previous version it was being reported as Btrfs.
