### ISSUE TITLE
Windows 10 v1809: Installed .inf file and rebooted, but there is no btrfs tab in drive Properties menu

### ISSUE THREAD

**Issue by jdrch** [maharmstone/btrfs#159]
First of all, thanks for this project. It's very cool that we have this available at all.

On Windows 10 v1809 x64, I installed the .inf file as directed and then rebooted as prompted, but there is not btrfs tab in the Properties menu of drives when I right-click on them in File Explorer -> Properties. 

Any ideas?

**Comment by theChaosCoder** [comment]
Did you also format a drive in btrfs? It only appears on btrfs drives.

**Comment by jdrch** [comment]
> 
> 
> Did you also format a drive in btrfs? It only appears on btrfs drives.

Ah, totally forgot about that part. Is there a documentation page for the usage of mkbtrfs.exe? I don't see one on the front page. I do see the `format` command, but it's presented as an alternative to the aforesaid. What's the syntax for it? Or is `format` now the preferred command?

**Comment by theChaosCoder** [comment]
I always used format https://github.com/maharmstone/btrfs#troubleshooting

**Comment by jdrch** [comment]
> 
> 
> I always used format https://github.com/maharmstone/btrfs#troubleshooting

I wound up starting a PowerShell Admin session and using `mkbtrfs.exe` from there. It's a really cool tool.

For anyone who encounters this thread and may be wondering: if you remove a drive from btrfs and it has no letter, File Explorer doesn't see it and Disk Management won't format it: use Mini Tool Partition Wizard to delete all the partitions on it, then create a new NTFS partition with a drive letter. Worked for me.

OK so next questions: 

1. I have a 120 GB and a 250 GB HDD. How do I create a RAID1 array with them? (This should result in usable array storage of 120 GB.)
2. Assuming the above is successful, how do add further RAID1 array pairs to the same btrfs pool? e.g. 2 x 2 TB HDDs, for a total of 2.12 TB usable storage on the pool?

Hopefully those questions make sense; I realize I might be using the wrong terminology but so far just about all the btrfs documentation I've read has been quite confusing, sadly.

**Comment by Atemu** [comment]
>I have a 120 GB and a 250 GB HDD. How do I create a RAID1 array with them? (This should result in usable array storage of 120 GB.)

If the mkbtrfs.exe doesn't support creating a btrfs on multiple devices at the same time, create a btrfs on one of them, add the other device to the btrfs and start a balance with mconvert and dconvert to RAID1.  

>Assuming the above is successful, how do add further RAID1 array pairs to the same btrfs pool? e.g. 2 x 2 TB HDDs, for a total of 2.12 TB usable storage on the pool?

Just add the drives to the btrfs, done.

Just FYI, there are no array pairs, vdevs or anything there are just devices. Btrfs distributes block groups (usually 1G in size) across all available devices according to the active block group profile (e.g. single, raid1, raid10 etc).  
The RAID1 block group profile just tells btrfs that every block group should have one copy of it written to any device but the device the original is written to.

I'd highly recommend you to read https://btrfs.wiki.kernel.org/index.php/Using_Btrfs_with_Multiple_Devices.

**Comment by jdrch** [comment]
> Just FYI, there are no array pairs, vdevs or anything there are just devices. Btrfs distributes block groups (usually 1G in size) across all available devices according to the active block group profile (e.g. single, raid1, raid10 etc). The RAID1 block group profile just tells btrfs that every block group should have one copy of it written to any device but the device the original is written to.

Thanks. I admit it's taking me a while to wrap my head around btrfs paradigms. I only just got around to [fully understanding zfs' concepts earlier this week](https://www.reddit.com/r/zfs/comments/bzhb02/help_understanding_which_removal_scenarios_are/eqsgir1/), for example. I'll read that link and probably return with more questions.

**Comment by Zero3K** [comment]
I guess this issue can be closed since it was user error that was the cause of it.

**Comment by SergeGautherie** [comment]
@jdrch, can you close this answered issue? Thanks.

**Comment by jdrch** [comment]
Done! FWIW I wound up [using the 2 drives I was experimenting with in ZFS mirror](https://github.com/jdrch/Hardware/blob/master/Dell%20OptiPlex%20390%20SFF.md#zfs-on-zpool-mirror).
