### ISSUE TITLE
Cannot mount Btrfs volume from Thecus NAS

### ISSUE THREAD

**Issue by ilgrank** [maharmstone/btrfs#160]
Hi
Installed Btrfs driver 1.3.0 and can't mount a Thecus-formatted Btrfs volume.
The drive show correctly, but no filesystem is detected (Check screenshot)
<img width="567" alt="btrfs" src="https://user-images.githubusercontent.com/4583412/59553176-8f606580-8f91-11e9-801f-575fbed7ec6b.PNG">
is there something I can do/check to provide any more meaningful info to try to mount this disk Btrfs volume?

**Comment by maharmstone** [comment]
Are you able to mount it on Linux? There's a note in the readme about Synology NAS devices, could it apply to Thecus as well?

**Comment by ilgrank** [comment]
Well.. most likely you are right.. Ubuntu shows this about the disk I'm trying to mount:
<img width="567" alt="btrfs" src="https://user-images.githubusercontent.com/4583412/59556899-62c93f80-8fcb-11e9-8f59-3db3b379dd2a.PNG">
I forgot to say the disk is part of a RAID1 mirror btw
My goal was to be able to have a resilient Filesystem (hence Btrfs over EXT4 or XFS) and, in case of hardware failure of the NAS, to be able to recover the data with a regular windows or linux pc..

**Comment by maharmstone** [comment]
There you are - it's using Linux RAID, which isn't supported on Windows. You'd be better off using Btrfs' own RAID functionality, which _would_ work on Windows, but this might not necessarily be possible with your NAS.

**Comment by ilgrank** [comment]
Thanks for your kind reply @maharmstone 
Indeed, the culprit here is not Btrfs here, but it is not LVM either.
The filesystem is marked as "linux_raid" and not BTRFS, hence the problem.
Under Linux it is quite easy (using mdadm) to mount it anyways
would it be possible under Windows? (doubt, since there's no mdadm equivalent)

**Comment by ilgrank** [comment]
Technically, this is *not* btrfs driver's fault

**Comment by ale5000-git** [comment]
@ilgrank
Now there is: [WinMD](https://github.com/maharmstone/winmd) (driver for MD RAID devices) and WinBtrfs 1.4 so it may works.

**Comment by ilgrank** [comment]
Wow, thanks @ale5000-git  😍 
You made my day 😄

**Comment by maharmstone** [comment]
Does it work for you?

**Comment by ilgrank** [comment]
It is not production-ready, but being a first release, it's promising.

**Comment by maharmstone** [comment]
Great. I wasn't sure if Thecus were using write-intent bitmaps, or any of the other things I've not yet implemented. Please let me know if you have any issues with it.
