### ISSUE TITLE
BOOTLOG_NOT_LOADED \SystemRoot\system32\DRIVERS\btrfs.sys

### ISSUE THREAD

**Issue by magic0whi** [maharmstone/btrfs#162]
OS build : 18362.175
I have a Surface Pro 4, and the driver didn't loaded, no changes.
Here are some intercept content from ntbtlog.txt: 
```
BOOTLOG_LOADED \SystemRoot\System32\DriverStore\FileRepository\basicdisplay.inf_amd64_25ab9510fd18cfda\BasicDisplay.sys
BOOTLOG_NOT_LOADED \SystemRoot\System32\drivers\dxgkrnl.sys
BOOTLOG_LOADED \SystemRoot\System32\DriverStore\FileRepository\basicrender.inf_amd64_9ff437f462543a42\BasicRender.sys
BOOTLOG_NOT_LOADED \SystemRoot\system32\DRIVERS\btrfs.sys
BOOTLOG_LOADED \SystemRoot\System32\Drivers\Npfs.SYS
BOOTLOG_LOADED \SystemRoot\System32\Drivers\Msfs.SYS
BOOTLOG_LOADED \SystemRoot\system32\DRIVERS\tdx.sys
```

**Comment by maharmstone** [comment]
Have you disabled Secure Boot?

**Comment by magic0whi** [comment]
> Have you disabled Secure Boot?

I just tried it, it didn't work.

**Comment by maharmstone** [comment]
What do you get if you run "sc start btrfs" from an admin command prompt?

**Comment by magic0whi** [comment]
> What do you get if you run "sc start btrfs" from an admin command prompt?

Solved
It's very strange, when I select "Normal startup" in msconfig.exe again, and disable boot secure, it works magically.
Perhaps its both the "Use original boot configuration" checkbox option and Secure Boot together cause the driver not to load
![image](https://user-images.githubusercontent.com/28147340/60099510-5c388600-978a-11e9-9ec2-e6bc62857d89.png)
![image](https://user-images.githubusercontent.com/28147340/60099555-75d9cd80-978a-11e9-9ebe-e9b87b9fb5be.png)
