### ISSUE TITLE
Memory leak when creating and deleting the created file multiple times 

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#164]
When I run the attached batch file (which outputs the help command to a help.txt file in the root directory of the BTRFS formatted drive and deletes it and then repeats until its closed) for a few minutes, I get a dialog box stating "help.exe is not a valid Win32 application" or a "bad command or filename" message in the Command Prompt window.

[leak.zip](https://github.com/maharmstone/btrfs/files/3465333/leak.zip)

**Comment by Atemu** [comment]
>```
>@echo off
>cd \
>:loop
>help > help.txt
>del help.txt
>goto loop
>```

Mate, this is an issue tracker for a very specific piece of Kernelspace software, would you mind as
looking for help somewhere else with your general userspace scripting issue?

**Comment by Zero3K** [comment]
Huh? Its how I was able to replicate the issue I mentioned.

**Comment by Zero3K** [comment]
You can try to replicate it in a Windows 7 VM that has 512 MB of RAM associated to it.

**Comment by SergeGautherie** [comment]
See also https://jira.reactos.org/browse/CORE-15138 and related, for some more ReactOS cases/details.

**Comment by Zero3K** [comment]
> 
> 
> See also https://jira.reactos.org/browse/CORE-15138 and related, for some more ReactOS cases/details.

Please delete your comment since he'll close it because of the mention of ReactOS.

**Comment by maharmstone** [comment]
@Zero3K - is this *actually* on Windows? You've used the same wording in your ReactOS bug - I'm very sceptical that Windows and ReactOS would respond to running out of memory in the exact same way.

I can't reproduce this on Windows 10. I'm going to close this unless somebody else can reproduce this on Windows.

**Comment by Zero3K** [comment]
Well, I cannot get it to run out of memory but I do encounter the "access denied", etc. message randomly.

**Comment by maharmstone** [comment]
So it's not an issue with Windows, and I've just wasted the time I spent looking into it.
