### ISSUE TITLE
Hang occurring when formatting a FAT32 formatted VHD as BTRFS

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#165]
I got Windows 7 to hang in Windows Explorer, etc. by doing the following:

1. Make a 512 MB VHD via Disk Management (under Windows 7),
2. Choose FAT32 as the file system to format it as.
3. Run format /fs:BTRFS on the drive letter that the VHD was assigned to.
4. Press F5 in Disk Management to refresh the list of disks.

**Comment by MegaZeroX10** [comment]
Pushing the PR available at #193 should fix this issue.

**Comment by maharmstone** [comment]
No it wouldn't. That PR clearly says it's an issue on Vista and below, whereas this is Windows 7. Please do not post comments based on supposition, as it makes debugging a lot harder.

**Comment by SergeGautherie** [comment]
#193 (and much more) is committed.
Can you re-test?

**Comment by MegaZeroX10** [comment]
It doesn't occur anymore since then and the new version that was released yesterday.
