### ISSUE TITLE
lie_about_fs_type()

### ISSUE THREAD

**Issue by ale5000-git** [maharmstone/btrfs#174]
Hi,
I know this driver don't support ReactOS directly but still it would be nice if it auto disable lie_about_fs_type() on ReactOS (since it isn't needed)
or alternatively it would be nice to have a registry setting to do it manually (without recompile the code).

**Comment by vayne3k** [comment]
I agree with this suggestion.

**Comment by maharmstone** [comment]
Is there an easy way to easily tell whether we're on Windows or ReactOS? A `RtlGetReactOSVersion` function, for instance? I'd prefer to keep the Windows and ReactOS binaries the same if at all possible, and the Registry stuff is complicated enough as it is...

**Comment by ale5000-git** [comment]
@HBelusca @ThFabba @learn-more
Is there?

**Comment by binarymaster** [comment]
> Is there an easy way to easily tell whether we're on Windows or ReactOS?

See this comment from JIRA: https://jira.reactos.org/browse/CORE-7986?focusedCommentId=65900&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-65900

Proper way is to treat ReactOS as Windows Server 2003, but if you really want to use hacky ways, you can query system name from registry, as answered in this forum thread:

https://reactos.org/forum/viewtopic.php?f=2&t=16863

**Comment by maharmstone** [comment]
Thanks @binarymaster. I didn't realize I'd waded into such a controversial issue...

@ale5000-git - is this actually causing problems, or is it just a visual irritation? The only time I'm aware that a user would see "NTFS" rather than "Btrfs" under ReactOS would be with a command prompt program.

**Comment by ale5000-git** [comment]
@binarymaster: WinBtrfs spoof BTRFS as NTFS on Windows Server 2003 so it is exactly the opposite of what is wanted.
It is needed since Windows allow some features only on an hardcoded list of file systems but on ReactOS it isn't needed and if the code doesn't expect this then the result are unknown.

**Comment by ale5000-git** [comment]
@maharmstone

The problem is:
- On Windows NTFS is fully supported but BTRFS no (from the OS perspective),
- On ReactOS instead BTRFS is fully supported but NTFS not completely.

I currently do not have time to do complete tests but spoofing as NTFS can possibly lead to "hard to diagnose" bugs.

**Comment by maharmstone** [comment]
It really shouldn't do. The only we lie are if...
* We're called from the command prompt
* We're called from mpr.dll (which UAC uses)
* We're called from Windows 10 Storage Services
* We're called from a 32-bit program on 64-bit Windows

I'm going to close this - if you encounter a bug relating to this, please open another issue. If ReactOS is ever querying the FS name for anything other than displaying it to the user, it's a bug in ReactOS - it should be querying the FS's capabilities instead. It's a bug that mpr.dll and mklink.exe do this on Windows, but unfortunately we can't do anything about that.

**Comment by ale5000-git** [comment]
Actually instead of OS detection a better way would be feature detection.

If ReactOS could provide an API like: `bool IsFileSystemSupported(string)`
And WinBtrfs call it like this `IsFileSystemSupported("BTRFS")` this wouldn't be hackish.

**Comment by HBelusca** [comment]
But that would be a ReactOS-specific API, and this is not our aim of doing that.

**Comment by ale5000-git** [comment]
Well, there are always at least 100 ways to do things; it would be nice to find an alternative way accepted by both :)

**Comment by BenNottelling** [comment]
Last I checked the built in version of BTRFS has already had the check changed, so this should only be an issue if you are building a non release version of the driver, in which case you're already compiling it and should be able to change it yourself
