### ISSUE TITLE
Issue with saving a file to a BTRFS drive

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#177]
When I try to save a file that is being downloaded by HTTP Downloader to a BTRFS drive, it gives me a FIle IO error. I am running the 32-bit version of it on a 64-bit version of Windows 7 and am using v1.3 of the BTRFS driver. Here is how to replicate it:

1. Download and extract https://github.com/erickutcher/httpdownloader/releases to a folder.
2. Make a 512 MB VHD and attach it.
3. Format the VHD as FAT.
4. Open a Command Prompt window.
5. Run format vhd_drive (the drive that the VHD is attached to) /fs:BTRFS
6. Run HTTP_Downloader.exe that is located in the directory you extracted the contents of the ZIP to.
7. Try to download any URL to the BTRFS drive.

**Comment by ale5000-git** [comment]
I suggest to try version 1.4, the problem may be already fixed.

**Comment by MegaZeroX10** [comment]
Nope, it hasn't been fixed in the new version.

**Comment by MegaZeroX10** [comment]
@maharmstone Any thoughts as to what could be causing it?

**Comment by MegaZeroX10** [comment]
Its been fixed somehow. So, I am now closing this issue.
