### ISSUE TITLE
ReadyBoost

### ISSUE THREAD

**Issue by ale5000-git** [maharmstone/btrfs#178]
Hi,
is it possible to use ReadyBoost with a btrfs formatted USB flash drive or SD card?
If not, could it be added please? (maybe spoofing NTFS)

**Comment by maharmstone** [comment]
I don't know - why don't you try it and see if it works?

**Comment by ale5000-git** [comment]
Currently I can't but I will try as soon I get a fast USB flash drive or SD card specifically for it.

**Comment by MegaZeroX10** [comment]
It doesn't work. I just tried it using a USB Flash Drive formatted as BTRFS and have gotten the following error show in the attached image:

![ReadyBoost Error](https://user-images.githubusercontent.com/54455611/64104514-5b037680-cd42-11e9-8003-f6f8863227f2.png)

**Comment by ale5000-git** [comment]
@maharmstone: Is it possible to spoof it as NTFS?

**Comment by MegaZeroX10** [comment]
> 
> 
> @maharmstone: Is it possible to spoof it as NTFS?

It already is (according to the General tab). Unless there's more spoofing that can be done.

**Comment by maharmstone** [comment]
Eh? The General tab shouldn't ever say NTFS...

**Comment by MegaZeroX10** [comment]
It does state that as the File system.

**Comment by maharmstone** [comment]
What version of Windows?

**Comment by MegaZeroX10** [comment]
Windows 7 SP1 x64.

**Comment by MegaZeroX10** [comment]
So, is it an issue with making the filter driver think that its a NTFS drive? I noticed that you mentioned it in the issue regarding Windows Store.

**Comment by maharmstone** [comment]
Closing old issues
