### ISSUE TITLE
I cannot install it under Windows 10 1809 x64

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#179]
Trying to do so results in a Code 31. I am attaching the log generated when doing so.

[setupapi.dev.log](https://github.com/maharmstone/btrfs/files/3563791/setupapi.dev.log)

**Comment by MegaZeroX10** [comment]
Could it be happening because of Secure Boot?

**Comment by ElpizoZ** [comment]
1.7.3 installs and works after rebooting.
