### ISSUE TITLE
The following batch doesn't work on a BTRFS drive

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#180]
@echo off
copy rename.bat "Git-2.23.0-64-bit.exe.part"
:loop
ren "Git-2.23.0-64-bit.exe.part" "Git-2.23.0-64-bit.exe"
ren "Git-2.23.0-64-bit.exe" "Git-2.23.0-64-bit.exe.part"
goto loop

Save as rename.bat and place it in any folder located on a BTRFS drive.

When its ran on a BTRFS drive, it gives an error stating "A duplicate file name exists, or the file
cannot be found". I am using the latest version of it on Windows 7 SP1 x64.

**Comment by MegaZeroX10** [comment]
It is no longer occurring since then and the new version that was released yesterday.

**Comment by MegaZeroX10** [comment]
Those messages are happening because of a memory leak.

**Comment by maharmstone** [comment]
What makes you so sure of that? Bear in mind our conversation about not posting unsubstantiated conjecture on bug reports...

**Comment by MegaZeroX10** [comment]
Do you have any thoughts as to why its happening?

**Comment by maharmstone** [comment]
@MegaZeroX10, I have enough to be getting on with without worrying about some theoretical corner case. My guess is that probably we need a lock for share access, but given that a) such behaviour is vanishingly unlikely to happen in the real word, b) introducing a lock slows down _all_ file opens, and c) programs are expected to handle share violations anyway, this isn't something I'm going to address.

Please don't open bug reports for something unless it might conceivably cause issues in real life.
