### ISSUE TITLE
The OS hangs when formatting a BTRFS drive as BTRFS

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#188]
When I tried to format a BTRFS drive as BTRFS, the OS I was running froze instead of having a BSOD. I was formatting a 40 GB VHD that was formatted as BTRFS via a different OS. The OS I was trying to format it under is Windows 7 SP1 x64.

**Comment by MegaZeroX10** [comment]
Pushing the PR available at https://github.com/maharmstone/btrfs/pull/193 should fix this issue.

**Comment by SergeGautherie** [comment]
> Pushing the PR available at #193 should fix this issue.

Did you actually test and confirm that?
As far as I can tell, that PR seems unrelated.

**Comment by SergeGautherie** [comment]
#193 (and much more) is committed.
Can you re-test?

**Comment by MegaZeroX10** [comment]
I did and it still crashes/hangs. A log made with Windbg (pointed to the directory containing the symbol and the directory containing its source) is attached:

[format_btrfs_as_btrfs_crash_win7_x64.txt](https://github.com/maharmstone/btrfs/files/3825053/format_btrfs_as_btrfs_crash_win7_x64.txt)

**Comment by MegaZeroX10** [comment]
It no longer hangs when I formatted a 4 GB VHD that was formatted as BTRFS via a different OS via the format /FS;BTRFS command. I instead got an "Access is denied" message when trying to view the drive letter associated to the VHD. It was fixed by detaching and attaching the VHD.

**Comment by MegaZeroX10** [comment]
I am closing this issue since the mentioned problem has been fixed.
