### ISSUE TITLE
mkbtrfs triggers a system error event when replacing a Btrfs partition, on WXP/WS03

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#189]
WinBtrfs v1.4 upgraded to 8ac71acf83a1f50700afa2c9b226283fa1a2e797.

On (at least) Windows XP and Windows Server 2003:
`mkbtrfs \Device\Harddisk2\Partition0`
on an already Btrfs formatted partition
triggers the following system error event:
```
Event Type:	Error
Event Source:	PlugPlayManager

The device 'Btrfs volume' (Btrfs\2aa865e8-74c2-4c59-2753-669817dc57c7\1&33e28aa7&0) disappeared from the system without first being prepared for removal.

Data:
0000: 00 00 00 00               ....    
```

Is it unavoidable or is some "clean unload" step missing?

**Comment by SergeGautherie** [comment]
> Is it unavoidable or is some "clean unload" step missing?

Related to #190?

**Comment by SergeGautherie** [comment]
26a05b3a51fe9bc1daf6301d43b9e4e17e755132, WXP: seems fixed. To be further tested...

**Comment by maharmstone** [comment]
Closing old issues
