### ISSUE TITLE
'Btrfs volume' install triggers a system error event, on WXP/WS03

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#190]
WinBtrfs v1.4 upgraded to 8ac71acf83a1f50700afa2c9b226283fa1a2e797.

On (at least) Windows XP:
soon after `mkbtrfs \Device\Harddisk2\Partition0`,
'Btrfs volume' install starts.
It triggers the following system error event:
```
Event Type:	Error
Event Source:	LDMS

The Logical Disk Manager Service failed while registering for device handle notifications on device \\?\Btrfs#30832d76-12a9-551e-6509-671964635744#1&33e28aa7&0#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}. Win32 Error: 42A.
```

Is it unavoidable or could it be improved/fixed?
PS:
Partition has a drive letter and works fine.

---

On (at least) Windows Server 2003:
Similar `[...] Win32 Error: 1066.` [== 0x042A]
It seems to happen on (every?) boot instead.
PS:
Device Manager lists both 'Btrfs controller' and 'Btrfs volume' as working.
Partition has no accessible drive (letter), so is unusable.
I don't know whether that is related to the WS03R2 VM I use or to WinBtrfs itself.

**Comment by SergeGautherie** [comment]
26a05b3a51fe9bc1daf6301d43b9e4e17e755132, WXP: seems fixed. To be further tested...

**Comment by maharmstone** [comment]
Closing old issues
