### ISSUE TITLE
Symantec detect file as threat, due to low reputation (WS.Reputaiton.1)

### ISSUE THREAD

**Issue by jrogby** [maharmstone/btrfs#195]
Security Risk Found! WS.Reputation.1 in File:  c:\xxxxx\Debug\mkbtrfs.exe by: Auto-Protect scan.  Action: Quarantine succeeded : Access denied. Action Description: The file was  quarantined successfully.

**Comment by maharmstone** [comment]
No idea what I'm supposed to do about this...

**Comment by MegaZeroX10** [comment]
You can learn more about it by going to https://www.symantec.com/security-center/writeup/2010-051308-1854-99. The link to report a false positive is https://submit.symantec.com/false_positive.

**Comment by maharmstone** [comment]
I'm not interested in doing it, but anybody else is free to if they wish.
