### ISSUE TITLE
Almost no free space reported

### ISSUE THREAD

**Issue by danielepaolella** [maharmstone/btrfs#196]
I'm experiencing a similar issue as described in #156 and #157.
Using v1.4 under Windows 10 Home version 1809 (OS Build 17763.805), a filesystem created under linux 4.19.34 ([SysRescueCD 6.0.2](http://www.system-rescue-cd.org/Changes-x86/)) made of two raid 1 devices, each sized about 150 GB containing 75 GB of data, is reported by Windows as having only 154 MB of free space; an error is given if I try to add more data, exceeding the shown available size.

![manage](https://user-images.githubusercontent.com/53744340/66463092-ad8c2d00-ea7c-11e9-8372-1651ddcd051a.png)

![general](https://user-images.githubusercontent.com/53744340/66463094-af55f080-ea7c-11e9-9395-814720608f11.png)

Btrfs usage shows:
```
Device size:		298.1 GB
Device allocated:		152.1 GB
Device unallocated:		146.0 GB
Data ratio:		2.00
Metadata ratio:		2.00

Data, RAID1: size: 75.0 GB, used: 74.1 GB
Disk 0, partition 1	75.0 GB
Disk 1, partition 2	75.0 GB

Metadata, RAID1: size: 1.0 GB, used: 359.2 MB
Disk 0, partition 1	1.0 GB
Disk 1, partition 2	1.0 GB

System, RAID1: size: 32.0 MB, used: 16.0 KB
Disk 0, partition 1	32.0 MB
Disk 1, partition 2	32.0 MB

Unallocated:
Disk 1, partition 2	73.0 GB
Disk 0, partition 1	73.0 GB
```

Edit: I added more details about what Windows is reporting and created a separate issue for #202.

**Comment by SergeGautherie** [comment]
> instead I see

Could you give more details about what Linux and Windows report and how they differ? Thanks.

> changing the drive letter

I would assume the two issues are unrelated. Could you file it separately? Thanks.

**Comment by danielepaolella** [comment]
Thanks for your quick reply, I took some time to try narrowing down the issue.

> Could you give more details about what Linux and Windows report and how they differ? Thanks.

I added screenshots of how the device is shown by Windows.
Under Linux `btrfs usage` shows _Used_ and _Free_ lines with expected values:

```
Overall:
    Device size:		 298.10GiB
    Device allocated:		 152.06GiB
    Device unallocated:		 146.04GiB
    Device missing:		     0.00B
    Used:			 148.92GiB
    Free (estimated):		  73.91GiB	(min: 73.91GiB)
    Data ratio:			      2.00
    Metadata ratio:		      2.00
    Global reserve:		  88.53MiB	(used: 0.00B)

Data,RAID1: Size:75.00GiB, Used:74.11GiB
   /dev/sda2	  75.00GiB
   /dev/sdb2	  75.00GiB

Metadata,RAID1: Size:1.00GiB, Used:359.11MiB
   /dev/sda2	   1.00GiB
   /dev/sdb2	   1.00GiB

System,RAID1: Size:32.00MiB, Used:16.00KiB
   /dev/sda2	  32.00MiB
   /dev/sdb2	  32.00MiB

Unallocated:
   /dev/sda2	  73.02GiB
   /dev/sdb2	  73.02GiB
```

What also differs is that under Linux I can add data and unallocated space is claimed as expected.
For instance, I tried adding 2 more GBs and then freed them up, a new `btrfs usage` gives:

```
Overall:
    Device size:		 298.10GiB
    Device allocated:		 154.06GiB
    Device unallocated:		 144.04GiB
    Device missing:		     0.00B
    Used:			 148.92GiB
    Free (estimated):		  73.91GiB	(min: 73.91GiB)
    Data ratio:			      2.00
    Metadata ratio:		      2.00
    Global reserve:		  88.55MiB	(used: 0.00B)

Data,RAID1: Size:76.00GiB, Used:74.11GiB
   /dev/sda2	  76.00GiB
   /dev/sdb2	  76.00GiB

Metadata,RAID1: Size:1.00GiB, Used:359.12MiB
   /dev/sda2	   1.00GiB
   /dev/sdb2	   1.00GiB

System,RAID1: Size:32.00MiB, Used:16.00KiB
   /dev/sda2	  32.00MiB
   /dev/sdb2	  32.00MiB

Unallocated:
   /dev/sda2	  72.02GiB
   /dev/sdb2	  72.02GiB
```
Back to Windows, it still shows the same 154 MB free and adding more data gives a _not enough space_ error.

![action](https://user-images.githubusercontent.com/53744340/66464673-b2061500-ea7f-11e9-84c4-a9b7115612c8.png)

> I would assume the two issues are unrelated. Could you file it separately? Thanks.

Sure, I moved it to #202.

**Comment by maharmstone** [comment]
Does the problem go away if you do a balance on Linux?

**Comment by danielepaolella** [comment]
I tried running in steps:

`btrfs balance start -dusage=0 /mnt/data`
> Done, had to relocate 0 out of 77 chunks

`btrfs balance start -musage=0 /mnt/data`
> Done, had to relocate 0 out of 77 chunks

`btrfs balance start -dusage=70 -musage=70 /mnt/data`
> Done, had to relocate 3 out of 77 chunks

`btrfs balance start -dusage=80 -musage=80 /mnt/data`
> Done, had to relocate 3 out of 77 chunks

`btrfs balance start -dusage=90 -musage=90 /mnt/data`
> Done, had to relocate 4 out of 77 chunks

But it seems it didn't change much on Windows: similar amount of free space and similar `usage` report.

I didn't run an unfiltered balance so far, would you recommend to do so, or with specific parameters?

(Also I apologize for the delay, had to reinstall Windows and took a while before I could check again.)

**Comment by noctrex** [comment]
I got the same "no free space" on Win10, but using a normal disk with metadata AND data as DUP. Will post screens later when I'll have the disk available.

**Comment by ElpizoZ** [comment]
This issue has been fixed for a while now.
