### ISSUE TITLE
BSOD when opening a shared video

### ISSUE THREAD

**Issue by FedericoMatera** [maharmstone/btrfs#197]
I have a shared directory (SMB) on my BTRFS partition. If I open a video contained in that directory from another device, the server machine crash with a BSOD with code _KMODE_EXCEPTION_NOT_HANDLED_

**Comment by maharmstone** [comment]
Can you send me a minidump please?

**Comment by FedericoMatera** [comment]
[100119-6000-01.zip](https://github.com/maharmstone/btrfs/files/3682456/100119-6000-01.zip)

**Comment by maharmstone** [comment]
Thanks. You're using v1.3 - does the same thing happen in the latest version, v1.4?

**Comment by FedericoMatera** [comment]
v1.4 works fine. Thank you
