### ISSUE TITLE
advanced compression options

### ISSUE THREAD

**Issue by Artofeel** [maharmstone/btrfs#198]
1. ability to choose compression ratio
2. ability to set compression for disk itself
I know there are registry settings for both request, but they work globally

**Comment by maharmstone** [comment]
If you add the settings into the volume subkeys (the ones named like a GUID) rather than in the registry root, they'll only affect that volume.

**Comment by ale5000-git** [comment]
Isn't possible to add more UI settings in the shell extension?

**Comment by Artofeel** [comment]
> 
> 
> If you add the settings into the volume subkeys (the ones named like a GUID) rather than in the registry root, they'll only affect that volume.
never would have guessed!
will try it

**Comment by maharmstone** [comment]
Closing old issues
