### ISSUE TITLE
better Directory Opus support

### ISSUE THREAD

**Issue by Artofeel** [maharmstone/btrfs#199]
DOpus - the Ultimate Windows File manager and Explorer Replacement
problem is: it doesn't like BTRFS
when I go to the root of the disk - it always causes "Service Exception" BSOD (Win7x64)

so I made a symbolic link to a subfolder on BTRFS and it worked, but BSOD happens time to time anyway
also sometimes I get odd folders on NTFS disk where I created symlink, all empty
like:
`##@abfuagyjbnduqwbwpyrtcnesqvyhzhenazbezxqdpadynjrunskycvknihbgungdaifnqgaxziysjdtwazulcfylfcsdulnwwssrlzfwjqiblsgpobllrtagbqqecxywbsjjrzmdvyexuyenigqcleyfyluxbgktqlresecgmysrkmmfqculqvniotrqnxgblufumykbgdnvghanhtopuydaqhqdbdvydzxehzbtoliynqokaexejjhycftm
##@ablmvbhxfiavvpkvdiuohspqcyiyiaocjlfpuhcxlxhmqkcvkjzjddhheplmfzkvppvjfueitwooknqpprxuniiulxtdytjitqcqsysovpiudurzxuztlsobcoflgwecjvzcrnvkccqruwsdqkzrbailbsnpvylfbftyiseizrmvkmeqqwsmhuffvwqujqtzzqlnhhycilpfbgsplbargqssxtbueomojyusdnpwfptmvqnhfhovsxwfzlpi
##@abqmkxvuqopdpzycfxcgveifsntrxsmmydmuvpplcvzrkjletbsibrnzjpkjaseyloxhhzdgkwahumofddftjahscevsfnmjrhlhqudzrbixxxjbqpjckgazojkxxwjuxbpmlrzzupmdaymakdfbxisotkcxlqvajeyzbqzpywkldixklzgkqjjtmwfcixdcstvcfcntubpgkieskfbrshinpgyyzxvfrlrsyrmxapxpuyqwthrtrptuxuai
##@acbazuxmhecthlegrpunkdmbppweqtgjoparmowzdqyoxytjbbhawdydcprjbxphoohpkwqyuhrqzhnbnfuvqnqqlrzjpxiogvliexdzuzosrkrusvojbrzmwzpowkjilefraamdigpnpuuhgxpqnjwjmwaxxmnsnhhlqqrzudltfzotcjtnzxuglsdsmzcnockvfajfrmxothowkbjzwucwljfrimpmyhchzriwkbarxbgfcbceyhjugixw
##@acprjgojpwadlbioqjsjlqpotcwihuqtjpszxbhfmyfbuuscgbtrabptzadbzjhtbjtlazoalubtqkyifmyelemgtumxilxxqbapcmrmghrkmbopomlmdckniokgcbszkkxyfoojatsvttwgomorlnlyjotqqpyjmbyiqtvvfsicaayyaztnorzuybqomvuigvvjxvqdnzudmclkzsyipattkwbemoqevqsspwgsbkuwnpgnsfvrnhjwxyml
##@adaskokyjszazjcovahdgbkmwkvocvyafzgqftguvoxsxckqdxiqnjgjtintkwmgegyqmfkhttkgtbfnowsnbstoxggbovzhnwjgqrkcbtcvjfskawgmbfipanpjgzbdeefmbhirfaldzdghmjvyvotkvfmfqxdtisyyuxxtldbkbjccavkyeraqwcwelrpuvofzbfqbwvjjlzlwfexpmjemutmdjtlvulrwgwjtowihnhpevtbfnosgfori
##@addinjznutnllpktvacwojrbrpqtbjeexyhahntnqutxmwcdgkrsuvzubhnhiolulwbgygkvpqenumrrxtwivirtdsxzqerinrqeraeveqnxnzicojcwwyiktfdchisrhmusxhufjmgjlggjmswnnuxeuacmzizqojrkqiyupsexyktoryjupelkvhxwbttlfqyhfofhsaezlpkkbzgeuajgolgjixnjwmnocujvwknbvbhxwenvdlvdnwyr
##@agbgbjcynzywnafegbsoqpfvazzbyagbaaezlwjxlsazeqpmtosypdiaksgtfuezdathbhnicoipmuxqskgdaflnfsaqwnecizueeoobcfyaaajoiiywsjrxklgbpbuxbmguzdfadjtucdeftytfnphgciftzzyxywgxotdvlcsjgxiwutlhxpexfqjaysrybqynbeglzycbmyfubrzegfbxeyrlbjryqdkwffpdnfyueguxaqgaihfglmsx`
hundreds of them

**Comment by maharmstone** [comment]
Can you send me a minidump please?

**Comment by Artofeel** [comment]
isn't better to reproduce it?
DOpus have two months of evaluation period
www.gpsoft.com.au/DScripts/evalrequest.asp

**Comment by Artofeel** [comment]
do you still need minidump? I randomly get one...

**Comment by ale5000-git** [comment]
It isn't always granted that the same problem happens under all OSes / configurations.

If you had posted the minidump in the first message, then the bug would probably have already been corrected.

**Comment by MegaZeroX10** [comment]
I wasn't able to replicate the BSODs using the latest version of Directory Opus and the BTRFS driver via a Windows 7 x64 VM.

**Comment by Artofeel** [comment]
hey! I just upgraded (yea I'm a little slowpoke) to 1.5 version and everything works fine
thanks!
