### ISSUE TITLE
Updating svn on btrfs partition crash

### ISSUE THREAD

**Issue by Gibbz** [maharmstone/btrfs#20]
I have a svn (subversion) directory on my btrfs. I just tried to update that folder through windows. And I received an instant BSOD crash.

From the event log:
The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xfffff800f1819d34, 0xffffd001fdcdad10, 0x0000000000000000). A dump was saved in: C:\WINDOWS\MEMORY.DMP. Report Id: ebee2170-776d-4fac-9304-e3b36e6f2494.

**Comment by maharmstone** [comment]
What's the name and version of your SVN client, and what version of Windows is this?

Also, unless it's absolutely massive, could you send me C:\Windows\memory.dmp please?

**Comment by Gibbz** [comment]
The dump was 400mb!

Windows 10 64bit
Tortise svn using windows explorer

Anything else I can help with?

**Comment by maharmstone** [comment]
Thanks. Don't worry about it then for the time being.

Does the crash happen every time you try and update SVN?

**Comment by Gibbz** [comment]
I haven't tried again as I'm copying large files atm. I'll test it again
tomorrow and let you know if it's reproducible.

**Comment by Gibbz** [comment]
Yep, this happens everytime.
I also have the same problem when I run chrome portable from the btrfs partition, the same crash. (http://portableapps.com/apps/internet/google_chrome_portable)

**Comment by maharmstone** [comment]
I've just tried Chrome Portable, and it didn't crash for me. Could you post the output of btrfs check please?

**Comment by Gibbz** [comment]
How to i do a btrfs check? (Im assuming via windows, not linux in this case?)

Here's a link to the memory dump (100mb zip):
https://drive.google.com/open?id=0B9ZlIfNWX1WUenI2ZTJaeFJ3eVE

**Comment by Gibbz** [comment]
btw i can copy files fine to and from the drive, it seems to be when anything other than explorer access' the drive i get the crash

**Comment by maharmstone** [comment]
No, btrfs check will have to be in Linux - there's no btrfs-progs for Windows yet.

**Comment by Gibbz** [comment]
sudo btrfs check /dev/sdc1
Checking filesystem on /dev/sdc1
UUID: d9e4907b-96fa-4e54-9cdf-ed13e3a8e04f
checking extents
checking free space cache
checking fs roots
checking csums
checking root refs
found 789562692358 bytes used err is 0
total csum bytes: 770071028
total tree bytes: 1009958912
total fs tree bytes: 169295872
total extent tree bytes: 15958016
btree space waste bytes: 83065508
file data blocks allocated: 788785283072
 referenced 788740571136


looks good fine to me, but not to sure what the output should look like.
I only formated the drive and set it all up a few days ago, so I dont think anything should have busted in that time....

I have noticed its not all apps. 
So far just svn and chrome portable cause this crash 100% of the time.

**Comment by Gibbz** [comment]
any progress on this?

I received the issue when copying through explorer on a file about 1.4gb, but copying a file that was 700mb worked fine... So possibly with files over a certain size?

the blue screen shows the error: bad_pool_caller (or bad_pool_collector)?

**Comment by maharmstone** [comment]
Yes, I think so. Your Chrome crash was caused by CcCopyRead, and should be fixed by https://github.com/maharmstone/btrfs/commit/4326ef65b086bc7e56e7c60393dc139998c45ca0. The next version ought to be out in a couple of days.

The crash when copying large files is a separate issue, one I happened to run into myself last night. I'm looking into it at the moment.

**Comment by Gibbz** [comment]
ok great :+1: 

ill keep an eye on the new version

**Comment by maharmstone** [comment]
I've just released version 0.5, can you test on that please?

**Comment by Gibbz** [comment]
gave it a whirl, got the crash again...
Im not sure it installed over the older version at all. Is there a way to see which version is currently installed?

**Comment by maharmstone** [comment]
If you open up the Properties of C:\Windows\System32\drivers\btrfs.sys, it should tell you there.

**Comment by Gibbz** [comment]
yeah it updated, ill upload you a new crash dump

**Comment by Gibbz** [comment]
https://drive.google.com/open?id=0B9ZlIfNWX1WURE51NUk5VUxpYTQ
mem dump

**Comment by maharmstone** [comment]
Cheers, I'll have a look

**Comment by Gibbz** [comment]
Did that last crash dump help at all?

**Comment by maharmstone** [comment]
I'm not sure. It's saying the crash was due to a memory error in the function open_fileref. I've tightened up open_fileref as a result, but the bugs fixed would have been race conditions rather than anything recurrent.

Has Windows by any chance decided to create a pagefile on your btrfs volume? This will be a large file on the root of the drive, with the extension .sys. It might be marked hidden.

**Comment by maharmstone** [comment]
I've just released a new version - can you try with that please?

**Comment by Gibbz** [comment]
nope it hasn't created any page file.
With the latest version i cannot get into windows. I managed to get the memory dump via my ubuntu install however...
And the newest version causes this crash, when it does so my btrfs partition becomes read only and i need to scan + repair it using:

sudo btrfs check /dev/sdc1
sudo btrfs check --repair /dev/sdc1

Is there a way to remove this driver, so i can access my other memory dumps also?

Thanks
Hopefully email notifications are working again too! :)

heres the link to the current issue preventing windows access:
https://drive.google.com/open?id=0B9ZlIfNWX1WUb2hYeEJOd0RHbDg

**Comment by maharmstone** [comment]
Thanks. That's a new one... reduce_tree_extent is crashing because it can't find the extent item corresponding to the tree at address 0x26174000. Looks to be some sort of extent tree corruption issue.

Is btrfs check definitely clear when you run it again after the repair? Can you see if `btrfs check --init-extent-tree /dev/sdc1` will fix it so you can get back into Windows?

Failing that, the easiest way is to delete your partition using fdisk, and recreate it later - make sure to write the values down, obviously. I'm not certain safe mode will work because it's a filesystem driver, but you might want to try that too.

**Comment by Gibbz** [comment]
Ive got read/write access to my windows partition using:
sudo ntfsfix /dev/sdb1
So ill try removing the btrfs.sys driver and see if i can get in that way :)

Ive ran:
sudo btrfs check --init-extent-tree /dev/sdc1
and it output a lot of warnings and stuff, so see how that goes also.

**Comment by Gibbz** [comment]
ok heres a link to the dump I was trying to get:
https://drive.google.com/open?id=0B9ZlIfNWX1WUTW1kcktTTjRsbUk

Ive made it back into windows after removing the sys driver. That btrfs check --init never finished, so i cancelled it.

**Comment by Gibbz** [comment]
did you have any luck finding fix this yet? :)

**Comment by maharmstone** [comment]
I've not been able to reproduce it. There'll be a new version out shortly with a lot of bugfixes, you might want to try that.

**Comment by maharmstone** [comment]
Can you try on the version I've just released, please?

**Comment by Gibbz** [comment]
ok, 0.7 no longer crashes! woo. But I have this other issue with the same 2 programs.
It seems as though they cannot read or write to the btrfs drive.

First example, install chrome portable to btrfs location.
Load chrome, change some settings, book mark pages, set display of bookmarks bar.
Close chrome portable.
Relaunch chrome portable.
Error: on launch, and its back at the default settings.

With SVN, installed tortise svn.
Right click on my project, svn update
It gets stuck updating, and I can no longer access the drive/windows explorer

**Comment by maharmstone** [comment]
Well, that's progress at least. Can you please send me a debug log of what happens when it hangs with svn? It sounds like either it's getting into an infinite loop, or something is dying while holding a lock.

**Comment by maharmstone** [comment]
Actually, it might be that your svn problem is fixed by: https://github.com/maharmstone/btrfs/commit/c06c4df291a5458a58bd3fef58081a6b26b05032. I caught it calling CreateDirectory on the root of the volume, which was causing a crash. I don't know if this is *the* bug, or merely *a* bug...

**Comment by Gibbz** [comment]
hrmm, i think it may have nuked my partition again... I copied a file on there in linux, rebooted to windows (which sees the drive, but not the files i copied on there). Then reboot back in to linux, and i can no longer mount the drive.... I can however access the drive via your windows driver still! Weird....

dmesg | tail 
[   14.358573] BTRFS error (device sdc1): parent transid verify failed on 21004288 wanted 2960 found 2990
[   14.363921] BTRFS error (device sdc1): parent transid verify failed on 21004288 wanted 2960 found 2990
[   14.363925] BTRFS: failed to read chunk root on sdc1
[   14.380906] BTRFS: open_ctree failed
[   19.619466] BTRFS info (device sdc1): disk space caching is enabled
[   19.619469] BTRFS: has skinny extents
[   19.620533] BTRFS error (device sdc1): parent transid verify failed on 21004288 wanted 2960 found 2990
[   19.620636] BTRFS error (device sdc1): parent transid verify failed on 21004288 wanted 2960 found 2990
[   19.620637] BTRFS: failed to read chunk root on sdc1
[   19.644629] BTRFS: open_ctree failed

**Comment by Gibbz** [comment]
ok ive captured a memory dump of trying to load into windows with the corrupted drive causing a blue screen, which is a different issue...

https://drive.google.com/file/d/0B9ZlIfNWX1WUeDNuY0tRcWg3X1k/view?usp=sharing

Im just wiping my drive and restoring my backup for now, ill try again with the next release :+1:

**Comment by maharmstone** [comment]
Thank you, I'll look into it.

**Comment by maharmstone** [comment]
I've just released a new version, which includes fixes for your SVN and Chrome problems.

**Comment by Gibbz** [comment]
Hi,
I no longer have a windows install to be able to test this issue. So ill close it and assume its been fixed :)
Thanks!
