### ISSUE TITLE
Windows blue screen when updating Samsung T3 SSD with BTRFS partition

### ISSUE THREAD

**Issue by qume** [maharmstone/btrfs#200]
Probably about as edge case as you can get, but perhaps this could help lead to an issue that also causes other problems.

The Samsung portable SSD tool can update the firmware on the device (T3, T5, etc). WIndows blue screens when this is done with a BTRFS partition.

**Comment by maharmstone** [comment]
Could you send me a minidump please?

**Comment by qume** [comment]
It won't let me re-update it, as it's at the latest version. I'll do this when there is another update from Samsung available

**Comment by ElpizoZ** [comment]
Do you have any .dmp files in C:\Windows\Minidump? If so, please compress them as a ZIP archive and attach it here.

**Comment by maharmstone** [comment]
Closing old issues
