### ISSUE TITLE
Error changing drive letter in the properties tab

### ISSUE THREAD

**Issue by danielepaolella** [maharmstone/btrfs#202]
Using v1.4 under Windows 10 Home version 1809 (OS Build 17763.805), if I try changing the drive letter from the Btrfs tab in the disk properties I get the error:
> The data area passed to a system call is too small.

then sometimes no letters show up in the drop down, sometimes they do.

![error](https://user-images.githubusercontent.com/53744340/66461635-c1825f80-ea79-11e9-9819-ab9feff997fe.png)

![dropdown](https://user-images.githubusercontent.com/53744340/66461647-c515e680-ea79-11e9-961a-1950b47701a7.png)

I can change letters successfully using `diskpart`.

Given a "data area" was mentioned in the error message, I assumed this issue could be related to #196 and Windows not recognizing available space; after I used the fs under linux and some unallocated space was claimed, this error doesn't pop up consistently any more: sometimes it does, sometimes it doesn't.

**Comment by SergeGautherie** [comment]
I wonder whether https://jira.reactos.org/browse/CORE-16371 could be the same issue...

**Comment by maharmstone** [comment]
@SergeGautherie - I don't think so. The ReactOS error is saying that IOCTL_ATA_PASS_THROUGH isn't supported by the SCSI driver.

I'm not sure what error "the data area passed to a system call is too small" translates to - presumably STATUS_BUFFER_OVERFLOW.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/5c831107554388c8620d626d02ee0c4d044da226. Thanks for reporting!

**Comment by SergeGautherie** [comment]
> `IOCTL_ATA_PASS_THROUGH`

Thanks for the clue.

**Comment by SergeGautherie** [comment]
> `IOCTL_ATA_PASS_THROUGH`

Thanks for the clue.I filed https://jira.reactos.org/browse/CORE-16422 .
Although the link between the ioctl log and the error messagebox is not obvious to me yet...
