### ISSUE TITLE
Makes a Linux partition unbootable

### ISSUE THREAD

**Issue by nullvideo** [maharmstone/btrfs#207]
This driver was installed on *Windows 8.1* and I was able to access the files on the Linux partition. But, when I tried to boot into Linux it didn't work for some reason.

Later I came to know that the driver converted partition to a **Btrfs volume**.
<sup>_(not confident about this statement)_</sup>

**Comment by maharmstone** [comment]
"Btrfs volume" is just how the filesystem is announced to Windows, it hasn't converted anything.

Can you post the output of `btrfs check` please? Also, what gets displayed in dmesg when you try to mount it?

**Comment by nullvideo** [comment]
I deleted the partition before I post this issue to Github. And, I'm currently using a Ext4 filesystem so the bug is no more traceable.
