### ISSUE TITLE
Long Filenames and deep folders

### ISSUE THREAD

**Issue by Popkultur** [maharmstone/btrfs#208]
I am using Btrfs für Win with Encfs file encryption, and now I had the issue that some very deep folders could not be read. This happened without mounted encryption, so it was just that the folders were deep and long. I can not tell the exact length though.

**Comment by maharmstone** [comment]
Is this definitely an issue with the driver - as in, would it behave differently if you used NTFS instead? The reason I ask is that I know ecryptfs on Linux has shorter filenames than would otherwise be allowed.

**Comment by Popkultur** [comment]
Well, I copied the files with linux to an ntfs partition, which worked flawlessly. So I believe it is an driver issue.

**Comment by maharmstone** [comment]
Sorry, it didn't send me an e-mail with your response for some reason. The Linux NTFS driver doesn't necessarily behave the same as the Windows NTFS driver. Does it behave differently if you try it with NTFS on Windows?

**Comment by maharmstone** [comment]
Closing old issues
