### ISSUE TITLE
Crash occurring when plugging in a flash drive that is formatted as BTRFS

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#209]
When I "plug in" the flash drive to my Windows 7 x64 VM (via the latest version of VMWare Workstation Player) that has the btrfs driver compiled from the latest master installed, it crashes. I have attached a debug log made with Windbg:

[usb_btrfs_crash.txt](https://github.com/maharmstone/btrfs/files/3826341/usb_btrfs_crash.txt)

**Comment by maharmstone** [comment]
Please do not submit bugs unless they are from an actual released version. Anything else is not supported.

**Comment by MegaZeroX10** [comment]
I'll try the release version when it comes out.
