### ISSUE TITLE
Registry groups mapping

### ISSUE THREAD

**Issue by Magissia** [maharmstone/btrfs#21]
There is no mention of groups mappings, only user mapping.
If groups mappings are supported, please update readme, if not, please consider this as a feature suggestion.

**Comment by maharmstone** [comment]
No, group mapping isn't supported. Windows stores the "primary group" of an object in its security descriptor, presumably for the sake of POSIX compatibility, but as far as I can see it isn't used _for_ anything. On top of that, there doesn't seem to be any easy way either to see what a user's default group is, or to change the group of an existing object.

If you can come up with a use case that'd be different, but for now I don't see the point.

**Comment by Magissia** [comment]
Hello, it is possible to use ACL on linux, when using this, multiple groups can have permissions on files and directories, btrfs supports ACL using the "acl" mount option.

Group mapping would be useful for that.

**Comment by maharmstone** [comment]
Unfortunately not, the two ACL implementations are too different. Windows' ACLs are far more advanced than those on Linux. I think you could probably do it with richacls on Linux, but pretty much nothing supports that.
