### ISSUE TITLE
Crash when plugging in a BTRFS formatted thumb drive

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#211]
When I plug in a BTRFS formatted thumb drive (formatted with v1.4 of the btrfs driver installed) into my Windows 7 x64 VM (ran via VMWare Workstation 15 Player) with v1.5 of the btrfs driver installed, it crashes the OS. The mini dump is attached:

[111019-14523-01.zip](https://github.com/maharmstone/btrfs/files/3829025/111019-14523-01.zip)

**Comment by MegaZeroX10** [comment]
I guess this issue is occurring only in v1.4 and not in v1.5.

**Comment by BenNottelling** [comment]
If the issue is fixed in the most recent version it can be closed
