### ISSUE TITLE
Capitalize Btrfs in the Properties of a BTRFS formatted drive

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#213]
I think that it makes sense to do that since Windows does that for NTFS, etc.

**Comment by ale5000-git** [comment]
I think Windows just use the original case (not specifically uppercasing it), you can see it using `format /?`:
` /FS:filesystem  Specifica il tipo di file system (FAT, FAT32, exFAT, NTFS, UDF, ReFS).`
