### ISSUE TITLE
I am trying to share files between guest OS and host OS using a RAW virtual disk image containing btrfs, but it seems to be a bit of a hassle.

### ISSUE THREAD

**Issue by daiaji** [maharmstone/btrfs#214]
It seems that the file write between guest OS (Win10) and host OS (Linux) is not real-time, you must restart the guest OS to get the new file.

**Comment by Atemu** [comment]
You're trying to have the same btrfs mounted on two operating systems at the same time?

That is not what on-disk filesystems like btrfs are supposed to be used for, stop doing that immediately if you have any important data in that image (this will undoubtedly lead to *serious* data loss) and look for a better way to share data between host and guest.

**Comment by daiaji** [comment]
I use winbtrfs on win10 and native btrfs support on Linux.  In fact, the terrible thing has already happened. I lost all the files written by the guest OS after umount the btrfs partition on the host OS. Although it is only testing, it is really terrible.😰

**Comment by maharmstone** [comment]
I think this is what's known as a learning experience. Samba's what you're looking for.

**Comment by daiaji** [comment]
The reason I am trying a variety of file sharing methods is because smb performance is too bad.
Maybe in the end I can only use it.

**Comment by ale5000-git** [comment]
Have you tried FTP (with local connection, without internet)?
An FTP server on the host OS and an FTP client on the guest OS, I have never tried it in this way but it may work.
