### ISSUE TITLE
Corrupts btrfs filessytem

### ISSUE THREAD

**Issue by ibrokemypie** [maharmstone/btrfs#218]
Using 1.5 on a 4tb btrfs hdd with compression and zstd enabled, I noticed that the drive kept becoming write protected. I tried setting compression to 0 and explicity setting readonly to 0 in the registry and restarting but that made no difference. Seeing issue #68 I booted back into linux and the drive was unable to be mounted. The kernel messages after trying to mount were "tree level mismatch" "failed to read block groups" and "open_ctree failed"
I then attempted ro run btrfs check and btrfs check --repair on the filesystem, and neither of those were able to start, reporting "child eb corrupted"  and "free_space_extent_key" failed

Booting back into windows however the disk still mounts, and it seems I am able to copy files off of it onto my windows disk.

Any ideas about how to fix the disk for linux, and prevent this from occurring again?

**Comment by Chaython** [comment]
Was your kernel out of date? / older version of BTRFS than the winbtrfs?
Anyways this is 8 months old, I assume you resolved it by now, if so please close.

**Comment by ibrokemypie** [comment]
Kernel was up to date (on arch)
My resolution was to uninstall winbtrfs, dump all of the files that a btrfs restore command could find on the broken filesystem onto another drive, recreate the btrfds filesystem and copy it all back, luckily there was minimum corruption/loss of files but it required creating a large ad-hoc raid array of small drives to make up the 4tb i needed to dump everything off the dead btrfs partition.

**Comment by maharmstone** [comment]
Closing old issues
