### ISSUE TITLE
Using an encrypted partition

### ISSUE THREAD

**Issue by jochenw** [maharmstone/btrfs#22]
Hi,

is it possible, or is intended to become possible to have WinBtrfs use a partition, which is encrypted by a typical corporate disk encryption solution like PGP Desktop, or McAffee Disk Encryption?

Thanks,

Jochen

**Comment by maharmstone** [comment]
Without knowing exactly how they operate, I can't say for certain. But if they expose the decrypted volume as a separate block device, I don't see why not.

Is this a theoretical question, or have you tried it and it doesn't work?

**Comment by jochenw** [comment]
I haven't tried, because the machine in question is my employers Laptop, and I don't want to crash that without a reasonable probability of success. Thus, just asking.

Thanks,

Jochen

**Comment by maharmstone** [comment]
Hi Jochen - just wondering, did you have any luck with this?

**Comment by maharmstone** [comment]
Closing old issues
