### ISSUE TITLE
Cannot add further Devices to Veracrypt Device (e.g. to make btrfs raid1 under Windows)

### ISSUE THREAD

**Issue by chscherrer** [maharmstone/btrfs#221]
Winbtrfs shows perfectly to use within fully encrypted [veracrypt](https://www.veracrypt.fr/en/Home.html) devices. However, when trying to add further devices to a Winbtrfs-formated veracrypt partition, e.g. to have the benefits of a software raid1, it is not possible to choose from other virtual veracrypt devices which are mounted since Windows XP under \Device\VeracryptVolumeXXX

May I please ask to allow for further devices selection (like \Device\VeracryptVolumeXXX) than the implemented \Device\HarddiskXXX\PartitionYYY?

**Comment by maharmstone** [comment]
IIRC, this is a bug in Veracrypt - they fiddle with mountmgr to get their device to appear, rather than exposing it as a PNP device as they ought to. Consequently, when we query for PNP block devices, such as on the "Add Device" screen, it doesn't show up.

You might want to log a bug with them about it. I'm not going to work around it, unless they have a very good reason for doing it the way they do...

**Comment by h-vetinari** [comment]
@chscherrer 
How did you get this to work? When I mount a (decrypted) veracrypt device that I formatted with btrfs on the linux side, windows(+winbtrfs) doesn't recognise the filesystem. And when I re-format it with `format /fs:btrfs D:`, nothing changes.

**Comment by chscherrer** [comment]
Hi @h-vetinari 
> How did you get this to work? When I mount a (decrypted) veracrypt device that I formatted with btrfs on the linux side, windows(+winbtrfs) doesn't recognise the filesystem. And when I re-format it with `format /fs:btrfs D:`, nothing changes.

I used only Windows. First creating a "Encrypt a non-system partition/drive" which I would after format with WinBTRFS. Never tried whether it interoperates with linux because not relevant for me.

**Comment by h-vetinari** [comment]
Thanks for the response. It seems I haven't fully figured out how to correctly use winbtrfs, in this case...
