### ISSUE TITLE
Can not install the driver "The data is invalid"

### ISSUE THREAD

**Issue by maghsk** [maharmstone/btrfs#223]
![image](https://user-images.githubusercontent.com/16971372/73910034-1b404c80-48e9-11ea-92a0-654dcba5b32b.png)

1. Download the latest release driver.
2. Extract to a folder.
3. Right click `btrfs.inf`, then `install`.
4. Error occured.

------ 

`winver.exe`
![image](https://user-images.githubusercontent.com/16971372/73910240-bb967100-48e9-11ea-9a1f-9d65265e2023.png)

**Comment by maharmstone** [comment]
Have you tried redownloading it, in case you got a corrupt download?

If it's not that, it might be something funny with prerelease versions of Windows? I tested it successfully up to 1909.

**Comment by maghsk** [comment]
> Have you tried redownloading it, in case you got a corrupt download?
> 
> If it's not that, it might be something funny with prerelease versions of Windows? I tested it successfully up to 1909.

I have downloaded three times and got the same result each time. Maybe it's up to the Windows update?

**Comment by maharmstone** [comment]
What was the solution?

**Comment by QuadlessPyjack** [comment]
> 
> 
> What was the solution?

Can't speak for maghsk but I just encountered the same issue on Build 19640.1 and the solution is ridiculously simple - reboot.
I checked in devmgmt.msc and the driver appeared in the device tree, all of its .sys, .dll, .exe files appeared registered but it was showing with an exclamation mark, saying that the device needs to be installed.
Rebooting fixed it, as can be seen in the image below:
![image](https://user-images.githubusercontent.com/10133217/84547930-ce400d00-ad04-11ea-8a9b-fc8f53a8e05c.png)
