### ISSUE TITLE
No Space left reported to Windows when using DUP data

### ISSUE THREAD

**Issue by noctrex** [maharmstone/btrfs#224]
Maybe similar to #196 or #156:
Formatted an external 1TB harddisk on Windows 10 x64 with WinBtrfs 1.5 using DUP data & metadata, intended for redundant backup copy. As I started to copy files onto it, as it began to reach the 50% full mark, now Windows reports that the disk is full, but still able to copy files onto it.
Disk Properties:
![image](https://user-images.githubusercontent.com/35490284/73916209-ab6c9a80-48c5-11ea-899a-d4047cfc9416.png)
WinBtrfs Disk Usage:
![image](https://user-images.githubusercontent.com/35490284/73916241-c0492e00-48c5-11ea-8da1-998b120f3d4a.png)

**Comment by ale5000-git** [comment]
Have you tried with version 1.6?

**Comment by noctrex** [comment]
> 
> 
> Have you tried with version 1.6?

Yes, tried it out today after seeing the available update. The behavior is the same.

**Comment by maharmstone** [comment]
Thanks - I'll have a look. Does doing a balance change matters any?

**Comment by noctrex** [comment]
> 
> 
> Thanks - I'll have a look. Does doing a balance change matters any?

Tried balancing the disk overnight, as it has been suggestet in the other tickets, but no, the reported space usage remains the same

**Comment by maharmstone** [comment]
This is fixed in version 1.7.
