### ISSUE TITLE
[Feature request] Online in place conversion

### ISSUE THREAD

**Issue by ale5000-git** [maharmstone/btrfs#226]
I know it will probably very difficult but a very nice feature of Btrfs file system is in-place conversion (with rollback support).

The software could for example convert an online partiton (even C:) from NTFS to Btrfs (but system still see as NTFS since Btrfs has very few pieces of metadata that live in fixed locations) and then ask to restart (and at restart change the remaining bits).

**Comment by maharmstone** [comment]
I'm closing this in favour of https://github.com/maharmstone/btrfs/issues/225, as it's essentially the same thing.
