### ISSUE TITLE
How to create a BTRFS RAID?

### ISSUE THREAD

**Issue by TheEmbyTower** [maharmstone/btrfs#227]
Hi,

I want to create to BTRFS pools: 1x RAID1 named Fabric with 2 discs, 1x RAID6 named Storage with 18 discs.
My problem: I can't find any information how to do this with Winbtrfs. No commands, no naming scheme for the discs.

I would be very very happy for any help!

Thanks a lot!

**Comment by TheEmbyTower** [comment]
No help?!

**Comment by maharmstone** [comment]
Maybe ask on https://www.reddit.com/r/btrfs/? This isn't an issue with the software.

**Comment by Atemu** [comment]
> Maybe ask on https://www.reddit.com/r/btrfs/?

Pretty sure that sub is mostly for Linux' btrfs.  
I have created [/r/WinBtrfs](https://www.reddit.com/r/WinBtrfs/) a while ago but I don't think anyone's on there.

>This isn't an issue with the software.

IMO it is, WinBtrfs' GUI's documentation being nearly non-existent is an issue. Not a particularly pressing one mind you (I don't think WinBtrfs is ready for anyone but btrfs enthusiasts yet) but an issue none the less.

**Comment by TheEmbyTower** [comment]
IMO it is an issue with the software. There is no known GUI I'm able to use and if there is one, there is no documentation how to use it correctly.
All I want to do is creating a RAID6 with BTRFS, but no one is willed to tell me how it is possible with Winbtrfs or show me where it is in the documentation.
And at Reddit there will be also no help, I think.

I'm so frustrated ...
