### ISSUE TITLE
maharmstone can you test to see if btrfs works in Win98SE?

### ISSUE THREAD

**Issue by toddfraser88** [maharmstone/btrfs#228]
can you test to see if this btrfs in Win98SE?

Win98SE has a partial implementation of ntoskrnl and hal in a file called ntkern.vxd

I know the hacked USB 2.0 drivers out there for windows98 make use of it

can you test to see if there is enough functionality in ntkern.vxd for btrfs to work?

**Comment by maharmstone** [comment]
It won't, because it uses some functions introduced with XP and Windows 2000. I'm not planning to go back further than XP, sorry.
