### ISSUE TITLE
is it possible to mount to a folder?

### ISSUE THREAD

**Issue by SKDS** [maharmstone/btrfs#229]
I would very much like to see such a function, I will be very happy if I appear. 
many thanks for the driver

**Comment by maharmstone** [comment]
You should be able to do this by creating a reparse point with mklink (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) - it doesn't need any support in the driver.

**Comment by SKDS** [comment]
Is it possible to do this without assigning a letter to a section?

> You should be able to do this by creating a reparse point with mklink (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) - it doesn't need any support in the driver.
