### ISSUE TITLE
Windows updating issue

### ISSUE THREAD

**Issue by DjArt** [maharmstone/btrfs#230]
Last phase of updating(90-99%) Windows fail with 0xc1900104. Btrfs isn't FS of system drive. If you say how(I mean how to share), I can provide crash dumps.

**Comment by ale5000-git** [comment]
What version of Windows?
32-bit Windows?

**Comment by DjArt** [comment]
x64, 10.0.18362 build

**Comment by maharmstone** [comment]
Is this definitely an issue with btrfs - does it go away if you temporarily disable it (i.e. set its start type to 4)? What about if the driver's present but there's no btrfs volumes?

**Comment by MegaZeroX10** [comment]
Please provide crash dumps.

**Comment by DjArt** [comment]
If I remove driver - update done successful. So yep, it's issue with btrfs. I'm not tested without btrfs volumes and now can't do this. May be later.

**Comment by maharmstone** [comment]
Thanks. I'm fairly sure that updates with Btrfs as the boot drive don't work because of our lack of Transactional "NTFS" support; perhaps it's the same issue here. Though why Windows is touching anything other than the C: drive during an update is anyone's guess...

**Comment by ale5000-git** [comment]
I sometimes notice that there are folders with apparently casual characters directly under C:\ that contains files that seems related to an update (unzipped); also in some rare cases I noticed a similar thing in external hard disks (probably a Windows bug).

**Comment by maharmstone** [comment]
I did manage to encounter this bug - the presence of the driver, regardless of whether there were any volumes, was enough to stop Windows Update from completing. But whatever the issue was, it seems to have gone now - I had no problems in upgrading to Windows 2004 with 1.7.3 installed.
