### ISSUE TITLE
Corrupting files on btrfs volume and crash when unusual access of them

### ISSUE THREAD

**Issue by DjArt** [maharmstone/btrfs#231]
I have 2,5 TB volume with music, that stored on 3 HDD. Reading these files, even corrupted(they filled with zeros, but without BSOD), is fine when read with explorer or Groove Music, but, if I copy files to that volume or indexes files with FlylinkDC(that funny case where bugcheck triggered by Windows Defender), bugcheck will be triggered. Repairing volume didn't help.

**Comment by maharmstone** [comment]
Could you send a minidump please?

**Comment by MegaZeroX10** [comment]
I am also curious about this issue.

**Comment by DjArt** [comment]
[030820-43734-01.zip](https://github.com/maharmstone/btrfs/files/4302884/030820-43734-01.zip)

**Comment by maharmstone** [comment]
Thanks for this. This is fixed by https://github.com/maharmstone/btrfs/commit/09749bb0e8207a9d910b1dd67d57b7d63d47f648.
