### ISSUE TITLE
exFAT boot support?

### ISSUE THREAD

**Issue by ZhuMa12345678** [maharmstone/btrfs#232]
Many years ago, I installed and started Windows on the exFAT partition, but only supported Windows 8 and above, I hope this project can support exFAT to boot Windows 7 and below.
 
exFAT boot preview
![image](https://user-images.githubusercontent.com/61312109/75029141-7cb50d80-54dc-11ea-84d3-c9546905da0f.png)
 
This is a detailed installation tutorial I wrote in Simplified Chinese (because I am from China)
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=388226&mobile=no
I appologize for my grammatical mistake because English isn't my main language.

**Comment by maharmstone** [comment]
Closing because wrong repo.
