### ISSUE TITLE
winBTRFS Signature - ReactOS Foundation?

### ISSUE THREAD

**Issue by Saijin-Naib** [maharmstone/btrfs#233]
You mention that the most recent Win10 driver signing requirements have gotten more strict and that an organization must sign for SecureBoot capability.

Do you know if the ReacOS foundation would qualify as a signing organization, especially since they're making use of winBTRFS in versions post v.4.10?

Thanks!

**Comment by binarymaster** [comment]
As far as I know, ReactOS does not sign open source drivers and binaries anymore.

Cc @ColinFinck

**Comment by binarymaster** [comment]
Yes, just like I said above: https://reactos.org/wiki/Driver_Signing

**Comment by Saijin-Naib** [comment]
> Yes, just like I said above: https://reactos.org/wiki/Driver_Signing

That is a quite a frustrating development. On the one hand, I get it, but on the other... Ugh.

Thanks for educating me on that.
