### ISSUE TITLE
Version 1.7 problem

### ISSUE THREAD

**Issue by jozsefk9** [maharmstone/btrfs#234]
1.5 and 1.6 worked fine so far. Today I got 1.7 and the drives are gone. Windows 10 Pro 64bit. I tried to uninstall the storage controller and to install the driver again, it didn't help. Shall I go back to version 1.6 or?

**Comment by maharmstone** [comment]
Is it definitely running? Try `sc query btrfs` from an Admin command prompt.

**Comment by jozsefk9** [comment]
`SERVICE_NAME: btrfs
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0`

**Comment by maharmstone** [comment]
What does `sc start btrfs` say?

**Comment by jozsefk9** [comment]
> [SC] StartService FAILED 577:

> Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

**Comment by maharmstone** [comment]
Cheers. Which version of Windows 10 is this? `winver` will tell you.

**Comment by jozsefk9** [comment]
Microsoft Windows Version 1909 (OS Build 18363.657)
Windows 10 Pro

**Comment by rconcept** [comment]
Hi,
I've a similar problem: I've tested (yesterday) v1.6. So far OK, today I wanted to test v1.7 but was unable to install the driver (both release and debug).
When I try to install it, it shows tow popups: the first "Error: Installation failed.", and just after a second with "The operation completed successfully".
But although the files (btrfs.sys, ubtrfs.dll, shellbtrfs.dll and mkbtrfs.exe) got copied into the windows system32/drivers and system32 directory, the service "btrfs" was not created.

When I try to create it manually:
`sc create btrfssc binpath=c:\Windows\System32\drivers\btrfs.sys type=kernel start=boot displayname="btrfssc"`
When I try to start it, I get the same error "[SC] StartService FAILED 577:" (as [**jozsef9** above](https://github.com/maharmstone/btrfs/issues/234#issuecomment-591912022) )

In the ProcessMonitor log, I noticed an other small problem:
InfDefaultInstall.exe used "CreateFileMapping" on filenames without an extension (e.g.: "C:\Windows\System32\shellbtrfs."), but the call succeded.

The [Logfile_btrfs_install_from_inf_file.zip](https://github.com/maharmstone/btrfs/files/4261319/Logfile_btrfs_install_from_inf_file.zip) was captured when I started to install the driver and stopped while the first popup was still visible.

The first CreateFileMapping call without extension, was at time: "11:52:06.0154875"

My system is x64:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

Hope that helps.

**Comment by MegaZeroX10** [comment]
I am also having a problem with upgrading to v1.7. I am attaching the setupapi logs as a ZIP archive:

[windows7_btrfs_install_logs.zip](https://github.com/maharmstone/btrfs/files/4262922/windows7_btrfs_install_logs.zip)

**Comment by valireality** [comment]
I think this is regarding Secure Boot.

**Comment by MegaZeroX10** [comment]
I don't think that's the case for me, at least. It seems to be a certificate issue for me.

**Comment by maharmstone** [comment]
Today I learnt two things:
* If you boot Windows with the DEBUG flag on, it'll accept certificates it'd otherwise reject
* If you run `signtool` without having a PhD in Microsoftology, you run the risk of creating certificates that Windows won't like, yet this isn't reflected in any way in the shell interface. Thanks guys.

I've resigned the binaries and replaced the zip files - can you redownload and try again please?

**Comment by jozsefk9** [comment]
> Today I learnt two things:
> 
> * If you boot Windows with the DEBUG flag on, it'll accept certificates it'd otherwise reject
> * If you run `signtool` without having a PhD in Microsoftology, you run the risk of creating certificates that Windows won't like, yet this isn't reflected in any way in the shell interface. Thanks guys.
> 
> I've resigned the binaries and replaced the zip files - can you redownload and try again please?

Bingo! It's working now. Thanks!

**Comment by maharmstone** [comment]
Phew!

**Comment by MegaZeroX10** [comment]
I can confirm that my error that was occurring when installing it has also been fixed.

**Comment by ale5000-git** [comment]
@maharmstone: Could you please share the command line used for `signtool`? (excluding the password part obviously)

**Comment by maharmstone** [comment]
`signtool sign /ph /ac "C:\Program Files (x86)\Windows Kits\10\crosscertificates\ctnca.crt" /tr http://timestamp.digicert.com x86\btrfs.sys x86\shellbtrfs.dll x86\ubtrfs.dll x86\mkbtrfs.exe x64\btrfs.sys x64\shellbtrfs.dll x64\ubtrfs.dll x64\mkbtrfs.exe arm\btrfs.sys arm\shellbtrfs.dll arm\ubtrfs.dll arm\mkbtrfs.exe aarch64\btrfs.sys aarch64\shellbtrfs.dll aarch64\ubtrfs.dll aarch64\mkbtrfs.exe`
