### ISSUE TITLE
Windows 7 support is broken

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#235]
*subject*

I tried installing v1.7 on Windows 7 x64. It didn't install and the following error was recorded in Event Viewer:

Application popup:  : \SystemRoot\system32\DRIVERS\btrfs.sys cannot find ntoskrnl.exe KeInitializeSpinLock

**Comment by SergeGautherie** [comment]
Guess:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keinitializespinlock
"you must define `WIN9X_COMPAT_SPINLOCK`"

**Comment by MegaZeroX10** [comment]
That or he should use Windows 7 as the Target OS when compiling it.

**Comment by maharmstone** [comment]
@SergeGautherie - you're right. Another gotcha...

I've recompiled the offending binaries. @MegaZeroX10, try redownloading the Zip file.

**Comment by MegaZeroX10** [comment]
It works. Thanks for fixing it.

**Comment by maharmstone** [comment]
No worries. Thanks for reporting it.

**Comment by SergeGautherie** [comment]
> recompiled

Could you commit an explicit support/reminder? (Code and/or `README.md`.)
Thanks.
