### ISSUE TITLE
BSOD with error "page fault in nonpaged area btrfs.sys" in windows 10

### ISSUE THREAD

**Issue by Charley-Cai** [maharmstone/btrfs#236]
System environment:
Windows 10 Pro Build 18363 
Windows 10 Pro Build 19041
Btrfs Raid 6 with 3TB x 8
winbtrfs 1.6
winbtrfs 1.7

The problem happened when I tried to use Duplicati to backup data to btrfs raid 6 volume.
When I tried to replicate it, I also found it will happen when I archive date to btrfs raid 6 volume with 7zip or Winzip. But if I just copy data to this volume, everything will be ok.

**Comment by maharmstone** [comment]
Could you send a minidump please?

**Comment by Charley-Cai** [comment]
[022920-51531-01.zip](https://github.com/maharmstone/btrfs/files/4271250/022920-51531-01.zip)

Attached please find the minidump.

OS:  Windows 10 Pro19041
Btrfs : Raid 6 with 3TB x 8
WinBtrfs: v1.7

Replication Proposal: archive the data to Btrfs Volume by 7zip with 1GB split.

**Comment by maharmstone** [comment]
Thanks, I'll have a look.

**Comment by smopucilowski** [comment]
Hit this today on a fresh Win 10 Home 1909 (18363.752). `choco install winbtrfs` would install but the driver wouldn't initialise; hand installing, pointing to a fresh btrfs image, and calling balance on it would trip a page fault in nonpaged area, destroying the image. Ditto if the image was populated/not-empty.

**Comment by maharmstone** [comment]
@smopucilowski - I'm fairly sure that's a different bug. The one that @Charley-Cai encountered is only with RAID5/6, and not when balancing. Could you send me a minidump please?

**Comment by maharmstone** [comment]
@Charley-Cai - I've not been able to reproduce the bug directly, but I can see what the issue is, and https://github.com/maharmstone/btrfs/commit/6fff4668fa6c0609b6fc5f3516e01b46855e0a96 ought to fix it. Feel free to open another issue if you continue to have problems after the next release.

**Comment by Hawk321** [comment]
I get the same error when I copy a file with Total Commander and there is already the same file or at least the same named file in the folder and the copied file should replace it.

When I do the same copy within Windows Explorer it stops copying and the Explorer freezes.
