### ISSUE TITLE
Moving files/folders from a subvolume to root, on drive with DUP data, Windows hangs

### ISSUE THREAD

**Issue by noctrex** [maharmstone/btrfs#239]
Using version 1.7.1, on Win10 x64 1909.

I have an external 750GB HDD with btrfs. it has a subvolume titled "backup". Selected all the contents, 2 files and 3 folders in it, right-click Cut, and go one folder up to the root folder of the drive, right-click, Paste. Explorer hangs, and cannot even restart windows, had to force it by pressing the power button.

**Comment by maharmstone** [comment]
Is this a one-off, or does it happen every time you try?

**Comment by Atemu** [comment]
Does it happen with block group modes other than dup?

**Comment by noctrex** [comment]
> 
> 
> Does it happen with block group modes other than dup?

Just formatted a test drive (external 120gb usb) with the default options, and it seems to be working fine. Only the drive with dup data hangs windows.

**Comment by maharmstone** [comment]
Thanks, I'll have a look. How full is your volume?

**Comment by noctrex** [comment]
> 
> 
> Thanks, I'll have a look. How full is your volume?

Tried on 2 disks, both with DUP data: an 1TB backup mirror drive, which is about 60% full, and a freshly formatted drive with only a few files copied into a subvolume

**Comment by maharmstone** [comment]
Closing old issues
