### ISSUE TITLE
1.7.1 BSOD on install

### ISSUE THREAD

**Issue by jozsefk9** [maharmstone/btrfs#240]
If I try to install 1.7.1 Windows 10 1909 (OS Build 18363.657) is just crashing with BSOD.

**Comment by Chaython** [comment]
Very unhelpful.
BSOD gives you an error message, specify it.
Did you have a BTRFS partition already?
Did you use previous versions of WinBTRFS?
Have you done any troubleshooting?
win10 | 18363.719 with 1.7.1 is working fine for me. Aside from error 31, before reboot.

**Comment by maharmstone** [comment]
@jozsefk9 - Sorry, I missed this. Could you send a minidump please?

**Comment by MegaZeroX10** [comment]
Maybe it has been fixed by the latest commit.

**Comment by tomscytale** [comment]
still in 1.7.2

![IMG_20200413_155858](https://user-images.githubusercontent.com/912257/79132038-7be47d80-7da1-11ea-8829-54e65767497e.jpg)

[041320-8156-01.zip](https://github.com/maharmstone/btrfs/files/4470130/041320-8156-01.zip)

**Comment by noradtux** [comment]
Settings HKLM\SYSTEM\CurrentControlSet\services\btrfs\Start to 4 (like described for manual uninstal) and rebooting circumvents this problem.

**Comment by jozsefk9** [comment]
In the meantime, I just switched completely to Linux and got Windows inside VMWare. I don't have any kinds of problems anymore. Thank you.

**Comment by ElpizoZ** [comment]
I didn't get 1.7.3 to BSOD for me when installed in Windows 10.
