### ISSUE TITLE
ServiceType in .inf file

### ISSUE THREAD

**Issue by Tellrec** [maharmstone/btrfs#242]
Hello,
After successful installation btrfs v1.6 on Windows 10 and formatting usb flash drive with btrfs, Windows 10 on different computers with btrfs installed cannot recognize that it is already formatted with btrfs and wants to format it again.
I tried new version 1.7 but after installation I always get bsod with different codes of failure.
After some research, I noticed changes in ServiceType in commits. Could I ask, why was it set from 2 to 1? According to Microsoft - https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-an-inf-file-for-a-file-system-driver value 2 should always be set.
Is it possible to change it back to value 2 or could you release a version with optional value for us? Maybe it would resolve my problem and other opened issues similar to this one.

**Comment by maharmstone** [comment]
IIRC, this was because it's not just a filesystem driver - it also exposes the Btrfs volumes as block devices, so that RAID works properly.

If you're getting a BSOD, could you send me the minidump please?

**Comment by SergeGautherie** [comment]
> Is it possible to change it back to value 2 or could you release a version with optional value for us?

You can edit the inf file yourself, before install. Try it and report the result. Thanks.

**Comment by Tellrec** [comment]
I invited you to private repo in my profile to view minidumps.
I edited the .inf file afterwards, but the issue still persist.

**Comment by MegaZeroX10** [comment]
You can compress it/them as a ZIP archive and attach it here.

**Comment by maharmstone** [comment]
Closing old issues
