### ISSUE TITLE
code analysis warnings

### ISSUE THREAD

**Issue by ariccio** [maharmstone/btrfs#243]
I ran this solution in visual studio code analysis, and found a few interesting, but obvious bugs.

At main.cpp:316 in shellbtrfs, you're passing `sizeof(dllpath)` instead of `countof(dllpath)` or a similar array size macro. 

At devices.cpp:200 in shellbtrfs, you're passing a bytecount instead of an element count to MultiByteToWideChar, as `(int)(ss * sizeof(WCHAR))`.

At send.cpp:435 in shellbtrfs, you're using TerminateThread, and [Raymond Chen will track you down and](https://devblogs.microsoft.com/oldnewthing/?p=91811) [condemn your code](https://devblogs.microsoft.com/oldnewthing/?p=293) like Liam Nesson in Taken.

At compress.c:282 in btrfs, you have a bad format string (it's a minor issue), where you're passing a 32 bit uint to a 64 bit format specifier.

At BTRFS.c:451, you're mixing signed and unsigned integers, and similarly at 3006, 3150, 3438, 3543, 3835, 3946, 3953, 4500, and 4563

At BTRFS.c:4211, you're not initializing the output parameter `*pno_pnp` in this path.

~~At fsctl.c:315 in btrfs, you're not holding the `vcb->tree_lock` lock, and as best as I can tell none of the parent functions acquire it either. Similarly at line 329, 355, 360,  371, and 435. At 435, you're also missing the `fcb_lock`~~

There are a ton of other little things, but those seem like the most important.

**Comment by maharmstone** [comment]
Thanks a lot for this - all the valid items should be fixed now.

> At send.cpp:435 in shellbtrfs, you're using TerminateThread, and Raymond Chen will track you down and condemn your code like Liam Nesson in Taken.

I don't think there should be an issue here - the thread in question does little more than call into the kernel.

> At BTRFS.c:451, you're mixing signed and unsigned integers, and similarly at 3006, 3150, 3438, 3543, 3835, 3946, 3953, 4500, and 4563

I don't know what it's going on about here - I'm comparing size_t to uint16_t, both of which are unsigned. It looks to be a bug in the analyser. GCC doesn't flag any problems here.

> At BTRFS.c:4211, you're not initializing the output parameter *pno_pnp in this path.

No, because it's set to false in the caller.
