### ISSUE TITLE
BSOD when using Rufus on a USB drive with mounted Btrfs partition

### ISSUE THREAD

**Issue by damian101** [maharmstone/btrfs#246]
This happened with WinBtrfs v1.7.1 and Rufus 3.9.

**Comment by maharmstone** [comment]
Can you send a minidump please?

**Comment by damian101** [comment]
@maharmstone The system where this issue happens doesn't seem to save any minidumps, I even checked the settings.
The BSOD points to exfat.sys as the cause of the crash. The issue can be replicated on that system, but doesn't happen on my other system, both of them have a mounted exFAT partition.

**Comment by wodim** [comment]
I have a hard disk connected via USB to my computer. That hard disk has a btrfs partition in it. If I pass control of said hard disk to a vmware guest, I get a BSOD. May it be related? And no, I don't have a minidump.

**Comment by maharmstone** [comment]
Closing old issues
