### ISSUE TITLE
Crashes on shutdown

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/btrfs#247]
*subject*

I have had a few crashes occur in the past week when using v1.7.1 on Windows 7 x64. The minidumps are attached as a ZIP archive.

[Minidump.zip](https://github.com/maharmstone/btrfs/files/4398161/Minidump.zip)

**Comment by maharmstone** [comment]
Thanks, I'll have a look

**Comment by MegaZeroX10** [comment]
I changed the title since it happens on shutdown and also when detaching an attached BTRFS formatted VHD after replacing a file that is stored in it, etc.

**Comment by maharmstone** [comment]
I've changed it back, as you can't unload filesystem drivers on Windows.

**Comment by MegaZeroX10** [comment]
Oh, okay. Then why does it crash when detaching the VHD? Is it the same thing that is occurring when shutting down?

**Comment by MegaZeroX10** [comment]
Do any of the latest commits fix it or are you still working on it?

**Comment by MegaZeroX10** [comment]
Were you able to fix it?

**Comment by blackerking** [comment]
Hey there,
got also BSOD on Windows 10 X64. WHen disconnecting an external HDD(safe or unsafe).

**Comment by ElpizoZ** [comment]
I am not getting it to crash on shutdown when using v1.7.3.

**Comment by maharmstone** [comment]
Great - I made some PNP changes on the latest version, hopefully that fixed it.
