### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by Chaython** [maharmstone/btrfs#248]
When a compression type is set to 0, how does the FS/driver determine which compression to use? Is it per file? Why does it refuse to compress certain files? [forcing compression of a folder using the folder's properties didn't work], only copying new files to the drive auto compress.

An example 
```
Star Wars - Dark Forces [GOG] 83.4mb
I selected [3]Zstd in regedit copied the game to the partition. 
It compressed to 41.7mb
inline 11,500 bytes
uncompressed 6mb
0
0
Zstd 35.7mb
```
Why did it refuse to compress certain files?
Checking some files it refused to compress GOGDOSConfig.exe [2.85 MB (2,989,648 bytes)] however WinBTRFS compressed every other .exe in the dir...

If anyone wanted a comparison of Zstd[3] to Compact[LZX](NTFS) is 40.9mb
GOGDOSConfig.exe in NTFS is compressed to 2.80 MB (2,945,024 bytes) by LZX
The small savings in LZX obviously came from compressing every file 

I was also wondering, do the compression levels match that of 7Zip-Zstd has 22 levels [PeaZip only has 19]. So Zstdlevel is 3/22? Or do you use your own/different levels? Levels in regedit are to be written in decimal?

**Comment by maharmstone** [comment]
IIRC, the heuristics about whether to use compression or not match those of the Linux driver, so you're best off checking the official FAQs first. For your incompressible file, it will have tried to compress the first 128 KB, and when it failed to make it any smaller marked the whole file as `nocompress`.

> I was also wondering, do the compression levels match that of 7Zip-Zstd has 22 levels [PeaZip only has 19].
More than likely. I haven't altered the zstd library any, and I doubt they have either.

>Levels in regedit are to be written in decimal?
`ZstdLevel` is a DWORD - this is in the README.
