### ISSUE TITLE
Driver installed with nothing happened

### ISSUE THREAD

**Issue by LXY1226** [maharmstone/btrfs#251]
I installed driver with right-click inf, and install. It shows me a dialog with _Operation successfully finished._ But btrfs volumes are still inaccessable as driver not install.
ubtrfs.dll shellbtrfs.dll mkbtrfs.exe btrfs.sys are in correct place (system32), the services mentioned in Uninstall section is also appeared with Start = 1

So could it be solved and more information is required?

_Sorry for bad english_

Edit: there is no _Btrfs controller_ under _Storage volumes_ in _Device Manager_ ...

**Comment by maharmstone** [comment]
Have you restarted? It seems that sometimes you need to, even if it doesn't prompt you.

What does `sc query btrfs` say?

**Comment by LXY1226** [comment]
Yes i've been restarted several times.
sc query btrfs :

```
SERVICE_NAME: btrfs
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by maharmstone** [comment]
Right, so it's installed but won't run. What does `sc start btrfs` say?

Can you please also give me the exact version of Windows you're using? `winver` will tell you.

**Comment by LXY1226** [comment]
Oh it shows there has an signing error I will try to disable secure boot

**Comment by maharmstone** [comment]
I'm closing this issue. Re-open if it still doesn't work with Secure Boot disabled.

**Comment by DuIslingr** [comment]
@maharmstone Installed through chocolatey, 
https://i.imgur.com/smJT6kf.png

sc query btrfs reports nothing

Manual install fails with some generic error that the data is invalid.
