### ISSUE TITLE
Windows Defender: Virus detected in release download 1.7.2

### ISSUE THREAD

**Issue by Spafbi** [maharmstone/btrfs#252]
![image](https://user-images.githubusercontent.com/11760047/79051397-abef1d80-7bf5-11ea-88be-fc73b57ef22e.png)

No virus is detected in the 1.7.1 release. This may be a false positive, but multiple downloads, using browsers or chocolately, both result in the downloaded resource being detected as having a trojan.

**Comment by ale5000-git** [comment]
Detected only by 11/63: https://www.virustotal.com/gui/file/9c48cd30330dbe603108449bac9ab9d192d52326583c27eb1c47071c0ba7dd65/detection

**Comment by ale5000-git** [comment]
Additionally the virus is only detected in the x86 version of mkbtrfs.exe.

**Comment by maharmstone** [comment]
Not this again... virus checkers love to pick on this file, for some reason.

This is a false positive - the only thing that changed in mkbtrfs.exe between 1.7.1 and 1.7.2 was the version number:

```
$ objdump -M intel -d 1.7.1/Release/x86/mkbtrfs.exe > 171.txt
$ objdump -M intel -d 1.7.2/Release/x86/mkbtrfs.exe > 172.txt
$ diff -u 171.txt 172.txt
--- 171.txt     2020-04-11 20:44:56.836554594 +0100
+++ 172.txt     2020-04-11 20:45:02.402594144 +0100
@@ -1,5 +1,5 @@
 
-1.7.1/Release/x86/mkbtrfs.exe:     file format pei-i386
+1.7.2/Release/x86/mkbtrfs.exe:     file format pei-i386
 
 
 Disassembly of section .text:
```

@Spafbi, could this be a false positive that they've since fixed? I've checked using Windows Defender on my clean 1909 VM, and it didn't find anything.

**Comment by maharmstone** [comment]
There's a thread at https://github.com/pyinstaller/pyinstaller/issues/4633, where the developers of another piece of open-source software are venting their frustrations at the same false positive.

I'm going to close this as there's nothing I can do. @Spafbi, you can log it as an issue with Microsoft if you like, but good luck with that. My advice would be to disable Windows Defender and use a better anti-virus tool - ClamAV's never steered me wrong, if you're looking for one.

**Comment by ale5000-git** [comment]
[Here](https://www.virustotal.com/gui/file/223f8e0749ed836d17c6e336693bf0bcd9a1bb725e0e5b9e6176c8523d9b64ba/behavior/VirusTotal%20Jujubox) in the behaviour detection it detect `C:\Windows\system32\cmd.exe`, is it possible that this help false positives?

**Comment by h-vetinari** [comment]
Sorry for not having seen this:

> @maharmstone: This is a false positive - the only thing that changed in mkbtrfs.exe between 1.7.1 and 1.7.2 was the version number:

For me, the same warning appears upon unpacking 1.7.1 and 1.7.0 as well.
