### ISSUE TITLE
Compression ComboBox style in BTRFS Properties shall be set to CBS_DROPDOWNLIST (shall not be editable)

### ISSUE THREAD

**Issue by KyleKatarn31** [maharmstone/btrfs#255]
Compression ComboBox style in BTRFS Properties shall be set to CBS_DROPDOWNLIST (shall not be editable)

See PR in reactOS : https://github.com/reactos/reactos/pull/2677 and associated Jira ticket : https://jira.reactos.org/browse/CORE-16971

Would you accept to do the change "upstream" in BTRFS ?

In shellbtrfs/shellbtrfs.rc  
COMBOBOX        IDC_COMPRESS_TYPE,63,245,48,13,CBS_DROPDOWN | WS_VSCROLL | WS_TABSTOP
to be changed in 
COMBOBOX        IDC_COMPRESS_TYPE,63,245,48,13,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP

I can provide a pull request for that if needed.

**Comment by KyleKatarn31** [comment]
@maharmstone : What's your view on this ?

**Comment by SergeGautherie** [comment]
> I can provide a pull request

Why not simply do that?

**Comment by KyleKatarn31** [comment]
Because I saw "no open PR"... but yes, you're right, i'll do it tomorrow for sure !

**Comment by KyleKatarn31** [comment]
PR created : https://github.com/maharmstone/btrfs/pull/258

**Comment by KyleKatarn31** [comment]
Any schedule for reviewing / integrating the above mentionned PR ? Thanks !

**Comment by KyleKatarn31** [comment]
Any roadmap for review and integration of this PR ?

**Comment by maharmstone** [comment]
It'll be done some time before the next release. I appreciate you sending a patch, but I've been busy with other things, and cosmetic changes are always going to be low priority.

**Comment by KyleKatarn31** [comment]
OK, very clear.
Expected time frame for next release ?

**Comment by ElpizoZ** [comment]
I can confirm that this issue has been fixed in 1.7.3.

**Comment by maharmstone** [comment]
@ElpizoZ, you have been told in both your previous incarnations not to spam the comments. If I ever decide that I need you to mind them for me, I'll be in touch.

**Comment by ElpizoZ** [comment]
So, I can't let you know that an issue is no longer occurring?
