### ISSUE TITLE
"Found new hardware" window freezes

### ISSUE THREAD

**Issue by M95D** [maharmstone/btrfs#257]
Hi.
I'm trying to install v1.7.2 on Win2003 x64. I installed the driver via right-click - install, then rebooted.
There is a btrfs volume present in the system: raid10 on 4x 500GB drives (whole drives, not partitions). It was created by Gentoo with "-m raid10 -d raid10 --sectorsize 4096".
The disks are not initalised in Disk Management. I don't think initialising them is a good ideea.

After reboot, "Found new hardware" window pops up. I point to the path where btrfs is extracted and it installs "Btrfs volume", then, a second "Found new hardware" window appears. This one can't find a compatible driver (by default, or by indicated path) and the only option is to finish without installing  a driver. As soon as I press "Finish", the window freezes. Not the whole computer, just that window. It can be "end task"-ed with no bad consequences.
The yellow device it failed to install is Device Instance ID: ROOT/BTRFS/0000. By displaying device tree, Btrfs volume appears attached to this yellow unknown device.
I tried to force-install "Btrfs controller", but the window hangs while copying files. The progress indicator reaches the end but it never finishes. This window is not frozen, but there's no other option but to force-close it.

**Comment by maharmstone** [comment]
What does `sc start btrfs` say - is it running?

**Comment by M95D** [comment]
Already running.

**Comment by maharmstone** [comment]
Closing old issues
