### ISSUE TITLE
copy large file stuck

### ISSUE THREAD

**Issue by novhy** [maharmstone/btrfs#259]
when i try copy many large file some times it stuck,to resolve i had to reboot the machine
when its stopped copying files, drive usage in task manager is 100% but no write activity

but when i use terracopy, all files copied without errors, but some times it freeze for a while,then continue

**Comment by ElpizoZ** [comment]
I was able to copy 3 3-4 GB ISOs to a 16 GB SD card formatted as BTRFS with no hangs occurring. The version of the driver is 1.7.3 and the OS is Windows 10 x64.

**Comment by novhy** [comment]
![Untitled](https://user-images.githubusercontent.com/7148317/87202794-81634c80-c32b-11ea-9eb7-dc524c1588b9.jpg)

updated to latest driver,
windows 10 1909,

still stuck at large files larger than 2G
BSOD when i try to reboot pc

**Comment by maharmstone** [comment]
Closing old issues
