### ISSUE TITLE
Cannot compile ReactOS using ReactOS Build Environment on BTRFS partition

### ISSUE THREAD

**Issue by ElpizoZ** [maharmstone/btrfs#264]
I am running into error(s) when trying to compile ReactOS using ReactOS Build Environment v2.2.0 (https://sourceforge.net/projects/reactos/files/RosBE-Windows/i386/2.2.0/RosBE-2.2.0.exe/download) when using the source code that is on a BTRFS partition. The version of the BTRFS driver that is being used is 1.7.3 and the OS is Windows 7 x86. The errors I am getting are "ninja: build stopped: subcommand failed", rsym.exe crashing, and "permission denied". If I try again, it continues and then fails (I will edit it again if I am able to repeatedly run ninja bootcd until it compiles the ISO). I am able to replicate it using the following steps:

1. Download ReactOS Build Environment.
2. Create a 8 GB VHD that has a RAW file system (which is done by choosing to not format it when prompted) with the MBR layout.
3. Open a Command Prompt.
4. Type format /FS:BTRFS DRIVE (replace DRIVE with the drive letter assigned to the VHD) and press Y.
5. Close the Command Prompt.
6. Clone or download and extract ReactOS' repository (which is located at https://github.com/reactos/reactos.git) to the root directory of the VHD that is mounted.
7. Install ReactOS Build Environment and set the source directory to the location that it was downloaded to in the previous step.
8. Run ReactOS Build Environment.
9. Run configure.
10. Type cd output-mingw-i386 and press Enter.
11. Run ninja bootcd.

**Comment by maharmstone** [comment]
Can you isolate which specific command it is that's failing? Presumably one involving rsym?

**Comment by ElpizoZ** [comment]
I am not able to get to that point. It keeps failing on "Generating evtmsgstr.h, evtmsgstr.rc".

**Comment by maharmstone** [comment]
Closing old issues
