### ISSUE TITLE
Driver signature: installation works but cannot be used on later windows versions

### ISSUE THREAD

**Issue by h-vetinari** [maharmstone/btrfs#270]
This is IMO not a duplicate of #114, since the installation part works, but then the drive cannot be recognized by windows - even though ultimately the underlying reason is the same: the driver signature.

I know that it's possible to use with Secure Boot turned off, but that seems to be an unnecessarily big hammer just to use _one_ unsigned driver (I also know that Microsoft is to blame for this policy).

Finally, I understand (from the README and responses by @maharmstone on the tracker) that this is a very annoying topic.

So this issue is about discussing/finding ways to get that driver certification after all. It does not seem completely impossible (for example, https://github.com/veracrypt/VeraCrypt/ is also essentially a one-man operation, yet has a working certificate). If it's a matter of money, maybe some people would participate in a crowd-funding effort, etc.

**Comment by maharmstone** [comment]
It'll be interesting to see if <a href="https://github.com/maharmstone/quibble">Quibble</a> solves this problem, once it's finished off. You can't use Quibble with Secure Boot at the moment as it still relies on the UEFI CSM, but once this is fixed we should be able to have whatever signing requirements we want.

Later versions of Windows 10 do check the drivers that the bootloader has loaded, but it's not clear what it's doing. I doubt it's sophisticated enough to be the full verification, including rejecting non-EV certificates if it's Secure Boot, but it's something I want to look into.

Finally, I do half-remember reading an article where someone had tricked Windows into accepting his driver by adding the driver signature to his UEFI keys, but unfortunately I can't find it now...

**Comment by mys721tx** [comment]
Alternatively would it be possible to set up a legal entity, such as a foundation, for the project so that a signature can be obtained from Microsoft?

**Comment by TheCakeIsNaOH** [comment]
Cross signed drivers (which winbtrfs is AFAIK), are still allowed in a couple of cases even on the latest Windows 10:
- Secure boot off
- Windows was installed pre win10 1607 and then upgraded to past 1607
- The driver was signed with a 2015 or older certificate 
- The driver is used at boot (ie raid driver)
- A specific registry key is set. Microsoft has not said/documented it, but presumably, this is the method it uses to determine if it was upgraded.

Setting the reg key is definitely the most palatable option. 
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000001
```

See this page for more info: https://www.geoffchappell.com/notes/security/whqlsettings/index.htm

**Comment by hv0905** [comment]
> Cross signed drivers (which winbtrfs is AFAIK), are still allowed in a couple of cases even on the latest Windows 10:
> 
> * Secure boot off
> * Windows was installed pre win10 1607 and then upgraded to past 1607
> * The driver was signed with a 2015 or older certificate
> * The driver is used at boot (ie raid driver)
> * A specific registry key is set. Microsoft has not said/documented it, but presumably, this is the method it uses to determine if it was upgraded.
> 
> Setting the reg key is definitely the most palatable option.
> 
> ```
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
> "UpgradedSystem"=dword:00000001
> ```
> 
> See this page for more info: https://www.geoffchappell.com/notes/security/whqlsettings/index.htm

Works on win10 20H2, this should be the ultimate way to solve the signing problem.

**Comment by Hyask** [comment]
> ```
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
> "UpgradedSystem"=dword:00000001
> ```
> 
> See this page for more info: https://www.geoffchappell.com/notes/security/whqlsettings/index.htm

This worked also on a 1909. This trick probably deserves more visibility.

**Comment by maharmstone** [comment]
Thanks @TheCakeIsNaOH, this does indeed work like a charm. I've added it to the README.

Closing this now, as this issue is essentially fixed.

**Comment by fhihu** [comment]
Hello, does this procedure still work on Windows 11.

I installed the driver and added this value in the registry "[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000001"

But it doesn't seems to work on my Computer. I added DWORD  and "Value 64 bit" and the value is hexadezimal. Is this correct?

thank you very much

**Comment by TheCakeIsNaOH** [comment]
> I added DWORD and "Value 64 bit" and the value is hexadezimal. Is this correct?

A `DWORD` is a 32-bit value, a 64-bit value is called a `QWORD`, so check which was actually created.
And yes, hexadecimal is correct.
