### ISSUE TITLE
Unable to format in VirtualBox Windows 10 guest

### ISSUE THREAD

**Issue by MakiseKurisu** [maharmstone/btrfs#271]
Just did a fresh install of Windows 10 2004 Professional 32-bits edition (Chinese language if that matters) and VirtualBox 6.1.10.

After installing btrfs (by right clicking btrfs.inf and click Install) and rebooting, neither `mkbtrfs` nor `format /fs:btrfs` works.

`mkbtrfs` outputs `Unable to load ubtrfs.dll` message, and I double checked that ubtrfs.dll is in System32 folder.

`format` says something like format cannot be used for btrfs. That message is the same as the message when you execute `format /fs:random_fs`, so the filesystem doesn't seem to be registered, at least for format.

I tested VHD file mounted by Windows and VDI file mounted by VirtualBox and none of them works. I tried formatting VHD in my physical machine (1909 and 2004) then copying to VM and it **can be** mounted.

I'm currently working on #221 to fix VeraCrypt, so not being able to format is a low priority issue for me.

**Comment by maharmstone** [comment]
Closing old issues

**Comment by sskras** [comment]
@MakiseKurisu, did you eventually resolved this issue? Looks pretty interesting to me.

**Comment by MakiseKurisu** [comment]
I'm now a full time NixOS enjoyer.
