### ISSUE TITLE
Invalid parameters to RtlUpcaseUnicodeString() trigger ASSERT in ReactOS

### ISSUE THREAD

**Issue by MaxPower2005** [maharmstone/btrfs#276]
Some applications trigger an ASSERT in the ReactOS kernel when using WinBtrFS.
According to the ReactOS devs, this is caused by invalid parameters to the RtlUpcaseUnicodeString() call, as for example here https://github.com/maharmstone/btrfs/blob/e8a848e8b8dc9e884a80b9edacd274d4e2721d7b/src/create.c#L190

Please see https://jira.reactos.org/browse/CORE-17145 for more details.

**Comment by MaxPower2005** [comment]
Is it a valid use case for [find_file_in_dir()](https://github.com/maharmstone/btrfs/blob/master/src/create.c#L181) be called with an empty filename parameter?

If not, would something as shown below be an acceptable fix?

`diff --git a/drivers/filesystems/btrfs/create.c b/drivers/filesystems/btrfs/create.c
index 082159053b..537d96a4cc 100644
--- a/drivers/filesystems/btrfs/create.c
+++ b/drivers/filesystems/btrfs/create.c
@@ -184,6 +184,10 @@ NTSTATUS find_file_in_dir(PUNICODE_STRING filename, fcb* fcb, root** subvol, uin
     uint8_t c;
     bool locked = false;
 
+    if (!filename->Length)
+        // files without a name are not found!
+        return STATUS_OBJECT_NAME_NOT_FOUND;
+
     if (!case_sensitive) {
         Status = RtlUpcaseUnicodeString(&fnus, filename, true);
`

**Comment by maharmstone** [comment]
What path is ReactOS trying to open when it triggers this assertion?

**Comment by MaxPower2005** [comment]
Attached is a log of the last few BtrFS messages.
The INT3 breakpoint triggers if the "filename" parameter of find_file_in_dir() has length 0.

**Comment by maharmstone** [comment]
Thanks for this. Fixed by https://github.com/maharmstone/btrfs/commit/15e9aa35de6ca509e93d1703ea67c0477abe9503
