### ISSUE TITLE
Winamp 5.666 doesn't work on a BTRFS partition

### ISSUE THREAD

**Issue by Vile2341** [maharmstone/btrfs#279]
When trying to run the version available at http://winamp.meggamusic.co.uk/winamp5666_full_en-us_redux.exe, it gives an error about not being able to load a library. It is because it doesn't have short filename support.

**Comment by maharmstone** [comment]
For the sake of anybody who has found their way here from https://jira.reactos.org/browse/CORE-14956...

It's 2020, a full 26 years after long filenames were introduced. I'm not going to add 8.3 support.
