### ISSUE TITLE
Issue relocating "Users" folder to Btrfs partition

### ISSUE THREAD

**Issue by lectrode** [maharmstone/btrfs#28]
When the partition is Btrfs, Windows fails to move the Users folder to that partition. There is no issue when the partition is NTFS.

Tested with Windows 10 Pro (both 32 bit and 64 bit). I have not tried other versions of Windows.
The issue is present with both 0.5 and 0.6 Btrfs driver versions

Steps to reproduce the issue (works on both hardware and VM):
(based on http://www.tenforums.com/tutorials/1964-users-folder-move-location-windows-10-a.html )
1. Fresh install Windows 10
2. At the first install wizard:
   - Remove Windows install media
   - Insert Linux Live CD
   - hit Ctrl Shift F3 to enter Audit mode
3. When it restarts, boot into Linux Live CD
   - (To make things easier for multiple tests, you might want to shutdown the VM at this point and archive it so you can extract it and come back to this point later)
4. Create a new "shared" partition (Either NTFS or Btrfs)
5. Restart and continue into Audit mode
6. Enable Testing mode, restart
   - run as admin: `bcdedit -set TESTSIGNING ON`
7. Install Btrfs driver, restart
8. Still in audit mode, use sysprep with an unattend file to move C:\Users to (for example) F:\Users
   - run as admin:
   - `%windir%\system32\sysprep\sysprep.exe /oobe /reboot /unattend:F:\relocate.xml`
9. System restarts and comes back to the first install wizard

If at step 4 you created an NTFS partition, walking through the first install wizard ends with creating a new user account and works as it should.

If you created a Btrfs partition, it will not get to creating a new user. Instead, it will get stuck in a first wizard loop. A difference between 0.5 and 0.6: with 0.5 Windows does not successfully move all files to the Btrfs partition. Looks like with 0.6 it does successfully move everything.

Here's an example relocate.xml file to relocate the Users folder:

```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
<settings pass="oobeSystem">
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<FolderLocations>
<ProfilesDirectory>F:\Users</ProfilesDirectory>
</FolderLocations>
</component>
</settings>
<cpi:offlineImage cpi:source="wim:E:\sources\install.wim#Windows 10 Pro" xmlns:cpi="urn:schemas-microsoft-com:cpi" />
</unattend>
```

There are 3 things you may need to change to reflect your setup:
- `processorArchitecture="amd64"`  may need to be `processorArchitecture="x86"` if using 32bit
- `<ProfilesDirectory>F:\Users</ProfilesDirectory>` will need to have the drive letter of the target partition
- `cpi:source="wim:E:\sources\install.wim#Windows 10 Pro"` 
  - The `#Windows 10 Pro` needs to be the correct edition
  - `E:\sources\install.win` path needs to point to an accessible install.wim file

Let me know if you need clarification on anything, or if there's anything I can do to help.

**Comment by maharmstone** [comment]
Can you try on the version I've just released, please? There's a number of fixes in it relating to the Users directory in particular.

**Comment by lectrode** [comment]
Sorry for the delayed response. I've tested the procedure outlined above with the latest build (as of this post: 0.10).

## Updated test results

### Systems tested: Windows 10 1703 x64, Windows 10 1607 x64

* NTFS - Works

* Btrfs (Driver 0.10) - Windows fails to finish configuring the installation
  * ![btrfs010-1703](https://user-images.githubusercontent.com/11493925/29095170-d2af6ffa-7c44-11e7-8dc9-7915f71cc6d1.png)

* ![btrfs010-1703b](https://user-images.githubusercontent.com/11493925/29095173-d6b67c9c-7c44-11e7-82b2-24ab46c4c768.png)

Looking at the partitions after the fact, looks like the Users folder was not moved at all. It wasn't even created on the Btrfs volume, although there was a `$RECYCLE.BIN` and `Sytem Volume Information` successfully created on the Btrfs volume.

Doesn't look like it is getting as far as it was at 0.6.

**Comment by maharmstone** [comment]
I'd forgotten about this. Yes, you're right - I'm getting the same blank error box that you are. I'll take a look.

**Comment by maharmstone** [comment]
I'm pleased to say that this is now working as of https://github.com/maharmstone/btrfs/commit/23b89771619e12a0700ab8d992b3df45a42cc2ae. That was a tough one!
