### ISSUE TITLE
send and receive?

### ISSUE THREAD

**Issue by MarcWeber** [maharmstone/btrfs#284]
Would you mind adding a short howto use send/receive ?

1) I tried creating a snapshot
2) I tried right mouse button send subvolume
3) hit the 'not readonly' message (which is fine ...)

didn't find the -r flag in to create readonly snapshot.

Either I failed finding it or it would be nice having it.
Eg 2 right mouse button menu entries 1) create writable snapshot 2) create readonly snapshot)
and have a command line .

Anyway: Well done. Didn't hit any issue till now.

Minimal example like the what is difference -c -p here https://btrfs.wiki.kernel.org/index.php/FAQ#What_is_the_difference_between_-c_and_-p_in_send.3F would be enough.

So does it require changing the registry and rebooting for now ?

**Comment by ticpu** [comment]
Oh no, you just need to make the subvolume read-only later on by the going in Property of the subvolume, Btrfs tab has a Read-only checkbox. Then the send work albeit the fact that you can't pipe it to another application, it has to be saved raw.

**Comment by MarcWeber** [comment]
I update the driver today. I tried again. But I still don't get it. On linux you can send and tell btrfs-send what subvolume contents are already on the target. This way you can create/send a differential archive. I created data created two snapshots, right click -> btrfs -> readonly and changed files. Then rmb btrfs send -> [x] incremental in the list only the subvolume I clicked on appears, but not the ones which eventually might be on the target. Am I missing something ?

**Comment by maharmstone** [comment]
Closing old issues
