### ISSUE TITLE
Unable to install on 2004

### ISSUE THREAD

**Issue by syqe** [maharmstone/btrfs#287]
Has it been tried on Windows 10 2004 build? 

I've tried to install it manually and via choco and even though I always get a success message I do not see any new hardware driver installed or noticeable change on drive mapping.

Is there a workaround, glitch, caveat for 2004?

Thanks

**Comment by madsl** [comment]
I had to boot with driver signature verification disabled on 2004 to make it install, but when I did it worked nicely. You only have to do it once for installing it and then it's a done deal.

**Comment by madsl** [comment]
It might have nothing to do with driver signature verification - I'm not sure. When I tried again, it seems like it works like this:
1) first try to install it, it will give an error message at the end
2) reboot
3) installing it again, it will install with no trouble

**Comment by jcurl** [comment]
I couldn't get it to install on Windows 10 v2004 (x64 Enterprise), when using a Virtual Machine VMWare. UEFI is used with SecureBoot disabled. Right click on the btrfs.inf file, and it fails the installation saying "The data is invalid.". The same happens with v1.7.4 debug and non-debug ZIP files.

I reboot, as suggested earlier, and try installing it. It now says it installed successfully. I go to Device Manager, under "Storage Volumes", there's the "Btrfs controller" with a yellow exclamation (!). 

> This device is not working properly because Windows cannot load the drives required for this device. (Code 31). The request is not supported.

So let's try rebooting (do a restart, not shutdown and power off which is just a hibernate).

And it now works.

**Comment by LinHeLurking** [comment]
Many thanks for @jcurl !
I ran into the same yellow exclamation mark and warning messages. Then rebooting windows twice solves this problem. Now it works though it's weird.

**Comment by Oxalin** [comment]
Same as issue #296

**Comment by maharmstone** [comment]
The need to reboot is fixed by https://github.com/maharmstone/btrfs/commit/ffa220b5d78110570567259cd0d658806d0fefd3.
