### ISSUE TITLE
Some files are written compressed even when compress option is unchecked in subvolume settings

### ISSUE THREAD

**Issue by GeorgeGhost** [maharmstone/btrfs#288]
Ways to reproduce:

- Compress is unchecked in subvolume settings
- Downloading a game on steam (Stardew Valley) to the drive caused some files to be zstd compressed and some uncompressed (I've run the "compsize -x" command on linux)
![image](https://user-images.githubusercontent.com/38662696/89643662-f2f8d100-d8be-11ea-9309-5d810eb0b00f.png)

Important as some games refuse to run on windows from btrfs drive if files are compressed

**Comment by maharmstone** [comment]
I don't think this is a bug, it's just that the compression rules are a bit counter-intuitive. You might have the `Compress` option enabled in the Registry, or the files might have been created in a directory which had the compress flag turned on (such as Steam's `downloading` directory).

Does Stardew run fine for you if it's uncompressed?

**Comment by GeorgeGhost** [comment]
Stardew runs fine, but there are other games like HITMAN 2 which just crush or get stuck. Will check the Registry to provide more information when I get back to home

**Comment by GeorgeGhost** [comment]
Checked and the Registry options for Compress and CompressForce were zeroed

**Comment by maharmstone** [comment]
Closing old issues
