### ISSUE TITLE
XAMPP installer creates file with empty ACL

### ISSUE THREAD

**Issue by changsijay** [maharmstone/btrfs#291]
Hi, I installed xampp and set the path to my `D:\xampp` which is btrfs.
After installation, I tried to open the control panel.

It error on cannot open file `D:\xampp\xampp-control.ini`.
I tried to open sublime in admin permission still failed to write it.

Howeever, other files, such as `D:\xampp\readme_en.txt` works fine, I can edit and save it.
Not sure what special about `ini` file?

**Comment by maharmstone** [comment]
Closing old issues
