### ISSUE TITLE
IDC_CONVERT_COMBO only lists 1 letter for each profile

### ISSUE THREAD

**Issue by MakiseKurisu** [maharmstone/btrfs#292]
See image below. This occurred after I upgraded from 1.7.3 to 1.7.4.
![image](https://user-images.githubusercontent.com/2321672/91081351-9c083100-e60c-11ea-8cb8-6153d1bf0783.png)

For people who need to do conversion please reference [this list](https://github.com/maharmstone/btrfs/blob/master/src/shellext/balance.cpp#L497).

**Comment by maharmstone** [comment]
Cheers - this is fixed with today's patches.
