### ISSUE TITLE
Text issue compress properties

### ISSUE THREAD

**Issue by Chaython** [maharmstone/btrfs#295]
since v1.7.4 (2020-08-23)
![image](https://user-images.githubusercontent.com/6486343/91672893-67a1e280-eaee-11ea-9fb5-6fa1619deccb.png)
As you can see instead of the algo it shows a single character, one being a bracket.
I could've sworn before it showed the actual algo's acronym

folder - properties - btrfs properties - flags

**Comment by SergeGautherie** [comment]
Very similar to #292.

**Comment by maharmstone** [comment]
Serge is right, this is the same issue.
