### ISSUE TITLE
Non-Administrative Users can create setuid owned-by-root executables on btrfs filesystems. (Windows 10, Pro)

### ISSUE THREAD

**Issue by perkinslr** [maharmstone/btrfs#299]
As the title says.  If you add a local user, make it *not* an administrator user, and have it make a new file, it can then go into the file properties `btrfs` tab and change the POSIX owner, and the umask flags.  

I have a mapping set in the registry for windows User IDs to POSIX ids, but that doesn't seem to matter.
Anyway, I can work around it by restricting the system partition, not mapping it to a drive, and mounting the data partition noexec on Linux, but a better workaround would be good...

**Comment by maharmstone** [comment]
No, this isn't brilliant, is it? I think probably the uid, gid, and setuid fields should all be restricted by UAC.

**Comment by perkinslr** [comment]
That would make sense.  `gid` is a bit of a harder case, as POSIX users can be in multiple groups.  Ideally you could provide that group mapping and restrict setting the values to valid ones (but that raises issues with the mapping getting out of date...).  It would also be good if non-administrator users couldn't read files they shouldn't have read-access to (like `/etc/shadow`).

**Comment by maharmstone** [comment]
> It would also be good if non-administrator users couldn't read files they shouldn't have read-access to (like `/etc/shadow`).

That's a different issue, i.e. mapping POSIX permissions to NT ones, which is definitely non-trivial. If it's a problem, you can always manually change the security of `/etc/shadow/` in Windows.

**Comment by perkinslr** [comment]
Aye.  The proper solution is to use subvolumes (or separate partitions) to keep anything sensitive hidden in windows by default.  I can't think of a good reason for non-administrator users to have access to Linux's `/` from Windows.

**Comment by maharmstone** [comment]
Closing old issues
