### ISSUE TITLE
Changing Pictures Location forces BTRFS partition to become Read-Only

### ISSUE THREAD

**Issue by chz101** [maharmstone/btrfs#300]
When I create a new empty BTRFS partition through Linux and try to set the location of Windows' Pictures directory to point to it, the partition becomes read only and I cannot change or create any files on either Windows or Linux. Unmounting and mounting as read write does not fix anything, and running btrfs check reports no errors.

DebugView also doesn't show any issues when the directory link is changed to a different partition, but I'm not sure if I'm using it correctly.

**Comment by maharmstone** [comment]
Closing old issues
