### ISSUE TITLE
question/feature: preventing windows automatically writing top-level files

### ISSUE THREAD

**Issue by brainchild0** [maharmstone/btrfs#303]
Reviewing the top level of a BTRFS volume previously mounted using WinBtrfs, I find a handful of artifacts of Windows, including items of the following familiar names:

- `System Volume Information`
- `$RECYCLING.BIN`

In one case I find a further item with the following unfamiliar name:

- `$MfeDeepRem`

To a volume used on a Linux system, these items add unwanted clutter.

Is any convenient method available for preventing their creation, and if not, then might  adding a feature for preventing it be considered?

**Comment by maharmstone** [comment]
I think someone might have raised this before... I remember concluding that even though it's a PITA, the driver is only following orders. Even if you were to suppress directory creation, it'd still break the Recycle Bin and whatever on earth it is that `System Volume Information` does.

**Comment by Masamune3210** [comment]
If I remember correctly there is a reg setting to disable it for remote drives but not for local ones. System Volume Information stores anything that windows thinks the normal user shouldn't see as it's hidden, like Chkdsk logs and Data Dedup stuff

**Comment by brainchild0** [comment]
So @maharmstone, are you saying that the driver gets requests to make the directories as though the requests were created by a regular application? Perhaps the driver could give special handling to names from a list of items designated as special. Names in this list might be exposed as being at the top level, but actually mapped into some special location, say `/.winbtrfs`. Then they would be to some degree hidden when mounted in a Linux or similar environment.

**Comment by ticpu** [comment]
> Perhaps the driver could give special handling to names from...

That sounds like a plan for disaster, a blacklist in a driver doesn't evolve well with time and adds some hard-coded logic that doesn't feel right in a filesystem module.

In fact, you shouldn't be using the root subvolume on Linux if you want to manage BTRFS correctly.
Just set yourself default subvolume for Windows to mount. And when using Linux, mount the correct subvolume using subvol=.

**Comment by brainchild0** [comment]
> > Perhaps the driver could give special handling to names from...
> 
> That sounds like a plan for disaster, a blacklist in a driver doesn't evolve well with time and adds some hard-coded logic that doesn't feel right in a filesystem module.

It  would not need to be hard coded, and I agree it should not be.

> 
> In fact, you shouldn't be using the root subvolume on Linux if you want to manage BTRFS correctly.
> Just set yourself default subvolume for Windows to mount. And when using Linux, mount the correct subvolume using subvol=.

I am using a root subvolume, but when Windows starts with   WinBtrfs installed, the top level volume mounts and Windows creates the annoying  directories.

**Comment by ticpu** [comment]
> but when Windows starts with WinBtrfs installed, the top level volume mounts

If you use subvolume set-default to set a new subvolume as default, the top-level subvolume will become $Root on Windows and Windows won't pollute your top level.

**Comment by brainchild0** [comment]
I suppose I could set a default, but there is no particular subvolume that lends itself for that distinction. On a Linux boot, the root file system contains the OS, and mounting during a Windows session is not useful toward the object of sharing data. In either case, Windows still creates these directories. I don't see it as comforting that they are created on some subvolume rather than the top-level volume, since I don't want them anywhere.

**Comment by Masamune3210** [comment]
Unfortunately its just part of messing with a drive on Windows for the most part for the same reason DS_Store folders are a norm when dealing with anything mounted by macos

**Comment by brainchild0** [comment]
> Unfortunately its just part of messing with a drive on Windows for the most part for the same reason DS_Store folders are a norm when dealing with anything mounted by macos

I accept this observation, but I would hesitate to eliminate completely the possibility of a useful and feasible engineering solution.

One idea is that  any directory entries found in `/.winbtrfs` and not found in `/`, the driver would map  to the top level. 

The effect of this solution is that whenever a user boots Linux and notices the extra entries, the user may simply run the following commands:

```
mkdir -p .winbtrfs
mv System\ Volume\ Information .winbtrfs/
```

Then the entries are out of sight in Linux, but not recreated by Windows. The Windows driver would still expose the entries as appearing in `/`.

Many other solutions are possible, and some may be better than the proposed. I am only demonstrating the existence of possibilities.

**Comment by ticpu** [comment]
From my point of view, I'm totally against using the filesystem to control what is being listed by the filesystem, the job of a filesystem is to show you all the files it knows and give you back your data. This is an aesthetic problem due to the fact that there's no "hide this item" flag on Linux. The real place to fix this is in the tool you use to view those file, that's where there should be a way to hide those file by either a chattr or xattr that you could set on the item you want to make invisible.

**Comment by maharmstone** [comment]
@brainchild0, I'm sympathetic, but this isn't something that's going to happen. I'm not going to add code for this purely for the sake of aesthetics.

If it's something you feel strongly about, I suggest you look into writing a filesystem filter driver to do what you want.
