### ISSUE TITLE
question: multiple subvolumes mounted simultaneously 

### ISSUE THREAD

**Issue by brainchild0** [maharmstone/btrfs#304]
Whereas the *Readme* gives instructions for specifying which particular subvolume WinBtrfs will mount in a given volume, I found no indication of how multiple subvolumes might be mounted at once. I suppose Windows probably is  not clever about supporting such kinds of flexibility for a driver, but I wonder whether multiple mounts is possible with WinBtrfs as it is under Linux.

**Comment by maharmstone** [comment]
Yes! `SUBST` is what you're looking for - https://en.wikipedia.org/wiki/SUBST.

**Comment by ticpu** [comment]
And for the other way around, there's Junction: https://docs.microsoft.com/en-us/sysinternals/downloads/junction

**Comment by brainchild0** [comment]
> Yes! `SUBST` is what you're looking for - https://en.wikipedia.org/wiki/SUBST.

So the recommendation is to mount the entire volume to some drive letter, then to use one or more `SUBST` commands to map subvolumes, each to a different driver letter?

**Comment by ticpu** [comment]
> So the recommendation is to mount the entire volume to some drive letter, then to use one or more `SUBST` commands to map subvolumes, each to a different driver letter?

That's basically what Linux does using the VFS, a subvol= mount is in fact a bind mount under the cover.

**Comment by brainchild0** [comment]
I was mainly trying to understand whether the recommended procedure requires committing a drive letter to the top-level volume even if the objective is only to get a drive letter mapped to a subvolume.

**Comment by ash-dvlpr** [comment]
Where can I find more information about how to seting up a `SUBST` for mounting subvolumes?
