### ISSUE TITLE
"catastrophic failure" reported for editing read-only mounts

### ISSUE THREAD

**Issue by brainchild0** [maharmstone/btrfs#305]
I followed instructions for marking a volume as a read-only mount.

After I rebooted the system and tested the change by attempting to create a new folder, the following message appeared:

> An unexpected error is keeping you from creating the folder. If you continue to receive this error, you can use the error code to search for help with this problem.
>
> Error 0x8000FFFF: Catastrophic failure

I am glad that the system declined to create the folder, but the specific message is not proportionate to the effect. Might the driver employ a more straightforward means to mark the mount as read only, such that the system would generate a more appropriate response to attempts to modify the files?

**Comment by maharmstone** [comment]
This is definitely not an error produced by the driver itself. When a write operation is attempted on a readonly volume, the driver returns STATUS_ACCESS_DENIED or STATUS_MEDIA_WRITE_PROTECTED, as it should.

I suggest you identify which program it is that's producing the error, and report it as a bug to them.

**Comment by brainchild0** [comment]
Windows explorer. 

`STATUS_MEDIA_WRITE_PROTECTED` certainly seems to be an appropriate error code for the circumstances.  `STATUS_ACCESS_DENIED` strikes me as slightly less clear.

I was not suggesting that the driver is generating the message provided, only that the likelihood that an application generates an appropriate user message is correlated to the likelihood that a driver generates an appropriate error code, and in this case, the application is not generating an appropriate user message.

**Comment by Chaython** [comment]
I get both this and drive is "write-protected"
It was previously writable, IDK what broke...
![image](https://user-images.githubusercontent.com/6486343/99928847-2a717900-2d08-11eb-8c4a-e58e972d5c96.png)
