### ISSUE TITLE
Is it possible to hide BTRFS drives?

### ISSUE THREAD

**Issue by UnicornsOnLSD** [maharmstone/btrfs#309]
I have 2 BTRFS drives in my system: An SSD that holds my Linux boot and a HDD that I want to share between Linux and Windows. Is it possible for me to tell Windows to ignore the SSD? Windows uses the SSD as the EFI system partition, so that may be an issue.

**Comment by maharmstone** [comment]
Yes - have a look at "Mount Options" in the README.
