### ISSUE TITLE
Create a btrfs volume

### ISSUE THREAD

**Issue by Borph** [maharmstone/btrfs#31]
On Win7, I wanted to try out the btrfs driver without repartitioning. As it already worked with an ext3 volume, I tried a VHD again:
- Created a virtual disk (VHD) (it's dynamicly growing if it matters).
- Attach it.
- Disk manager shows volume with MBR but no partitions.

But how do I create a btrfs volume in it?

**Comment by maharmstone** [comment]
You can't, yet - an equivalent to mkfs.btrfs is on the to-do list. If you just want to test it out, the easiest way is to get a spare pen drive and format that as btrfs under Linux.

**Comment by maharmstone** [comment]
I've just released version 0.8, which includes mkbtrfs.exe which allows you to do this.

**Comment by Borph** [comment]
Thanks! It said "Completed successfully." But have problems mounting now. Ok, didn't start Win7 x64 in test mode. Executed 'launcher.exe' as admin, formatted with mkbtrfs.exe, but filesystem is still "RAW", explorer won't access, and although I changed partition type with diskpart to 07 no change.

Maybe wrong way of doing? I attached a VHD file, created a partition in it, but didn't format. Assigned a drive letter. Called "mkbtrfs.exe N: btrfsvol". Tried to restart explorer, but no success.

**Comment by maharmstone** [comment]
You *didn't* start Windows in test mode - was that a typo? It won't work otherwise.

Can you please check if the driver is actually loaded? Download WinObj from Sysinternals, run it as Admin, and see if there is a Btrfs entry under Filesystems. Thanks

**Comment by Borph** [comment]
Right, I misunderstood the "try out" chapter and didn't have Windows in test mode - so my bad. In test mode the driver and the volume worked.

I successfully copied a file, created a hardlink, but FYI creating a softlink with "ln -s a b" freezed, using the Git bash shell.

**Comment by maharmstone** [comment]
Great. When you say it froze, do you mean just bash, the FS (i.e. you can't browse the drive any more in Explorer), or the whole OS? Does it do the same thing if you try it again?

**Comment by Borph** [comment]
The FS I suppose, couldn't browse, another shell (cygwin) froze when doing autocompletion on "cd", had to reboot. Didn't try again, no time, but can test something for you if you give instructions.

**Comment by smischke** [comment]
Great work!

Is is possible to create a raid volume? Something like this:
`mkbtrfs -f -d raid5 -m raid5 -L RAID5 \Device\Harddisk5\Partition0 \Device\Harddisk6\Partition0 \Device\Harddisk7\Partition0 \Device\Harddisk8\Partition0`

**Comment by maharmstone** [comment]
Yes - create the FS on the first disk, then in volume properties add the others and balance to RAID 5.
