### ISSUE TITLE
Cannot Set Execute Bit via WSL, no problems with GUI in Explorer

### ISSUE THREAD

**Issue by TheConner** [maharmstone/btrfs#310]
Let's say I have a simple bash script, or anything else that could be marked as executable:
```bash
#!/bin/bash
echo "Hello world"
pwd
echo "Goodbye world"
```
In WSL I can create a file with these contents on a WinBTRFS volume without issue. Permissions of the created file:
```
$ ls -al
total 4
drwxr-xr-x 1 conner conner 4096 Oct  4 15:32 ./
drwxr-xr-x 1 conner conner 4096 Oct  4 15:31 ../
-rw-r--r-- 1 conner conner   56 Oct  4 15:32 test.sh
```

However, when I try to mark it as executable it does not work:
```
$ chmod +x test.sh
$ ./test.sh
fish: The file “./test.sh” is not executable by this user
```
If I go through the UI in explorer, I can go and manually set the execute bit by clicking my crudely drawn red circle:
![image](https://user-images.githubusercontent.com/59540839/95028724-46856200-0657-11eb-985a-81f6d9142d02.png)
And then life is good
```
$ ./test.sh
Hello world
/mnt/e/conner/tests
Goodbye world
```

Hopefully this is a clear bug description. Let me know if there's any other questions or things I can check to resolve this :) I love this project by the way! This is incredibly useful for a weird use case like mine

**Comment by maharmstone** [comment]
Thanks. Yes, you're right, it's stopped working again. Microsoft must have made some changes to how WSL works - I'll investigate...

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/3641f5742c862e6dd8c7db3fe81f25af7a470346. Thanks for reporting!
