### ISSUE TITLE
Dual boot : exclude some partitions from the driver

### ISSUE THREAD

**Issue by lapineige** [maharmstone/btrfs#311]
Hello,

I'm using a Dual Boot, Windows 10 + Linux, both using btrfs (thanks to your driver, great work :).

But because of the driver, Windows can now read my Linux files (because they are not encrypted, I would like to avoid that).
I would like to remove that ability.

Is there a way to "reduce the scope" of this driver, in order to make it available/working only for some specified partitions (the windows ones) and not for some other (the linux ones) ?

Thank you in advance

**Comment by maharmstone** [comment]
Yes - have a look under "Mount Options" in the README.

**Comment by lapineige** [comment]
Thanks you, I'll have a look.

(Kind of duplicate of #309 )
