### ISSUE TITLE
File copy fails with "Not enough space" when there is plenty of empty space.

### ISSUE THREAD

**Issue by HubKing** [maharmstone/btrfs#312]
I formatted a new disk as a BTRFS drive (Ubuntu 20.04), and then mounted it on a Windows PC, and then copied files from an old disk to the new disk. All files were copied but 4 files were not copied with a "not enough space" error. The four files were 3 "...csproj.vs10x" text files, and a ".pkg" file The "vs10x" file is just a text file created by an extension. I attach the file (zipped because the site does not allow that extension). I don't think there is anything special about that, so why I get this

![image](https://user-images.githubusercontent.com/10900489/95399840-10402f00-0944-11eb-82c0-eea2de28c282.png)

Of course, there is plenty of space. Copying another file or creating a new file on the disk works, but somehow I cannot copy this specific file. I don't think the source disk is a problem. I copied it to another disk (NTFS), and there was no problem. But when I tried to copy that copied file to the BTRFS drive, I got the exact same error.

Also, file name or extension is probably not the problem, because I tried changing it, but I got the same error. What could be the possible cause of this? If it is of any help, here is the screen recording of this problem: https://imgur.com/a/JRt6tXB

Since the "vs10x" file is an automatically created file, there were many other "vs10x" files on the disk with the exact same data, and they seem to have been copied, so not all "vs10x" files seem to have this problem. Also, there were no same ".pkg" files, so, I am not sure why that file has the same issue.

[AvalonDock35.csproj.vs10x.zip](https://github.com/maharmstone/btrfs/files/5344576/AvalonDock35.csproj.vs10x.zip)

**Comment by maharmstone** [comment]
I think there's probably a hint in the contents of the file...

```
This file contains Alternate Data Streams, storing configuration information used by CodeSMART 10 and VS10X Extensions.
```

As in, I think it's probably failing when creating the ADSes rather than the file itself.

What streams are attached to the file, and how big are they? Try `dir /R` in the NTFS directory.

**Comment by HubKing** [comment]
> What streams are attached to the file, and how big are they? Try `dir /R` in the NTFS directory.

I get the following for `dir /R`.

```
04/08/2011  10:27               142 AvalonDock35.csproj.vs10x
                             26,133 AvalonDock35.csproj.vs10x:codesmart_codemap:$DATA
                             10,867 AvalonDock35.csproj.vs10x:codesmart_global_history:$DATA
```

**Comment by maharmstone** [comment]
```
                             26,133 AvalonDock35.csproj.vs10x:codesmart_codemap:$DATA
```

That'll be why - NTFS allows streams of arbitrary size, whereas on Btrfs they're limited to just under 16 KB. This is part of the design of the filesystem, there's nothing I can do about it.

I suggest you log this as a bug with CodeSMART, it's a pretty bad design flaw for them to by relying on arbitrary-length streams like this. It won't work with three out of Microsoft's four filesystems (FAT, exFAT, ReFS), it won't work if stored on a Samba server, it won't work with Zip files, it won't work with Git...

**Comment by HubKing** [comment]
Thanks.

> It won't work with three out of Microsoft's four filesystems (FAT, exFAT, ReFS)

It worked on ReFS. When I tried to copy it to a FAT32 drive, I got a message like this:

![image](https://user-images.githubusercontent.com/10900489/95491139-2bf31600-09d4-11eb-9768-8f7400175e0f.png)

So, I think it would be better to show a message like that than the current "Not enough space -- 0 bytes required" error. Of course, it would be more helpful if File Explorer could show additional message with that confirmation, like "This file has alternative stream(s) bigger than 16KB, which is the maximum limit of BTRFS", but if showing such custom message on Windows File Explorer is not possible, at least the exact same message as the case of FAT32 would be helpful.

**Comment by maharmstone** [comment]
It won't _necessarily_ work on ReFS - ReFS has the same issue, but its limit is 128KB rather than 16KB.

You can't have custom error messages, unfortunately. I'll have a look what's going on with FAT, but I'm not optimistic - it's returning the error when Explorer tries to create a stream, whereas in the case of Btrfs the error only arises when you try to write to it.

**Comment by ale5000-git** [comment]
@maharmstone: Isn't possible to allow copying it to Btrfs and just dropping the single unsupported ads while still copying the others?

**Comment by maharmstone** [comment]
@ale5000-git - it's entirely possible... but this isn't what Explorer does.

**Comment by ale5000-git** [comment]
If  I'm not wrong it does it (dropping unsupported thing while still copying the file) when copying to FAT32 so there must be a way.
