### ISSUE TITLE
Compiling source with Visual Studio 2019 doesn't work

### ISSUE THREAD

**Issue by Trevomader** [maharmstone/btrfs#313]
Tried to compile "master" and also "tag 1.7.4", none of them worked, it compiles fine but the driver doesn't work.
The utility "serviwin" says the driver is stopped and I can't see my volumes in Windows Explorer and no events in Event Viewer.
Reinstalling your own compiled version makes it work again.

**Comment by maharmstone** [comment]
That's because Windows insists on drivers being signed. If you want to use a version you've compiled yourself, you need to self-sign and boot Windows in TESTSIGNING mode.
