### ISSUE TITLE
System lockup when trying to compile Firefox

### ISSUE THREAD

**Issue by Trevomader** [maharmstone/btrfs#314]
Whenever I try to compile Firefox, the system will lock up, I can still move the mouse but I can't ctrl+alt+del or shutdown the computer by pressing power button, I have to forcibly shutdown by holding the power button.

**Comment by alex4401** [comment]
Seems to be happening almost every time the filesystem is going through a high write load and is committing (or deleting lots of files). I've been experiencing this while compiling Unreal Engine from source, and while I did manage to do that eventually, the filesystem ended up with several missing references on extents.

**Comment by maharmstone** [comment]
I've just tried compiling Firefox, and it gets several minutes in before lld-link fails saying "The filename or extension is too long." Even though it's not. It's not clear what's going on here...

**Comment by maharmstone** [comment]
Could either of you try with the latest version? I suspect this is fixed.

**Comment by alex4401** [comment]
About halfway through a clean UE compilation and haven't encountered a lockup yet, while there's been at least 2 at this point with the previous driver version. Looks promising so far.

**Comment by maharmstone** [comment]
Closing old issues
