### ISSUE TITLE
Successful installation of btrfs has no effect

### ISSUE THREAD

**Issue by JSchmiegel** [maharmstone/btrfs#316]
Hello,
when I try to install winbtrfs (Windows 20H2) the installation process is completed without any problems (success message from the installer is displayed). However, I am not able to access drives with BTRFS afterwards (not even after a reboot).
I have already tried the following (multiple times):
- Installation via chocolatey
- Uninstall via chocolatey
- Installation via btrfs.ini 
- Remove the registry entries and reinstall btrfs.ini
- Reboot after installation

Problem here is I always get a message that btrfs was successfully installed (regardless of installing it with choco or with .ini ), but I can't use it to access any drive.

The only clue I have: 
When I call the following command at the command line to uninstall btrfs.inf :  
`RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultUninstall 132 C:\PathTo\btrefs-1.7.4\btrfs.inf`

Then the following error message appears in the Windows Event manager. 
![image](https://user-images.githubusercontent.com/51242445/97483883-4e83a980-1958-11eb-8864-99f72084d207.png)

Maybe this is completely incoherent, but in the meantime I am really desperate. Can anyone help me? 

P.S.: Unfortunately I can't add a debug log, because the btrfs doesn't write one (There is no C:\btrfs.log) (Maybe it's because I made a mistake during the setup? see picture)
![image](https://user-images.githubusercontent.com/51242445/97484082-90145480-1958-11eb-9cdb-837271cdf348.png)

**Comment by maharmstone** [comment]
Do you have Secure Boot enabled?

**Comment by JSchmiegel** [comment]
Thank you very much for the quick answer. I am a great example for "RTFM". 
Yes Secure Boot was enabled. After deactivating I could simply install btrfs.ini and my drive was recognized correctly. Thanks for the help.
