### ISSUE TITLE
Compatibility: Simple Wall

### ISSUE THREAD

**Issue by Chaython** [maharmstone/btrfs#324]
[Simplewall](https://github.com/henrypp/simplewall) a FOSS GUI for WFP cannot "open containing folder" nor can it detect Firefox "Updater" while it's in BTRFS / compressed, it detects Firefox however.

![image](https://user-images.githubusercontent.com/6486343/99462417-e25deb00-28f0-11eb-8c52-c8015ea075f4.png)
![image](https://user-images.githubusercontent.com/6486343/99462579-3963c000-28f1-11eb-9328-cf1a8967bfbc.png)
It may be more of an issue with Simplewall, but hopefully you can figure it out.
I know it's a niche, but it's great software if you want a Windows firewall...

**Comment by henrypp** [comment]
This is btrfs issue, i think.

simplewall does enumerate registered dos devices through ProcessDeviceMap enumeration https://github.com/henrypp/routine/blame/b77854b58f5f931ea3dcb93b24aa7b2c7c200aab/routine.c#L1891 and as a workaround exactly for a brtfs, which cannot registered in device map, simplewall does enumerate `\GLOBAL??` directory objects https://github.com/henrypp/routine/blame/b77854b58f5f931ea3dcb93b24aa7b2c7c200aab/routine.c#L1949 to find registered drive letter.

As example, TrueCrypt/VeraCrypt does not need this workaround, so brtfs author can dig `TCCreateRootDeviceObject` in it's source code.

**Comment by maharmstone** [comment]
I'd be interested to know if this workaround is still necessary in v.1.7.7. I suspect this is a variant of the Genshin Impact issue.

@henrypp - Is there a particular reason why you call NtQueryInformationProcess? `\??\` is a pseudo-directory which corresponds to the device map of the current process - why can't you just loop from `\??\A:` to `\??\Z:`? You shouldn't have to concern yourself with `\GLOBAL??` at all.

**Comment by Chaython** [comment]
It's still present in 1.7.7, though FF no longer seems to require "updater.exe" to have firewall access in order to update, by going to ff - about.
No icon is displayed, cannot open containing folder, shows as \device\btrfs{9a4303e1-1560-464f-b7c9-b4ca52335b48}\
A similar issue is present with MS store games/apps, where icon isn't displayed, can't open containing folder [though it's fair, as the folder is owned by system, not accessible by user], and is written as \device\harddiskvolume??\ ?? being a new hard disk volume, on every game launch and as there's no wildcard in simplewall, for MS apps, you have to whitelist them every time.
At least BTRFS is persistent.
It's likely an issue just with simplewall, but I posted to both just to be fair to henrypp, also maharmstone, is very smart, so I assumed he'd be able to help regardless of whether it's his issue or not. :P

**Comment by maharmstone** [comment]
Thanks Chaython. It does look like an issue with Simplewall then, if it's doing the same thing with AppContainers. @henrypp, feel free to reopen this if in your investigations you find something that btrfs.sys is doing wrong.
