### ISSUE TITLE
PAGE_FAULT_IN_NONPAGED_AREA with volume mounted read-only

### ISSUE THREAD

**Issue by AWiederin** [maharmstone/btrfs#326]
I have my BTRFS volume mounted read-only in Veracrypt until I can fix everything, but just a bit ago I got the titular BSOD.

Attached is the minidump. Thanks!
[112320-10843-01.zip](https://github.com/maharmstone/btrfs/files/5586204/112320-10843-01.zip)

**Comment by maharmstone** [comment]
Closing old issues
