### ISSUE TITLE
BTRFS Partion Label Length

### ISSUE THREAD

**Issue by FrederikLauber** [maharmstone/btrfs#327]
Hello,
why experimenting with WinBTRFS, I noticed that the length of a label you can assign to a WinBTRFS partition is only 11 characters.
For example, if want to have the name "Stuff Backup2" as a label which works with NTFS but with BTRFS, it gets cut of at "Stuff Backu". Is this an intended limit?

Cheers,

**Comment by maharmstone** [comment]
You're right. No, it's supposed to be 255, but Explorer is limiting the size of the text box for some reason.

**Comment by maharmstone** [comment]
Closing old issues
