### ISSUE TITLE
Cannot create a reflink between two different filesystems.

### ISSUE THREAD

**Issue by KenJyn76** [maharmstone/btrfs#328]
Hey. not sure if this is somehow user error, or I'm not understanding the feature, but I'm trying to make a copy of a game (I have two accounts, and the files are the same across the two launchers, except for two files), so to keep the game versions synced, and avoid having to update twice every time I update, I'm trying to create a reflink. Problem is, my btrfs drive is a RAID drive, created within BTRFS, and I'm getting the error in the title. Maybe the reflink copy isn't recognizing that these two drives are both one BTRFS volume?

**Comment by maharmstone** [comment]
I don't understand... are you saying that you're getting this message when trying to do a reflink copy on the same volume? As in, the paths have the same drive letter?

> avoid having to update twice every time I update

That's not how reflink copies work - from the user's point of view they're functionally identical to normal copies. I think a symlink is probably what you're after.

**Comment by KenJyn76** [comment]
Yes, I'm getting the error trying to create a link with a source and target
on D:.

I know a symlink would likely be better for what I'm after, but I wanted to
experiment with reflinks a little to be honest.

**Comment by KenJyn76** [comment]
I responded while I was at work, I'm pretty sure I was clear, but:

Yes, reflink source and target are on the same volume. Volume is two drives formatted to BTRFS as the same volume, in RAID 0. I'm suspecting what's happening is that the handler is trying to create the reflink on the other drive in the volume, and therefore throwing an error, thinking it's a different volume. I'm just spitballing a little bit though.

Steps to reproduce (if possible):

Format two drives to BTRFS using mkbtrfs
Make both drives into one volume, using the Btrfs section of the Properties dialog
Try to make a reflink on that volume
(Hopefully) see it fail, or not have the option in the context menu appear at all

Command line method, as expected, fails without any error.

**Comment by Chaython** [comment]
.symlinks are working fine for me, what's the benefit of a reflink?

**Comment by TheMadHau5** [comment]
How _do_ you use reflinks? Because I am not able to able to make one using `rundll32` as well (with args: `0 0 "src dest" 0`)

**Comment by maharmstone** [comment]
Closing old issues
