### ISSUE TITLE
WinBtrfs Causing Hanging and BSODs?

### ISSUE THREAD

**Issue by KenJyn76** [maharmstone/btrfs#332]
I've been having hanging and BSODs, relating to storage drivers, primarily while read/writing from my btrfs RAID 0 array. Both drives, as well as the partition health, are fine. I ran driver verifier and was getting BSODs on startup, caused by btrfs.sys.

[The minidump is located here](https://1drv.ms/u/s!AkrrUE8cw8IBjAbuaQHLCB4oefhA?e=jIeNsm)

**Comment by KenJyn76** [comment]
I don't know if this is helpful, but here's the log of a crash, set to Debug Level 2 :

`Starting logging at 2020-12-21 22:17:17
FFFF9C0177B8B040:remove_drive_letter:IOCTL_MOUNTMGR_DELETE_POINTS 1 returned c000000d
FFFF9C0177B8B040:drive_letter_callback2:remove_drive_letter returned c000000d
FFFF9C0177B35080:vol_device_control:passing through ioctl 2d1190 (returning c0000010)
FFFF9C0177B8B040:remove_drive_letter:IOCTL_MOUNTMGR_DELETE_POINTS 1 returned c000000d
FFFF9C0177B35080:vol_device_control:passing through ioctl 4d0010 (returning c0000010)
FFFF9C0177B8B040:drive_letter_callback2:remove_drive_letter returned c000000d
FFFF9C0177B35080:vol_device_control:passing through ioctl 4d0010 (returning c0000010)
FFFF9C0177B35080:vol_device_control:passing through ioctl 2d1190 (returning c0000010)
FFFF9C0177B35080:vol_device_control:passing through ioctl 2d1400 (returning c0000010)
FFFF9C017C0C5080:vol_device_control:passing through ioctl 70048 (returning c0000010)
FFFF9C017C0C5080:vol_device_control:passing through ioctl 2d0c14 (returning c0000010)
FFFF9C017C0C5080:vol_device_control:passing through ioctl 2d0c14 (returning c0000010)
FFFF9C017C0C5080:vol_device_control:passing through ioctl 2d1400 (returning c0000010)
FFFF9C017C1B2080:vol_device_control:passing through ioctl 2d1400 (returning c0000010)
FFFF9C017C45A040:drv_query_volume_information:utf8_to_utf16 returned 80000005
FFFF9C017C1B2080:vol_device_control:passing through ioctl 2d1400 (returning c0000010)
FFFF9C017C1B2080:vol_device_control:passing through ioctl 2d5928 (returning c0000010)
FFFF9C017C1B2080:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01866680C0:vol_device_control:passing through ioctl 560030 (returning c0000010)
FFFF9C01866680C0:vol_device_control:passing through ioctl 2d1400 (returning c0000010)
FFFF9C01866680C0:vol_device_control:passing through ioctl 455610d4 (returning c0000010)
FFFF9C01831BB0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01831BB0C0:vol_device_control:passing through ioctl 70048 (returning c0000010)
FFFF9C01831BB0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01831BB0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01831BB0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01831BB0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C018838F080:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01812E2080:vol_device_control:passing through ioctl 4100c (returning c0000010)
FFFF9C01812E2080:vol_device_control:passing through ioctl 4100c (returning c0000010)
FFFF9C01812E2080:vol_device_control:passing through ioctl 4100c (returning c0000010)
FFFF9C0188668080:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C01848B8040:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C0186677080:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010
FFFF9C0183F5B0C0:vol_get_disk_extents:IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS returned c0000010

---`

**Comment by lbibass** [comment]
I am also having bluesceens disconnecting my btrfs formatted drive.

**Comment by maharmstone** [comment]
Closing old issues
