### ISSUE TITLE
Btrfs drives will not show up in windows file manager.

### ISSUE THREAD

**Issue by joshontech** [maharmstone/btrfs#333]
I have 3 disks all created on Linux using btrfs. I have them set up with the entire disk as btrfs meaning that the disk /dev/sdc for example is btrfs and one subvolume inside of that. I am upgraded to the newest windows 10 stable build 20H2 and I installed winbtrfs via chocolaty. 

I have not used winbtrfs for a long time but last time I used it I just installed it and the btrfs devices just showed up in the windows 10 file manager. I just want to know if I am doing something wrong.

**Comment by TheMadHau5** [comment]
Did you reboot after installing winbtrfs?

**Comment by joshontech** [comment]
> 
> 
> Did you reboot after installing winbtrfs?

Yes I have multiple times and the drives will not show up. I have actually deleted and recreated my drives on linux with btrfs and still it will not see them on windows. Do you have to use partitions on btrfs for it to see it? I am using the entire disk for the btrfs and than subvolumes under that.

**Comment by joshontech** [comment]
By the way thanks for getting back to me and sorry it took me so long to get back to you.

**Comment by TheMadHau5** [comment]
Yeah, I think you'll need to use partitions. Windows itself can't detect volumes not on an MBR / a GPT formatted disk.
I'm pinging @maharmstone just in case.

**Comment by maharmstone** [comment]
@TheMadHau5 - no, I added a workaround for that. The driver should work with anything that appears to Windows as a PNP disk or as a PNP volume (i.e. partition).

@joshontech - if you go to Device Manager, is there an entry called "Btrfs controller" under Storage Volumes? Does it have any children?

**Comment by TheMadHau5** [comment]
This is why I pinged you ;)

**Comment by joshontech** [comment]
> @TheMadHau5 - no, I added a workaround for that. The driver should work with anything that appears to Windows as a PNP disk or as a PNP volume (i.e. partition).
> 
> @joshontech - if you go to Device Manager, is there an entry called "Btrfs controller" under Storage Volumes? Does it have any children?

In all honesty I'm afraid to go to device manager cause last time I did (before I installed winbtrfs) it nuked my btrfs disks and I didn't even do anything. A dialogue box poped up saying something about initialize disks I said no cause I didn't want to and than when I went to linux my btrfs raid was toast and I had to rebuild. A painstakingly long process I might add.

**Comment by maharmstone** [comment]
Well, I don't know what that's about - it sounds like you either have faulty hardware or a faulty disk driver. I'm going to close this issue - please reopen it if you can reproduce the issue on healthy hardware.
