### ISSUE TITLE
Steam causes filesystem to become read-only

### ISSUE THREAD

**Issue by ticpu** [maharmstone/btrfs#334]
When I launch Steam and it starts to update, the Btrfs switches to read-only and sometimes indicates Catastrophic failure 0x0000FFFF depending on what write actions were happening.

I'm absolutely unsure how this did happen, however, I did a Btrfsck and found many errors, including free space cache, backref and checksum errors.

The included btrfs-read-only-Logfile.7z is a procmon capture showing exactly when the "Result" switches from SUCCESS to MEDIA WRITE PROTECTED.  The other log files are from all the btrfsck runs until I get a clean filesystem, this was done prior to the procmon log capture. The problem was the same before and after the btrfsck so it might be irrelevant for this issue.

Compression has been disabled after finding many checksum mismatch when I was using Zstd.  This Btrfs volume has 2 drives with RAID1 meta, single data.

[btrfs-read-only-Logfile.zip](https://github.com/maharmstone/btrfs/files/5742662/btrfs-read-only-Logfile.zip)
[btrfs-win10-csum-init.log](https://github.com/maharmstone/btrfs/files/5742665/btrfs-win10-csum-init.log)
[btrfs-win10-free-space-cache.log](https://github.com/maharmstone/btrfs/files/5742666/btrfs-win10-free-space-cache.log)
[btrfs-win10-more-corruption.log](https://github.com/maharmstone/btrfs/files/5742667/btrfs-win10-more-corruption.log)
[btrfs-win10-more-corruption-after-repair.log](https://github.com/maharmstone/btrfs/files/5742668/btrfs-win10-more-corruption-after-repair.log)
[btrfs-win10-more-corruption-repair.log](https://github.com/maharmstone/btrfs/files/5742669/btrfs-win10-more-corruption-repair.log)

**Comment by ticpu** [comment]
I found a folder full of folders ending with a \ that are un-deletable while trying to reinstall Steam in E:\SteamLibrary\userdata\97660332\ugc\referenced

I'm starting to wonder if this isn't what btrfsck has "fixed".

![2020-12-27 13_44_45-referenced](https://user-images.githubusercontent.com/1229687/103177588-d64b3e80-4849-11eb-8db0-e616cdfdeb45.png)

**Comment by ticpu** [comment]
After re-creating my subvolume and cp --reflink=always everything that wasn't in the attached list, I can now launch Steam again without the volume remounting read-only.  You can close the issue if you don't need more information about this.

[corrupt.txt](https://github.com/maharmstone/btrfs/files/5745045/corrupt.txt)

**Comment by ticpu** [comment]
Bad news, after doing the same exact thing (installing Celeste via steam and playing to the first save point), the filesystem has again been remounted read-only.

This time, the path isn't the same as I reinstalled Steam in another directory different from the games directory to save the time it takes to uninstall all games when uninstalling Steam.

![2020-12-27 18_32_24-referenced](https://user-images.githubusercontent.com/1229687/103181685-e5de7d80-4871-11eb-9da0-b7ec99a06162.png)

I'm guessing that this games found a way to write folders with backslashes appended at the end that breaks everything.

**Comment by maharmstone** [comment]
Thanks. This looks to me to be the same issue as https://github.com/maharmstone/btrfs/issues/267 - Steam is, as you say, creating directories with backslashes at the end.

You're also right that `btrfs-check` doesn't fix (or indeed detect) multiple files with the same name, though IMHO it really should!

Are you using a controller? The UGC files appear to be controller configurations - it might help me reproduce the bug.

**Comment by ticpu** [comment]
> Are you using a controller? The UGC files appear to be controller configurations - it might help me reproduce the bug.

Yes!  This game, Céleste, is one where I started using my controller,  it didn't crash before-hand (like when setting the options with my keyboard).

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/b7f8d9325488001ccd7143de495c8d7ce2487703. Thanks for reporting.

**Comment by ticpu** [comment]
Would you happen to have the compiled driver handy to test this out?

**Comment by maharmstone** [comment]
Fixed in v1.7.6

**Comment by PJB3005** [comment]
I still seem to be getting this when deleting games.
