### ISSUE TITLE
Some problems with auto repair of btrfs

### ISSUE THREAD

**Issue by Silvan87** [maharmstone/btrfs#34]
I have an ordinary - but specific - file that causes a crash on Windows and a freeze on Linux. During the copy this file crashes at 434,8 MB of 725,3 MB with WinBtrfs from Windows and on Linux too.

This file is good, I can read it. Both Windows and Linux can read it and copying it without errors toward an ntfs partition.

On Windows I used WinBtrfs 0.7. I have Windows 8.1 32 bit and Debian testing with Xfce 32 bit. My HD is 298,1 GiB with 4 primary partitions.

I have to exclude an hard disk damage because I have tried 2 different hard disks and it rises up the same error.

Maybe WinBtrfs is innocent because the same error rises up on Linux. But this means that there is a very basilar bug.

This file is correctly copied from ntfs partition to another ntfs partition. Windows and Linux can do this correct copy, but when the file is copied from ntfs partition to btrfs partition Windows rises up a death screen and Linux freezes.

The copy is executed by usb and from internal partition to another internal partition. This doesn't make a difference.

**Comment by maharmstone** [comment]
If it's happening on both OSes, it sounds like your filesystem might be corrupt. Could you post the output of btrfs check please?

**Comment by Druido87** [comment]
I forgot to add that - after first crash - btrfs is corrupted and I used "btrfsck --repair" from System Rescue CD. All problems are fixed. Debian start again. But when I copy again such file, the system crashes again. This is the output for "btrfsck /dev/sda3 --repair":

enabling repair mode
Checking filesystem on /dev/sda3
UUID: ba962ffa-b744-4d06-93f6-7ffd4a43ef06
checking extents
Fixed 0 roots
checking free space cache
cache and super generation don't match, space cache will be invalidated
checking fs roots
checking csums
checking root refs
found 65385836544 bytes used err is 0
total csum bytes: 63564722
total tree bytes: 270139392
total fs tree bytes: 191217664
total extent tree bytes: 10502144
btree space waste bytes: 44674695
file data blocks allocated: 65124974592
    referenced 65111736320

**Comment by maharmstone** [comment]
That makes things more interesting... It doesn't rule out corruption entirely though, as I've found many instances where a filesystem was corrupt but btrfs check didn't pick it up.

Could you make Windows BSOD, please, and send me a crash dump?

**Comment by Druido87** [comment]
Do you want a complete memory dump or only kernel memory dump?

**Comment by maharmstone** [comment]
Kernel should do, I think

**Comment by Druido87** [comment]
Sorry... the error doesn't occur anymore. So, btrfsck doesn't work very well. Deleting and writing other files and repeat fs check, it solves that error. There could be something wrong on auto repair of btrfs...

I have seen that Windows has created a minidump on the first crash. I put it here.
[Minidump.zip](https://github.com/maharmstone/btrfs/files/612311/Minidump.zip)

**Comment by Druido87** [comment]
I looked for the first HD damaged sectors. That HD with NTFS has corrupted the file system btrfs during the file copy (on healthy internal HD). There were some damaged sectors on HD with NTFS.

However, it remains an open problem related to self-repair of btrfs.

So, the title of this issue is misleading. Feel free to close the issue or give it a different title. Thank you.
