### ISSUE TITLE
I cannot see any btrfs partitions

### ISSUE THREAD

**Issue by joshontech** [maharmstone/btrfs#342]
Windows 10 
Version: 20H2
Build: 19042.685

I have winbtrfs installed via chocolaty and I cannot see any btrfs formatted partitions in Windows file manager. It only shows my C drive. I have installed this before and it worked it showed the btrfs drive as D drive and I had no issues. Since than I reinstalled windows and am on a newer version and it will not work at all as if it is not installed. 

I posted an issue before but found out that it does not support btrfs formatted hard drives without partitions. So I formatted another drive and created a partition and still no partition shows up.

**Comment by maharmstone** [comment]
> I posted an issue before but found out that it does not support btrfs formatted hard drives without partitions.

That's not true, I don't know where you've got that from.

Did you disable Secure Boot, as it says in the README?

**Comment by joshontech** [comment]
I thought I was told that sorry for misinformation. 

Yes I always have secure boot disabled because linux won't boot with it enabled.

**Comment by TheMadHau5** [comment]
Chocolatey apparently doesn't install the driver (I found this out a couple of weeks ago) and just extracts it in the chocolatey folder. Please try installing via the release zip file and telling whether that works out.

**Comment by maharmstone** [comment]
Really? @TheCakeIsNaOH, is this right?

**Comment by TheCakeIsNaOH** [comment]
@TheMadHau5 @maharmstone 

The Chocolatey package does install the driver. It uses `pnputil` 
https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/winbtrfs/tools/chocolateyinstall.ps1#L22

-----

@joshontech 
> Yes I always have secure boot disabled because linux won't boot with it enabled.

This is not universally true. Many major distros (Ubuntu, Debian, Redhat, SUSE, Fedora, etc) support secure boot out of the box, and the others generally support it if you enroll your own keys and sign your binaries. And even if you can't use it out of the box. generally due to out of tree drivers (cough Nvidia cough), you can still do your own signing to work with secure boot.

To be fair, for most home users, secure boot is probably not worth the hassle, and it is just easier to turn it off.

**Comment by maharmstone** [comment]
Cheers

**Comment by joshontech** [comment]
> Chocolatey apparently doesn't install the driver (I found this out a couple of weeks ago) and just extracts it in the chocolatey folder. Please try installing via the release zip file and telling whether that works out.

I will try this again but before I tried out chocolatey I did install it via the normal method of installing. I installed it via the zip on my last install of windows back in 2018. 

Regardless I will try this method again thanks.

**Comment by joshontech** [comment]
> @TheMadHau5 @maharmstone 
> 
> The Chocolatey package does install the driver. It uses `pnputil` 
> https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/winbtrfs/tools/chocolateyinstall.ps1#L22
> 
> -----
> 
> @joshontech 
> > Yes I always have secure boot disabled because linux won't boot with it enabled.
> 
> This is not universally true. Many major distros (Ubuntu, Debian, Redhat, SUSE, Fedora, etc) support secure boot out of the box, and the others generally support it if you enroll your own keys and sign your binaries. And even if you can't use it out of the box. generally due to out of tree drivers (cough Nvidia cough), you can still do your own signing to work with secure boot.
> 
> To be fair, for most home users, secure boot is probably not worth the hassle, and it is just easier to turn it off.
> 
> 

You hit the nail on the head with Nvidia that's my graphics card and I don't feel like signing my own because I tend to distrohop although I have been stable on linux mint for about 2 months now.

**Comment by TheCakeIsNaOH** [comment]
> The Chocolatey package does install the driver. It uses `pnputil`

So I might have spoke too soon. I decided to play around with this, and apparently, `pnputil` does not consistently work to install the driver. It gets the driver copied, but does not always create the controller. 

@maharmstone would you mind playing around with installation through `pnputil` and seeing where the behavior differs from `infdefaultinstall.exe` (what right-click -> install uses).

**Comment by joshontech** [comment]
Ok so installing it via the zip file worked like a charm I guess I need to pop a bug report about the chocolaty install method.

**Comment by maharmstone** [comment]
Great, I'll close this then.

Erm, @TheCakeIsNaOH - why don't you just change your script to do `infdefaultinstall.exe`, then?

**Comment by TheCakeIsNaOH** [comment]
@maharmstone Because `infdefaultinstall.exe` pops up a message box asking if you want to reboot and I don't know of a way to stop it from doing that. Chocolatey packages are supposed to install without user intervention, so it waiting for the message box to be clicked is a no go. I could use autohotkey or something to click the box automatically, but I would prefer to avoid that if at all possible.

**Comment by TheMadHau5** [comment]
This might not be a great idea, but what about installing it manually? (i.e. copying the files over and then creating the services)

**Comment by sitiom** [comment]
> @maharmstone Because `infdefaultinstall.exe` pops up a message box asking if you want to reboot and I don't know of a way to stop it from doing that. Chocolatey packages are supposed to install without user intervention, so it waiting for the message box to be clicked is a no go. I could use autohotkey or something to click the box automatically, but I would prefer to avoid that if at all possible.

@TheCakeIsNaOH Just chiming in, [nefcon](https://github.com/nefarius/nefcon) now has a command to install a driver that emulates the behavior of `infdefaultinstall.exe` (and it works silently!):

>### Install file system volume controller driver
>
>```text
>.\nefconw --inf-default-install --inf-path "F:\Downloads\btrfs-1.8\btrfs.inf"
>```

**Comment by TheCakeIsNaOH** [comment]
Thanks for letting me know about that @sitiom, I've opened an issue to investigate switching over to it: https://github.com/TheCakeIsNaOH/chocolatey-packages/issues/23

**Comment by nefarius** [comment]
Bear in mind we're currently still hardening and tweaking the installation process, especially trying to fix erratic reboot required detection.

**Comment by sitiom** [comment]
As of https://github.com/maharmstone/btrfs/releases/tag/v1.8.2, installation via `pnputil` works normally now. @TheCakeIsNaOH Can you test to confirm that it does?

**Comment by maharmstone** [comment]
That's good to hear, I did wonder whether my changes would fix that. I had to change the INF to a "universal INF" so that it would work with my Windows 11 aarch64 laptop. It's clear that some versions of Windows are fussier about INFs than others, but unfortunately it's not documented which these are.

**Comment by sitiom** [comment]
> That's good to hear, I did wonder whether my changes would fix that. I had to change the INF to a "universal INF" so that it would work with my Windows 11 aarch64 laptop.

That is most likely the case, and I think you should have done that from the start.

**Comment by TheCakeIsNaOH** [comment]
@sitiom I've tested on a clean Windows 10 system, and `pnputil` seems to be working. There is a [v1.8.2](https://community.chocolatey.org/packages/winbtrfs/1.8.2) package in moderation, should be listed in a couple of hours.
