### ISSUE TITLE
WinBtrfs' current state

### ISSUE THREAD

**Issue by eute** [maharmstone/btrfs#344]
I am looking for a newer, robust, long term filesystem alternative to NTFS on Windows, particularly one that is suitable for data archival and does checksumming. Is WinBtrfs in a good enough state for that, at its current point of development? Or is it too early to recommend relying on it?

**Comment by TheMadHau5** [comment]
I'd say it's mostly stable but there are a few bugs here and there so you might wanna wait and come back in a bit when it's more polished.

**Comment by eute** [comment]
Alright, thanks for the info.

**Comment by maharmstone** [comment]
I'm assuming you've already seen this in the README...

> It ought to be suitable for day-to-day use, but make sure you take backups anyway.

For what it's worth, it's been a _long_ time since anyone's reported a non-trivial issue that I was able to reproduce.

**Comment by eute** [comment]
I've seen it, just wanted to make sure that the driver is stable enough and suitable for my particular use case.

Thank you.

**Comment by maharmstone** [comment]
Closing old issues
