### ISSUE TITLE
Not all letters are available to change the drive letter

### ISSUE THREAD

**Issue by zamtmn** [maharmstone/btrfs#349]
Not all letters are available to change the drive letter. I need the disk "Y", and only "ABFGHJKL"is offered to me, Although at the moment are used only "CDEIMNQZ". At the same time, when you click the "Change drive letter" button, a window first appears with the error "the parameter is set incorrectly" (параметр задан неверно)
<img width="385" alt="1" src="https://user-images.githubusercontent.com/39580611/107189883-e3904700-6a0b-11eb-82ce-7ebb467cf559.PNG">
<img width="339" alt="2" src="https://user-images.githubusercontent.com/39580611/107189888-e4c17400-6a0b-11eb-9013-1383d7d6191f.PNG">

**Comment by maharmstone** [comment]
Closing old issues
