### ISSUE TITLE
Can't get BTRFS to work on MBR laptop

### ISSUE THREAD

**Issue by atwk** [maharmstone/btrfs#350]
I can't get BTRFS driver to work on my laptops (Lenovo T430, Win10). Have tried several versions, also installed WinMD. A big difference with my PC - hard drive is MBR instead of GPT. Does the driver run on older systems with MBR?

**Comment by lesderid** [comment]
> Does the driver run on older systems with MBR?

Yes.

**Comment by maharmstone** [comment]
What @lesderid said - it works with all partition types that Windows recognizes. Is the driver running (`sc query btrfs`)?

**Comment by atwk** [comment]
Driver is running (State 4). In Windows Disk Management or Diskpart no letter can be assigned, in other hard disk programs it can, but it still does not show up.

**Comment by atwk** [comment]
I was able to narrow down the problem. If I format a drive as btrfs, it works. When I format a single partition in the system, it is not recognized (on any of my systems). I want to use multiple operating systems, and was hoping to be able to use certain Linux partitions in Windows as well.

**Comment by maharmstone** [comment]
Closing old issues
