### ISSUE TITLE
Driver doesn't work on Windows 7 and MicroSD cards

### ISSUE THREAD

**Issue by Psycho-A** [maharmstone/btrfs#351]
I have Windows 7 x64 OS and MicroSD card with two partitions (one is Fat32, other is Btrfs) that running via USB card reader. Btrfs partition is active, but when I plug it, Windows just says there's no filesystem on this partition and suggest to format it. Driver service (sc query btrfs) shows it's running but seems like does nothing. The same partition detects fine if it's formatted as ExFat.

**Comment by maharmstone** [comment]
Let me look into it. I remember there was something distinctly screwy involving the second partition of SD cards, but I can't remember what...

**Comment by Psycho-A** [comment]
Thanks. I very much hope for a fix if it's possible...

**Comment by Psycho-A** [comment]
Any news...?

**Comment by maharmstone** [comment]
Closing old issues
