### ISSUE TITLE
[Win 10 x64] BSOD

### ISSUE THREAD

**Issue by dotqurter** [maharmstone/btrfs#352]
I noticed my shared BTRFS drive was BSOD'ing after steam was trying to write to the steamlibrary folder, and upon manually checking the folders/subfolders of my steamlibrary, I noticed (right before BSOD'ing) that a empty (or invalid, it read 0kb) "steam.dll.symlink" file had been placed in the folder, which when Windows tried to interact, it would cause a hard BSOD. Deleting the file through linux fixed the issue. If needed, I can try to fish out the file that caused the crashing.

**Comment by dotqurter** [comment]
Actually, I just doublechecked -- I errornously thought that the root cause was the symlink file, yet I'm back to crashing. Checking the bluescreen dump, the crash seems to come from storachi.sys, and sometimes dumping CLASSPNP.sys, which is a SCSI driver. Weird, since it's not using any SCSI, all SATA.

**Comment by dotqurter** [comment]
Windows dump reports that the storahci,sys driver is running into an access violation trying to access 0x0000000. This only occurs on my btrfs drive, all other drives are fine to search and dir through subdirectories.

**Comment by lbibass** [comment]
I have also had the same issue.

**Comment by publicarray** [comment]
![Screenshot 2021-02-25 123928](https://user-images.githubusercontent.com/5497998/109090204-8504e180-770a-11eb-9c00-49daf2b824ad.png)

**Comment by dotqurter** [comment]
I recently found the issue with my driver. It's always after coming back from my linux VM that I have this issue; turns out winbtrfs hard-crashes if it can't resolve the location of a hardlink. The offending file is just a symlink to a steam dll in my /home/ folder for compatibility reasons (Proton stuff).

**Comment by TheMadHau5** [comment]
maybe you could boot into linux and try to fix the issue from there?

**Comment by maharmstone** [comment]
@publicarray, @dotqurter - could you send me your minidumps please?

**Comment by dotqurter** [comment]
> maybe you could boot into linux and try to fix the issue from there?

I usually can, problem is that it happens everytime steam is started from linux. It's a pain.

> @publicarray, @dotqurter - could you send me your minidumps please?

I'm having trouble getting one -- Windows' error dumper gets hung at 60% for me while doing it.

**Comment by publicarray** [comment]
Sorry @dotqurter I no longer have the minidumps, and I've not noticed any more issues. Maybe I need to run a steam game with the game library on a btrf volume again.

**Comment by dotqurter** [comment]
I'm on latest driver and still suffering from crashes. Last crash was right now.

**Comment by emrefs** [comment]
> 
> 
> @publicarray, @dotqurter - could you send me your minidumps please?

i'm suffering same BSOD's with latest version (1.7.7). i have minidumps. 
[Minidumps.zip](https://github.com/maharmstone/btrfs/files/6300113/Minidumps.zip)

**Comment by kusalux** [comment]
I just had the problem too with a new setup on 1.8. Still have the minidump but besides the CLASSPNP.sys nothing of interest. But I think the reason was the btrfs drive to be assigned as G: and after a new linux configuration I did de- and now reattach the drive that's been previously G:.

But I could not rename the drive letter in btrfs tab. For now i've simply renamed the sys (to be save on win system using the repair options). Is there any other way to rename the drive letter? In any way such conflicts should be taken in advance.

**Comment by maharmstone** [comment]
Closing old issues

**Comment by reinux** [comment]
Also experiencing bsods.
