### ISSUE TITLE
Adobe Lightroom refuse to work on Btrfs volume

### ISSUE THREAD

**Issue by llccd** [maharmstone/btrfs#353]
![Untitled12](https://user-images.githubusercontent.com/56721858/107844685-a3b4cf80-6e10-11eb-99cd-1abcdbcf589a.png)

**Comment by TheMadHau5** [comment]
I'm guessing Btrfs volumes are somehow wrongly being detected as one of those? Sounds like a bug, as it's a regular volume.

**Comment by maharmstone** [comment]
Whereabouts are you saving it? Non-elevated users can't create files in the root of a drive - it's not that, is it?

**Comment by llccd** [comment]
> 
> 
> Whereabouts are you saving it? Non-elevated users can't create files in the root of a drive - it's not that, is it?

Saving everywhere in Btrfs volume have the same result. Using some tricks like `subst`/`symbolic link`/`junction` also not work. I use an administrative account with UAC disabled, so it's not related to permission.

**Comment by llccd** [comment]
Finally I found a workaround that can "fool" Lightroom. 

After using `subst R: \\localhost\e$`, I got a drive `R:` which has the same content of my Btrfs volume `E:`. Then I can successfully saving to drive `R:`.
