### ISSUE TITLE
Copying of files using cmd copy command with wildcard fails on btrfs drive

### ISSUE THREAD

**Issue by RobertSpir** [maharmstone/btrfs#354]
easy to reproduce

- make some folder with multiple files on btrfs volume, for example multiple txt files
- open cmd, browse to btrfs volume to that folder
- try to copy the files to some other folder using "copy" command with wildcard i.e.: `copy *.txt ..`
- command will fail with **The system cannot find the file specified.**
- on ntfs volume, this copies all txt files up one dir
- copying single file using full name works

**Comment by TheMadHau5** [comment]
As mentioned in # 353:
> Non-elevated users can't create files in the root of a drive - it's not that, is it?

`cmd.exe` doesn't run with elevated permissions, even if the user is an administrator, unless it is opened with "Run as administrator".
Maybe try it a couple of levels deeper?

**Comment by RobertSpir** [comment]
It wasn't in the root, also using xcopy instead of copy or cp in powershell in the same place worked without problems

**Comment by maharmstone** [comment]
Yes, you're right! Thanks for this, I'll have a look.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/64a6f6012b4871a9357ac22744883cd061d2494f
