### ISSUE TITLE
BSOD when writing lots of small files

### ISSUE THREAD

**Issue by chengyuhui** [maharmstone/btrfs#356]
I was recording HLS streams today (which means 1 small file per 3 seconds for several hours) when this BSOD happened.
[021521-19375-01.zip](https://github.com/maharmstone/btrfs/files/5981943/021521-19375-01.zip)

**Comment by maharmstone** [comment]
Thanks. You're using 1.7.1 though, which is five versions out of date. Please upgrade, and reopen this if you can reproduce it on the latest version.
