### ISSUE TITLE
How can we know that btrfs has installed properly on latest Windows 10?

### ISSUE THREAD

**Issue by mackonsti** [maharmstone/btrfs#357]
Hello and thank you for your great work @maharmstone.

I have discovered `btrfs` recently when installing the Batocera retro gaming software on a USB stick for use with an Intel PC at https://batocera.org/

There was a mention in some readme to install `btrfs` in order to access the main partition after deploying the (available) `img` release to a USB drive.

I followed your guide on your main page, for Windows 10 (recently updated to 20H2) but I cannot seem to make it work.

Can you kindly update your guide to show all the possible ways and indications that `btrfs` was installed properly? As it's a file system driver and not a service, it can't be see e.g. on the Computer Management console.

And since I don't have other drives to test, I cannot be sure if it's your driver has installed properly, with all the administrator permissions required as well as security tweaks that you describe in your guide.

Thank you in advance.

**Comment by maharmstone** [comment]
Try `sc query btrfs`

**Comment by mackonsti** [comment]
Hello and thank you for your assistance @maharmstone Here's the output of `sc query btrfs` :
```
SERVICE_NAME: btrfs
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
I assume it's correctly installed, yes?

If yes, can you kindly update your guide in README.md for others like me to verify when needed? Something like "Verification" as title section.

Finally, if a disk/partition is supported by `btrfs` what would **Disk Management** show as "File System" ? Just to know what to expect. I can't get the Batocera IMG on USB mount the seemingly Linux partition...

Many thanks again!

**Comment by TheMadHau5** [comment]
That is correctly installed, yes. A mounted Btrfs volume should show "Btrfs" as the file system, IIRC.

**Comment by mackonsti** [comment]
Hi @maharmstone thank you for confirming. Please, kindly update your front-page document, you can use my output from my `sc query btrfs` done above as to how to validate driver installation was successful.

The means that the Batocera partition I am supposed to access, is not formatted to a file-system supported by btrfs then :-/

FYI, I did also follow the advised change in RegEdit, too:

> For the very latest versions of Windows 10, Microsoft introduced more onerous requirements for signing, which seemingly aren't available for open-source drivers.
> 
> To work around this, go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy` in Regedit, create a new DWORD value called `UpgradedSystem` and set to **1**, and reboot.

I have no solid understanding if this also helped but, just so that you know, it was applied before installing manually your driver.

Thank you for your work and support. I guess we can close this ticket.

**Comment by maharmstone** [comment]
What does `mount` say if you run it on Batocera?

**Comment by mackonsti** [comment]
I have not tried yet. I plan to re-install the image on the USB flash disk and see what happens. However, I have the impression that the second partition created (by the image, via Etcher) is a **swap-file** partition as it's not recognised by MiniTool Partition Wizard, either. Nevermind, please don't bother with this, I will figure it out and if needed I will post again here, even if it's closed (for just informing you). Cheers.

**Comment by mackonsti** [comment]
Hello @maharmstone I hope you're well and safe. Just an update so we can close this ticket.

I reinstalled the latest Batocera retro image to my bootable USB and I was under the impression that the secondary partition would be using BTRFS by default; this was not the case.

After some research, I found "How can you format a disk in Btrfs (or ext4, or exFAT)? Batocera can do it for you, in SYSTEM SETTINGS –> DEVELOPER –> FORMAT A DISK. Of course, when you format a partition, you lose everything that was on it. So, backup your data before doing this!" Source: https://wiki.batocera.org/batocera.linux_architecture

The driver on my Windows 10 installation thus seems to run great, I am able to access the partition and read/write files, as I performed the step above. Just FYI: In Computer Management > Disk Management there is no mention of "btrfs" as partition name, nor an assigned (working) letter, despite being able to access the BTRFS partition via e.g. drive letter G: but a right-click and in Properties, we do get to see a reference to "btrfs" as File System.

Thank you again for your support. We can this close the ticket.

A final question: What would be the best way (if any) to do a file-check like `chkdsk` on a BTRFS partition when mounted in Windows 10? I assume there is no tool included in your installation package, correct? Alternatively, a right-click and selecting Properties mini-menu (go to Tools > Error Checking) won't probably support this partition, either.

Thank you again, stay safe.

**Comment by lesderid** [comment]
> What would be the best way (if any) to do a file-check like `chkdsk` on a BTRFS partition when mounted in Windows 10?

The closest thing would be: right click on volume in explorer > Properties > Btrfs > Scrub, or `rundll32.exe shellbtrfs.dll,StartScrub <drive>`.

**Comment by mackonsti** [comment]
I totally missed the new "btrfs" tab in Properties when doing the right-click mini-menu on the drive in Explorer. Thank you @lesderid !

**Comment by cooper2k4** [comment]
> A final question: What would be the best way (if any) to do a file-check like `chkdsk` on a BTRFS partition when mounted in Windows 10? I assume there is no tool included in your installation package, correct? Alternatively, in Explorer and a right-click and selecting Properties mini-menu (go to Tools > Error Checking) won't probably support this partition, either.

With a Linux live CD you can use [btrfs check](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-check) which checks the meta data of a BTRFS volume.

[btrfs scrub](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-scrub) is not a _file system_ checker. It verifies the correctness of the _files_ on the disk and therefore takes much longer to run. Scrub can only correct files if you use a redundant RAID option.

**Comment by maharmstone** [comment]
^ This. `btrfs check` is the equivalent to `chkdsk`, but AFAIK there's no way to do it on Windows. (The last time I checked WSL didn't expose block devices.)
