### ISSUE TITLE
Some program can not detect how much free space a btrfs disk has

### ISSUE THREAD

**Issue by OnikenX** [maharmstone/btrfs#358]
as you can see where there genshin can not read the free space from disk D witch is a btrfs disk:

![](https://pleroma.pt/media/b0c3b7a06328652404adfb4403efdad40b3c4324102addfb7456f3518ebf9a6b.jpg)

**Comment by TheMadHau5** [comment]
AFAIK (@maharmstone feel free to correct me), this is a Btrfs issue as subvolumes can have different RAID levels, causing the same amount of disk space to be utilised in different ways, making the amount of data space uncertain. This would then also be reflected by WinBtrfs, not giving a correct/valid answer.

**Comment by maharmstone** [comment]
That's not right: there's no way for subvolumes to have different RAID levels (more's the pity).

**Comment by OnikenX** [comment]
just wanna say that it is a normal disk just formated in btrfs, nothing fancy, at least in this case, the third volume has multiple subvolumes

**Comment by TheMadHau5** [comment]
@maharmstone Ah, I forgot to mention: while not currently supported, it _is_ planned ([Source](https://btrfs.wiki.kernel.org/index.php/FAQ#Why_is_free_space_so_complicated.3F)). This also means that while currently not a problem, it can quickly become one, and that my conclusion still remains accurate (as far as I know about the implementation of WinBtrfs).

**Comment by maharmstone** [comment]
@TheMadHau5 - that message has been in the FAQs for at least nine years. If the situation ever changes, I'll update the driver.

@OnikenX - I'll have to see what it's doing. As far as I know, there's no way to check the free space that's not already supported...

**Comment by Masamune3210** [comment]
I know some tools will check the MFT to get file sizes manually, could it be tripping up on that?

**Comment by TheMadHau5** [comment]
Just got Genshin myself, same error. Gotta go back to C: I guess 🤷🏻

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/8b36a1aef419b6f2d5feb0b942b2f9502687feb5
