### ISSUE TITLE
PAGE_FAULT_IN_NONPAGED_AREA BSOD

### ISSUE THREAD

**Issue by BluCobalt** [maharmstone/btrfs#359]
![IMG_20210220_225836](https://user-images.githubusercontent.com/37788256/108618269-9cbe2c00-73d1-11eb-855d-0a0f498575fa.jpg)
Not sure what happened, I was browsing in explorer and got this.

Windows 20H2 build 19042.804

**Comment by TheMadHau5** [comment]
Are you able to reproduce this error? Or did it just happen that once?

**Comment by BluCobalt** [comment]
It has only happened once.
[Minidump.zip](https://github.com/maharmstone/btrfs/files/6044783/Minidump.zip)

**Comment by alex4o** [comment]
I don't know if this is useful, but I also have gotten the same crash, here is a minidump file.
I am on windows 1909
Os build 18363.1379
[030621-15953-01.zip](https://github.com/maharmstone/btrfs/files/6096019/030621-15953-01.zip)

**Comment by maharmstone** [comment]
Thanks all.

@BluCobalt - you're using version 1.7.5, try the latest version. Your crash was in `open_fcb`, and there's some fixes for that in 1.7.6. Please reopen this if you have further issues.

@alex4o - this is a weird one, you have a crash on one core while a file is being deleted on another. I'll keep my eyes open for something similar, but given btrfs.sys isn't in the stack trace anywhere I'm not 100% certain it's even my fault.
