### ISSUE TITLE
Allow to mount different subvolumes of one btrfs simultaniously

### ISSUE THREAD

**Issue by raetiacorvus** [maharmstone/btrfs#36]
The current approach only allows for one subvolume mount per UUID. It would be nice if it was somehow possible to mount more then one subvolume per UUID.
e.g. my btrfs partition (subvolid 5) with the following subvolumes: 
`/@root` (default subvolume)
`/@home`

for me on linux
`@root` gets mounted to `/`
`@home` gets mounted to `/home`

it would be nice if it was possible on windows to either replicate this in similar fashion
e.g.  `@root` to `X:/` and `@home` to `X:/home`
or `@root` to `X:/` and `@home` to `Y:/`

Currently I have to set subvolid 5 explicitly so i can access both subvolumes.

**Comment by maharmstone** [comment]
I think what you're looking for is the DOS command `subst`: https://en.wikipedia.org/wiki/SUBST

Couldn't you just move /@home to /@root/home though?

**Comment by maharmstone** [comment]
Crap, not subst, you want a reparse point. Something like `mklink /D Y:\ X:\home`.

**Comment by raetiacorvus** [comment]
> Couldn't you just move /@home to /@root/home though?

It would be possible, but that would mean i would have to change to a nested layout with all its  drawbacks. See https://btrfs.wiki.kernel.org/index.php/SysadminGuide for flat vs nested subvolume layout in btrfs.

On of the upsides of a flat subvolume Layout is that you can mount your subvolumes with different mount options, which does not seem possible yet to me with the windows btrfs driver at least i was not able to extract that information from the description.

The examples I made where just there to illustrate how someone could want to use multiple mounts from a single btrfs filesystem.

This would be a nice to have feature for the future. For now it already a great feat of yours that we are able to mount btrfs including a lot of mount features on Windows. Thank you for your effort.

**Comment by maharmstone** [comment]
This is out of the scope of the project, I'm afraid, as mklink already does exactly what you want.
