### ISSUE TITLE
creating softlinks from a btrfs to a ntfs makes the linked directory unwritable

### ISSUE THREAD

**Issue by OnikenX** [maharmstone/btrfs#360]
steps:
1. mklink /d c:\path\to\link g:\path\to\original\folder\in\btrfs\partition
2. try to write there
3. fail
expected:
the linked directory should be writable like the original
obtained:
the linked directory gives an error when trying to write in it
![image](https://user-images.githubusercontent.com/25059102/108836938-64813e00-75c9-11eb-94c1-b85c1fdd6c66.png)

**Comment by lesderid** [comment]
I can't seem to be able to reproduce this on Windows 8.1 on 2818f989deeaa1ae13014fa857cc489e6dc81f64:

```
C:\>mkdir C:\linktest E:\linktest

C:\>mklink /D C:\linktest\link E:\linktest
symbolic link created for C:\linktest\link <<===>> E:\linktest

C:\>echo test > C:\linktest\link\test

C:\>echo test >> E:\linktest\test

C:\>type C:\linktest\link\test
test
test
```

**Comment by maharmstone** [comment]
Closing old issues
