### ISSUE TITLE
Latest 1.7.6 version corrupted filesystem: checksum verify failed

### ISSUE THREAD

**Issue by Fogapod** [maharmstone/btrfs#362]
I installed version 1.7.6 on Windows 10, after installation popup asking for restart appeared and I clicked restart.
While shutting down, messages about new drives started appearing (I have 4 btrfs volumes).
After restart 2/4 of my btrfs volumes got corrupted. They cannot be mounted in rw or ro anymore. Both drives have exact same errors, the only difference is block number.
Errors: `bad tree block start, want 543731711200 have 0`
They show up as drives with unknown fs in windows, the only option is to format them.

I tried running `btrfs rescue zero-log`, it did nothing.
All other commands like `btrfs check` or `btrfs rescue` fail with similar checksum errors:
`checksum verify failed on 543731711200 found 000000B6 wanted 00000000`
`bad tree block 543731711200, bytenr mismatch, want=543731711200, have=0`
So I was only able to make a dd backup.

I also tried recently added mount options: `mount -t btrfs -o ro,rescue=idatacsums,ibadroots /device /mnt`, same result.

What could cause this and is there any hope of restoring my partitions? I can run inspect commands if needed, they work, I'm just not sure which ones are relevant here.

**Comment by lesderid** [comment]
Are the volumes on the same physical disk? SSD or HDD?

**Comment by Fogapod** [comment]
Yes, all 4 volumes are on same disk (SSD).
2 working volumes can be mounted in both widows and linux

**Comment by Fogapod** [comment]
It looks like there are windows specific files created in 2 survived volumes: `System Volume Information`, `$RECYCLE.BIN`.
Could writing these during shutdown be the reason of corruption?

**Comment by Connor22** [comment]
Had a similar issue with my HDD, same error messages, and none of the restore commands or rescue mount options (even with the newest kernel) have helped.

**Comment by Fogapod** [comment]
I partially restored most of my filesystem to a working state with the help of https://gist.github.com/Changaco/45f8d171027ea2655d74, some manual digging for individual files and a few days of pain, but some of files are gone forever.

Do not use this driver.

**Comment by maharmstone** [comment]
@Fogapod, can you give me the make and models of the drives in question?

Also, it'd greatly help if you could do a full test in `gsmartcontrol` or whatever, to confirm there's nothing wrong with the disks themselves.

**Comment by hydranix** [comment]
Same exact corruption took place on my btrfs partition after using this driver.

SMART data all shows my SSD is 100% healthy and was not the cause of the failure.

**Comment by maharmstone** [comment]
Same question as to @Fogapod - what's the make and model of your drive?

Also, have you definitely done the full SMART test? This is the one that takes a couple of hours to complete (at least on a HDD).

**Comment by maharmstone** [comment]
Closing old issues
