### ISSUE TITLE
can't locate btrfs volume after remove drive letter

### ISSUE THREAD

**Issue by ilazycat** [maharmstone/btrfs#363]
Hi,
First of all thank you for your amazing job. 
I removed drive letter for the btrfs volume using `mountvol X: /D` and afterward I found it quite hard to locate and remount this btrfs volume.

The partition GUID reported by disk tool (in my case I use DiskGenius) is different from the result by `btrfs fi show` (which match the registry `HKLM\SYSTEM\CurrentControlSet\Services\btrfs\` item), and none of which match any result in the output of `mountvol /?`

What I did was try and mount every single item in `mountvol /?` output and check whether it is the desired volume. But since there are many hidden volumes (efi, recovery, etc...) it is quite painful. So I wonder what is the proper way to locate and mount a specific btrfs volume after removing the drive letter for it?

**Comment by alex4401** [comment]
I did the same mistake a while ago. If you know the volume's GUID (as assigned by Windows), you can use Powershell:
```Get-WmiObject -class Win32_Volume | where-object {$_.DeviceID -Like "\\?\Volume{VOLUME GUID HERE KEEP BRACKETS}\"} | foreach-object -process {$_.AddMountPoint("R:")}```

**Comment by maharmstone** [comment]
Closing old issues
