### ISSUE TITLE
Ensure existing volume is not mounted read-write, even on first run

### ISSUE THREAD

**Issue by mralusw** [maharmstone/btrfs#366]
The current README talks about registry keys that can be set per-UUID under `HKLM\SYSTEM\CurrentControlSet\Services\btrfs`. I *assume* that putting the Readonly key for an existing Linux partition **before** installing the `.inf` driver would prevent the driver from destroying my current Linux installs, but.. is that so? Maybe I should also hide the partitions in `diskpart` before installing the driver?

This would be an excellent way to access my Linux data (there doesn't seem to be anything equivalent that I'm aware of, even for ext4), but I really wouldn't want to sacrifice a carefully curated system that took years to build to the "principle of least astonishment" you mentioned in #52 (and *only* to that principle, since the software could easily refrain itself from rw-mounting with no downsides). Yeah, I know, there's always "don't install it", but having to duplicate userdata to NTFS-accessible locations all the time is quite annoying.

**Comment by lss4** [comment]
I think users definitely should be allowed to choose whether or not mount their partitions r/w before first run, considering potentially dangerous issues (which I'm yet to encounter one) and depending on the user's use case.

Personally I use Btrfs only for data partitions. For Linux root and home partitions I still prefer using ext4, XFS or even f2fs (each with its own pros and cons). I think this debate mostly affects users who use Btrfs for their Linux root or home partition, as users most likely would not want Windows to have full access to their Linux root and home partitions (which can break things), similar to my use cases where I would normally not automount Windows system partitions when running Linux, either.

But again, my experience with WinBtrfs is positive and I haven't encountered anything serious yet. I sincerely hope this can eventually reach the point to become a viable alternative to exFAT/NTFS.

**Comment by mralusw** [comment]
I've ended up [de-clawing WinBTRFS in my fork](https://github.com/mralusw/btrfs), which is a bit overkill, but I only really want to read Linux data without rebooting.

@lss4 I've looked into other filesystems before, but
- couldn't find windows drivers for accessing Linux partitions
- BTRFS supports compression, and zstd at that, while others, AFAIK, don't

**Comment by lss4** [comment]
> I've ended up de-clawing WinBTRFS in my fork (impossible to mount r/w), which is overkill, but I only really want to read Linux data without rebooting.

Yeah, if reading btrfs (but not writing) is all you need then this is safest.

> couldn't find windows drivers for accessing Linux partitions

My current aim is to eventually replace NTFS with Btrfs for data partitions. After all, Btrfs offers some interesting features and is more friendly on Linux than NTFS.

Support for other Linux file systems are still limited, but personally I'd keep it this way to ensure a good layer of isolation between the two systems, that they won't accidentally break each other.

**Comment by fice-t** [comment]
The README states, under `Mount options`:

> If a value is set in the key above this, it will use this by default.

Does creating a `Readonly` item directly in `HKLM\SYSTEM\CurrentControlSet\Services\btrfs` work in ensuring no write-access even on first run?

**Comment by CodeCubeNeo** [comment]
So is there a way to mount the volume as read only?

**Comment by mralusw** [comment]
@CodeCubeNeo https://github.com/maharmstone/btrfs#mount-options but it's not clear whether this works before installing (i.e. the first run might still mount r/w). Then again I haven't kept up with the changes. I have a fork (mentioned above) which currently doesn't merge anymore. Even if I update it, though, it leads to driver signing hell (doable, but annoying)

**Comment by mralusw** [comment]
Actually, the read-only changes still seem to merge just fine. These are trivial changes (three lines of setting `mount_readonly = 1`), unlikely to cause problems, but use at your own risk.  Keep in mind that that these changes make it *impossible* to mount R/W. Installation, as mentioned, becomes more complicated.

I've renamed my fork: https://github.com/mralusw/maharmstone-btrfs-ro

**Comment by Bananaman** [comment]
There really should be a "global defaults" key used for all disks that don't have a per-disk change. Something like:

```
HKLM\SYSTEM\CurrentControlSet\Services\btrfs\global_defaults
```

Where we can set "read only" which would then apply to every disk that doesn't have an explicit "allow writing" override in its own per-partition key.

**Comment by maharmstone** [comment]
Closing old issues
