### ISSUE TITLE
Undeletable empty directories

### ISSUE THREAD

**Issue by Chaython** [maharmstone/btrfs#368]
I can move them but not delete them, there's duplicate entries, and they all have a backslash at the end, but scrub finds no issue.
Scrub started at 4/2/2021 1:11:40 AM.
Scrub finished at 4/2/2021 1:24:40 AM.
Scrubbed 477.5 GB in 779 seconds (627.6 MB/s).
Recovered from 0 error(s).
0 unrecoverable error(s) found.
![image](https://user-images.githubusercontent.com/6486343/113393088-64582900-9353-11eb-817c-ba396855614a.png)

**Comment by Chaython** [comment]
![image](https://user-images.githubusercontent.com/6486343/113393146-79cd5300-9353-11eb-9c5f-7a5b15955c33.png)
![image](https://user-images.githubusercontent.com/6486343/113393177-8487e800-9353-11eb-8e19-adacb9d5e8fa.png)

**Comment by TheMadHau5** [comment]
Are you on the latest version? I remember a similar bug and it getting fixed.

**Comment by maharmstone** [comment]
Yes, this is definitely fixed in the latest version.

If you can't get rid of them in Windows by deleting the parent directory, try `cd`ing there in a bash prompt on Linux, and doing something like `for i in *; do rmdir $i; done`.

**Comment by Chaython** [comment]
> Are you on the latest version? I remember a similar bug and it getting fixed.

![image](https://user-images.githubusercontent.com/6486343/113451745-dfefbf80-93bf-11eb-845c-51826fb6c024.png)


> Yes, this is definitely fixed in the latest version.
> 
> If you can't get rid of them in Windows by deleting the parent directory, try `cd`ing there in a bash prompt on Linux, and doing something like `for i in *; do rmdir $i; done`.

Ya you can delete anything in Linux, just saying these random files were created and can't be deleted within winbtrfs, thanks. I was using the latest version.

**Comment by TheMadHau5** [comment]
Hmmm, that's odd

**Comment by TheMadHau5** [comment]
Hmmm, that's odd. Were the files created before updating to 1.7.6? @maharmstone maybe reopen?

**Comment by Chaython** [comment]
The files were likely created beforehand.

**Comment by TheMadHau5** [comment]
Then, there's nothing that can be done about it now. Delete them, move on, it won't happen again.
