### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [maharmstone/btrfs#372]
I apologize. From the description it is not quite clear how to mount subvolumes if there are several of them on the same partition? As far as I understand, the SubvolId parameter cannot be specified multiple times for a single FS.

P.S. I apologize for the automatic translation

**Comment by TheMadHau5** [comment]
Subvolumes are not separately mounted; the root subvol is mounted and you have to access all subvolumes from there.

![image](https://user-images.githubusercontent.com/35187665/115186280-0ec79e80-a0ff-11eb-8d7d-fa42440e2915.png)

**Comment by maharmstone** [comment]
Yep. If you want certain subvols to appear as different drives, have a look at the Windows commands `mklink` and `subst`.
