### ISSUE TITLE
Degraded RAID1 is not mounted

### ISSUE THREAD

**Issue by Vladimir295** [maharmstone/btrfs#373]
Hi. 
Thank you for your hard work. 
Registry changed AllowDegraded=1. I take one raid1 disk and connect it to windows 10. It is not mounted. 
At the same time, the partition without raid1 is mounted normally.  "Readonly" set to 1 or 0 -- didn't help.
Can you help me?

Windows 10 LTSC 1809 with last update.
Raid1 maked on Debian 10 with kernel 5.10 by btrfs only.

**Comment by maharmstone** [comment]
Closing old issues
