### ISSUE TITLE
can't eject the device safely when using Btrfs file system on USB disk!

### ISSUE THREAD

**Issue by zhangjint5** [maharmstone/btrfs#375]
Windows 10 64 bit can't eject the device safely when using Btrfs file system on USB disk!
Btrfs file system volume cannot be unloaded when using Btrfs file system in Windows version of veracrypt encrypted volume! And will cause the system to jam, unable to safely shut down windows and other issues!

**Comment by maharmstone** [comment]
Yes, this is a known issue, caused by Veracrypt not exposing their block devices correctly. See https://github.com/veracrypt/VeraCrypt/issues/577.

**Comment by INeedTogepi** [comment]
I have this issue and as far as I know, I don't have VeraCrypt installed on my Windows 10 Pro 64bit machine.
