### ISSUE TITLE
EXRESOURCE_TIMEOUT_LIVEDUMP (1cc)

### ISSUE THREAD

**Issue by dima333750** [maharmstone/btrfs#377]
Hi, I am using btrfs Version 1.7.7 on windows 10 1809, I formatted the btrfs ram disk (Primo Ramdisk) in the settings, I used zstd compression, after 5 hours of work, I got a disk freeze that prevented me from turning off the computer (I repeated this 2 times to make sure problem)
In folder
`C:\Windows\LiveKernelReports`
I found
`ResourceTimeout-20210514-0917.dmp`
and analyzed it
`"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" -y "srv*c:\cache*https://msdl.microsoft.com/download/symbols" -z "C:\Windows\LiveKernelReports\ResourceTimeout-20210514-0917.dmp" `

Got the result:
```
EXRESOURCE_TIMEOUT_LIVEDUMP (1cc)
A kernel ERESOURCE has timed out. This can indicate a deadlock condition or
heavy contention which can cause performance issues.
Arguments:
Arg1: ffffe6036f56e750, The ERESOURCE that has timed out
Arg2: ffffe6034a711100, The thread that detected the timeout
Arg3: 0000000000000003, The ERESOURCE contention count
Arg4: 0000000000000096, The configured timeout in seconds
```
I attach the full result in the file 
[btrfs v1.txt](https://github.com/maharmstone/btrfs/files/6482676/btrfs.v1.txt)

**Comment by maharmstone** [comment]
Thanks, but I've not tested against this Primo Ramdisk, and the problem might just as well be there. Please reopen this if you can reproduce on an actual disk drive.
