### ISSUE TITLE
Corrupted Leaf, Read time tree block corruption.

### ISSUE THREAD

**Issue by quentinrossetti** [maharmstone/btrfs#379]
Hi,
I setup a dual boot on my existant Debian machine. My setup looks like this 
```sh
# Debian Root (SSD NVMe)
nvnme0n1p2 Btrfs subvol=/subvolumes/root,rw,noatime,ssd,discard,autodefrag,compress=lzo,space_cache,inode_cache
# Debian Home (SSD SATA)
sda1 Btrfs subvol=/subvolumes/home,rw,user,users,extra,noatime,ssd,discard,autodefrag,compress=lzo,space_cache,inode_cache
# My backup HDD "Vault"
sdb1 Btrfs rw,noatime,compress=zlib,autodefrag
```
After installing Windows I installed WinBtrfs 1.7.7, all drives are here Read-Write works perfectly, so I install a few Windows softwares on the Home partiton.
When rebooted into Debian, I got to the intramfs stage and see a "corrupt leaf" and "read time tree block corruption detected".
In the intramfs environnement I managed to mount Home, I saw that some directories where missing. 

No problem, I got backup (the "Vault") for (almost) all my system and data, I just reinstall all.
I tried to save a large file (a vm I had some work on) that I had no backup for in my "Vault". "System protected in read and write" from Windows

Loaded a Live Manjaro ISO to try access "Vault". The partition is mounted but the subvolume isn't accessible
```
cd /mnt/Vault/subvolumes/vault
cd: Input/ouptut error: vault
```

`btrfs scrub start /mnt/Vault` gave 8 uncorrectable data.

I've got very partial external backup, the all thing was part of my plan to setup a safe, resilent system but I backfires hard!

Does someone has the knowledge to help me recover the Vault ?
or Does someone knows a good company for that kind of recovery ?

All my data is gone, please help.

**Comment by maharmstone** [comment]
Closing old issues
