### ISSUE TITLE
mkbtrfs on existing btrfs volume

### ISSUE THREAD

**Issue by uroni** [maharmstone/btrfs#38]
So I accidentally did a mkbtrfs on an existing volume which caused a bluescreen. After reboot the volume wasn't accessible anymore and I had problems creating new partitions. This was on Windows 7 x64 with version 0.8.
It also bluescreens if I delete a volume with btrfs on it in the volume manager.
Tell me if you need logs or stack straces. Thanks!

**Comment by maharmstone** [comment]
Please, if you wouldn't mind. Was the existing volume Btrfs or something else?

**Comment by uroni** [comment]
It was already btrfs (so two exact same mkbtrfs commands).

**Comment by maharmstone** [comment]
Closing old issues
