### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by jyte** [maharmstone/btrfs#380]
Hi,

I just encountered a problem when windows decided it would be a great idea to write its swap on my linux rootfs partition... Ofc it filled it up and now it cannot be mounted anymore and my linux system is currently broken.

I think it would be wise to add a warning to remember to disable windows swap on btrfs partitions ?

**Comment by maharmstone** [comment]
I wasn't aware of any problems involving swap files, it should just work. What does `btrfs check` say?

**Comment by jyte** [comment]
```
sudo btrfs check /dev/sda6
Opening filesystem to check...
checksum verify failed on 10027008 found 000000B6 wanted 00000000
checksum verify failed on 10027008 found 000000B6 wanted 00000000
bad tree block 10027008, bytenr mismatch, want=10027008, have=0
ERROR: failed to read block groups: Input/output error
```

**Comment by jyte** [comment]
I tried several things so far. `btrfs restore` seems to see everything. `btrfs rescue super-recover`, `btrfs rescue zero-log` and `btrfs rescue chunk-recover` all say everything is fine. But mount fails with `wrong fs type, bad option, bad superblock on /dev/sda6, missing codepage or helper program, or other error.`. And dmesg shows `BTRFS error (device sda6): bad tree block start, want 10027008 have 0`

**Comment by maharmstone** [comment]
Closing old issues

**Comment by RokeJulianLockhart** [comment]
https://github.com/maharmstone/btrfs/issues/466#issuecomment-1833004364
