### ISSUE TITLE
How can we mount BTRFS file with a blank folder?

### ISSUE THREAD

**Issue by lohitagarwalla** [maharmstone/btrfs#383]
If a btrfs file is present along with many other files in a hard drive(For example: D:\ drive), how can we mount it with a blank folder in the same drive? 
As a use case I need to modify a btrfs file (add some files in the btrfs filesystem) and then flash it in a memory card. How can it be done using this repository?

**Comment by jsebean** [comment]
I really don't understand your question.

First off by "btrfs file" I assume you mean btrfs filesystem, and hard drive I assume you mean a partition formatted btrfs that you mount as D:. 

If you have subvolumes, if that's what you mean by mounting it with a "blank folder", and you want to mount a subvolume to a drive letter, you can mount it using the `SubvolId` option as described under the "Mount Options" header of the readme.

**Comment by maharmstone** [comment]
@lohitagarwalla - No idea. Using a VHD and whatever Windows has instead of `dd`. Either way, this isn't an issue with the driver.
