### ISSUE TITLE
Can't find btrfs service after being installed using (Chocolatey)

### ISSUE THREAD

**Issue by M1ndo** [maharmstone/btrfs#384]
Not sure what's the problem here , but can't figure out why winbtrfs is not installed a storage controller in windows 10 .
```
C:\Windows\System32>choco install winbtrfs
Chocolatey v0.10.15
Installing the following packages:
winbtrfs
By installing you accept licenses for the packages.
winbtrfs v1.7.7 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```
Checking service 
```
C:\Windows\System32>sc query btrfs
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:
The specified service does not exist as an installed service.
```
Also btrfs.sys doesn't exists on C:\windows/system32/drivers .
Specifications: Windows 10 Pro (2004)

**Comment by maharmstone** [comment]
You're best off raising this as an issue with Chocolatey, I haven't a clue how it operates...
