### ISSUE TITLE
Add changelogs to upcoming versions

### ISSUE THREAD

**Issue by second2050** [maharmstone/btrfs#387]
For users and fellow developers to see what important changes are being made to the project, it's always a good idea to maintain a changelog. It presents the average user with a rough idea of what to expect in an update and it gives contributors a good idea of what is being worked on or already resolved, to ensure they are putting in work where it matters.

**Comment by Kellegram** [comment]
Seconded (heh), I am quite interested in the development of Btrfs and it would be great to know when issues are resolved, straight from here.

**Comment by TheMadHau5** [comment]
Also, if this is going to be a thing, I suggest following the format of https://keepachangelog.com/en/1.0.0/
(it's like semver.org but for changelogs)

**Comment by TheEvilSkeleton** [comment]
@maharmstone this sounds like an important issue.

**Comment by second2050** [comment]
I just realized that a changelog is in the `README.md`, it would still be nice to have on the Releases themselves though

**Comment by maharmstone** [comment]
I'm happy with the present system.
