### ISSUE TITLE
Copied files are partially not displayed in the directory on the BTRFS disk after updating the driver to version 1.7.8

### ISSUE THREAD

**Issue by Denis-VG** [maharmstone/btrfs#389]
After updating the driver to version 1.7.8, when copying or creating files on disk, they are not displayed in Explorer. But when I try to re-copy or create a file, Explorer says that the file already exists. Total Commander does not see new files the same way. After restarting Windows, new files are displayed correctly. But if I try to copy or create a file again, then the process goes fine and the new files are not displayed again. Rolled back to version 1.7.7 - everything happens correctly. Files are visible both during creation and copying.
BTRFS disk - raid 5 by 1.5 TB from 4 physical disks.
The number of files and directories is about 65 thousand. Sincerely, Denis.

**Comment by Denis-VG** [comment]
https://user-images.githubusercontent.com/55048891/121776290-b3f97300-cb94-11eb-9146-66d79ad54689.mp4

**Comment by ewy0** [comment]
I am experiencing this issue as well.

**Comment by Obi001** [comment]
uncompressed folders seems to be ok.

**Comment by Denis-VG** [comment]
The entire disk is not compressed. I do not use compression, due to the fact that backups are stored on this disk. And they are already compressed, in most cases. And yes. "Hidden" folders and files are opened by specifying the full path, even if they are not visible in Explorer.

**Comment by maharmstone** [comment]
This is fixed by https://github.com/maharmstone/btrfs/commit/cf152dad97540d2dd63d7fa43358ecfe1732d7fc. Thanks Denis, especially for the video - that helped a lot.

I've just released v1.7.8.1, which includes this fix.
