### ISSUE TITLE
Bluescreen when iterating over files with Explorer (properties)

### ISSUE THREAD

**Issue by uroni** [maharmstone/btrfs#39]
Version 0.8 on Windows 7 x64:

DUMP_CLASS: 1
DUMP_QUALIFIER: 0
BUILD_VERSION_STRING:  7601.18741.amd64fre.win7sp1_gdr.150202-1526
WRONG_SYMBOLS_TIMESTAMP: 54d0317d
WRONG_SYMBOLS_SIZE: 5e7000
FAULTING_MODULE: fffff8000285a000 nt
DEBUG_FLR_IMAGE_TIMESTAMP:  54d0317d
DUMP_TYPE:  0
BUGCHECK_P1: ffffffffc0000005
BUGCHECK_P2: fffff88002caf3e2
BUGCHECK_P3: fffff8800420d4f8
BUGCHECK_P4: fffff8800420cd50
EXCEPTION_CODE: (NTSTATUS) 0x54d0317d - <Unable to get error code text>
FAULTING_IP: 
btrfs!update_tree_extents+602 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 793]
fffff880`02caf3e2 8b402c          mov     eax,dword ptr [rax+2Ch]

EXCEPTION_RECORD:  fffff8800420d4f8 -- (.exr 0xfffff8800420d4f8)
ExceptionAddress: fffff88002caf3e2 (btrfs!update_tree_extents+0x0000000000000602)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 000000000000002c
Attempt to read from address 000000000000002c

CONTEXT:  fffff8800420cd50 -- (.cxr 0xfffff8800420cd50)
rax=0000000000000000 rbx=fffffa80056d2060 rcx=fffff8a010bf0b83
rdx=fffff8a010bf0b83 rsi=fffffa8003fd8450 rdi=0000000000000001
rip=fffff88002caf3e2 rsp=fffff8800420d730 rbp=0000000000000080
 r8=fffff8800420d6b8  r9=0000000000000001 r10=fffffa8003f40148
r11=fffff8a010bf0aa0 r12=fffffa8006745050 r13=fffff88002cbd7a0
r14=0000000000000000 r15=fffff80000b94080
iopl=0         nv up ei pl nz na pe nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
btrfs!update_tree_extents+0x602:
fffff880`02caf3e2 8b402c          mov     eax,dword ptr [rax+2Ch] ds:002b:00000000`0000002c=????????
Resetting default scope

CPU_COUNT: 2
CPU_MHZ: d4b
CPU_VENDOR:  GenuineIntel
CPU_FAMILY: 6
CPU_MODEL: 3a
CPU_STEPPING: 9
CURRENT_IRQL:  0
ANALYSIS_SESSION_HOST:  URPC
ANALYSIS_SESSION_TIME:  01-11-2017 13:26:30.0205
ANALYSIS_VERSION: 10.0.10586.567 amd64fre
LAST_CONTROL_TRANSFER:  from fffff88002caecc6 to fffff88002caf3e2
STACK_TEXT:  
fffff880`0420d730 fffff880`02caecc6 : fffffa80`067451a0 fffff8a0`03605bd0 00000000`00000000 fffff880`0420db80 : btrfs!update_tree_extents+0x602 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 793]
fffff880`0420d980 fffff880`02cadb54 : fffffa80`067451a0 00000000`00000000 fffff880`0420db80 fffff880`0420db80 : btrfs!allocate_tree_extents+0x2f6 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 1116]
fffff880`0420da00 fffff880`02cbd93b : fffffa80`067451a0 00000000`00000000 fffff880`0420db80 00000000`00000001 : btrfs!do_write+0x764 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 5502]
fffff880`0420db60 fffff880`02cbd873 : fffffa80`067451a0 fffffa80`00000000 fffffa80`00000000 fffff880`0420dc00 : btrfs!do_flush+0x5b [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 5662]
fffff880`0420dba0 fffff800`02b6db8a : fffffa80`06745050 fffff800`02a4be80 fffff880`0420dc70 fffffa80`056d2060 : btrfs!flush_thread+0xd3 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 5693]
fffff880`0420dc00 fffff800`028c08e6 : fffff800`02a4be80 fffffa80`056d2060 fffffa80`0401bb50 00000000`00000000 : nt!PsCreateSystemThread+0x1da
fffff880`0420dc40 00000000`00000000 : fffff880`0420e000 fffff880`04208000 fffff880`0420cca0 00000000`00000000 : nt!KeInitializeSemaphore+0x25a
THREAD_SHA1_HASH_MOD_FUNC:  0bd7c172bee0e06aa4acb424ebc1375d875c8368
THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  434b67b48b834ff5a6464515b05028d3f918ce26
THREAD_SHA1_HASH_MOD:  d8536f19397b300fcb041d1189453fb65a43a6b1
FOLLOWUP_IP: 
btrfs!update_tree_extents+602 [z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c @ 793]
fffff880`02caf3e2 8b402c          mov     eax,dword ptr [rax+2Ch]
FAULT_INSTR_CODE:  892c408b
FAULTING_SOURCE_LINE:  z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c
FAULTING_SOURCE_FILE:  z:\home\hellas\desktop\wine\fs\btrfs\src\flushthread.c
FAULTING_SOURCE_LINE_NUMBER:  793
SYMBOL_STACK_INDEX:  0
SYMBOL_NAME:  nt_wrong_symbols!54D0317D5E7000
FOLLOWUP_NAME:  MachineOwner
STACK_COMMAND:  .cxr 0xfffff8800420cd50 ; kb
BUGCHECK_STR:  54D0317D
EXCEPTION_CODE_STR:  54D0317D
FAILURE_EXCEPTION_CODE:  54D0317D
EXCEPTION_STR:  WRONG_SYMBOLS
PROCESS_NAME:  ntoskrnl.wrong.symbols.exe
IMAGE_NAME:  ntoskrnl.wrong.symbols.exe
MODULE_NAME: nt_wrong_symbols
BUCKET_ID:  WRONG_SYMBOLS_X64_7601.18741.amd64fre.win7sp1_gdr.150202-1526_TIMESTAMP_150203-022501
DEFAULT_BUCKET_ID:  WRONG_SYMBOLS_X64_7601.18741.amd64fre.win7sp1_gdr.150202-1526_TIMESTAMP_150203-022501
PRIMARY_PROBLEM_CLASS:  WRONG_SYMBOLS
FAILURE_BUCKET_ID:  WRONG_SYMBOLS_X64_7601.18741.amd64fre.win7sp1_gdr.150202-1526_TIMESTAMP_150203-022501_54D0317D_nt_wrong_symbols!54D0317D5E7000
TARGET_TIME:  2017-01-11T12:26:00.000Z
OSBUILD:  7601
OSSERVICEPACK:  1000
SERVICEPACK_NUMBER: 0
OS_REVISION: 0
SUITE_MASK:  272
PRODUCT_TYPE:  1
OSPLATFORM_TYPE:  x64
OSNAME:  Windows 7
OSEDITION:  Windows 7 WinNt (Service Pack 1) TerminalServer SingleUserTS
OS_LOCALE:  
USER_LCID:  0
OSBUILD_TIMESTAMP:  2015-02-03 03:25:01
BUILDDATESTAMP_STR:  150202-1526
BUILDLAB_STR:  win7sp1_gdr
BUILDOSVER_STR:  6.1.7601.18741.amd64fre.win7sp1_gdr.150202-1526
ANALYSIS_SESSION_ELAPSED_TIME: 3c
ANALYSIS_SOURCE:  KM
FAILURE_ID_HASH_STRING:  km:wrong_symbols_x64_7601.18741.amd64fre.win7sp1_gdr.150202-1526_timestamp_150203-022501_54d0317d_nt_wrong_symbols!54d0317d5e7000
FAILURE_ID_HASH:  {c3603831-0fe3-e90c-bda5-7cc3bb41a047}
Followup:     MachineOwner

**Comment by maharmstone** [comment]
Thank you. This should be fixed by https://github.com/maharmstone/btrfs/commit/8e3e91388f04b5e4788dd3b588d0681912557308.
