### ISSUE TITLE
Win7: Some files don't get listed (maybe compression related?)

### ISSUE THREAD

**Issue by lss4** [maharmstone/btrfs#393]
On Windows 7 I noticed this strange phenomenon with Btrfs partitions. This is observed on latest versions (since 1.7.7).

A newly created file may not be listed. `DIR` command, or function calls that list files in a directory, would not return the file in question. However, they can be accessed, copied or moved without issues, if I explicitly specify the file path in the command line. Usually a reboot would make the affected files show up correctly.

The issue is relatively easy to reproduce. Download a file using a web browser (like Firefox) has a good chance of triggering the issue, that after finishing the download, the downloaded file doesn't show up when you browse the folder, but Firefox can still correctly open the file.

However, the issue does indeed affect some programs and batch scripts, as checking whether the file in question exists may return false (depending on how the check was done) resulting in unexpected execution paths despite the file in reality does exist.

The partitions were made on Linux. As they're mounted with zstd compression by default on Linux, I mounted them on Windows with compression turned on (using default compression parameters which would also be zstd) from the registry as well.

I don't know if compression might be causing this as on some other PCs that also use WinBtrfs I did not enable compression before and never really noticed this happening. Also, WinBtrfs also doesn't cope well with "show compressed/encrypted NTFS files in color" option. Files in the Btrfs volume are in default color regardless of whether they're compressed or not, but compressed files copied from NTFS partitions would stay blue, perhaps until next system boot (I didn't pay attention, though).

**Comment by maharmstone** [comment]
Even on v.1.7.8.1?

**Comment by lss4** [comment]
Whoa, didn't notice a new version just came out...

Just tried the 1.7.8.1 and it appears the issue seems gone. The batch script I was having problems with finished smoothly this time.
