### ISSUE TITLE
btrfs-1.7.8.1  on windows 10 - Configure to manually mount only needed partition ?

### ISSUE THREAD

**Issue by jonau01** [maharmstone/btrfs#394]
Hi,

I have several hard disks ( different linux distros ) and and each has several partitions.  When I boot from windows there are too many mounted and I don't need any of them.   I use btrfs-1.7.8.1 mainly to access external USB disk.

Is it possible to configure it to manually mount only partition that I need ?  Especially USB external disk ?

Thanks

**Comment by itsTyrion** [comment]
No, but you can set the ignore flag for persistent partitions
https://github.com/maharmstone/btrfs#mount-options

**Comment by maharmstone** [comment]
Closing old issues
