### ISSUE TITLE
Rename file to be larger than 255 bytes is possible in 1.7.8

### ISSUE THREAD

**Issue by MakiseKurisu** [maharmstone/btrfs#398]
I was trying to restore my file from a backup and one of the file cannot be restored. Out of curiosity I created an empty file and renamed to that long name from File Explorer. Well it worked, and left me an immutable file. I have to reverted to 1.7.5 to delete the said file.

**Comment by MakiseKurisu** [comment]
The troublesome name is "[111109] TVアニメ 真剣で私に恋しなさい!! ED主題歌「君の真剣をちょうだい」／川神百代（CV：浅川悠）、川神一子（CV：友永朱音）、椎名京（CV：氷青）、クリス（CV：伊藤静）、黛由紀江（CV.rar". I'd like to see if there is a way to find those long names, and if we can add a mount option to allow very long file name so we can fix them.

**Comment by MakiseKurisu** [comment]
I made a simple PowerShell function to find those offending files. You can't change them under Linux so PowerShell is the way to go.
```powershell
Function Check-FileNameSize([string]$Target) {
    Get-ChildItem -LiteralPath $Target |
    Foreach-Object {
        If ($_ -is [System.IO.DirectoryInfo]) {
            Check-FileNameSize($_.FullName)
        }
        Elseif ($_ -is [System.IO.FileInfo]) {
            If ([System.Text.Encoding]::UTF8.GetByteCount($_.Name) -gt 255) {
                Write-Output $_.FullName
            }
        }
        Else {
            Write-Output "Unknown type: $_.FullName"
        }
    }
}
```

Related: #322

**Comment by maharmstone** [comment]
Thanks. Yep, you're right - `set_rename_information` doesn't call `check_file_name_valid`. I'll sort it.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/8d1d5d64aeedd960fa6d9d39c2079619bb844560.
