### ISSUE TITLE
Windows 11 Compatible?

### ISSUE THREAD

**Issue by bshor** [maharmstone/btrfs#399]
Hi, I just started using this great software on Windows 10 -- works really well!

I am thinking about installing the Windows insider dev channel build of Windows 11. Is Winbtrfs compatible with Win11? Seems like it should be, but I wanted to be sure.

**Comment by maharmstone** [comment]
Thanks @bshor. I don't develop or test against unreleased versions of Windows - if for some reason it doesn't work, I'll fix it once Windows 11 is released properly.

**Comment by bshor** [comment]
I totally understand. Ok, I'll check back in October!

**Comment by Masamune3210** [comment]
upgrading to 11 bugchecked repeatedly until I uninstalled the driver so doubt you would have much luck
