### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [maharmstone/btrfs#4]
Would you like to [replace more defines for constant values](https://github.com/maharmstone/btrfs/blob/839ca8c6b889f33c372772d13f700de9c0d4babe/src/btrfs.h#L18 "Update candidate") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?

**Comment by maharmstone** [comment]
Hmm, not sure about this. To my mind, enums imply something which is a) internal, b) arbitrary, and c) (usually) consecutive, whereas all the values in btrfs.h are constants the filesystem itself uses. Plus the TYPE_ values you linked to are all UINT8s; I'm uncomfortable with using a type larger than that (like an enum, which is an int) to store them, unless we absolutely have to.
