### ISSUE TITLE
Reflink support

### ISSUE THREAD

**Issue by uroni** [maharmstone/btrfs#40]
Are there plans to implement an BTRFS_IOC_CLONE ioctl equivalent on Windows?

I am asking, because if this is implemented I would be able to have UrBackup Server run on Windows with btrfs :)

**Comment by maharmstone** [comment]
Yep, it's on my list! Probably not the next version, but the one after that.

I don't think there's an existing Windows ioctl I can co-opt though... I'm not sure FSCTL_SIS_COPYFILE does what we need it to. You might have to patch your program to get it to use the right fsctl.

**Comment by 0xbadfca11** [comment]
@maharmstone Windows 10 & Server 2016 has [FSCTL_DUPLICATE_EXTENTS_TO_FILE](https://msdn.microsoft.com/en-us/library/windows/desktop/mt590820.aspx), and [FILE_SUPPORTS_BLOCK_REFCOUNTING](https://msdn.microsoft.com/en-us/library/cc232101.aspx) indicating that filesystem supports it.
This FSCTL is similar to BTRFS_IOC_CLONE_RANGE.
Veeam Backup & Replication software and Hyper-V version 2016 is already using this.

**Comment by maharmstone** [comment]
Thank you, that looks promising.

**Comment by maharmstone** [comment]
This is fully implemented now, and will be available in the next version.

**Comment by maharmstone** [comment]
Thank you - you're right, I wasn't aware of that. Confusingly, it seems that the AllocationSize in the FCB header isn't necessarily the same as the AllocationSize returned by QueryStandardInfo etc. I've fixed it now: https://github.com/maharmstone/btrfs/commit/5347e4bb42c910038555aebd7adba0316d6bc29b
