### ISSUE TITLE
Windows Insider Dev Channel Issues?

### ISSUE THREAD

**Issue by bshor** [maharmstone/btrfs#400]
I know winbtrfs is not tested under the new Windows 11. But I'd still wanted to switch to the Windows 10 dev channel to get access to the new WSLg (graphical interface for WSL2). Does anybody have experience with the dev channel and btrfs?

**Comment by Masamune3210** [comment]
it at least didn't bugcheck on latest dev build right before 11, didn't have any drives to check at the time though so your milage may vary farther than that

**Comment by Snoop05** [comment]
Not working on 22000.51, disabling secureboot / reg entry mentioned work for making the driver install (Btrfs controller shows up in device manager) but when i connect my 2hdd raid0 array, login screen / explorer just hang indefinetly to the point i have to force shutdown.

**Comment by alex4401** [comment]
Getting hangs on a specific partition during high activity (seems to happen regardless of whether it's reads or writes). It might be safer for you not to upgrade to Windows 11.

It did work rather flawlessly on the previous build. If you download an ISO from [this page](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?wa=wsignin1.0) it should still be Windows 10.

**Comment by bshor** [comment]
Yes, I'm not going to do anything until people report good experiences with winbtrfs on something other than the stock Windows 10.

I asked about 11 in a separate thread and people warned me off. This thread was about an Insider build for Windows 10, not 11 (just for the WSLg feature), but again people are warning me off too...

**Comment by alex4401** [comment]
The warnings here so far refer to 22000.51, which is the Windows 11 build. Masamune3210's and my comments both state the latest Windows 10 devbuild was fine.

**Comment by wael444** [comment]
I couldn't get my version of windows 11 but it is 22000.X installing winbtrfs breaks my install of windows 11 and I'm stuck at the boot screen (safe mode works), I've tried upgrading windows 10 with winbtrfs already installed and it gives the same result.

**Comment by alex4401** [comment]
Got a similar problem with one machine out of three. 22000.160, two BTRFS partitions. One's around 80 gigabytes, second's well around 700. Survives first few boots, then stops booting soon after with no event log updates. Driver's debug log doesn't differ from a clean boot. Boots again when the second (bigger) partition has been removed from the setup, so far no interruption after 3 days.

**Comment by maharmstone** [comment]
Closing old issues
