### ISSUE TITLE
Read-only mount

### ISSUE THREAD

**Issue by ShashaankHari** [maharmstone/btrfs#403]
Is there any way I could mount the drives as read only, always and write when only absolutely necessary.?
I really don't want to mess up my partitions on windows in any way..

**Comment by ShashaankHari** [comment]
Is there any way I could mount the drives as read only, always and write when only absolutely necessary.?

**Comment by cooper2k4** [comment]
With the `Readonly` registry key.

See [mount-options](https://github.com/maharmstone/btrfs#mount-options)
