### ISSUE TITLE
WinBtrfs mounting in read-only-mode?

### ISSUE THREAD

**Issue by gih19** [maharmstone/btrfs#407]
Hello, first, thanks for the program. It seems quite useful. Is it possible to mount a btrfs raid1 in read-only-mode? And how? Mounting in normal (read-write-) mode works quite well.

**Comment by lss4** [comment]
You're not the first one asking this (#366, #403).

There's a registry key for it but it's currently not enforced on first run. If you're concerned about corruption you may set it before you actually access any files in it.

**Comment by maharmstone** [comment]
Closing old issues
