### ISSUE TITLE
Accessing btrfs filesystem through WSL

### ISSUE THREAD

**Issue by fuwwy** [maharmstone/btrfs#408]
I create a btrfs partition which completely works through Windows and shows up on WSL under /mnt/e, however, when I try to run anything btrfs related on WSL, such as `btrfs subvolume create test` or `btrfs subvolume list .`  I get `ERROR: not a btrfs filesystem: .`. How can I make WSL have the correct filesystem type?

**Comment by maharmstone** [comment]
As far as I'm aware, you can't. Unless they've changed it since, Microsoft's pseudo-driver drvfs doesn't forward Linux ioctls to the underlying filesystem driver. More's the pity.

**Comment by fuwwy** [comment]
@maharmstone I found a way to do it by mounting the drive to wsl using --bare, however, that requires unmounting it from Windows. Is there any way to make the driver pick up on the disk once it's mounted back to Windows? Right now it seems to only work on system restart

**Comment by RokeJulianLockhart** [comment]
@itsfolf, https://github.com/microsoft/WSL/issues/6711#issuecomment-1245808537 might be useful.
