### ISSUE TITLE
bitlocker encrypted btrfs not detected

### ISSUE THREAD

**Issue by darrellenns** [maharmstone/btrfs#409]
Bitlocker encrypted btrfs drivers don't currently seem to work. I suspect it may be that the btrfs volume is just not being detected when bitlocker is unlocked - maybe some extra trigger to probe for volumes is needed?

If winbtrfs worked with bitlocker, it would be possible to have a fully encrypted disk with btrfs that can be used on both windows and linux.

I tested this as follows:

- Installed latest winbtrfs release and verified it works with plain (non-bitlocker) btrfs volumes
- Created a normal NTFS bitlocker volume in Windows (protected with a password)
- Using Linux, unlocked the bitlocker volume (cryptsetup bitlkOpen /dev/XXX foo) and reformatted it as btrfs (mkfs.btrfs /dev/mapper/foo)
- In windows, unlock the bitlocker volume. The volume unlocks but is not recognized as btrfs (no btrfs tab in properties, and opening the volume prompts to format it).

Is there some way to manually tell winbtrfs to rescan/treat the volume as btrfs? Maybe some extra hooks/triggers needed to make btrfs re-detect when the volume is unlocked?

**Comment by maharmstone** [comment]
Hmm, you're right. Thanks, I'll look into it!

**Comment by maharmstone** [comment]
This is now working as of the latest master.
