### ISSUE TITLE
Как в драйвере BtrFS версии 1.7.8.1 снять ограничение на название файла длиной в 255 байт

### ISSUE THREAD

**Issue by OlegVF** [maharmstone/btrfs#413]
Нужно в исходном файле btrfs.c в папке src изменить такие строки:

-  Нужно строку **1025** в исходном коде:

       data->MaximumComponentNameLength = 255; // FIXME - check

- изменить на:

       data->MaximumComponentNameLength = 510; // FIXME - check

-  Нужно строку **5788** в исходном коде:

       if (utf8len > 255)

- изменить на:

       if (utf8len > 510)

-  Нужно строку **5790** в исходном коде:

       else if (stream && utf8len > 250) // minus five bytes for "user."

- изменить на:

       else if (stream && utf8len > 500) // minus five bytes for "user."

Причина этих действий в том, что в Windows на кодирование имени файла используется кодировка UTF16 и длина имени файла ограничена в 255 символов, а не в 255 байт. Так же русские символы в кодировке UTF8 (BtrFS) кодируются в 2 байта на символ, что приводит к конфликту и урезанию длины названия файла в 2 раза. Чтобы исправить ситуацию и добавить поддержку в 255 русских символов в названии файла, приходится увеличивать в 2 раза ограничение в 255 байт.

Просьба к разработчику BtrFS for Windows, внести данные изменения в свое решение для большей совместимости с Windows...

**Comment by maharmstone** [comment]
If you're not going to at least do the courtesy of running this through Google Translate, why should I waste my time in looking at this?
