### ISSUE TITLE
Problems with RAID1 array

### ISSUE THREAD

**Issue by yesgrey** [maharmstone/btrfs#419]
Hi,

First let me thank you for your work on this. It's really nice software and quite helpful for a dual boot system.
 
I am running a dual boot system with Win10 21H1 and Linux Fedora34.

I decided to create a btrfs RAID1 volume on my Fed34 with two 14TB HDs, using BLAK2b as checksum algo and noatime for mounting. This is to store all my important files: my films, photos, music, etc.
I use Win10 to watch the films, because Linux has not the same quality and speed, and for that I am using Winbtrfs to mount this volume on Windows, and, for safety, I set the volume only as readonly in Win10.
Unfortunately, this configuration is not usable at all. Whenever I try to watch a film directly from this volume I hear a lot of noise coming from my computer (the intensive read access sound from the hard disks), the file explorer blocks completely, and I always have to shutdown my computer.
I have another btrfs RAID0 volume on my Fed34 with two 1TB SSDs, using xxhash, and this works flawlessly on Win10. This I run with both R/W access.
I already thought of running the RAID1 with R/W, but considering the behaviour I'm gettting I'm afraid of having the volume corrupted, so, I would rather not try that.
I tried to see if I could mount the volume on Windows 10 with the noatime option, but I cannot find any setting for that, so, I'm assuming it's on, and maybe this could be the issue?
I'm not sure if this is a bug or normal performance with hard disks, but considering that the disks get fully blocked, I suspect something is not right...

Please let me know if I could give you more info on how to debug this. I'm using version 1.7.8.1

Thanks!

**Comment by yesgrey** [comment]
An update after testing version 1.7.9...

It still has the problem, but is not as bad as 1.7.8.1:
-on folders with a small number of files the system is usable, but if the number of files is significant (50+), it starts behaving the same way. However, it improved slightly, because if I close File Explorer, the system hangs for a few minutes, but eventually it closes File Explorer and stops the intense reading of the disks, and the system becomes responsive again without having to restart it.
-I've tried mounting the volume as Read/Write, but same behaviour, so, not related to have it as Readonly.
-I've noticed that on the RAID0 volume, the one that works fine, if I see the volume properties the "Allow files on this drive to have contents indexed..." is not enabled, however, on the RAID1 volume, it is enabled. I wonder if this could be one of the possible causes?
-I have also tried to disable the automatic folder type detection, but I'm not sure if your driver is ignoring that. Maybe could also be one of the potential issues?
-Is there any option to decide how to mount the volumes either with noatime or relatime?

Please let me know if I could help you debugging this in any way.

Thank you.

**Comment by maharmstone** [comment]
Closing old issues
