### ISSUE TITLE
Scrub failed with error c000009c

### ISSUE THREAD

**Issue by jonassimpson** [maharmstone/btrfs#423]
**OS: Windows 10 Pro build 19043.1237
btrfs volume is a single 6 TB drive connected via SATA**

This is a drive formatted yesterday using mkbtrfs. About 600 GB of data has been copied to the drive so far. The volume is configured as follows:

---------------------------------------------------------
Device size:		5.5 TB
Device allocated:		1.2 TB
Device unallocated:		4.2 TB
Data ratio:		2.00
Metadata ratio:		2.00

Data, DUP: size: 619.0 GB, used: 618.8 GB
Disk 1, partition 2	1.2 TB

Metadata, DUP: size: 1.0 GB, used: 789.7 MB
Disk 1, partition 2	2.0 GB

System, DUP: size: 8.0 MB, used: 112.0 KB
Disk 1, partition 2	16.0 MB

Unallocated:
Disk 1, partition 2	4.2 TB

---------------------------------------------------------

The scrub progress bar gets to about 0.6% before the failure and the status log above it in the window reports 7.7 GB scrubbed.

Any ideas of the cause or is there another way to run a scrub?

Thanks,

JS

**Comment by maharmstone** [comment]
C000009C is STATUS_DEVICE_DATA_ERROR, which isn't an error generated by the driver directly. Probably it's your device? You might want to do a full check for bad blocks using gsmartcontrol or similar.

**Comment by jonassimpson** [comment]
Hmm, interesting... the reason I'm trying btrfs and why I've got Data set to DUP is for that exact reason. It's a disk with a fixed number of blocks that have been reallocated (about 9000) but I wanted to still use for some third or fourth tier backups. I've run multiple full surface scans with HD Sentinel and the number of reallocated blocks does not increase so I thought if I could use btrfs with all data stored twice on the disk I could still use about 3 TB of space for something. If a scrub doesn't work because the disk is misbehaving in other ways, however, I guess it might not be worth the hassle and I should just chuck it out.

Thanks for the quick reply, much appreciated.

**Comment by maharmstone** [comment]
No problem.

There's no provision in btrfs for bad blocks, as there is in e.g. ext2 or NTFS... so btrfs isn't your best bet if that's what you're trying. But from a cost-benefit point of view, I think pretty much everyone would agree that the only place for a dodgy drive is the bin...

**Comment by jonassimpson** [comment]
Yes, I know that to be true... it would make the decision so much easier if the drive would just die completely... :)

Thanks again!
