### ISSUE TITLE
External drive not visible

### ISSUE THREAD

**Issue by pmroot** [maharmstone/btrfs#424]
The external drive with the Btrfs filesystem is not visible in windows explorer after rebooting. In the device manager it is visible. The drive was formatted for nextcloud.

**Comment by maharmstone** [comment]
I don't know anything about how Nextcloud works, but it sounds like it might have some sort of intermediate layer. If you were to mount it under Linux, what device name would you use?

**Comment by Catalinox** [comment]
Thanks for your answer. The mountpoint ist /media/myCloudDrive

![Screenshot (488)](https://user-images.githubusercontent.com/73262661/135072189-9b8d1260-5833-4da3-9db9-f930be0e30ed.png)

**Comment by maharmstone** [comment]
Closing old issues

**Comment by RokeJulianLockhart** [comment]
https://github.com/maharmstone/btrfs/issues/466#issuecomment-1833004364
