### ISSUE TITLE
Not working on win11, all versions。

### ISSUE THREAD

**Issue by harvey-git** [maharmstone/btrfs#430]
Not working on win11, all versions。
 I was the one who reported that the btrfs volume under winmd did not show up. At that time, I didn’t expect the reason why win11 was not supported.  in order to solve the problem that my raid5 partition was not displayed under win11, I put those three The hard disk array is connected to a diy nas, shared to win11 through iscsi, and then iscsi is connected, the system directly stops responding, except that the mouse can move, everything just hang indefinetly to the point i have to force shutdown.

**Comment by sovy666** [comment]
> Not working on win11, all versions。 I was the one who reported that the btrfs volume under winmd did not show up. At that time, I didn’t expect the reason why win11 was not supported. in order to solve the problem that my raid5 partition was not displayed under win11, I put those three The hard disk array is connected to a diy nas, shared to win11 through iscsi, and then iscsi is connected, the system directly stops responding, except that the mouse can move, everything just hang indefinetly to the point i have to force shutdown.

After disabling secure boot everything works fine for me. I write this for information, it is clear that it will take a solution from the developers for those who want to have the secure boot enabled but for now you can try to solve this way.

**Comment by dhdgves** [comment]
I got several crash after I first install this driver on win11(Dev channel). But it works fine now(win11 Build 22471). Maybe you can try to follow the guide about secureboot in README, if you haven't follow that prompt. It's fine for me to enable secure boot. I'm dual system user, both archlinux and windows, using rEFInd.

**Comment by Masamune3210** [comment]
You dont even have to go that far, there is a reg tweak you can do while in the installer to tell it to ignore the checks
