### ISSUE TITLE
Just some questions about Snapshots

### ISSUE THREAD

**Issue by AlecMcCutcheon** [maharmstone/btrfs#431]
First of all how do I successfully create a snapshot, second of all where are you supposed to save that snapshot if it has to be done with the command line, and 3rd is there a GUI for creating and restoring snapshots?.

If someone could give me some examples and how to on how to do this or where to find the GUI, I was kinda half expecting the snapshot to show up in the previous versions tab inside the context menu of the folder but I suppose it probably won't be there.

**Comment by maharmstone** [comment]
Closing old issues
