### ISSUE TITLE
it is too easy to cause bsod

### ISSUE THREAD

**Issue by layerfsd** [maharmstone/btrfs#435]
when i copy huge counts of files( more than 100 millions,around 4TB) to winbtrfs base volume,it is very high frequency bsod,win 10 ltsc 1809 x64

**Comment by maharmstone** [comment]
Can you send me a minidump?

**Comment by layerfsd** [comment]
> Can you send me a minidump?

here is the dump:https://github.com/layerfsd/mydmp

This is a problem that is easy to reproduce，you can copy many many files from a ntfs volume to the winbtrfs volume,i try copy 2TB files once a time from a nvme to the other, files size less then 4kb,or bigger than 100gb.

and there is a other problem,it is easy to getlasterror code 23 while i read a file from winbtrfs volume

**Comment by layerfsd** [comment]
and it might has memory leaked,while copy many files ,the memory usage will very very high,i try copy 2TB data using fastcopy,my machine will bsod with memory empty.i have 32GB memory,win10 1809 x64

**Comment by maharmstone** [comment]
Are you sure this is caused by btrfs? Neither of these has btrfs.sys in the stack trace - one is reading from the registry, the other is seemingly doing nothing. You're not overclocking, are you, or have dodgy RAM?

> getlasterror code 23 while i read a file from winbtrfs volume

Which is ERROR_CRC, and definitely sounds to me like a hardware error of some variety.

**Comment by dLCarbonX** [comment]
@maharmstone I think you are onto something with mentioning OC and dodgy RAM for a good bit of these hard locks and BSODs mentioned in other issues. I know I have some issues with my RAM that I'm using outside of intended purposes and getting similar BSODs and softlocks to multiple issues mentioned.

**Comment by maharmstone** [comment]
Closing old issues
