### ISSUE TITLE
Crash when deleting snapshot of subvolume having subvolume

### ISSUE THREAD

**Issue by 0xbadfca11** [maharmstone/btrfs#44]
Windows 10 v1703 x64
btrfs volume was created with mkbtrfs.exe without options.

Create a subvolume and create a subvolume in previous subvolume.
```
\  
└───New subvolume  
    └───New subvolume  
```
Create a snapshot of the upper subvolume in the above state.
```
\
├───New subvolume
│   └───New subvolume
└───Snapshot of New subvolume (2017-04-06)
    └───New subvolume
```
Delete snapshot, then crash.
Sometimes it does not crash, but at that time the lower subvolume disappears.

Log file(DebugLogLevel=3) of v0.9 [btrfs1.txt](https://github.com/maharmstone/btrfs/files/902555/btrfs1.txt)
This log file is the one when crashed with the binary I built from source code at 7c208a44afa931d381189192e04e151d52e7aa16. [btrfs2.txt](https://github.com/maharmstone/btrfs/files/902559/btrfs2.txt)

**Comment by maharmstone** [comment]
Thank you. The last few patches should fix this.
