### ISSUE TITLE
Bitlocker not suitable for btrfs?

### ISSUE THREAD

**Issue by n8w8** [maharmstone/btrfs#441]
The issue seems to be not with WinBtrfs per se, but with btrfs on Bitlocker in general (or at least in Linux).
Maybe WinBtrfs is also affected, or maybe you want to put a note about this in the docs?

In Windows I fully format a volume as NTFS, then fully Bitlocker encrypt it.
In Linux I unlock it, then the unlocked device I reformat as btrfs.
I find the problem with that is, that in Linux the unlocked device is not a "normal" block device suitable for btrfs.

In Bitlocker, some space in the volume is reserved for metadata (keys etc).
But when I open the Bitlocker volume in Linux, the unlocked dm device is the same size as the raw encrypted device.
I expected it to be smaller, due to the metadata being unmapped (like with LUKS).
But in this case, the metadata blocks are part of the unlocked dm device.
Writes to there get ignored, reads from there return zero.
That is by design, as can be seen [here](https://vtrefny.fedorapeople.org/misc/devconf-bitlocker.pdf) on page 8.

So, you can create and use btrfs on such a device, AS LONG AS by chance, it only uses the properly working blocks.
But as soon as it tries to use the metadata blocks, things go wrong, I assume.
At least, I notice I/O errors by filling up the unlocked btrfs (cat /dev/urandom > /mnt/test or something), umount/remount, and then reading it back.
I assume with NTFS this isn't a problem, as that metadata area is also marked as reserved in the filesystem itself?
For btrfs to then work properly, it should do the same somehow.

This is how I understand it, but I don't know much about Windows/Bitlocker. Am I doing it wrong?
Note, for my personal day-to-day use, I only seek to read btrfs in Windows, and do all writing in Linux.
Though as I have to create Bitlocker in Windows anyway, I'm ok formatting btrfs in Windows, which I tried but failed. Also ntfs2btrfs failed. Hence the format in Linux.

Let me also put this to @darrellenns attention, as he also wanted to run btrfs on bitlocker ([here](https://github.com/maharmstone/btrfs/issues/409)).

Anyway, thanks! Awesome project.

**Comment by maharmstone** [comment]
If it's an issue with BitLocker in Linux, sorry, but it doesn't belong here...

All BitLocker-like things I've ever come across expose themselves to the filesystem as a normal block device, and I'm not aware that BitLocker itself is any different.
