### ISSUE TITLE
Code integrity determined that the image hash of a file is not valid

### ISSUE THREAD

**Issue by tadryanom** [maharmstone/btrfs#443]
Code integrity determined that the image hash of a file is not valid. The file could be corrupt due to unauthorized modification or the invalid hash could indicate a potential disk device error.

File name: \Device\HarddiskVolume3\Windows\System32\drivers\btrfs.sys

Windows 11 Pro Insider Preview
Build 22509.rs_prerelease.211119-1136

btrfs-1.7.9

**Comment by Masamune3210** [comment]
That is not a issue with the project, if I remember all that message is saying is that somehow the file was read and it didn't match the expected contents. Either the file is corrupt or you have a failing drive/filesystem corruption/ other issue with your computer

**Comment by tadryanom** [comment]
Problem solved, it was a Windows update that broke the driver.

**Comment by maharmstone** [comment]
Closing old issues
