### ISSUE TITLE
ON WINBTRFS i cannot publish NFS Share

### ISSUE THREAD

**Issue by tango38317** [maharmstone/btrfs#444]
Hi,
one question regarding sharing an NFS on WINBTRFS.
i have tried it, but run into publishing issues.
is this not implemented at the moment, or should it work?

i receive following error:
"Server for NFS cannot update the share configuration. Try updating the shared directory again, or delete and recreate the shared directory."

br
Chris

**Comment by maharmstone** [comment]
I've never tried using NFS on Windows - is this something built-in? What version of Windows are you on?

**Comment by tango38317** [comment]
Hi,
i have tried it with Windows Server 2019/2022.
Windows Server has an NFS Server as Server Role.
I think, the NFS Server tries to write some information on the share, and this does not work.
br
Chris

**Comment by maharmstone** [comment]
Closing old issues
