### ISSUE TITLE
How can a single bitflip cause 256 errors reported during scrubbing?

### ISSUE THREAD

**Issue by JustMyGithub** [maharmstone/btrfs#445]
For testing, I created a vhd file with a btrfs file system. I unplugged the vhd, flipped a single bit in a hex editor and then plugged in the vhd again. Scrubbing reports 256 errors even though a single bit was flipped and compression was not enabled for this file. how is that possible?

**Comment by ticpu** [comment]
Where did you flip that bit? In a metadata section? Folder entry? B-tree? Any snapshots? Pure data?

If it's in a b-tree, or any non-redundant critical metadata, that's no wonder. I think this issue needs more details to be valid.

**Comment by JustMyGithub** [comment]
I flipped the bit in a large area with high entropy, so it should be very likely that it was within the file and not within the metadata. However, if the Hex Editor does not understand BTRFS on the bit level (and neither do I) I cannot be 100% sure that it was not in the metadata. However: Bitrot happens randomly as well.

**Comment by maharmstone** [comment]
This bug report is too vague to be useful. Sorry.

**Comment by JustMyGithub** [comment]
Wouldn't it be useful to tell me how I can obtain the needed information instead of just closing the ticket?

**Comment by ticpu** [comment]
@JustMyGithub you can use the btrfs inspect-internal command to resolve and find out many aspects of the filesystem, including offsets.  So if you want to try flipping bits, use one of its sub-command to make sure you're in the data sections of a file.  Make sure to document everything including inspect-internal output before and after. Logs output of btrfsck would also help and how it reacts in Linux vs Windows to confirm it is a bug in winbtrfs itself.

Also make sure to try the same in RAID1 or DUP mode to see if the issue fixes itself, if it does, it is not a bug.
