### ISSUE TITLE
BSOD when (re)formating a volume

### ISSUE THREAD

**Issue by JustMyGithub** [maharmstone/btrfs#447]
Trying to compare the resource usage of different checksum algorithms I repeatedly got BSODed. I used

mkbrtfs f: /csum:xxhash
and
mkbrtfs f: /csum:blake2

if you send like 2-4 format commands like this quickly after each other that seems to crash the driver. It definitely happened with both csums, so it is not caused csum-specific parts of the code.

**Comment by maharmstone** [comment]
Can you please attach a minidump?

**Comment by JustMyGithub** [comment]
Please provide details on how to create a minidump (or where to find it), as the Readme.md does not mention it. In AppData\Local\CrashDumps I do not see any dump that matches the BSODs. I am not even sure weather/how minidump files are written on BSOD. %SystemRoot%\MEMORY.DMP does not exist as well.

**Comment by Masamune3210** [comment]
Make sure you have memory dumps turned on, it's in advanced system properties

**Comment by JustMyGithub** [comment]
So you are talking about system-level dumps. Those are activated, but nevertheless %SystemRoot%\MEMORY.DMP does not exists.

And when providing such files, how can I be sure not to accidentally provide Bitlocker keys or other critical information?

**Comment by megapro17** [comment]
It still exist. Got a few bsod's. But dump can't be saved, because it hangs saving at 0%. Waited a minute and pressed reset

**Comment by maharmstone** [comment]
Closing old issues
