### ISSUE TITLE
Corrupted drive after mounting subvolume

### ISSUE THREAD

**Issue by afeuerstein** [maharmstone/btrfs#450]
I am using WinBtrfs in a Windows VM on my linux (Artix, kernel `5.15.10-artix1-1`, btrfs-progs `v5.15.1`) host. I created a subvolume on my btrfs partition for the Windows VM and, after initially starting the VM with access to the root volume, pointed WinBtrfs' mout options to the submodule. Until then, everything worked normally under both operating systems. After rebooting the Windows VM the subvolume had been mounted successfully, but when I returned to linux I couldn't mount the whole partition:
```
~ mount /dev/mapper/sshd -t btrfs /mnt
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/mapper/sshd, missing codepage or helper program, or other error.
```
dmesg:
```
[ 5261.253078] BTRFS error (device dm-1): tree level mismatch detected, bytenr=162365440 level expected=1 has=0
[ 5261.253082] BTRFS error (device dm-1): tree level mismatch detected, bytenr=162365440 level expected=1 has=0
[ 5261.253084] BTRFS error (device dm-1): failed to read block groups: -117
[ 5261.254345] BTRFS error (device dm-1): open_ctree failed
```
btrfs check:
```
~ btrfs check /dev/mapper/sshd
Opening filesystem to check...
ERROR: child eb corrupted: parent bytenr=162840576 item=1 parent level=2 child bytenr=162365440 child level=0
ERROR: failed to read block groups: Input/output error
ERROR: cannot open file system
```
super-recover:
```
~ btrfs rescue super-recover /dev/mapper/sshd
All supers are valid, no need to recover
```
After booting back into the Windows VM WinBtrfs still could mount the subvolume. I removed the subvolume mount option and after a reboot WinBtrfs could read the whole disk. Any ideas about how I can restore functionality under linux? Is there any more information that I could supply to clear up the issue?

**Comment by afeuerstein** [comment]
After double-checking I noticed that in Windows i couldn't write anything to the device anymore. This may or may not be my fault, since I ran the `btrfs check --repair` program which warned me about not running it. I will try to reproduce this bug as soon as I have restored my backup.

**Comment by maharmstone** [comment]
>I created a subvolume on my btrfs partition for the Windows VM and, after initially starting the VM with access to the root volume

Are you saying here that you started a VM with access to a block device that the host also had mounted? Because that's going to corrupt any filesystem.

**Comment by afeuerstein** [comment]
No I didn't mount the device on both systems simultaneously. Should've phrased that better.

**Comment by afeuerstein** [comment]
Somehow I can't manage to recreate the issue. I'll re-open if I experience something similar again.
