### ISSUE TITLE
BSOD on btrfs!RemoveHeadList

### ISSUE THREAD

**Issue by BiatuAutMiahn** [maharmstone/btrfs#451]
```
Host: Windows 11 (10.0.22523.1000)
WinBtrfs: Version: v1.7.9
Issue: Fault During `btrfs!RemoveHeadList`
```

`MEMORY.DMP`: [https://mega.nz/file/gBQjjIyL](https://mega.nz/file/gBQjjIyL)
Biatu#4837 @ Discord for decryption key

**Comment by maharmstone** [comment]
I'm not messing around with Discord, please e-mail me the key if you want me to have a look at this.

**Comment by BiatuAutMiahn** [comment]
What's ur email?

**Comment by BiatuAutMiahn** [comment]
Any updates?

**Comment by maharmstone** [comment]
Closing old issues
