### ISSUE TITLE
Support to removable media

### ISSUE THREAD

**Issue by tadryanom** [maharmstone/btrfs#452]
Hey guys! Any plans to support removable media like external HD/SDD and USB sticks? I formatted a removable media, in this case an external HD, but the operating system does not allow me to eject it safely, I need to turn off the computer if I want to disconnect the device.

**Comment by arthurmv** [comment]
I can't eject my USB HDD too... it says my drive is in use, but I don't do anything.

**Comment by devurandom** [comment]
There seem to be more problems with this: 

* Windows appears to put the USB drive into power saving mode, which appears to hang the whole operating system and to screw up the file system. (Could be related to https://github.com/maharmstone/btrfs/issues/438) 
* Unplugging the drive physically causes an `IRQL_NOT_LESS_OR_EQUAL` blue screen.

**Comment by maharmstone** [comment]
Closing old issues
