### ISSUE TITLE
Windows XP SP3 x86 is not supported by latest version

### ISSUE THREAD

**Issue by GeorgeK1ng** [maharmstone/btrfs#453]
Hi,

I have discovered this awesome project and I would like to boot XP in UEFI mode. I have tried BTRFS drivers, but latest one compatible with XP SP3 x86 (Fully updated until 05-2019) is v 1.7.7.0. Newer versions have missing import from kernel32.dll. I haven't tried x64 version yet. I decided to save for future same version for both x86 and x64.

**Comment by maharmstone** [comment]
As I understand it this is something snuck in by later versions of MSVC, not the code itself, and it only affects the userspace helpers (the shell extension etc.). You should be able to install just the driver.

If you really need everything else, you'll have to find a new version of MSVC and compile it manually - or maybe try MinGW.

**Comment by ruevs** [comment]
https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-170

> ### Install the Windows XP platform toolset
> To get the v141_xp platform toolset and components to target Windows XP and Windows Server 2003, run the Visual Studio Installer.

The only thing I am not sure about is if the CMake configuration uses the DDK only to compile the driver and the SDK/platform toolset for the user space parts.

**Comment by lss4** [comment]
> Hi,
> 
> I have discovered this awesome project and I would like to boot XP in UEFI mode. I have tried BTRFS drivers, but latest one compatible with XP SP3 x86 (Fully updated until 05-2019) is v 1.7.7.0. Newer versions have missing import from kernel32.dll. I haven't tried x64 version yet. I decided to save for future same version for both x86 and x64.

I don't know which version exactly. I just walked the 1.7.9 version of `btrfs.sys` and it looks okay. No missing symbols on XP.

If you're talking about other components, such as shell extensions, see [my issue](https://github.com/maharmstone/btrfs/issues/378#issuecomment-901718056).

While I can't compile `btrfs.sys` from a Linux environment, with the correct Linux and MinGW-w64 environment you can build companion components such as `shellbtrfs.dll` that are Windows XP compatible.
