### ISSUE TITLE
How to mount a drive with nodatacow?

### ISSUE THREAD

**Issue by tonibgd** [maharmstone/btrfs#454]
On Linux i can set `nodatacow` mount parameter in `fstab`, how do i make sure `WinBtrfs` mounts that drive with `nodatacow` also?

**Comment by Lieutenant-L-T-Smash** [comment]
Just found that I need this for one of my drives. I'm dual-booting so I can set it on Linux but how to do this on Windows?

**Comment by maharmstone** [comment]
There's no global mount option at present, but you can set the flag on directories for it to be inherited by its children.

**Comment by maharmstone** [comment]
I've added a global mount option: https://github.com/maharmstone/btrfs/commit/c0219b39e48707f465c2b723ed379effd89c9284

**Comment by Lieutenant-L-T-Smash** [comment]
Thank you!
