### ISSUE TITLE
Figures Cache Chromium

### ISSUE THREAD

**Issue by dima333750** [maharmstone/btrfs#455]
Hello.
I decided to try WinBTRFS, created a section with the parameters of the compression of the ZSTD level 1.
I placed the Iron Portable on it (Browser based on Chromium) and for 3 days 2 times I received a complete hanging system caused by the hanging of BRTFS volume, I had to turn off the button.
I noticed that in both cases I looked through the video on the Internet and I think the problem in the cache browser is probably BRTFS poorly handles fast minor files.
I do not know how to hold a debugging hang because This is not bsod.

**Comment by maharmstone** [comment]
Closing old issues
