### ISSUE TITLE
NTFS md raid array under ubuntu not showing up in windows

### ISSUE THREAD

**Issue by wtfiwinomgs** [maharmstone/btrfs#457]
using winbtrfs and WinMD but the ntfs raid md array not showing up in windows.

**Comment by ticpu** [comment]
This seems to be a WinMD issue. WinBtrfs handles neither NTFS nor MD arrays.

**Comment by wtfiwinomgs** [comment]
> This seems to be a WinMD issue. WinBtrfs handles neither NTFS nor MD arrays.

is it possible to add support under WinMD/WinBtrfs for NTFS md arrays thats created under ubuntu so that it'll show under windows?

**Comment by ticpu** [comment]
This project is WinBtrfs, to handle Btrfs formatted volumes. Not related to NTFS.

**Comment by maharmstone** [comment]
Closing old issues
