### ISSUE TITLE
Can't go deeper into the btrfs partition under WSL

### ISSUE THREAD

**Issue by vheathen** [maharmstone/btrfs#46]
Hello!

  I'm trying to use WinBtrfs with Windows 10 Home, build 14393.-.170327-1835. While it seems to work perfectly within Explorer, I can't get access to the partition from WSL. Every time I'm trying to cd into /mnt/d/root I get "Permission denied". I've tried to run bash as Administrator, I've tried to sudo -i first: it doesn't help.
  BTRFS partition is a partition on the same drive, the root partition of the installed Fedora Linux.

  Did I miss something, could you please point me to the right direction?

Thanks!

**Comment by maharmstone** [comment]
Thanks - I'll have a look. You're using a more recent version of Windows 10 than I am - it looks like they might have changed something in LXSS in the meantime.

**Comment by maharmstone** [comment]
Yes, they have - stat now opens the file without asking for any permissions whatsoever, which for some reason known only to Microsoft return ACCESS_DENIED rather than SUCCESS. This should be fixed by https://github.com/maharmstone/btrfs/commit/f331964c060fef1d1d5b6802d6d7bd86376a74db.
