### ISSUE TITLE
Improvement: Display Winbtrfs version

### ISSUE THREAD

**Issue by cooper2k4** [maharmstone/btrfs#462]
It would be a nice feature if Winbtrfs could display its version. This would be quite helpfull for bug reports to do a check if the newest version is installed.

It would be possible in the explorer extension:
![grafik](https://user-images.githubusercontent.com/14296001/154341343-67af466f-9702-4b05-b8cb-5f11afa1ea86.png)

And perhaps also via `rundll32`:
```
rundll32.exe shellbtrfs.dll,GetVersion
```

**Comment by maharmstone** [comment]
I can see how that might be useful, but the version number is already exposed in the version info of the sys file. That's the usual way of doing it on Windows.
