### ISSUE TITLE
Cannot save file in Qt creator, throws ERROR_SYMLINK_NOT_SUPPORTED

### ISSUE THREAD

**Issue by maz-1** [maharmstone/btrfs#464]
![src](https://user-images.githubusercontent.com/5277060/155888044-4a96ac8d-9cf8-4d9a-bd2d-c9f7c6dcb71d.PNG)

The error message says "This application does not support the current operation on symbolic links", however the file being saved is not a symbolic link

**Comment by maharmstone** [comment]
What version of Qt Creator is this? I couldn't reproduce on 6.0.2.

Also, where did you get "ERROR_SYMLINK_NOT_SUPPORTED" from?

**Comment by maz-1** [comment]
Qt creator 4.14
From what I searched "This application does not support the current operation on symbolic links" is a win32 error, code 1464 (ERROR_SYMLINK_NOT_SUPPORTED)

**Comment by maz-1** [comment]
I tried to compress the source and extract, the message is gone
So I guess there is some permission problem, but winbtrfs does not report it correctly

**Comment by maz-1** [comment]
Permissions seem to mess up after I copy my project from onedrive to btrfs (Files have permissions inherited from "None")
This does not happen to all files. I still doesn't know the exact way to reproduce

**Comment by Masamune3210** [comment]
I'm not sure if OneDrive perserves Unix permissions on files, considering it expects a Windows permission model

**Comment by maz-1** [comment]
> 

I am copying from onedrive to btrfs not vise versa

**Comment by maz-1** [comment]
> I'm not sure if OneDrive perserves Unix permissions on files, considering it expects a Windows permission model

I am copying from onedrive to btrfs not vise versa

**Comment by maharmstone** [comment]
Closing old issues
