### ISSUE TITLE
[Request] File hashes

### ISSUE THREAD

**Issue by m1karii** [maharmstone/btrfs#465]
Could you please release file hashes (ideally SHA256 or SHA512) with official file releases?

**Comment by maharmstone** [comment]
Why? The files are all signed, so you can already tell if they've been corrupted.

**Comment by m1karii** [comment]
i might have misunderstood but what exactly is ...
> For the very latest versions of Windows 10, Microsoft introduced more onerous requirements for signing, which seemingly aren't available for open-source drivers.
> 
> To work around this, go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy` in Regedit, create a new DWORD value called `UpgradedSystem` and set to 1, and reboot.

... then about ?

**Comment by m1karii** [comment]
@maharmstone

**Comment by maharmstone** [comment]
These are unrelated things. Windows 10 changed which certificates it automatically trusts; it'll still verify the file hash against the certificate.
