### ISSUE TITLE
MSI/EXE installer

### ISSUE THREAD

**Issue by rollingmoai** [maharmstone/btrfs#466]
Can you create an installer for this? I would like to install this via winget but it doesn't [support installing drivers](https://github.com/microsoft/winget-cli/issues/684) from zip files yet.

**Comment by itsmeboy0** [comment]
> It won't matter what format the archive is in, since driver install isn't supported either as it usually isn't silent

Hopefully that isn't the case for this one, I have just installed [`ViGEmBus`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/ViGEm/ViGEmBus) from Winget and it was completely silent.

**Comment by rokejulianlockhart** [comment]
Would you add /MSIX to the title? That's the ideal format to use.

**Comment by Masamune3210** [comment]
There is nothing wrong with using a MSI with winget, as long as the information to be put into the registry is correct. Furthermore, MSIX has a whole host of issues that it brings to the table. They both have their pros and cons

**Comment by rollingmoai** [comment]
I do not think MSIX supports packaging for drivers.

**Comment by maharmstone** [comment]
Closing old issues

**Comment by RokeJulianLockhart** [comment]
> https://github.com/maharmstone/btrfs/issues/466#issuecomment-1832983152

Then close it as unplanned, not completed. But why close it merely because it is old, @maharmstone? I don't understand why that would factor into consideration.
