### ISSUE TITLE
[Bug?] Btrfs partition goes read-only

### ISSUE THREAD

**Issue by vukitoso** [maharmstone/btrfs#468]
Hello.
OS: Windows 7 (Russian language)
WinBtrfs: btrfs-1.8

1)
Today I decided to try the btrfs file system on linux and windows.
On the HDD, I freed 4GB from the end of the disk and created an additional partition, formatted it in btrfs.
I installed the driver from "btrfs-1.8.zip", rebooted the computer, then the driver was installed and required another reboot.
Immediately after installing the driver (before 1 reboot), I started testing the write speed to a partition with btrfs.
So many times I copied different files, of different sizes, from 30mb to 3gb.
After 1 reboot, I again continued to copy and monitor the speed of copying.
At some point, either after the first or after the second reboot, I noticed that the partition went into read-only mode.
Windows Explorer gave error 65535 when trying to create a directory.
Photo - https://disk.yandex.ru/d/OHqBh5LKvoHPag/Windows7_Error_65535.jpg
Video - https://disk.yandex.ru/d/OHqBh5LKvoHPag/Windows7_Error_65535-Video.mp4
Disk property - devices tab - https://disk.yandex.ru/d/OHqBh5LKvoHPag/Windows7_BTRFS_tab_devices.jpg
Disk property - volume Usage tab - https://disk.yandex.ru/d/OHqBh5LKvoHPag/Windows7_BTRFS_tab_volumeUsage.jpg

In the video, you can see that at the root of the partition is the file "ru_windows_7_home_premium_with_sp1_x64_dvd_u_676728.iso", which weighs 3.0 GB.
Only 2.7GB is available on an empty partition. Screenshot of the output of the "df -hT" command in linux - https://disk.yandex.ru/d/OHqBh5LKvoHPag/btrfs-4gb-df.png
It is logical to assume that it is impossible to write a 3GB file to a partition where only 2.7GB is free.
I make an assumption that this is some kind of error, as a result of which the file system switched to read-only mode.

2)
Also after that I found another problem.
After the first problem, I started writing a lot of files larger than the size of the btrfs disk partition.
Surprisingly, the files continued to be written, as if the place had not run out. I do not understand what it is and how it can be at all?
Video - https://disk.yandex.ru/d/OHqBh5LKvoHPag/The_files_are_larger_than_the_disk.mp4

**Comment by maharmstone** [comment]
Thanks - so there's no corruption on the disk. What's `/dev/xvdj`, though? I don't think I've ever seen a device name like that.

**Comment by vebmaster** [comment]
> What's `/dev/xvdj`

This is the name of the hard disk, analogous to /dev/sda
OS: Qubes Linux

**Comment by lesderid** [comment]
> What's `/dev/xvdj`, though? I don't think I've ever seen a device name like that.

`/dev/xvdX` are virtualised Xen block devices.

**Comment by maharmstone** [comment]
Not that I can remember - I'll have to do some testing. It might be that Total Commander is doing something I've not accounted for.

**Comment by Schroedingers-Cat** [comment]
I downgraded the WinBTRFS driver to v1.7.2 today to avoid the BSODs from another issue (#87).  

After roughly 30GB of downloaded data from Steam, the drive went into read-only mode. After restarting the OS, it's writeable again (I can create text files) until I start Steam again, which causes the drive to go into read-only mode, again.  
![grafik](https://user-images.githubusercontent.com/6382400/173616295-baeacf1d-d32d-4530-9b7a-e5aa624b2ef1.png)  

I didn't find anything of interest in the Windows event view.

**Comment by maharmstone** [comment]
@Schroedingers-Cat - there's not much point in logging bugs encountered in an old version.

**Comment by Schroedingers-Cat** [comment]
@maharmstone anything else you might need? It could be that this issue has existed since v1.7.2, that's why I posted some details about it.

**Comment by DarkStarZN** [comment]
I'm having the same issue with the latest version. The drive keeps going into read-only mode shortly after boot in Windows.

**Comment by jz579** [comment]
I encountered this issue too. While trying to CrystalDiskMark a btrfs volume with ~3GiB free space, some write benches cannot perform correctly (SEQ1M Q1T1). If the remaining space is less than 2GiB, no write benches can be performed successfully.

CrystalDiskMark: 8.0.4 x64 [Admin], 2 iterations, 1GiB file size, other settings are default.
Winbtrfs: v1.8 on a factory new Windows 11 (only installed winbtrfs and VeraCrypt)
Note: Volume is encrypted by VeraCrypt. The fs is created manually by mkfs.btrfs. The write protect is off after I remount the volume through VeraCrypt.

**Comment by maharmstone** [comment]
Closing old issues
