### ISSUE TITLE
Install error - Certificate

### ISSUE THREAD

**Issue by adolfotregosa** [maharmstone/btrfs#470]
Cannot install. Windows 11 build 22579.ni_release.220315-1501

![image](https://user-images.githubusercontent.com/7437931/159277257-4bfd4a3c-c0a9-4cb2-a1f9-aba6dde21ddc.png)

Suggestions ?

**Comment by maharmstone** [comment]
Have you tried the Secure Boot thing mentioned in the README?

**Comment by adolfotregosa** [comment]
My secure boot is off but I did not try the registry thing yet because secure boot is off. 
I'll post results.

**Comment by maharmstone** [comment]
Hang on, is this a preview build of Windows? Because if it is, you might want to go back to normal Windows 11 - I've had a lot of trouble getting drivers to work on preview builds.

**Comment by adolfotregosa** [comment]
Yes, I even gave you the exact build number. It has been working beautifully, until today. I would very much not prefer reinstalling windows, that's why I asked for help. I'll try the registry and post results

**Comment by maharmstone** [comment]
Sorry, I'm going to have to close this then - I don't support preview builds, as they vary too much in quality. If this is still a problem whenever the next substantial build of Windows 11 comes out, please reopen this.
