### ISSUE TITLE
Using nodejs in a btrfs environment occurs `kernel_security_check_failure`.

### ISSUE THREAD

**Issue by sousuke0422** [maharmstone/btrfs#475]
OS is windows11 (10.0.22593.1).

This error appeared when you executed the yarn command after running git clone.

----
I am using a translation because I am not good at English.

**Comment by maharmstone** [comment]
Does this happen every time you do this? If so, a minidump would greatly help.

**Comment by sousuke0422** [comment]
Yes.  Occurs almost every time.

**Comment by maharmstone** [comment]
Just noticed this is a preview build of Windows, which I don't support. Please reopen this if you can reproduce it on a normal build.
