### ISSUE TITLE
Only read home folder and root folder

### ISSUE THREAD

**Issue by larsmartin4** [maharmstone/btrfs#478]
tryed to read fedora 35 HDD but only home folder and root folder is showed.
![fedora hdd](https://user-images.githubusercontent.com/50201527/164235230-ee8a770b-3651-4437-9d8e-13e908f16829.png)

But this software help me some to get files.
DiskInternals Linux Reader pro cost more than 50$ so its high cost.

But is did not show all partions.

**Comment by larsmartin4** [comment]
How to add list to diskpart (list disk) or list volume?

How to add code for ReactOS or windows XP?

**Comment by maharmstone** [comment]
Is there a hidden directory called $Root?

**Comment by larsmartin4** [comment]
i only compared with linux:

NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda     8:0    0 931,5G  0 disk 
├─sda1
│       8:1    0   529M  0 part 
├─sda2
│       8:2    0    99M  0 part 
├─sda3
│       8:3    0    16M  0 part 
├─sda4
│       8:4    0 867,9G  0 part /run/media/larsmartinhambro/5A16BCED16BCCAF1
├─sda5
│       8:5    0   632M  0 part 
├─sda6
│       8:6    0     1G  0 part /boot/efi
└─sda7
        8:7    0  61,4G  0 part /
sr0    11:0    1   1,9G  0 rom  /run/media/larsmartinhambro/Fedora-WS-Live-35-1-2
zram0 252:0    0     8G  0 disk [SWAP]
![Screenshot from 2022-04-20 20-10-11](https://user-images.githubusercontent.com/50201527/164296427-b6d08411-74c4-4c39-acc7-1f4ae2a059eb.png)

**Comment by crzsotona** [comment]
@larsmartin4 what you're expecting to see?
What is in root folder?

**Comment by maharmstone** [comment]
Closing old issues
