### ISSUE TITLE
Suggestion: Add mount and umount executables

### ISSUE THREAD

**Issue by AEAEAEAE4343** [maharmstone/btrfs#483]
Currently the only way to mount/remount/umount a volume is by changing values in registry and restarting the computer. This is less than ideal and costs a lot of time. I suggest adding a mount command, similar to the Linux mount command. Examples on how you would mount:

Since windows doesn't have a mount command, syntax can be simplified to this for btrfs only:
`mountbtrfs <device> <letter:> [options...]`
`umountbtrfs <letter> [force]`

Mount the volume on disk 0 partition 3 normally to letter G:
`mountbtrfs \\?\Device\Harddisk0\Partition3 G:`

Mount subvolume home on disk 2 partition 4 to letter Z readonly:
`mountbtrfs \\?\Device\Harddisk2\Partition4 G: readonly subvol=home`

Force unmount the volume on D:
`umountbtrfs D: force`

**Comment by maharmstone** [comment]
@AEAEAEAE4343, this can't be done unfortunately, it's not how Windows works. `mountmgr.sys` will attempt to mount any unmounted volumes that it finds.

@SEVENID, you can do this already with `mklink`.
