### ISSUE TITLE
cannot open disk: The process cannot access the file because it is using by another process

### ISSUE THREAD

**Issue by ghost** [maharmstone/btrfs#485]
![image](https://user-images.githubusercontent.com/35184399/170172388-cbe6725e-d188-4ac5-9740-d2efc3188d76.png)
I came across this problem a lot, the root path of D: can't be visited, but I can go to subpath like D:\Downloads via simbol links. 
btw I format this disk on linux via btrfs command, if that's helpful.

OS: Win10 pro 21H2
btrfs driver version: 1.8

**Comment by blinky39** [comment]
btw I'm not copying anything to that disk and I have a WSL setup in my windows

**Comment by jarrard** [comment]
I might have come across this when running gShade on KCD game, the game folder popped up with this and I thought it was odd. Not sure why it lock up, but gshade does do some symlinking of DLL's to that folder (gshade is basically a rebased reshade with better compatibility).

**Comment by jarrard** [comment]
I'm able to reproduce this by opening a text file within the folder here such as user.cfg and then try to open the folder with another process... The result! 

Definitely a winbtrfs bug going on!

<img width="1053" alt="Untitled" src="https://user-images.githubusercontent.com/17428910/172035248-7e25630f-8086-422d-a398-e94d92741116.png">

**Comment by maharmstone** [comment]
Closing old issues

**Comment by aarmn** [comment]
I have this issue.
I also have WSL2, is there a correlation or causation, I'm not sure of yet! where probably the problem originates, and is there a fix yet?
thank you.

**Comment by aarmn** [comment]
killing the explorer.exe fixed the issue, explorer.exe seems suspicious generally.
