### ISSUE TITLE
Can't build due to missing file src/tests/test.rc.in

### ISSUE THREAD

**Issue by andrewc12** [maharmstone/btrfs#486]
I was trying to build the fs test program but wasn't able to straight from source.
Removing these lines helped for me but I don't think it's an actual solution.
https://github.com/maharmstone/btrfs/blob/master/CMakeLists.txt#L331
https://github.com/maharmstone/btrfs/blob/master/CMakeLists.txt#L334

**Comment by maharmstone** [comment]
Sorry, looks like I missed that file out. Fixed now.
