### ISSUE TITLE
Is there any sha-256 hardware acceleration support?

### ISSUE THREAD

**Issue by megapro17** [maharmstone/btrfs#487]
Skimmed though the source code, and didn't found any mentions of sha-ni or something similar. It is not supported?

**Comment by maharmstone** [comment]
No, not yet. It's something I'm planning to get around to.

**Comment by megapro17** [comment]
Even for crc32?

**Comment by maharmstone** [comment]
https://github.com/maharmstone/btrfs/blob/master/src/crc32c-masm.asm

**Comment by megapro17** [comment]
Okay, thanks
