### ISSUE TITLE
BSOD when updating Visual Studio to 17.2.3

### ISSUE THREAD

**Issue by benpaulsen-qut** [maharmstone/btrfs#488]
Ok so VS 17.2.3 must be a major update of some kind because it requires a full windows restart. In saying that, if you try to install the update with the btrfs driver running, you will get a PAGE_FAULT_IN_NONPAGED_AREA blue screen citing btrfs.sys as the cause. I thought this was strange since I don't even have visual studio installed on one of my btrfs drives, but it was a consistent error. I ended up uninstalling the driver to update VS and reinstalling it after, but thought I'd report it here anyway since the driver was directly cited as the cause of the crash. 

I can upload dumps if need, just lmk! 😄

(FYI I was running the latest version of the btrfs driver)

**Comment by maharmstone** [comment]
If you could upload the dumps, it'd be appreciated. Thanks

**Comment by benpaulsen-qut** [comment]
As you wish!
[Here is the Google Drive link](https://drive.google.com/file/d/1vngc4N4RvbMpexkbm9l9_65dPXD6yDY-/view?usp=sharing)

It appears that windows was overwriting the dump each time so this is the most recent crash that happened before I decided to try the update again with the update uninstalled, but I tried about 4 times beforehand. 

Hope this helps, keep up the good work 😄

**Comment by maharmstone** [comment]
Thanks for this - I think this should be fixed by https://github.com/maharmstone/btrfs/commit/76b13080cecf8dad4ba23ca4b6e4b85e2c242dbc.
