### ISSUE TITLE
How can I delete the "System Volume Information" directory?

### ISSUE THREAD

**Issue by pragmaticmero** [maharmstone/btrfs#489]
As I understand, the "System Volume Information" folder is created for the NTFS filesystem.... I suppose that its not needed for BTRFS, I might be wrong mmmm.... Can I delete that folder without Windows creating it again?

**Comment by maharmstone** [comment]
This isn't an issue with the driver, it's doing what the OS is telling it to. If there's a way to disable it, it'll be hidden in the Registry somewhere.
