### ISSUE TITLE
Not stable for running some games on.

### ISSUE THREAD

**Issue by jarrard** [maharmstone/btrfs#490]
I had to stop using winbtrfs because its just not stable read/write for executing some programs on that have a high read/write access.

It also seems that things like symlinking and such to the volumes can cause access denial issues as I found when messing with KCD (kingdomcome deliverance) and a gshade tool which does such a thing for dxgi.dll symlinks etc..

KCD had a issue where it would often micro-freeze in-game on the winbtrfs partition; this is likely due to the nature of texture streaming this game does (ALLOT).

There is also people reporting corruption issues which is concerning. 

I really think these issues need to be tested/reviewed closely; merely testing synthetic read/write performance is NOT enough to check for stability issues.

Additionally it should be mention my btrfs partitions (nvme) are using zstd:normal (3) which is likely also a contributing factor.

If anyone else has had similar odd experiences like this please post them here. _(relating to running applications off winbtrfs drives and stability of said apps/games)_

**Comment by maharmstone** [comment]
You've already logged the access denial issue for KCD (https://github.com/maharmstone/btrfs/issues/485).

Funnily enough, I did play Kingdom Come Deliverance from a btrfs partition just a few weeks ago, and didn't have any problems. Though this was without compression turned on - I wouldn't recommend compression for any games as it increases CPU load, which the game will be expecting it can use for other things.

I don't think it's very useful to have an umbrella issue; I'd prefer people log individual issues as and when they find them.

**Comment by jarrard** [comment]
Compression only consumes 3-5% CPU usage; so it should be fine on 6 or 8 core CPU's especially newer ones. 
People have actually tested the effect of compression on games but I can't remember the article URL sorry. 

Playing KCD under Linux now off same drive and setup, not a problem.
