### ISSUE TITLE
How to change mounting option?

### ISSUE THREAD

**Issue by tribbloid** [maharmstone/btrfs#492]
When the btrfs option is mounted under linux. It has the following option:

```
default,SSD,nodatacow,nodatasum
```

I need to replicate this setting in Windows, how can I do this?

**Comment by ticpu** [comment]
From the readme there is a section for the Mount options
https://github.com/maharmstone/btrfs#mount-options

**Comment by maharmstone** [comment]
Yep, as @ticpu says.
