### ISSUE TITLE
How to submit an error report after a GREEN SCREEN OF DEATH?

### ISSUE THREAD

**Issue by tribbloid** [maharmstone/btrfs#493]
winbtrfs frequently causes Windows 11 to crash with the following information:

```
Stop code: PAGE_FAULT_IN_NONPAGED_AREA

What failed: btrfs.sys
```

But then the error report appears to be sent to no where.

I need to collect the report to identify the actual reason of this crash. How to do it?

**Comment by maharmstone** [comment]
As I understand it, the funny-coloured screens of death only happen on non-release versions of Windows, which I don't support. Please open another issue if you can reproduce this on a normal version of Windows.

**Comment by Masamune3210** [comment]
Indeed, GSOD is non-retail, usually Insider build
