### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [maharmstone/btrfs#5]
Would you like to [add more error handling](https://github.com/maharmstone/btrfs/blob/839ca8c6b889f33c372772d13f700de9c0d4babe/src/btrfs.c#L858 "Update candidate: read_data()") for return values from calls of [a function like "ExAllocatePoolWithTag"](https://msdn.microsoft.com/en-us/library/windows/hardware/ff544520%28v=vs.85%29.aspx "Allocation of pool memory")?

**Comment by maharmstone** [comment]
Good point - I'll have a look at it. Thanks.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by maharmstone** [comment]
Thank you for the suggestion, but this does not strike me as something suitable for a filesystem driver.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for this software?

**Comment by maharmstone** [comment]
Elfring, look at the issue Jarrard logged - paraphrasing, "WinBtrfs worked for a while, then hosed my entired Windows system". The driver is in alpha, and there's currently much larger problems to deal with. I'm closing this thread.

**Comment by elfring** [comment]
Would it be better to keep this issue open until the remaining open issues will also be fixed for proper exception handling?
