### ISSUE TITLE
How to delete subvolume?

### ISSUE THREAD

**Issue by hex11** [maharmstone/btrfs#50]

**Comment by maharmstone** [comment]
If you're not even going to leave a message, why should I waste my time on this?

**Comment by hex11** [comment]
: )

**Comment by hex11** [comment]
Sorry for my poor English. And I am asking again...
How can I have WinBtrfs do `btrfs subvolume delete path_to_a_btrfs_subvolume` ?
Thanks for this amazing project, by the way.

**Comment by maharmstone** [comment]
Unlike on Linux, you can delete subvolumes on Windows as if they were any other directory.

**Comment by hex11** [comment]
I created a snapshot 'bak' of a subvolume. There were tons of files in the snapshot.
And I found doing `btrfs subvolume delete -c bak` on Linux is much faster than deleting 'bak' with shift-delete shortcut.
I think this is because they're not doing the same thing. The latter deletes files in the directory one by one before it deletes the directory (or subvolume/snapshot). And the former should just delete the subvolume... Hmm, I don't know. :joy:
So I want to know can I delete subvolumes like on Linux, but with WinBtrfs?

**Comment by michal-ruzicka** [comment]
Dear @maharmstone, I think this question is very relevant. I am going to use WinBtrfs to effectively and efficiently keep history of my backups from Windows as I am used to from Linux. From time to time, with storage getting full, I expect need for deleting old snapshots. The great thing on Btrfs snapshots is, among others, the ease of their creation, copy (cloning) and deletion as, as noted by @hex11, it is **_huge_** difference in speed between `btrfs subvolume delete`, that is almost instantaneous on Linux regardless of the number and size of files on the subvolume, and deleting the subvolume as directory where recursive deletion of the full content of the subvolume is necessary, that is _very_ slow operation on directories with hundreds of thousands or more files inside.

Is there any design issue on Windows preventing `subvolume delete` implementation?

**Comment by maharmstone** [comment]
Yes, I know. It's something I want to look at, it's just never been a priority.

**Comment by michal-ruzicka** [comment]
Ok, thanks for a quick response, @maharmstone. So, if there is something I can do for increasing priority of this... At least have my +1 for this issue. :-)

**Comment by shaokn** [comment]
![Image](https://github.com/user-attachments/assets/37a51086-1e15-4032-ae91-b9ad9f137010)

shift+delete showed this message. 
then how to delete this snapshot?

**Comment by maharmstone** [comment]
> ![Image](https://github.com/user-attachments/assets/37a51086-1e15-4032-ae91-b9ad9f137010)
> 
> shift+delete showed this message. then how to delete this snapshot?

Which says what exactly?

**Comment by shaokn** [comment]
> > ![Image](https://github.com/user-attachments/assets/37a51086-1e15-4032-ae91-b9ad9f137010)
> > shift+delete showed this message. then how to delete this snapshot?
> 
> Which says what exactly?

I create a snapshot of the whole partition D: using command line as "dcm_20250205", (rundll32.exe shellbtrfs.dll,ReflinkCopy d: d:\dcm_20250205)
shift+delete this snapshot folder shows " need premission from SYSTEM" (showed in picture). (finally delete it in WSL sudo btrfs delete subvolume dcm_20250205)

Instead first create a subvolume in D:, then use right click blank and 'create subvolume' as 'dcms', and right click this folder and make a snapshot as "Snapshot of dcms (2025-02-07)", and then  shift+delete this snapshot folder works well.
