### ISSUE TITLE
Version 1.8 broken on Windows 2003

### ISSUE THREAD

**Issue by oskar-skog** [maharmstone/btrfs#508]
Disregard this bug report until I've tested in-between versions.

I tested the pre-compiled releases on Windows Server 2003 and found that 1.8 is broken.

- **Files are padded up to 4096 byte multiple**
- "Btrfs" / "Btrfs properties" is missing in Explorer

Version 1.5, 1.6 and 1.7 work fine.

![1.8-pad1.png](https://oskog97.com/.bugs/btrfs-508/1.8-pad1.png)
![1.8-pad2.png](https://oskog97.com/.bugs/btrfs-508/1.8-pad2.png)

**Comment by oskar-skog** [comment]
Oh, I didn't notice there are releases between 1.7 and 1.8.  Github is quite broken on Firefox 52.
I'll retest this later.

**Comment by maharmstone** [comment]
This sounds awfully like https://github.com/maharmstone/btrfs/issues/469, which is fixed in the current master.

**Comment by maharmstone** [comment]
> "Btrfs" / "Btrfs properties" is missing in Explorer

IIRC the latest versions of MSVC produce C++ binaries that aren't compatible with XP and WS03, so you're probably out of luck here. You could try compiling shellbtrfs.dll with MinGW, but you'll have to do this yourself.

**Comment by oskar-skog** [comment]
Release 1.8.1 is working fine (except for shellbtrfs.dll)
