### ISSUE TITLE
RAM overload

### ISSUE THREAD

**Issue by guglovich** [maharmstone/btrfs#509]
At full capacity on a BTRFS partition, the RAM runs out in a few minutes, and sometimes in less than a minute. Sometimes it takes up all of the RAM as a cache, but sometimes free -m shows RAM usage as "usage".

Examples of playback:
1) Torrent at about 100Mbits upload speed.
2) Running defragmentation with compression

![изображение](https://user-images.githubusercontent.com/54148165/185611086-7bc86007-5fa9-43d8-861c-1fbf0176d717.png)

**Comment by maharmstone** [comment]
Why is your screenshot of Linux? I'm confused.

**Comment by guglovich** [comment]
> Why is your screenshot of Linux? I'm confused.

Oh, yeah. I think I stumbled onto the wrong github. I was looking for a generic GIT for BTRFS.
