### ISSUE TITLE
Transparent compression when downloading files

### ISSUE THREAD

**Issue by guglovich** [maharmstone/btrfs#510]
When migrating to BTRFS after copying files from another partition they were all successfully compressed. However, the files I download via torrent do not get compressed and I have to use defragmentation with compression.

**Comment by maharmstone** [comment]
What sort of files? It won't try to compress anything that's incompressible.

**Comment by guglovich** [comment]
> What sort of files? It won't try to compress anything that's incompressible.

I did not notice that this is a GIT for Windows implementation. Not relevant then.
