### ISSUE TITLE
[Feature Request] Make devices in Devices dialog selectable by row

### ISSUE THREAD

**Issue by 13xforever** [maharmstone/btrfs#513]
Currently it's only possible to select the first column and clicking anywhere on the rest of the line deselects it.
It will be more friendly to have selection work on the full row.

![image](https://user-images.githubusercontent.com/36445/186944778-5b1e07ce-c6ce-49c9-8dd5-a30a4ff81297.png)

**Comment by maharmstone** [comment]
Thanks, I agree. Fixed by https://github.com/maharmstone/btrfs/commit/e1668bc69c41a9556ddc05a9b7180058756057bf.
