### ISSUE TITLE
ReactOS installation fails on 64-bit (32-bit works)

### ISSUE THREAD

**Issue by jobermayr** [maharmstone/btrfs#528]
From: https://jira.reactos.org/browse/CORE-18233 (not sure whether ReactOS or WinBtrfs issue ...)
> Btrfs ERR : add_checksum_entry : out of memory
(ntoskrnl\mm\ARM3\pool.c:497) FAILED to allocate 4096 bytes from paged pool
Btrfs ERR : add_checksum_entry : out of memory
(ntoskrnl\mm\ARM3\pool.c:497) FAILED to allocate 4096 bytes from paged pool
Btrfs ERR : add_checksum_entry : out of memory
(ntoskrnl\mm\ARM3\pool.c:497) FAILED to allocate 4096 bytes from paged pool
Btrfs ERR : rationalize_extents : out of memory
(ntoskrnl\mm\ARM3\pool.c:497) FAILED to allocate 4096 bytes from paged pool
Btrfs ERR : insert_tree_item_batch : out of memory
Btrfs ERR : flush_fcb : insert_tree_item_batch returned c000009a
Btrfs ERR : do_write2 : flush_fcb returned c000009a
Btrfs ERR : do_write : do_write2 returned c000009a, dropping into readonly mode
Btrfs ERR : do_flush : do_write returned c000009a
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\localui.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\localui.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\localmon.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\localmon.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\spool\prtprocs\x64\winprint.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\spool\prtprocs\x64\winprint.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\localspl.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\localspl.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxapi.sys) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxapi.sys' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxg.sys) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxg.sys' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxgthk.sys) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\drivers\dxgthk.sys' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\user32.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\user32.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\winsrv.dll) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\winsrv.dll' (error 0xc0000001), skipping it...
(base\setup\usetup\spapisup\cabinet.c:1090) NtCreateFile() failed (\Device\Harddisk0\Partition1\ReactOS\system32\win32k.sys) (c00000a2)
(base\setup\usetup\usetup.c:3671) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\win32k.sys' (error 0xc0000001), skipping it...
(base\setup\lib\setuplib.c:333) Cannot load \Device\Harddisk0\Partition1\ReactOS\System32\$winnt$.inf as an INI file!
WARNING:  HvHiveWillShrink at sdk\lib\cmlib\hivewrt.c:280 is UNIMPLEMENTED!
Btrfs ERR : open_fileref_child : open_fcb returned c000000d
Btrfs ERR : open_fileref : open_fileref_child returned c000000d
Btrfs ERR : open_file : open_fileref returned c000000d
Btrfs ERR : open_fileref_child : open_fcb returned c000000d
Btrfs ERR : open_fileref : open_fileref_child returned c000000d
Btrfs ERR : open_file : open_fileref returned c000000d
(base\setup\lib\utils\regutil.c:236) NtCreateFile(\Device\Harddisk0\Partition1\ReactOS\System32\config\SYSTEM) failed, Status 0xc000000d
(base\setup\lib\registry.c:749) CreateRegistryFile(SYSTEM) failed, Status 0xc000000d
(base\setup\lib\setuplib.c:961) RegInitializeRegistry() failed

**Comment by maharmstone** [comment]
ReactOS isn't a supported OS.

**Comment by jobermayr** [comment]
> ReactOS isn't a supported OS.

That means it isn't definetly possible to be a issue in WinBtrfs code which could also lead to issues with 64-bit Microsoft software?

**Comment by maharmstone** [comment]
No idea - maybe. If you can reproduce this on Windows, please re-open.
