### ISSUE TITLE
Include zstd compression format

### ISSUE THREAD

**Issue by dxzdxz1** [maharmstone/btrfs#53]
There is a patch made for linux that adds support for zstd, it improves compression without compromise performance. Is much better than zlib but faster as lzo.

[Here](
https://github.com/facebook/zstd/tree/dev/contrib/linux-kernel#btrfs
) is the patch

I know that your driver has nothing to do with the linux code, so I don't know if it's possible to port support for zstd, but since it's a great alternative for transparent compression I believe it's worth to try it out.

**Comment by maharmstone** [comment]
I'm not going to start including features until they've been accepted in Linux, sorry - that'd be impossible to maintain. I'll have a look once it reaches the mainline kernel.
