### ISSUE TITLE
License compatible with FreeBSD?

### ISSUE THREAD

**Issue by TurkeyMan** [maharmstone/btrfs#531]
Not an issue, just a question...
It's usually said by the bsd crowd that btrfs is not available on bsd because of the original code's gpl license, and nobody could be bothered re-implementing from scratch.
Is your license compatible with bsd, and is there any amount of your code here that's not windows specific such that the btrfs code could be adapted to bsd instead of windows?
This might be a leg-up needed to stop people complaining about the incompatible license if it's not intensely windows-specific.

**Comment by maharmstone** [comment]
IANAL, so I don't know. If any of the BSD people think that my code would be useful to them, I'm happy to relicense it as whatever.

**Comment by TurkeyMan** [comment]
A brief browse; looks kinda windows-ey... I see lots of direct calls to WINAPI without abstraction.
