### ISSUE TITLE
Confusing 1 line dropdown combox for "Change Letter"

### ISSUE THREAD

**Issue by KRosUser2** [maharmstone/btrfs#533]
Confusing 1 line dropdown combox for "Change Letter"
As seen in ReactOS : https://jira.reactos.org/browse/CORE-16371

![image](https://user-images.githubusercontent.com/114949464/201465462-cf13f58d-b96d-4a07-8048-7d5b1d92a7da.png)

The design of the ComboBox should have a larger dropdown zone in the ressource definition file

**Comment by JoachimHenze** [comment]
Please double-check the outcome on Windows @KRosUser2 . It makes sense for Mr. Harmstone only to change his code if the outcome would also render like that on real Windows. And as far as I see, that test has not been performed yet! In the future please wait with filing tickets in any 3rd party trackers until you have performed such a test!

**Comment by KRosUser2** [comment]
> Please double-check the outcome on Windows @KRosUser2 . It makes sense for Mr. Harmstone only to change his code if the outcome would also render like that on real Windows. And as far as I see, that test has not been performed yet! In the future please wait with filing tickets in any 3rd party trackers until you have performed such a test!

Unable to get this dialog in WinXP :
![image](https://user-images.githubusercontent.com/114949464/201474743-3740097c-c63e-4edb-9c79-e9ce5a2f5225.png)

**Comment by JoachimHenze** [comment]
Well then test with Win7 or whatever is supported officially by that driver.

**Comment by KRosUser2** [comment]
I don't have such setup, but i'll test WinBTRFS 1.7.7 in WinXP

**Comment by KRosUser2** [comment]
![image](https://user-images.githubusercontent.com/114949464/201475659-d70d0171-907a-48ef-be23-24090b1178fd.png)

Works fine, bug is in ReactOS
![image](https://user-images.githubusercontent.com/114949464/201475674-77c9edae-97c7-499c-a898-277b8bdc84e9.png)

**Comment by KRosUser2** [comment]
https://jira.reactos.org/browse/CORE-18637
