### ISSUE TITLE
Publish WinBtrfs to Windows Update

### ISSUE THREAD

**Issue by wordlesswind** [maharmstone/btrfs#534]
Hello,

I know this is not simple or even possible, but I would still like to ask if there are plans to publish WinBtrfs to Windows Update?

https://learn.microsoft.com/windows-hardware/drivers/dashboard/

**Comment by Masamune3210** [comment]
If I'm not mistaken, that is more for Hardware Vendors to add their drivers to Update so Windows can automatically fetch on initial install and updates afterwards, not for drivers that are voluntary

**Comment by maharmstone** [comment]
Unless things have changed dramatically, Microsoft aren't interested in any driver that doesn't have an EV certificate, which are only granted to corporations, not hobbyists. Plus I think they make you jump through their hardware verification rigmarole, which IIRC explicitly prohibits open-source drivers for some reason.

So no, unfortunately not happening any time soon.
