### ISSUE TITLE
Microsoft's linker crashes on BTRFS

### ISSUE THREAD

**Issue by TurkeyMan** [maharmstone/btrfs#535]
Okay, so this is super weird...
I was compiling my project as a perf test on NTFS and on BTRFS to test build time differences. It is a little slower on BTRFS (around 15% slower in my initial test), but there's a rather larger issue which I have absolutely no idea how to explain when it finished compiling and tries to link:

On NTFS:
```
3>Generating Code...
3>   Creating library ..\..\dist\lib\x64\Fuji_debug.lib and object ..\..\dist\lib\x64\Fuji_debug.exp
3>FujiDLL.vcxproj -> D:\Code\fuji\Fuji\Project\..\..\dist\lib\x64\Fuji_debug.dll
3>Done building project "FujiDLL.vcxproj".
```

On BTRFS:
```
1>Generating Code...
1>   Creating library ..\..\dist\lib\x86\Fuji_debug.lib and object ..\..\dist\lib\x86\Fuji_debug.exp
1>
1>LINK : fatal error LNK1000: Internal error during IMAGE::Pass1
1>
1>  Version 14.24.28316.0
1>
1>  ExceptionCode            = C0000005
1>  ExceptionFlags           = 00000000
1>  ExceptionAddress         = 00FB2012 (00F00000) "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\link.exe"
1>  NumberParameters         = 00000002
1>  ExceptionInformation[ 0] = 00000000
1>  ExceptionInformation[ 1] = 00000008
1>
1>CONTEXT:
1>  Eax    = 00000000  Esp    = 004FD954
1>  Ebx    = 80400000  Ebp    = 004FE6B0
1>  Ecx    = B4AE6B12  Esi    = 00000000
1>  Edx    = 004FD488  Edi    = 01243EEE
1>  Eip    = 00FB2012  EFlags = 00010246
1>  SegCs  = 00000023  SegDs  = 0000002B
1>  SegSs  = 0000002B  SegEs  = 0000002B
1>  SegFs  = 00000053  SegGs  = 0000002B
1>  Dr0    = 00000000  Dr3    = 00000000
1>  Dr1    = 00000000  Dr6    = 00000000
1>  Dr2    = 00000000  Dr7    = 00000000
1>Done building project "FujiDLL.vcxproj" -- FAILED.
```

For whatever reason, Microsoft's linker crashes internally when trying to link on the BTRFS volume.
I never would have expected this, but it's 100% repeatable.

**Comment by maharmstone** [comment]
That's interesting. FujiDLL is in https://github.com/TurkeyMan/fuji, presumably?

Also, does this happen for everything or just this particular project?

**Comment by TurkeyMan** [comment]
That's the one. It's the only one I tried.
Building with VS2019.

**Comment by sakhnik** [comment]
Hi all. I also experience these crashes on a couple of projects like GLFW and DevIL in Debug configuration. If necessary, I could perform tests and provide diagnostics.

**Comment by maharmstone** [comment]
If you could provide a way of reproducing this it'd be appreciated, because I haven't had any luck so far.

**Comment by sakhnik** [comment]
Would the following sequence fail for you?
```
git clone https://github.com/glfw/glfw
cd glfw
mkdir B
cd B
cmake -G "Visual Studio 16 2019" -A x64 .. -Wno-dev -DGLFW_BUILD_EXAMPLES=False -DGLFW_BUILD_TESTS
=False -DGLFW_BUILD_DOCS=False -DBUILD_SHARED_LIBS=On
cmake --build . --config Debug -j3
<...>
LINK : fatal error LNK1000: Internal error during IMAGE::Pass1 [E:\glfw\B\src\glfw.vcxproj]
```

**Comment by maharmstone** [comment]
Thank you - yes, that works.

The command in question:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"M:\glfw\B\src\Debug\glfw3.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"M:/glfw/B/src/Debug/glfw3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"M:/glfw/B/src/Debug/glfw3dll.lib" /MACHINE:X64  /machine:x64 /DLL glfw.dir\Debug\glfw.res`

I can use the linker through Wine on Linux successfully, so it's not the case that it's actually `cl` producing invalid files (which was another possibility). I'll investigate.

**Comment by maharmstone** [comment]
So the reason link.exe crashes rather than reporting an error is that link!LIB::PmodFind can return NULL but link!FPass1DefFile doesn't check for it. I could report it as a bug, but I doubt Microsoft would care.

I think the problem btrfs-wise is that dwVolumeSerialNumber isn't getting filled in for GetFileInformationByHandle calls.

**Comment by maharmstone** [comment]
Yes, that's it. @sakhnik, if you want a workaround before the next version's out, try changing your drive label to be a single character.
