### ISSUE TITLE
mkbtrfs: support specifying `single` metadata profile?

### ISSUE THREAD

**Issue by cooltech-bs** [maharmstone/btrfs#537]
On the Linux `mkfs.btrfs` you can use `-m single` to disable duplication of metadata and system blocks. That is useful on external flash storage devices which cannot be automatically detected as SSD and you don't want duplicated metadata on.

`mkbtrfs` does not seem to support that yet. Is there a plan of adding the feature? Or better - adding support for all data and metadata profiles (`raid0, raid1, raid1c3, raid1c4, raid5, raid6, raid10, single, dup`)?

**Comment by maharmstone** [comment]
This is semi-deliberate: I wanted to make `mkbtrfs` as simple as possible, and didn't see the point in replicating something which can be trivially done through the driver. I'm not certain that Linux is doing the right thing here.
