### ISSUE TITLE
Please don't track builds in source control

### ISSUE THREAD

**Issue by ur0** [maharmstone/btrfs#54]
Hi!

First up, thanks for all the work you've done on this driver - it makes using BTRFS partitions on Windows a real breeze.

I've noticed that you track [built versions of the driver](https://github.com/maharmstone/btrfs/blob/master/x64/btrfs.sys) in this repository - it is highly unrecommended to check in binary files into git.

I suggest that you use GitHub's [releases feature](https://github.com/maharmstone/btrfs/releases) to upload the prebuilt binaries - it will help keep the repository cleaner.

**Comment by maharmstone** [comment]
Thanks. Yes, you're right - I've removed the binaries. There were release packages already, but removing them from the tree entirely does make things more straightforward.
