### ISSUE TITLE
Corrupted an archive tar.Gz while transferring to Windows

### ISSUE THREAD

**Issue by linux-printer-troubleshooter** [maharmstone/btrfs#541]
I lost around 14.3 gigs of data
Data was on pen drive
Transferred this big archive and it got corrupted
Not all files are retrievable
Archive can not be repaired
Moreover the pendrive itself got corrupted/wiped
I keep getting bsods (BLUE SCREENs) / crashes on WINDOWS immediately after plugging in the pen drive with the brtfs system. Also got nightmares uninstalling it brtfs.sys does not exist in the location and yet the brtfs driver would not uninstall tried many ways finally had to DISABLE it in device manager.
Developer should make the disclaimer more loud on its page This is not a stable product and no one should use it let alone make the mistake of installing it unless you like to play stupid games and win stupid prizes

**Comment by maharmstone** [comment]
That sounds awfully like a hardware issue to me. There's no way the driver could corrupt your volume if all you were doing was copying from it to NTFS.

If you can send me a minidump for these BSODs, I'll have a look at them.

**Comment by maharmstone** [comment]
Closing as no response.
