### ISSUE TITLE
Mount multiple subvolumes

### ISSUE THREAD

**Issue by monroth** [maharmstone/btrfs#543]
Current design of mounting subvolumes from registry qwords does not tell how to mount multiple subvolumes from one UUID
Is there a way to do so?

**Comment by maharmstone** [comment]
The design of Windows means you can't do that directly. But have a look into `mklink` and `subst`, you can emulate it fairly easily.

**Comment by BEvgeniyS** [comment]
Sorry for the necrobump, but.

I'm using this awesome thing to have a dual boot windows 10 with steamos on steam deck

Having converted the steam os home partition to the btrfs, and created working windows btrfs installation, I am booting windows as a subvolume in steamos' home folder (/home/@windows)

I am trying to access the parent subvolume (/home) from windows. Is this possible?
