### ISSUE TITLE
Run .exe as admin gives error

### ISSUE THREAD

**Issue by yaroslav-minieiev** [maharmstone/btrfs#545]
Hey, @maharmstone !
Great work!

I have a btrfs partition  with windows binaries that can be run only as administrator.
Windows User `S-*-*-**-**********-********-**********-1001` maped in register as linux user `1000`
Default subvol is `data/@`. Root of FS is hiden.
Non-binary files have permissions `0666`.
All irectories have permissions `0777`.
Binary files have permissions `0777`.

All binaries, that not require to run as admin, can be launched 2from any user, except the Administrator.
Some binaries require to be run only from admin.

When I try to launch `$anybinary.exe` as admin I get an error. Error code is `0x800704b3`.
Error message is:
`The network path was either typed incorrectly, does not exist, or the network provider is not currently available. Please try retyping the path or contact your network administrator.`

Path to binarries consist of english letters, `-` and spaces only.

There is a way to launch it from admin via `cmd.exe`:
1. Launch `cmd.exe` as amin.
2. Run binary.

But, I'd like to do it using GUI.

OFFTOPIC:
What about LUKS driver? It would be great to have it.

Thank you in advance.

**Comment by maharmstone** [comment]
Thanks @yaroslav-minieiev. This is issue https://github.com/maharmstone/btrfs/issues/519, which is fixed in the next version.

**Comment by yaroslav-minieiev** [comment]
Oh, I see now.
Thank you, @maharmstone .
Sorry for taking your time, I should be more attentive.)))

**Comment by maharmstone** [comment]
No worries!
