### ISSUE TITLE
Installed 1.0 on top of old install, nothing works.

### ISSUE THREAD

**Issue by lynxcs** [maharmstone/btrfs#55]
After running the v1.0 install inf file (While still having the old one installed) I tried to open my btrfs volume,  but I was met with a bluescreen. After trying to uninstall the old one and also trying to install the new one again, I think I just broke everything. I disabled and removed the btrfs key in regedit, deleted the btrfs file in C:/Windows. Now when I try to install the 1.0 inf file I get an error saying installation failed and then a pop-up saying operation completed successfully but even then my btrfs partition doesn't open. Any advice on how I fucked up would be appreciated.

**Comment by lynxcs** [comment]
Restarting a few times and reinstalling fixed this! 😄

**Comment by maharmstone** [comment]
Oh, great! I'm guessing it was something to do with Plug and Play - the dummy devices created by the old driver might have been confusing the new one. It shouldn't be a problem with future versions.
