### ISSUE TITLE
Xbox Game Pass Workaround

### ISSUE THREAD

**Issue by gcars06** [maharmstone/btrfs#550]
Is there any workaround for Xbox Game Pass's requirement for a ntfs drive. I don't have enough space on my other drives for games and my 2tb drive is formatted as btrfs. 

WinBTRFS 1.8.2
Windows 11 Version 22h2 (OS Build 22623.1105)

This is what pops up in Xbox app
![image](https://user-images.githubusercontent.com/82978385/212779934-2f8a409d-71aa-4ee3-8692-140bfe059c1b.png)

**Comment by Masamune3210** [comment]
No, they use features specific to NTFS like junctions and SID assigning. People have tried before, even if you get the app to install the game, Windows itself will refuse to launch the game off of anything that isn't NTFS

**Comment by gcars06** [comment]
> No, they use features specific to NTFS like junctions and SID assigning. People have tried before, even if you get the app to install the game, Windows itself will refuse to launch the game off of anything that isn't NTFS

So, the only way to run Xbox game pass games to run would be to reformate the drive? I have seen the ntfs2btrfs conversion tool. Is there some way to do that process but in reverse.
