### ISSUE TITLE
Cannot find SHA-256 key

### ISSUE THREAD

**Issue by LittleAlf** [maharmstone/btrfs#555]
Sorry for this small request: I just looked all over this site, but I just **cannot find the valid SHA-256 key** for the latest version file 'btrfs-1.8.2.zip'.

Did I miss it somewhere?

**Comment by maharmstone** [comment]
You mean the hash? I've never provided hashes for downloads.

**Comment by LittleAlf** [comment]
If I am not mistaken you did it back at Version 1.7.2: #254. Would it be too much to ask, if you could provide just the hash for the zip-file?

**Comment by Masamune3210** [comment]
I think its been covered before, but the reason hashes arent posted is that Windows will verify the signature is correct when it tries to install it anyway, so the files are verified to be correct before anything serious changes

**Comment by LittleAlf** [comment]
Okay, thanks.
