### ISSUE TITLE
How to get drive letters for btrfs drive in Windows?

### ISSUE THREAD

**Issue by cw2k** [maharmstone/btrfs#561]
**paragon linux file systems for windows** works and gives me drive letters to access my 2 btrfs volumes.

However I wanted to give winbtrfs a try.
Installation via inf-file work. 
I disabled secure boot  and now the 
Device Manager ( devmgmt.msc ) shows 

- 1 btrfs-controller and 
- 2 btrfs-drives

However do I assign these drives a drive letter so I can access them in the windows explorer?

I tried Disk Manager ( diskmgmt.msc ) I occasionally use fix the problem that some usb drives doesn't show up with a drive letter.
But it won't help since Disk Manager still doesn't 'know' how to access / recognise these btrfs partitions.

The readme mentions something about mapping mounting GID SID but I don't really understand what it is for?
Okay GID is that linux Group ID and 
SID  Security IDentifier some Windows equivalent to GID? 

Anyway do I need to use the same usernames in windows that were used in linux to make winbtrfs work?

**Comment by maharmstone** [comment]
It should assign drive letters automatically. Is automounting turned off? Try running `diskpart`, then typing `automount`.

**Comment by cw2k** [comment]
```
Wow thanks a lot for you feedback

I ran
`Diskpart.exe`
Enter 
**Aut**omount
to see the status.
It was disabled.

`aut enable`
to fixed it. 

However still no drives and after a reboot and diskpart automount was disabled again.

The problem was the 
**ParagonLinuxFSMounter**
that interfered with winbtrfs.

on some 'elevated' (run as Admin)
cmd.exe shell enter:
`sc query ParagonLinuxFSMounter`
to see if paragon Service is running.

`sc qc ParagonLinuxFSMounter`
to check its configurations
and 
`sc config ParagonLinuxFSMounter start=disabled`
to disable that service.
Now finally a restart later winbtrfs

Maybe consider adding a note about 
ParagonLinuxFSMounter and diskpart automount to the readme.md

**Comment by maharmstone** [comment]
That's good. You're not the first person to log such issues, and I'm glad we finally know what was causing it. I've added a note to the README.

You also probably want to log this as a bug with Paragon. It absolutely should not be doing this. As you said, it's already caused you problems with your USB drives.
