### ISSUE TITLE
Changing the registry has no effect to recognize my partition in BTRFS.

### ISSUE THREAD

**Issue by jngit23** [maharmstone/btrfs#566]
Hello good afternoon. I am not able to access BTRFS volumes even after installing the driver and modifying the registry, because in my case it is a system with Secure Boot.
I would like to know how to proceed, if there is an alternative to not disabling secure boot.

**Comment by maharmstone** [comment]
> if there is an alternative to not disabling secure boot.

I wish there was, but no.
