### ISSUE TITLE
Explorer shows wrong amount of free remaining disk space

### ISSUE THREAD

**Issue by stephtr** [maharmstone/btrfs#568]
Hi,

First of all, this project is really awesome!

I have two 16 TB disks and BTRFS in RAID1 configuration. Windows shows me that there would be 7.04 TB used / 9.33 TB disk space remaining, but BTRFS usage shows me that both disks are filled with 14.1 TB of data (allocated and used are the same), 15 GB of metadata and 32 MB system. Only 2.3 TB would be unallocated. Whether I use linux, df or du, the answer is always the same, I never get 9.33 TB remaining.

**Comment by maharmstone** [comment]
Thanks Stephan.

That looks right to me. The 14TB is your 7TB twice, because it's RAID1. You have 32TB - 14TB = 18TB free, which means you can put 9TB more data there.

**Comment by stephtr** [comment]
I don't think so.
`btrfs fi show` outputs:
```
Total devices 3 FS bytes used 14.08TiB
devid    1 size 16.37TiB used 14.08TiB path /dev/sde
devid    2 size 16.37TiB used 14.08TiB path /dev/sdf
```
Which I think means that I have 14 TiB of data, duplicated across both disks (2*14). That's also consistent with the 2.3 TiB unallocated space per disk (2*14 + 2*2 = 32). I just verified it by replacing one of the 16 TiB disks with a 8 TB one. If I would've only 7 TiB of data, that would have fitted, but the process stopped with a full 8 TB disk and 6.8 TiB still being left on one of the large disks. I think this is a bug

**Comment by maharmstone** [comment]
No, that's not right. `btrfs fi show` is saying that each disk has 14TB of data chunks allocated, not that there's 14TB worth of data there. If you were to do a balance on Linux, this number would go down.

It's a little counter-intuitive, but my driver reports things the same way as on Linux, so there's no bug here.

**Comment by stephtr** [comment]
I'm sorry to bother you again.

I fully agree with chunks allocated vs. data. In my case however, I ran `btrfs balance` and it didn't find a single chunk with <90% usage. The output of `btrfs fi usage` is consistent with that (14 TiB allocated, but also 14 TiB actual data):
```
Overall:
    Device size:                  32.74TiB
    Device allocated:             28.16TiB
    Device unallocated:            4.58TiB
    Device missing:                  0.00B
    Used:                         28.15TiB
    Free (estimated):              2.29TiB      (min: 2.29TiB)
    Free (statfs, df):             2.29TiB
    Data ratio:                       2.00
    Metadata ratio:                   2.00
    Global reserve:              512.00MiB      (used: 0.00B)
    Multiple profiles:                  no

Data,RAID1: Size:14.06TiB, Used:14.06TiB (99.99%)
   /dev/sdf1      14.06TiB
   /dev/sde1      14.06TiB

Metadata,RAID1: Size:17.00GiB, Used:14.89GiB (87.61%)
   /dev/sdf1      17.00GiB
   /dev/sde1      17.00GiB

System,RAID1: Size:32.00MiB, Used:1.94MiB (6.05%)
   /dev/sdf1      32.00MiB
   /dev/sde1      32.00MiB

Unallocated:
   /dev/sdf1       2.29TiB
   /dev/sde1       2.29TiB
```
Nautilus also states that there are only 2.3 TiB left and if I sum up all file sizes on Windows, I get to 14.3 TB (mostly raw film data, therefore hardly anything to deduplicate or compress). I also checked that the file sizes reported by Windows are the actual filesizes.

I'm therefore still thinking that this could be a bug in how WinBtrfs handles RAID1 size calculations.
