### ISSUE TITLE
Symlinks both in Windows and Linux

### ISSUE THREAD

**Issue by DocMAX** [maharmstone/btrfs#571]
Can you make symlinks more compatible?
For example in linux i create a relative symlink "/games" points to "/syncthing/handheld/games".
In windows the path is correctly shown in the properties tab and is regarded as symlink, but i cannot enter the dir?

![grafik](https://github.com/maharmstone/btrfs/assets/5351323/1ba7ad79-7dde-490a-a920-b2e053afffe7)

And on the opposide way if i create symlinks in windows the are shown as empty directories under linux.
Edit: Just figured out that those symlinks are FILE symlinks. They have to be DIR symlinks. Can this be corrected with this driver?

(Sorry for the german language)

**Comment by maharmstone** [comment]
> Sorry for the german language

Apology accepted.

Unfortunately not - Windows uses different symlink types for files and directories, and without doing an expensive lookup the driver doesn't know which is which. Microsoft did add a Linux-compatible symlink type for WSL, but IIRC Explorer doesn't understand it at all.

You can get round this by manually creating "mount point" symlinks using `mklink`, but Linux won't be able to understand them.

**Comment by DocMAX** [comment]
Thank you for the reply.
So i understand there is no way to have both worlds together.
Then my workaround is to recreate symlinks on boottime with shell/vbs scripts.

**Comment by maharmstone** [comment]
Or set up bind mounts in your Linux `/etc/fstab`.
