### ISSUE TITLE
2 drives with BTRFS, 1 drive seen, 1 drive seen, then disappeared and won't assign to drive letter.

### ISSUE THREAD

**Issue by Zodiaksl** [maharmstone/btrfs#577]
Hello,

Currently using Windows 11

Had been using WinBTRFS for a while now and I have 2x external USB drives formatted as BTRFS.

1x is a 5TB WD_Black
1x is a 18TB TB WD Elements drive

Both drives are known to be good. both are instantly detected by my Steam Deck, mounted and usable from my Steam Deck in Desktop mode (Which I believe SteamOS is Arch Linux).

The 5TB WD_Black is detected by WIndows 11 and is currently assigned to F:\ and G:\ in windows since it has both an EXT4 and BTRFS partition and has Batocera on it.

The 18TB WD Elements drive has only 1 partition on it and is formatted only in BTRFS. It USED to show up on WIndows 11 and is currently being detected in WIndows as the USB indicator in the WIndows System tray at the bottom right of my screen shows it.

From what I remember, Drive 1 used to mount and assign as F:\ and G:\ and the drive that isn't being assigned used to assign as H:\

Since WinBTRFS isn't assigning a drive letter to the WD Elements drive and that I can't assign a drive letter within WIndows Disk Management, I am scratching my head as what to do here.

Drive used to show up, used to work fine, now same drive still works within Arch Linux but won't assign a drive letter in Windows.

I thought that maybe another device could have been assigned to H:\ causing the drive not to get assigned properly, but I have no other USB devices other than the 2x USB drives.

I even tried changing the drive letters of F:\ and G:\ around to see if the H:\ drive would appear but no such luck.

Is there any way to change the BTRFS drive letter of a drive other than once it does have a drive letter > right clicking > going to Properties > Going to BTRFS tab and picking a drive letter there?

Thank you very much for your time.

**Comment by Zodiaksl** [comment]
- I've tried re-assigning the assigned drive letters of the good drive.
- I've tried removing the problematic drive.
- I've tried removing the non problematic drive
- I've tried plugging in only the problematic drive to see if it would show up.

According to windows, the give is being detected and is being configured through disk.inf according to the Windows 11 Device Management under Disk Drives > WD Elements > Events

**Comment by maharmstone** [comment]
Try going to HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices in Regedit, deleting the entries for F:, G:, and H:, and rebooting. Does that help?

**Comment by Zodiaksl** [comment]
> Try going to HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices in Regedit, deleting the entries for F:, G:, and H:, and rebooting. Does that help?

This worked!

Hooray!

Please don't delete this so others can see it if they get the same problem :)

**Comment by maharmstone** [comment]
Great - I'm glad that turned out to be an easy one. I've added a bit about it to the README.
