### ISSUE TITLE
can winbtrfs ruin the partition even though it mounts it read only?

### ISSUE THREAD

**Issue by kfirufk** [maharmstone/btrfs#584]
after restarting from windows back to linux, i couldn't mount my btrfs partition, some errors and something about failing opening ctree.

now since winbtrfs mounts the partition as read only i assumed that it might not be related. i just wanted to  confirm
is there a chance that this driver is tempering with my partition?

had to run btrfsck, it fixed the problem , just want to make sure that this driver 100%  and the problem occured because of something else.

**Comment by maharmstone** [comment]
If the `Readonly` flag is set, WinBtrfs won't do any writes to the disk.

**Comment by kfirufk** [comment]
ok so Readonly flag is not set, how do I enable the readonly flag? the documentation is not clear

i went to the location it said in the documentation
i tried editing the default REG_SZ, i added the data Readonly=1 but it didn't work
tried adding a new string value Readonly with the value 1, it didn't work.

how do i make it read only ?
