### ISSUE TITLE
Can this driver be installed for "portable" use?

### ISSUE THREAD

**Issue by spflaumer** [maharmstone/btrfs#585]
I would like to combine this with FreeOTFE to decrypt and browse a partition on my pendrive on my colleges PC's (i'm starting a course in IT), mounting the drive is not strictly necessary; Simply exploring and copying the files is enough.

If it isn't, are you perhaps aware of any such implementation (should be an Open Source)?
If there aren't I would then have to write my own  btrfs filesystem explorer/utility, which I am reluctant to do due to a momentary lack of skill and knowledge of the filesystems internals.

**Comment by spflaumer** [comment]
I feel like I should clarify a bit more.
The Windows installation can't be modified, the btrfs driver should reside on a Windows accessible partition (FAT32/exFAT/NTFS etc.) while providing a way to open a btrfs partition (mounting isn't necessary)

**Comment by maharmstone** [comment]
You can't load a kernel driver without modifying the Windows installation. I know Paragon makes some sort of userspace tool which might be what you're after.

If you're not wedded to Btrfs specifically, I know there's a few ext2 browsers out there as well.

**Comment by spflaumer** [comment]
I would've wanted to keep on using btrfs though... I'll look into the program by paragon. Thank you for your help

**Comment by rautamiekka** [comment]
If we were using Win9x, then yeah you could install/boot a kernel driver. Should be obvious why that ain't allowed.
