### ISSUE TITLE
Error: "The parameter is incorrect"

### ISSUE THREAD

**Issue by ilyyuna** [maharmstone/btrfs#586]
Trying to change the drive letter on my btrfs drive, an error occured, as the following image shows:
![image](https://github.com/maharmstone/btrfs/assets/132998455/2752838f-9979-4641-88e7-04ffb5243151)
I assume it's related to the "path" environment variable, as other programs errored out due to the path variable being null?

**Comment by maharmstone** [comment]
Why is your PATH empty?

**Comment by ilyyuna** [comment]
i do not know

**Comment by maharmstone** [comment]
Okay. I think pretty much every program will assume that PATH is set, as you've found out, so I don't think it's a bug that the shell extension behaves the same way.
