### ISSUE TITLE
btrfs.sys?

### ISSUE THREAD

**Issue by Matthew98405** [maharmstone/btrfs#59]
I've cloned the repo onto windows, enabled test mode, and right-clicked the .inf to install, but it prompts me for btrfs.sys, which is nowhere to be found. Am I missing something?

**Comment by maharmstone** [comment]
I've moved the binaries into the release zip. Unless you want to compile it yourself, you'll need to download that.

**Comment by Matthew98405** [comment]
Thanks for the quick reply, but where can I find that .zip?

**Comment by maharmstone** [comment]
https://github.com/maharmstone/btrfs/releases

**Comment by Matthew98405** [comment]
Oh, of course, thanks!
