### ISSUE TITLE
LUKS Encryption support

### ISSUE THREAD

**Issue by newborking** [maharmstone/btrfs#594]
As far as I'm aware I'm unable to access a BTRFS drive encrypted with LUKS on Windows. I did not see it in features so I'm assuming It's not in here at all. I'm currently using LUKS2.

Definitely a feature this project needs and should be added to the Todo. Would love to hear a response on this. Thanks!

**Comment by maharmstone** [comment]
Out of scope. Someone needs to write a LUKS2 driver for Windows, which would expose the decrypted volume as a block device. As far as I'm aware no-one's done it yet.
