### ISSUE TITLE
Just a thank-you to the developer

### ISSUE THREAD

**Issue by TheBeeBoi** [maharmstone/btrfs#598]
I've been looking for a stable btrfs driver for so long, and it's really been hindering my dualboot. Thanks to you, I have no problems anymore!
You made my day.

**Comment by grahamIT** [comment]
Why did you opened a new issue for this? I appreciate the dev to but there are so many issues already.

**Comment by maharmstone** [comment]
Thank you @TheBeeBoi, I appreciate it.

Graham, lighten up.
