### ISSUE TITLE
Cyberpunk 2077 crashing on BTRFS volume

### ISSUE THREAD

**Issue by DocMAX** [maharmstone/btrfs#599]
I have installed the game (GOG version 2.0) on NTFS and BTRFS volume. On BTRFS the game is crashing right on launch. Any chance to debug this?

**Comment by CodingWithAnxiety** [comment]
This likely isn't a driver bug and is far more likely to be a game bug.

**Comment by DocMAX** [comment]
I had no issues with 1.x versions. Begins with 2.x for me.

**Comment by maharmstone** [comment]
I've just tried it with a fresh installation of the Steam version, and it flatlined for me too. STATUS_ACCESS_VIOLATION when reading from address 0x48, which suggests that a function is returning NULL and it's not handling it correctly. This was just as it finished loading the save game.

It should be set up to automatically create a crashdump in the hidden directory AppData\Local\REDEngine\ReportQueue in your user directory. Could you send it me please?

**Comment by DocMAX** [comment]
Thank you for looking into this. Here is my crashdump.
[Cyberpunk2077-20231029-184736-9544-15892.zip](https://github.com/maharmstone/btrfs/files/13198799/Cyberpunk2077-20231029-184736-9544-15892.zip)

**Comment by maharmstone** [comment]
Possibly this is related to the FSCTL_QUERY_VOLUME_CONTAINER_STATE messages that CP77 is (indirectly) sending just before things go wrong.

Unfortunately Googling it leads, erm, to here, which isn't very helpful: https://github.com/maharmstone/btrfs/blob/master/src/fsctl.c#L5770

**Comment by DocMAX** [comment]
I'm sorry i can't help. I'm no programmer. I hope you can find a solution. (If it's a driver fault)

**Comment by maharmstone** [comment]
> I'm sorry i can't help. I'm no programmer. I hope you can find a solution. (If it's a driver fault)

That's fine, the note was primarily for my benefit, or anybody interested passing by. I'm fairly sure it is a driver fault.

**Comment by maharmstone** [comment]
Okay, scratch that, I don't think it is a driver fault. I got the same crash playing off an NTFS partition. I think @CodingWithAnxiety is right, it's a bug in the game - see e.g. https://old.reddit.com/r/cyberpunkgame/comments/16rjnjn/error_exception_access_violation_0xc0000005/

Loading an older save worked, but then I got the same crash again after about 5 minutes or so.

**Comment by DocMAX** [comment]
OK, for me running on NTFS (also via network share) works fine.
