### ISSUE TITLE
Dokan?

### ISSUE THREAD

**Issue by peci1** [maharmstone/btrfs#6]
Hey, have you considered implementing the driver in userspace using Dokan? It provides both its own callback API and FUSE API. It might make the development easier (or not, I can't make a qualified guess here). 

https://github.com/dokan-dev/dokany

**Comment by maharmstone** [comment]
Possibly, if you were starting from scratch, but all the hard kernel work is done now!

**Comment by peci1** [comment]
Ok, so happy development :)

**Comment by nille02** [comment]
And userspace FS drivers are horrible slow.
