### ISSUE TITLE
Volume is not accessible. 

### ISSUE THREAD

**Issue by zatroch** [maharmstone/btrfs#60]
After messing with x86 PAE patch (from wj32.org) and other lame "bcdedit /set pae ForceEnabled" stuff; getting "An internal error occured." message while selecting the drive within File Explorer.

// It happens after removing the PAE boot entry from within msconfig utility and reinstalling *.inf as well.

Driver status in Device Manager >>> Storage volumes says it's working properly.

Any hints much appreciated.

**Comment by maharmstone** [comment]
Thanks. Is the device still working on Linux? Can you post the output of btrfs check please?

**Comment by zatroch** [comment]
We are getting there! Thank you for help so far.
![msg](https://user-images.githubusercontent.com/12057459/31585089-f90db972-b1aa-11e7-9c33-ea44f0a13610.png)

**Comment by maharmstone** [comment]
Oh, it looks like PAE must have corrupted it - bummer. I'll look into this for the next release. Thanks for reporting it.

**Comment by zatroch** [comment]
You're welcome and keep on rolling with this awesome project.

**Comment by WolfMad** [comment]
this looks similar to a error i got today i have the drive working now i fixed the error using a Linux distro
GParted log 
checksum verify failed on 740524032 found 3203B60F wanted 00000000
checksum verify failed on 740524032 found 3203B60F wanted 00000000
checksum verify failed on 740524032 found 48B38479 wanted 00000000
checksum verify failed on 740524032 found 3203B60F wanted 00000000
bad tree block 740524032, bytenr mismatch, want=740524032, have=0
ERROR: cannot open file system
