### ISSUE TITLE
Windows 10 Not Recognising USB Docking Station With Synology NAS Hard Drive

### ISSUE THREAD

**Issue by Champudak** [maharmstone/btrfs#602]
I have a Synology NAS RAID 1- 8Tb harddrive (taken from a DS220+) that I am trying to access on my Windows 10 laptop.
I have downloaded the driver WinBtrfs and installed on the laptop and followed some steps that included modifying the windows registry but the laptop does not see the usb drive unfortunately and its not showing in 'Disk Management' either, though an entry does show in Device Manager as 'USB Attached SCSI (UAS) Mass Storage Device'? 

When I look more closely in Device Manager (Events Tab) I get this log:
Device USB\VID_174C&PID_55AA\MSFT3000000000000000000000 was not migrated due to partial or ambiguous match.

Last Device Instance Id: USB\VID_05AC&PID_129F\6eb03b4ecfe647e7f77f543018060ca005ff4827
Class Guid: {88bae032-5a81-49f0-bc3d-a4ff138216d6}
Location Path: PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(2)
Migration Rank: 0xF000FFFFFFFF0023
Present: false
Status: 0xC0000719

Does anyone have any ideas?

Thank you!

**Comment by maharmstone** [comment]
C0000719 is STATUS_CONTEXT_MISMATCH.

If the drive isn't showing up at all, I don't think this is a problem with this driver. Plus search for Synology in the README, to find out why even if it worked you'd probably be out of luck.
