### ISSUE TITLE
Drive doesn't mount

### ISSUE THREAD

**Issue by one-eyed-man** [maharmstone/btrfs#603]
I connected my old 8TB NAS btrfs drive to my Windows 10 PC, installed btrfs.inf ("The operation completed successfully"), and restarted my computer. The drive doesn't show up. 
![image](https://github.com/maharmstone/btrfs/assets/58844201/eed4bf8d-4042-4cda-969c-bfac844ffcce)

The drive appears in DiskInternals so I know it's connected:
![image](https://github.com/maharmstone/btrfs/assets/58844201/eed86568-2cbd-4d9d-af75-a6401d782e1f)

Any ideas?

**Comment by maharmstone** [comment]
Which NAS? If it's Synology, see the note about that in the README.

**Comment by one-eyed-man** [comment]
It is Synology. Looks like I'm out of luck for now. Thanks anyway.

**Comment by maharmstone** [comment]
Bummer. No worries.

**Comment by one-eyed-man** [comment]
Kind of off topic but do you know of a simple way to reformat BTRFS to NTFS? (I don't mind if the drives get wiped)

**Comment by maharmstone** [comment]
If you can't do it with diskmgmt.msc, I'd do it in Linux. You might need to `dd if=/dev/zero of=/dev/whatever` to clear the LVM beforehand.

**Comment by one-eyed-man** [comment]
I got it, thank you. Solution for future viewers: [this worked in my specific situation - drive previously used in a Synology NAS, Windows 10 PC. YMMV]
1. Connect old Synology BTRFS-formatted drive to PC with USB SATA reader
2. Run **Command Prompt** as administrator
3. Enter the following commands
	diskpart
	list disk
	select disk [disk # - make sure you select the correct one]
	clean
4. Open **Disk Management**. An "Initialize Disk" message should pop up. Choose GPT -> Ok.
5. Scroll down Disk Management until you find the newly initialized disk. It should have a black bar with zebra stripes and "####.## GB Unallocated". Right-click zebra area -> New Simple Volume -> Next -> Next -> Choose a drive letter -> Change volume label to desired drive name -> Next -> Finish
