### ISSUE TITLE
Cannot Format Partition As BTRFS:   FormatEx Fail

### ISSUE THREAD

**Issue by daxiaoming** [maharmstone/btrfs#62]
Btrfs  version:  v1.0.1
OS:  win7   x64
Security Software:   Commodo Firewall 10,  ESET NOD32 v4.2.76.1, GlassWire Lite v1.2.118
Partition:   2nd main partition on a USB harddisk

I tried the following commands, they both said:   FormatEx failed

`format /fs:btrfs    s:`

and 

`mkbtrfs s:`

**Comment by daxiaoming** [comment]
Tried v1.0,   also failed.

**Comment by PSam95** [comment]
Same error in #63 Issue.

**Comment by danis-ahmaev** [comment]
same

**Comment by Zero3K** [comment]
I cannot do that under Windows 7. There's no BTRFS option (just FAT32 and NTFS).

**Comment by Atemu** [comment]
>   * How do I format a partition as Btrfs?
>
>Use the included command line program mkbtrfs.exe. We can't add Btrfs to Windows' own dialog box, unfortunately, as its list of filesystems has been hardcoded. You can also run format /fs:btrfs, if you don't need to set any Btrfs-specific options.

https://github.com/maharmstone/btrfs/blob/master/README.md

**Comment by woodsleaf** [comment]
windows 10
mkbtrfs j:
success, but  after it volume J: not found in explorer(filemanager).

**Comment by SergeGautherie** [comment]
@daxiaoming Do you still reproduce, with new releases (current is v1.4)?

--

@Zero3K Can't you use the command line tools?

--

@woodsleaf your comment/case does not seem relevant to this very issue...
Or did you simply mean that your are not reproducing this issue on your Win10?

**Comment by ElpizoZ** [comment]
Mkbtrfs gives the same error. I am using 1.7.3 on Windows 10 x64.

**Comment by csdvrx** [comment]
This bug is still active:

With the existing partition, in Win+X A powershell admin session:

```
PS C:\WINDOWS\system32> .\mkbtrfs.exe L:
FormatEx failed
PS C:\WINDOWS\system32> .\mkbtrfs.exe \Device\Harddisk0\Partition4
FormatEx failed
```

After deleting the partition from "Disk Management", and creating a new unformatted partition, mkbrtfs seems to succeed, but if we launch a format right afterwards, it reports the partition is still raw:

```
PS C:\WINDOWS\system32> .\mkbtrfs.exe L:
Completed successfully.
PS C:\WINDOWS\system32> .\mkbtrfs.exe L: WSL
Completed successfully.
PS C:\WINDOWS\system32> format /fs:brtfs L:
The type of the file system is RAW.
The new file system is BRTFS.
FORMAT is not available for BRTFS drives.
```

**Comment by maharmstone** [comment]
```
PS C:\WINDOWS\system32> format /fs:brtfs L:
The type of the file system is RAW.
The new file system is BRTFS.
FORMAT is not available for BRTFS drives.
```

Erm... what happens if you spell it correctly?

**Comment by maharmstone** [comment]
Closing old issues

**Comment by Starbuck1991** [comment]
Hello,

I'm encountering a similar issue. I'm using the latest version installed on Windows 11 via Chocolatey. The drive is formatted with NTFS and mounted as Z:

C:\>mkbtrfs Z: Videoeditor
FormatEx failed

I attempted to use the format command as well:

D:\>format /fs:btrfs /v:Videoeditor Z:

However, I received a "format error" message. When trying with a RAW disk, it states "Formatting," but nothing happens, and the disk remains as RAW. Any assistance would be greatly appreciated.

**Comment by wooseopkim** [comment]
For those who might be still suffering and future visiters, I managed to make it happen. I'm not sure if this would work for everyone though.

1. Press `Windows` + `X`.
2. Click `Run`.
3. Type in `diskmgmt.msc` and click `OK`.

![Image](https://github.com/user-attachments/assets/14605efa-f512-4619-aac4-3bbc914d66a5)

4. In the bottom list, find the disk you'd like to format. It was `Disk 3` in my case.
5. Right click on its name (probably `Disk <number>`) and choose `Properties`.

![Image](https://github.com/user-attachments/assets/5f644649-760c-4bec-91cb-6c6a8d41618f)

6. Go to `Details` tab.
7. There should be a dropdown list under `Property`.
8. Choose `Physical Device Object name`.

![Image](https://github.com/user-attachments/assets/d0ac3404-dd1a-4330-a8a5-9ccaad008dc1)

9. Copy the value. It should be something that looks like `\Device\<some ID>`.
10. Open the terminal, and run `mkbtrfs <value from step 9>`. I tried in the Admin terminal, and I have no idea whether that's a must.
11. Open Explorer, check the side menu, and voila! (at least in my case.)
12. To double-check, right click on the disk and choose `Properties`.

![Image](https://github.com/user-attachments/assets/ef0c676d-2e55-4845-8272-c17f172e54b4)
