### ISSUE TITLE
Add installer for winget

### ISSUE THREAD

**Issue by trajano** [maharmstone/btrfs#620]
so we can do 
```
winget install btrfs
```

**Comment by maharmstone** [comment]
I don't know anything about winget, but if you'd like to contribute this be my guest.

**Comment by trajano** [comment]
I think it needs to be the owner of the project anyway here's the information https://learn.microsoft.com/en-us/windows/package-manager/package/

Over here you have to send the submission but I am not sure how to fill in the required information.

https://github.com/microsoft/winget-pkgs/issues/new/choose

**Comment by maharmstone** [comment]
Okay, if this is a Microsoft thing there's no chance, unfortunately - Microsoft doesn't approve of drivers that haven't been EV-signed. Ah well.

**Comment by 8bitZeta** [comment]
I would like to reopen this issue as I don't believe EV is required for hosting on Winget.

I believe that is only required for the hardware dashboard and Windows Updates. 

I've opened a discussion on one of their GitHub repos, so I will hopefully have a more concrete answer soon.
