### ISSUE TITLE
[Question] is rw filesystem with Block Group Tree (added Linux v6.1) supported?

### ISSUE THREAD

**Issue by Interpause** [maharmstone/btrfs#628]
https://btrfs.readthedocs.io/en/latest/Feature-by-version.html

In Linux v6.1, Block Group Tree became stable. Switching to block group tree is backwards incompatible such that old kernels can no longer write to the btrfs filesystem. Can I check if writing to block group tree enabled filesystems is supported by winbtrfs?

**Comment by maharmstone** [comment]
Not yet - I only learnt about this a few weeks ago. I'm planning to have it in the next version, when I get round to it.

**Comment by Interpause** [comment]
good job with v1.9, ill go try it soon. thanks!
