### ISSUE TITLE
[Documentation] Using a GUI for win-btrfs?

### ISSUE THREAD

**Issue by rubyFeedback** [maharmstone/btrfs#630]
Could the documentation aka main README:

a)  make it more clear whether there is a GUI for win-btrfs, including a screenshot?

Right now this is mentioned, I think, but I am not sure if this works. A screenshot would
be nice. Could be hosted externally at imgur etc...

b) if a is true, could you also explain how to start that GUI then and use it? I know 
ext2fsd already, so I wonder how similar win-btrfs would be usage wise.

Anyway thank you for reading this issue request.

**Comment by maharmstone** [comment]
This is a kernel driver. The only "GUI" is the shell extension, which allows you to do things like create subvolumes using Explorer.

**Comment by sskras** [comment]
@maharmstone commented [on Feb 23](https://github.com/maharmstone/btrfs/issues/630#issuecomment-1962007259):

> The only "GUI" is the shell extension, which allows you to do things like create subvolumes using Explorer.

TIL about the "New subvolume" item found in the context menu of the mounted Btrs drive:

![image](https://github.com/maharmstone/btrfs/assets/7887758/4354fda4-8d11-4293-bdee-e445abdd4338)

This would be nice to have documented in some other place than the random closed issue.
Haven't found any.
