### ISSUE TITLE
Question on document

### ISSUE THREAD

**Issue by mio-19** [maharmstone/btrfs#633]
In the "Mount options" section:

> If a value is set in the key above this, it will use this by default.

Does "the key above this" refer to HKLM\SYSTEM\CurrentControlSet\Services\btrfs? What does the second "this" refer to?

Does this sentence mean that I can set default options for all volumes directly under HKLM\SYSTEM\CurrentControlSet\Services\btrfs?

**Comment by maharmstone** [comment]
> Does "the key above this" refer to HKLM\SYSTEM\CurrentControlSet\Services\btrfs?
Yes

> What does the second "this" refer to?
"This value"

> Does this sentence mean that I can set default options for all volumes directly under HKLM\SYSTEM\CurrentControlSet\Services\btrfs?
That's correct
