### ISSUE TITLE
doc clarification on mappings

### ISSUE THREAD

**Issue by amunra** [maharmstone/btrfs#634]
I read the section for mappings.

> The user mappings are stored in the registry key HKLM\SYSTEM\CurrentControlSet\services\btrfs\Mappings. Create a DWORD with the name of your Windows SID (e.g. S-1-5-21-1379886684-2432464051-424789967-1001), and the value of your Linux uid (e.g. 1000). It will take effect next time the driver is loaded.

Should the Linux UID uid valued be entered as hex or decimal? (I'm assuming decimal, but I wanted to be sure).

**Comment by rautamiekka** [comment]
It's always decimal (normal numbers) unless otherwise specified, which I presume is simply cuz any other conversion on the User's end just ain't worth it.

**Comment by maharmstone** [comment]
Yes, as Jouni says, Linux UIDs are customarily given in decimal rather than hex.

I do plan to add a GUI for this at some point, as a number of people have had problems with it.

**Comment by amunra** [comment]
I think the main thing I struggled with was the fact that I had to mess about with regedit to etll windows this is an upgraded system for it to pick up the btrfs drives.

It would be neat if there were an installer or configurator program, even if this was a command line tool that asked a few basic questions.
