### ISSUE TITLE
Directory listings appear to be unsorted

### ISSUE THREAD

**Issue by ThePuzzlemaker** [maharmstone/btrfs#635]
I really don't know what this error is, if it's related to WinBTRFS or not. But I thought I'd ask here since it only happens on my BTRFS drive, and breaks programs needing whatever Windows API functions to return a sorted directory listing.

This is evidenced by running `dir` in PowerShell in `C:\Windows\System32`:
```
PS C:\Windows\System32> dir


    Directory: C:\Windows\System32


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         12/7/2019   3:49 AM                0409
d-----         9/28/2023   8:56 PM                1028
d-----         9/28/2023   8:56 PM                1029
d-----         9/28/2023   8:56 PM                1031
d-----         9/28/2023   8:56 PM                1033
d-----         9/28/2023   8:56 PM                1036
d-----         9/28/2023   8:56 PM                1040
d-----         9/28/2023   8:56 PM                1041
d-----         9/28/2023   8:56 PM                1042
d-----         9/28/2023   8:56 PM                1045
d-----         9/28/2023   8:56 PM                1046
d-----         9/28/2023   8:56 PM                1049
d-----         9/28/2023   8:56 PM                1055
d-----         9/28/2023   8:56 PM                2052
d-----         9/28/2023   8:56 PM                3082
d-----         12/8/2023  11:54 PM                AdvancedInstallers
d-----         12/7/2019   3:14 AM                am-et
d-----         9/25/2023   5:19 PM                AMD
d-----         12/7/2019   3:14 AM                AppLocker
d-----          3/1/2024  11:07 PM                appraiser
d-----         12/9/2023  10:31 PM                ar-SA
d-----         12/9/2023  10:31 PM                bg-BG
d-----         3/13/2024   1:47 AM                Boot
d-----         12/7/2019   3:14 AM                Bthprops
d-----         9/25/2023   6:41 PM                CatRoot
d-----         3/16/2024   3:42 PM                catroot2
d-----          3/1/2024  11:07 PM                CodeIntegrity
d-----         12/8/2023  11:54 PM                Com
d-----         3/16/2024   2:22 AM                config
d---s-         12/7/2019   3:31 AM                Configuration
d-----         12/7/2019   3:14 AM                ContainerSettingsProviders
d-----         12/9/2023  10:31 PM                cs-CZ
d-----         12/9/2023  10:31 PM                da-DK
d-----          5/5/2023   7:27 AM                DDFs
d-----         12/9/2023  10:31 PM                de-DE
d---s-          3/1/2024  11:07 PM                DiagSvcs
d-----         3/13/2024   1:47 AM                Dism
[... and so on ...]
```
Whereas in `D:\Kerbal Space Program\GameData` (which has to be sorted because of oddities of how KSP modding works):
```
PS D:\Kerbal Space Program\GameData> dir


    Directory: D:\Kerbal Space Program\GameData


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
da----          8/1/2023   2:25 PM                Squad
da----         3/12/2024   1:46 AM                000_Harmony
da----         3/12/2024   1:46 AM                ModularFlightIntegrator
da----         3/12/2024   2:10 AM                000_ClickThroughBlocker
da----         3/12/2024   1:46 AM                001_ToolbarControl
da----         3/12/2024   1:46 AM                KerbalChangelog
da----         3/12/2024   1:46 AM                SolverEngines
da----         3/12/2024   1:46 AM                AJE
da----         3/12/2024   1:46 AM                B9PartSwitch
da----         3/12/2024   1:46 AM                CommunityResourcePack
da----         3/12/2024   1:46 AM                KerbalJointReinforcement
da----         3/12/2024   1:46 AM                RealChute
da----         3/12/2024   1:46 AM                RealHeat
da----         3/12/2024   1:46 AM                ROUtils
da----         3/12/2024   1:46 AM                SmokeScreen
da----         3/12/2024   1:46 AM                RealPlume
da----         3/12/2024   1:46 AM                Shabby
da----         3/12/2024   1:46 AM                CommunityCategoryKit
da----         3/12/2024   1:46 AM                Firespitter
da----         3/12/2024   1:58 AM                Kerbalism
[... and so on ...]
```

This lack of sorting in `dir` in my BTRFS drive makes me think that there is some Windows API "invariant" being broken here, for directory listings. Is there any way to solve this on the BTRFS end, or must I just use another filesystem? Patching KSP is not a viable option, so it's either a fix with WinBTRFS or switching filesystems.

Thanks in advance for any solutions.

**Comment by ThePuzzlemaker** [comment]
Sorry if this is a non-issue, I'm not very experienced with filesystems and I don't really know.

**Comment by ThePuzzlemaker** [comment]
I've realized it's probably more likely a problem to be solved on the KSP side, no matter how infeasible such a patch may be.

**Comment by jonm58** [comment]
> I've realized it's probably more likely a problem to be solved on the KSP side, no matter how infeasible such a patch may be.

?

**Comment by maharmstone** [comment]
Directory listings on Windows _are_ unsorted, unless you specify otherwise. I suspect the files in C:\Windows\System32 are like that because they were installed in alphabetical order.

>Whereas in D:\Kerbal Space Program\GameData (which has to be sorted because of oddities of how KSP modding works):

If that's true, the game is relying on undefined behaviour.

**Comment by lesderid** [comment]
> I've realized it's probably more likely a problem to be solved on the KSP side, no matter how infeasible such a patch may be.

Are you sure? Does it also not work on FAT filesystems? Excerpt from [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findnextfilea#remarks):

> The order in which this function returns the file names is dependent on the file system type. With the NTFS file system and CDFS file systems, the names are usually returned in alphabetical order. With FAT file systems, the names are usually returned in the order the files were written to the disk, which may or may not be in alphabetical order. However, as stated previously, these behaviors are not guaranteed.
