### ISSUE TITLE
How to disable mounting in Windows 11

### ISSUE THREAD

**Issue by fhihu** [maharmstone/btrfs#639]
Hello I installed the driver and alle btrfs partitions are mounted automatically.

However I would like to hide the root partition. In the computer managment overview, you should be able to assign the drive letter. But there I have no drive letters assigned, however in the windows explorere those letters are assigned and I'm not able to delete them.

I created a picture of it.

Help is much appreciated.
fhihu
<img width="1533" alt="Screenshot 2024-04-01 073342" src="https://github.com/maharmstone/btrfs/assets/32387035/e9af84be-6902-4929-affb-0d2205e988fc">
<img width="1332" alt="Screenshot 2024-04-01 073420" src="https://github.com/maharmstone/btrfs/assets/32387035/495ced05-95fc-4ef7-be50-d17138413bf0">

**Comment by jonm58** [comment]
Computer Managment only supports file systems made by Microsoft

**Comment by maharmstone** [comment]
You can change the drive's letter in its Properties page in Explorer.

Search for "Ignore" in the README for how to stop certain devices being mounted.
