### ISSUE TITLE
Question about compression

### ISSUE THREAD

**Issue by theChaosCoder** [maharmstone/btrfs#64]
In btrfs properties you can set a compression flag. I have a file and a folder compressed with zlib but want to change it to lzo, so I set it via the flag option, but it seems like it has no effect. I also ran a balancing.

Compressiontype is now set to 2 in registry (was 0 before)

Am I doing something wrong?

**Comment by maharmstone** [comment]
The flag works the same way as on Linux - it's just a hint for new files. If you want to change the compression type used by a file you have to rewrite. In your case, that would presumably be by moving the files to another location, then copying (not moving) them back to where they were originally.

**Comment by Magissia** [comment]
You can remove the compressed attribute with chattr and re set it to decompress and recompress with new settings.
Don't know if it'll work from Windows.

**Comment by Atemu** [comment]
The correct way of changing the compression type is to mount the filesystem in Linux and then use `btrfs filesystem defragment -r -clzo /path/to/folder`.

**Comment by Eideen** [comment]
> The flag works the same way as on Linux

Yes, but you don't set with chattr, you use file/folder property menu to set compress flags.

**Comment by endolith** [comment]
@Atemu Does that work for single files too? https://unix.stackexchange.com/q/563749/19012

**Comment by Atemu** [comment]
Yes.

**Comment by maharmstone** [comment]
Closing old issues
