### ISSUE TITLE
Where did the btrfs command go？I need to dismantle read-only to rescue opensuse

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [maharmstone/btrfs#643]
![image](https://github.com/maharmstone/btrfs/assets/67987607/e37d6e9f-9af0-4d68-8984-976ffed043da)

**Comment by jonm58** [comment]
This is the Windows driver for Btrfs, not the Windows program that manages Btrfs

**Comment by maharmstone** [comment]
There's no direct port of the `btrfs` program. Whatever you're trying to do, I think booting from a Linux live CD would be a better choice.
