### ISSUE TITLE
Support for .img files contain btrfs file system 💾

### ISSUE THREAD

**Issue by Silitonix** [maharmstone/btrfs#656]
### Support for .img files
Hello and all appreciate for your great project.
i trying to mount a **.img** file with Windows explorer contain **BtrFS** filesystem but it doesn't work at all. is there any way to support this feature?

**Comment by Silitonix** [comment]
also sparse files doesn't show correct size on disk

**Comment by musicomputer-tao** [comment]
Try a third part software to mount img file, IMDISK?
