### ISSUE TITLE
more dynamic uid<->sid mapping

### ISSUE THREAD

**Issue by darkstar** [maharmstone/btrfs#67]
It would be useful if the user mappings could be adjusted dynamically, without having to reload the driver/reboot.

For example, check the registry every *n* seconds for new entries (*n*=5? *n*=30? *n* configurable?)

Additionally, if the computer is in an Active Directory domain, it might be useful to pull the UNIX uid / gid for a specific user from there (and cache it locally for some time). I understand that this is not something that the driver itself should be doing, it probably needs a user-space companion that does the actual AD query and that replaces the uid on the file system as soon as they have been received from the AD

**Comment by maharmstone** [comment]
As of (I think) version 1.0, the user mappings, and indeed all other global parameters, are updated as soon as they are changed in the Registry.

And yes, if Active Directory does have the ability to provide a UNIX uid and gid, it would make sense to pull it from there! I'll have to see precisely what it does.

**Comment by darkstar** [comment]
@maharmstone Ah, then maybe all that's required is a change to the documentation stating that the settings are read every time they are required (there should still be some cache though, I hope, as the registry is not actually the fastest database out there ;-)

Regarding Active Directory, the AD has been RFC2307 compliant for quite some time now, the corresponding LDAP attributes are uidNumber and gidNumber. I think they are not populated unconditionally by default unless you install some role or feature (NIS server?) or if you sync/set them manually or with a 3rd party tool.

**Comment by 5dec17** [comment]
Darkstar, hello. I don't know how to contact you directly on this site.

I have files (from a CD-I disc that I own). I want to look at the stills/pictures/photos (I don't have a CD-I console).

The files are named "green.3t" and "yellow.3t". Inside those files are more hidden files: BMPs, JPGs (etc) without headers for each of those files.

Can Cmake and your Ripper help me to see those files?

If yes, how do I set up CMake and Ripper to do that? I'll need step-by-step instructions, etc.

(I've read your "README" note but I don't understand it.)

I'm using Windows 8.1. Thanks for reading.

**Comment by maharmstone** [comment]
Closing old issues
