### ISSUE TITLE
btrfs driver corrupted/delete btrfs parition

### ISSUE THREAD

**Issue by MacharaStormwing** [maharmstone/btrfs#672]
I used this driver on and off and for some partitions and subvolumes it works, I can even see the subvolumes listed as directories. This is the case for fedora for example if I remember right.

On other distros such as OpenSUSE Tumbleweed and CachyOS (based on Arch) it only mounts the root parition, the home folder is empty (probably along with other sub-paritions).
I fiddled along with the drive mounting... when you go to the property of the drive there is a BTFS section where you can assign driver letter, and manage btrfs partitions.
It listed the btrfs parition of the Tumbleweed and CachyOS installation twice each, each mounted unter one drive letter.
After seeing that I could not do anything there the Tumbleweed partition was not available anymore.
I don't know exactly what action caused this though.

Subsequent tracking determined that the parition is now gone unter the parition table (when booting another linux os and using gparted to look).
Various recovery utilities like dmde (dmde.com) and testdisk (cgsecurity.org) did not find any delete parition or were able to recover anything.

Currently it looks like this driver is no longer developed (many open issues that are not assigned, one similar to this one) and quite frankly this driver appears too buggy to be safely used.
I created this bug to let people know of this experience so they are warned and hopefully give devs a chance to fix this some time.

Just to give you an idea of how the subvolumes of CachyOS are structured here is the /etc/fstab content (copied from a virtual machine of cachyos, since I no longer have my bare-metal parition):

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
UUID=EC59-E781                            /boot/efi      vfat    defaults,noatime 0 2
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /              btrfs   subvol=/@,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /home          btrfs   subvol=/@home,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /root          btrfs   subvol=/@root,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /srv           btrfs   subvol=/@srv,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /var/cache     btrfs   subvol=/@cache,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /var/tmp       btrfs   subvol=/@tmp,defaults,noatime,compress=zstd,commit=120 0 0
UUID=b9a655ee-442b-4774-9e27-0d8acef58dc6 /var/log       btrfs   subvol=/@log,defaults,noatime,compress=zstd,commit=120 0 0
tmpfs                                     /tmp           tmpfs   defaults,noatime,mode=1777 0 0
```

**Comment by maharmstone** [comment]
> Subsequent tracking determined that the parition is now gone unter the parition table (when booting another linux os and using gparted to look).

I don't know what's happened here, but it's definitely not WinBtrfs' doing. To delete a partition you would have to open the disk (rather than the partition) read-write, read the GPT table, delete the entry, rewrite it, and then repeat for the backup copy - none of which we do.

> On other distros such as OpenSUSE Tumbleweed and CachyOS (based on Arch) it only mounts the root parition, the home folder is empty (probably along with other sub-paritions).

Yes, you're not going to get your bind mounts without explicit entries in /etc/fstab.

> Currently it looks like this driver is no longer developed

The last release was in March...
