### ISSUE TITLE
Windows 10:  OBS recording AV1/X264 dropped frames issue

### ISSUE THREAD

**Issue by jarrard** [maharmstone/btrfs#673]
So yeah, as title says.

Anyone tested this with OBS recording and notice its dropping frames every 2000 or so frames which approximates to 5-10% of total frames making it unusable.   ONLY happens on a winbtrfs opporated drive. 

Any solution?

**Comment by jarrard** [comment]
I'm currently doing a scrub on the drive and I've also enabled the compress flag again because I believe that was enabled when I had this drive under Linux so perhaps that will help.

The recording was tested on stable and beta versions of OBS with a ARC Intel GPU and QuickSync, both AV1 and X264 had this issue. It seemed to be purely a write issue to the BTRFS partition but perhaps the method of which OBS writes (persistent write to a open mkv file) was creating a IO issue with driver.

This will need to be investigated further unless a scrub manages to fix the issue (unlikely).  I will also test a few other filetypes but MKV is the best choice as on failure it can still be read and used, unlike other filetypes.

**Comment by jarrard** [comment]
Happens with a USB btrfs drive also.

Formated to NTFS, problem gone.   So that is my solution for the time being.  This is probably the 3rd or 4th time I have had a major I/O issue with winbtrfs driver sadly.  I think I just need to stop using btrfs for multi-os partitions. 

NOTE: OBS under Linux does not have a issue with btrfs partition usage. 

PS. Both these drives were spinning rust hard drives.

**Comment by maharmstone** [comment]
Have you raised it with OBS? This looks like a race condition to me.

**Comment by jarrard** [comment]
> Have you raised it with OBS? This looks like a race condition to me.

I just use NTFS, no problems now.
