### ISSUE TITLE
Files and folders created as Administrators do not respect mappings

### ISSUE THREAD

**Issue by arslan-charyyev** [maharmstone/btrfs#675]
I've mapped **all** users in the `HKLM\SYSTEM\CurrentControlSet\services\btrfs\Mappings` key to uid `1000`. This works as intended for files and folders created as an unprivileged regular user. However, when creating files and folders with elevated privileges, i.e. as Administrator, the uid of such files ends up being `65534` (which can also be interpreted as `-1`). I first discovered this when an installer running as Administrator has created some files, and then later was able to easily replicate it myself when running `echo hi > test.txt` in an elevated PowerShell. I've double-checked for any SID mismatches, but couldn't find any. The reported SIDs match the ones in the registry.

Hence, my question is: Is this a bug, or do I have to perform extra steps to ensure that programs with elevated privileges assign the intended uid?

**Comment by maharmstone** [comment]
The UAC token is unusual in that it creates files as the group BUILTIN\\Administators rather than as the user. Have you included the SID S-1-5-32-544?

**Comment by arslan-charyyev** [comment]
> The UAC token is unusual in that it creates files as the group BUILTIN\Administators rather than as the user. Have you included the SID S-1-5-32-544?

Wow, it worked! Thank you so much for your swift response. If I may offer a suggestion: Could this entry be automatically added to the registry alongside with others? If not, then I believe mentioning this issue in the relevant section of the README would be quite helpful.

**Comment by maharmstone** [comment]
Great. Yes, I've added something to the README.
