### ISSUE TITLE
Fuller description of the modules to lie to about the actual FS type

### ISSUE THREAD

**Issue by sskras** [maharmstone/btrfs#681]
https://github.com/maharmstone/btrfs/blob/99c109ee3e63bb6317ee0afb31156c70ddc3b408/src/btrfs.c#L681-L687

The comment above mentions two cases:
- the `MPR!MprGetConnection()` call
- `cmd.exe` + `mklink` command

But the blacklist includes another three names:
https://github.com/maharmstone/btrfs/blob/99c109ee3e63bb6317ee0afb31156c70ddc3b408/src/btrfs.c#L696-L704

Namely:
- `FSUTIL.EXE`
- `STORSVC.DLL`
- `IFSTEST.EXE`

Can an interested code navigators get descriptions of these cases too, please?

**Comment by maharmstone** [comment]
These are all instances where Microsoft has mistakenly hard-coded their code to only work on NTFS.

**Comment by sskras** [comment]
Fair. Strangely enough `fsutil` seems to work fine with RFSD and EXT4FSD drivers (to me). At least the `fstutil fsinfo volumeinfo`.
Uhm, you probably don't remember any specific subcommands already?

Details about STORSVC issues are also interesting (at least direction / tips for reproducing:)

**Comment by maharmstone** [comment]
> Fair. Strangely enough `fsutil` seems to work fine with RFSD and EXT4FSD drivers (to me). At least the `fstutil fsinfo volumeinfo`. Uhm, you probably don't remember any specific subcommands already?

Sorry, no. It's a complicated program though, and there's definitely parts of it that didn't work without this.

> Details about STORSVC issues are also interesting (at least direction / tips for reproducing:)

IIRC this was an attempt to get it so that Windows Store UWP apps could be moved onto btrfs volumes. This was part of the problem, but there was also some weirdness involving a FS filter driver that stopped it from working.
