### ISSUE TITLE
Failed installation due to digital siganture

### ISSUE THREAD

**Issue by sdpb** [maharmstone/btrfs#687]
Hi there, and thank you for this amazing project:

Recently I did a factory reset of my Desktop and reinstalled all the tools and stuff.
I'm having issues with BTRFS because it installs "successfully" but when I restart it shows nothing.

I did some debugging on it based on another closed issue: [Version 1.7 problem](https://github.com/maharmstone/btrfs/issues/234)

And got this:
```
PS > sc query btrfs

SERVICE_NAME: btrfs
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS > sc start btrfs
[SC] StartService FAILED 577:

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

Current version of windows where I got the problem:

```
PS > systeminfo

Host Name:                 ---------
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
```

**Comment by maharmstone** [comment]
Have you tried disabling Secure Boot?

**Comment by sdpb** [comment]
Well, after rebooting and disabling Secure Boot it worked perfectly, and following the troubleshooting guide in the Readme (As I should have done before) I could make it run with SB enabled by modifying the DWORD in Registry Editor.

!Thank you so much for your help!
