### ISSUE TITLE
data error "Data error (cyclic redundancy check)".

### ISSUE THREAD

**Issue by bhcopeland** [maharmstone/btrfs#69]
This was working perfectly, just rebooted into windows and get:

"Data error (cyclic redundancy check)".

**Comment by Edwin-Edward** [comment]
Hello,
I got this same error today (version 1.5) and I have the strong feeling that it's something related to Windows' fast startup (which is a hybrid hibernation, AFAIK) and dual boot with Linux which mounts the same volume.
Somehow the volume should be unmounted and remounted in Windows after a fast startup (?)

BTW where can I find some logs about what winbtrfs is doing and errors?

**Comment by maharmstone** [comment]
If that's what you're doing, yes, that would definitely cause errors. I'd say it's not a bug in this driver, as Windows assumes that nobody's has been messing around with its volumes while it's been hibernating - see also the way Linux will refuse to mount your NTFS volume RW in the same situation. Maybe it warrants an entry in the FAQ, though.

**Comment by maharmstone** [comment]
I changed my mind, having realized that a lot of people won't even know that Fast Startup is a thing. Today's patches ensure that whenever Windows sleeps or hibernates, all dirty volumes will be flushed, and when it wakes up again they will be forcibly remounted if they've changed. It's still a good idea to disable Fast Startup if you're dual-booting, but at least this should stop people inadvertently corrupting their volumes.
