### ISSUE TITLE
Secure boot support?

### ISSUE THREAD

**Issue by wsanders** [maharmstone/btrfs#693]
1.9 (and 1.8.2) doesn't work with secure boot enabled, presumably because the driver is not signed. If that is correct, then this is a feature request to sign the driver. Can you even do that with FOSS in Windows 11? I know there's a way in Fedora. I have Windows 11 OEM keys (2011 MS KEK etc) installed. Note: I installed WinBTRFS 1.9 with secure boot off, then turned secure boot on. Other info: 

Edition	Windows 11 Pro
Version	23H2
Installed on	‎8/‎8/‎2023
OS build	22635.4082
Experience	Windows Feature Experience Pack 1000.22700.1038.0

**Comment by jonm58** [comment]
Have you checked [README.md](https://github.com/maharmstone/btrfs/blob/master/README.md)?

![图片](https://github.com/user-attachments/assets/edb1db46-5295-4ed0-b8c8-2674dbf649ba)

**Comment by maharmstone** [comment]
> 1.9 (and 1.8.2) doesn't work with secure boot enabled, presumably because the driver is not signed.

The driver is signed, but with a normal code signing certificate, not the more expensive EV ones that aren't available to individual FOSS developers. Unfortunately this isn't a problem that I'm able to solve.

Unless they've changed something recently, Secure Boot should work with the Registry option changed. You might need to disable it, install the driver, then re-enable it.

**Comment by SaulGoodman1337** [comment]
Hi,
I would like to open the thread again. 
Your method works, but the anticheat of battlefield 6 doesn't seem to like it.

Is there really no way to sign the thing properly without using any hacks ?
Is a donation collection useful?

**Comment by AstralStorm** [comment]
It is possible to sign the driver with a custom Secure Boot Platform Key involved.

Process is a bit involved, requires potentially enrolling the key in firmware by hand (which depends on the motherboard brand, but is always available somewhere in advanced firmware options) and does not work on Home edition.

See:
https://learn.microsoft.com/en-us/windows/security/application-security/application-control/app-control-for-business/design/custom-kernel-signers

and someone made a guide for slightly older windows with a rather nasty licensing change to China hack:
https://github.com/MysticSnows/Custom-Kernel-Signer-Win11-KnowledgeBase

You can skip the SSDE/CKS hacks on Windows 11 24H2 or newer, but you need to **Reset Windows** to apply the policy, apparently, which loses apps. Someone needs to see what sort of a step is done during this Reset so it can be duplicated without it.
