### ISSUE TITLE
Add btrfs support to ReactOS

### ISSUE THREAD

**Issue by MailYouLater** [maharmstone/btrfs#7]
It seems there is some work being done by the people working on ReactOS to add this driver to it.
I'd like to see this happen, as I think it will likely be helpful both for ReactOS, and for btrfs, and specifically this btrfs for Windows implementation .
See [Jira:CORE-10892](https://jira.reactos.org/browse/CORE-10892) for what they have so far, and hopefully any changes required for ReactOS integration can be merged upstream (into this codebase) so that keeping it up-to-date in the ReactOS codebase is easy (meaning that it will be more likely to actually be updated when this implementation gets updates).

Thank you for making this, and please keep up the good work.

**Comment by hatermater** [comment]
Thanks for sharing your work with all the people and I'm sure ReactOS developers and community will appreciate it also. Any remarks, patches, advices, comments or any other help will also be appreciated greatly. ReactOS might be still alpha, but developers are trying hard to fix all found issues and implement missing stuff.
I wish you all the best and keep up the good work.

**Comment by MailYouLater** [comment]
I don't think this should be closed until [Jira:CORE-10892](https://jira.reactos.org/browse/CORE-10892) is merged into ReactOS trunk.
:(.

**Comment by maharmstone** [comment]
Sorry, you're right.

**Comment by mdickie** [comment]
It's merged. Ready to close.

**Comment by maharmstone** [comment]
Thank you
