### ISSUE TITLE
[Feedback]  Congratulations, it's fully compatible with veracrypt.

### ISSUE THREAD

**Issue by universish** [maharmstone/btrfs#707]
First of all, this is not a bug report. It is a feedback. If @maharmstone developer sees this partition I will change the title to complete.

To try it out, I created a hidden, deniable and encrypted partition on a Windows PC with veracrypt, in the btrfs file system. I mounted the volume with Veracrypt. Windows File Explorer recognized the volume and I can use it without any problem, just like with ntfs. 
After mounting the btrfs partition I created with Veracrypt, DiskGenius and other Disk Partition Manager programs did not see it either.
I also tried DiskInternals Linux Reader, Linux File Systems for Windows by Paragon, Paragon ExtFS, Ext2Read, which are supposed to be btrfs file viewers or drivers. They could not see the Veracrypt btrfs partition.

I had no problems with normal btrfs space either.

Congratulations. 

You are doing successful work. I wish you continued success.

 As a Windows 11 and fedora 41 user, we need such programs very much. Thanks to you, we have smooth experiences.
Thank you very much for your efforts.

**Comment by universish** [comment]
@maharmstone  
I want to ask you something:
What is btrfs-1.9-pdb.zip used for? How to install it or can it be installed? What does pdb stand for?

**Comment by Hanatarou** [comment]
> @maharmstone Can I ask you one more question? This drive works with windows file explorer. Is there a driver for Ext 2/3/4 (especially for Ext4) on git platforms that works with File Explorer like this driver? I couldn't find it...

Hello everyone,

I believe your best option would be: https://github.com/bobranten/Ext4Fsd

Best regards,

Hanatarou

**Comment by maharmstone** [comment]
Thanks @universish. I don't normally test with Veracrypt, so it's good to hear that it's still working.
There's actually special code to work around Veracrypt's quirks, as their plug and play code isn't quite right.

>What is btrfs-1.9-pdb.zip used for? How to install it or can it be installed? What does pdb stand for?

Program Database, I think. These are the debugging symbols, you don't need them unless you're working on the code.

>Is there a driver for Ext 2/3/4 (especially for Ext4) on git platforms that works with File Explorer like this driver?

Like @Hanatarou says, Matt Wu's driver, which has been resurrected by Bo Branten. I can't speak to the quality, it's been years since I've tried it.

**Comment by universish** [comment]
> There's actually special code to work around Veracrypt's quirks,

What is this code?
Or do you mean that this code exists in your software?
I don't know if I made a mistake in translation or misunderstood.
