### ISSUE TITLE
Mapping not working

### ISSUE THREAD

**Issue by Stef-00012** [maharmstone/btrfs#711]
I got my current user `Stef` SID with the command in the mapping section and in `Mapping` and `GroupMapping` i set the DWORD as `1000` base hexadecimal (my linux user), then i rebooted windows and tried to create a file in `/home/stef/test-from-windows.txt`, it did create the file but when i logged into windows it shown the file as with no owner

<details>
<summary>How it appears on linux</summary>

![image](https://github.com/user-attachments/assets/935bf4bc-a4ea-41ee-bd82-88b86d946600)
</details>

<details>
<summary>My linux info</summary>

![image](https://github.com/user-attachments/assets/46901ad0-d3b2-4421-a0fb-e8f0a6664805)
</details>

<details>
<summary>SID</summary>

![SID](https://github.com/user-attachments/assets/22479cd8-7ebe-42b6-acd2-bfbf13932672)
</details>

<details>
<summary>GroupMappings</summary>

![groupMapping](https://github.com/user-attachments/assets/8b98b890-78d2-40ee-8a15-ce20e2ef7218)
</details>

<details>
<summary>Mappings</summary>

![mapping](https://github.com/user-attachments/assets/4dd364e2-6497-4516-a0a0-4c9826e879b0)
</details>

i installed the driver though choco on powershell ran as admin

**Comment by Stef-00012** [comment]
GroupMapping:
![groupMapping](https://github.com/user-attachments/assets/c31fb9ee-b001-4ff9-a938-27120d4c1aff)

Mapping
![mapping](https://github.com/user-attachments/assets/29607bc4-f0bb-4407-a0bf-d10c9c62cf14)

**Comment by Stef-00012** [comment]
SID:
![SID](https://github.com/user-attachments/assets/22479cd8-7ebe-42b6-acd2-bfbf13932672)

GroupMappings:
![groupMapping](https://github.com/user-attachments/assets/8b98b890-78d2-40ee-8a15-ce20e2ef7218)

Mappings:
![mapping](https://github.com/user-attachments/assets/4dd364e2-6497-4516-a0a0-4c9826e879b0)

**Comment by maharmstone** [comment]
I don't know if this is the entirety of your issue or just part of it, but UIDs on Linux are expressed in decimal. It should be 1000 decimal, not 1000 hexadecimal.

**Comment by Stef-00012** [comment]
> I don't know if this is the entirety of your issue or just part of it, but UIDs on Linux are expressed in decimal. It should be 1000 decimal, not 1000 hexadecimal.

i switched the DWORD to decimal `1000` and now it works, maybe in the [`README.md` Mappings](https://github.com/maharmstone/btrfs#mappings) section you should specify that the value has to be decimal (since windows seems to use hex as default, atleast on windows 11 through `regedit`)
