### ISSUE TITLE
Feature Request: zstd compression support

### ISSUE THREAD

**Issue by intelfx** [maharmstone/btrfs#72]
Hi,

it would be nice to support zstd compression (the `COMPRESS_ZSTD` incompat flag) that was introduced in upstream btrfs in Linux 4.14.

**Comment by maharmstone** [comment]
Thanks. Yes, seen as this is now out, this is now on the planned features list.

**Comment by Zero3K** [comment]
I think this issue can be closed since the feature has been implemented.
