### ISSUE TITLE
Without Tools like ext2fsd for mount & umount!

### ISSUE THREAD

**Issue by xfront** [maharmstone/btrfs#76]
It's hard to use!

**Comment by maharmstone** [comment]
No it's not. It's a Windows driver, mounting and unmounting is taken care of by the OS.

**Comment by theChaosCoder** [comment]
But there must be an issue somewhere. Because deleting a winbtrfs Partiton (via Disk Management gui of Win) results in an instant BSOD.

**Comment by xfront** [comment]
Yes,just as a driver,winbtrfs is good enough.But the window disk manager can't  identify the btrfs partitions,and assign drive number(mount & umount);So,this will bother the users who want manual
 control this!

**Comment by jdunn0** [comment]
@xfront: There is manual control using the mountvol.exe command line tool.
I listed how to use it to assign drive letters / Mount Points in [a comment on issue 82](https://github.com/maharmstone/btrfs/issues/82#issuecomment-380343688).
I'm sure a GUI Tool that uses the mountvol.exe tool could be created if someone wanted to do so.
