### ISSUE TITLE
Blue screen with SYSTEM_SERVICE_EXCEPTION [COMODO Auto-Containment Mode]

### ISSUE THREAD

**Issue by BakasuraRCE** [maharmstone/btrfs#78]
I am getting a blue screen when trying to execute any executable file located in the btrfs partition, only when the "COMODO" Antivirus "Auto-Containment" mode is enabled.

As far as I can see, the only driver that seems to be responsible for this is "cmdguard.sys".

When disabling this mode, the executable starts without problems. When enabling this mode, it returns to give a blue screen.

Now try to add the whole file system and the file itself in the exclusions, but apparently the driver anyway interferes with the loading of the executable and then decides whether or not it is excluded (a bit logical).

I leave you a DUMP of the error.

![image](https://user-images.githubusercontent.com/26231582/34732547-97d5ecc0-f533-11e7-8a53-25e5c50ceeca.png)

[btfs 010818-51781-01.zip](https://github.com/maharmstone/btrfs/files/1615332/btfs.010818-51781-01.zip)

**Comment by maharmstone** [comment]
Hmm. It looks like Comodo is at fault here - it is trying to query the file attributes of your directory "home", but passing it a null buffer which causes it to segfault. It's only the fact it's a kernel driver that it can get away with it, otherwise NT would stop it before it even got to us.

I can't reproduce it myself, so I don't know, but the mystery is why it presumably doesn't crash on NTFS...

**Comment by Artofeel** [comment]
same here
but I just use Sandbox mode on executable on btrfs disk and BSOD happen

**Comment by ale5000-git** [comment]
Just a supposition: can it be that doing this trigger an undocumented behaviour on certain version of Windows?

@Artofeel: You should also report the exact version of Windows, the exact version of WinBtrfs andthe exact version of COMODO Antivirus for the report to be more complete.

**Comment by Artofeel** [comment]
Win7 x64
btrfs 1.4
COMODO 11.0.0.6728
and is not antivirus, it's firewall

**Comment by maharmstone** [comment]
Closing old issues
