### ISSUE TITLE
Installing driver on windows 7 makes it go SYSTEM_THREAD_EXCEPTION_NOT_HANDLED

### ISSUE THREAD

**Issue by Magissia** [maharmstone/btrfs#80]
Installing the driver from release 1.0.1 is sufficient to make the computer BSOD, using Win7 x64.

Install made by right click on btrfs.inf and install.

Here's what the memory dump says :

Bug check string : 
Bug check code : 0x1000007e	
Parameters : ffffffff`c0000005	, fffff800`02099054 , fffff880`02d55328 , fffff880`02d54b90	
Caused by driver : btrfs.sys	
Caused by address : btrfs.sys+43808	
File description : WinBtrfs	
Product name : WinBtrfs		
File version : 1.0.1	
Processor : x64	
Crash address : ntoskrnl.exe+3e054
Processor count : 4	
Major version : 15	
Minor version : 7601

Can send full memory dump by private means if of any use.

**Comment by maharmstone** [comment]
Please, if you could. You don't need to send the full thing, just the minidump.

btrfs.sys+43808 is in drv_pnp, line 501 of pnp.c: https://github.com/maharmstone/btrfs/blob/master/src/pnp.c#L501

**Comment by IsaakGroepT** [comment]
Same problem here but I wouldn't know how to convert the .dmp to a minidump file

**Comment by timofonic** [comment]
@maharmstone Would you like to provide more clear instructions about the minidump thing? It would be nice if these are in the README.md file. Thanks in advance.

**Comment by maharmstone** [comment]
Closing old issues
