### ISSUE TITLE
Provide *any* way to check+repair corrupted volume?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [maharmstone/btrfs#81]
Is there currently any way of fixing issue #68 without the aid of a Linux-based rescue CD?

I had set this up on my brother's computer (I was partitioning out his Documents folder because he's always playing video games and downloading programs, so the computer needs to be factory-reset every few years, figured I might as well make it future-proof and cross-compatible), but if(when) Windows chokes and corrupts the drive, it goes read-only, essentially bricking his Steam library until I can come over, boot up a Linux rescue CD, and fix it.

Is there currently any workaround, or is production-readiness still on the agenda?

Even if I could just drop a shortcut to `rundll32.exe shellbtrfs.dll,Check \Device\Harddisk0\Partition5` on his desktop to run as admin every time it craps out, that would be awesome. Just *something* other than having to manually be a computer technician..is it possible currently?

**Comment by maharmstone** [comment]
If you want to port btrfs-check to Windows, or find a way to get it run under LXSS, be my guest. There's no reason why it wouldn't work, it's just that nobody's done it yet.

**Comment by JamesTheAwesomeDude** [comment]
So, to confirm: there is currently **no** way* to re-enable read-write access once Windows gets bored of using a BTRFS partition?

_*excepting manual intervention by a Linux technician_

**Comment by JamesTheAwesomeDude** [comment]
Sorry for the confusion; I thought that my original post was clear, but in hindsight I should have offloaded the context to a comment to avoid distracting from the original question asked in the first and last sentences of the OP.

**Comment by maharmstone** [comment]
You are correct - the only way to fix a Btrfs partition is with btrs-check, which doesn't (yet) have a Windows version. If the driver is corrupting filesystems, I need to know about it so I can fix it.

**Comment by JamesTheAwesomeDude** [comment]
It looks like the filesystem repair I did the other day didn't take (it restored read access, but not write access).

I'm heading over again today to fix it.

**What logs/information do you need while I'm in there?**

**Comment by maharmstone** [comment]
The output of btrfs check, please.

**Comment by JamesTheAwesomeDude** [comment]
$ btrfs check /dev/sda5 2>&1 > /tmp/check-1.log
	checking extents
	checking free space cache
	Wanted bytes 49152, found 17304 for off 20971520
	Wanted bytes 8388609, found 1736704 for off 20971520
	cache appears valid but isnt 2091520
	$ cat /tmp/check-1.log
	Checking filesystem on /dev/sda5
	UUID: 3dad8bee-bd3f-473c-9f5c-b70693cbcec4
	found 332644049252 bytes used err is -22
	total csum bytes: 327445244
	total tree bytes: 684441600
	total fs tree bytes: 273006592
	total extent tree bytes: 37437440
	btree space waste bytes: 80648260
	file data blocks allocated: 4719901712384
	 referenced 335059857408

**Comment by JamesTheAwesomeDude** [comment]
I suspect the error itself may be #69, since I just now found out that *that's* the error Windows GUI was printing.

(Leaving this issue open for now, since the inability to recover from errors is a separate, standalone blocker)

**Comment by JamesTheAwesomeDude** [comment]
![capture](https://user-images.githubusercontent.com/2776014/35782049-409ce3c0-09ea-11e8-8f2c-f08b1ad08e3f.PNG)

**Comment by JamesTheAwesomeDude** [comment]
which seems to have allowed the drive to function read/write across two reboots so far.

I disabled Windows' Write Caching on the drive, hopefully we'll see if this fixes it

(Do these logs look like they belong in #68, #69, or a new Issue of their own?)

**Comment by JamesTheAwesomeDude** [comment]
..and it's back to 
![Steam: DISK WRITE ERROR](https://user-images.githubusercontent.com/2776014/35782358-922b9d22-09ee-11e8-8d72-c3a5c8c92ac1.PNG)

**Comment by G-Bigo** [comment]
Yep, unfortunately still holds true for WinBTRFS v1.1.

Had ~15TB on an external SATA drive. Started a consolidation, which for whatever reason went awry after 15% of the job done. Computer froze, had to pull power and restart. Afterwards the BTRFS volume was 'read only' for Windows and couldn't be 'scrubbed', too.

As said by James nearly a year ago it would be great if the Linux btrfs check could somehow be done from within Windows. Perhaps integrated into the Windows 'Scrub'. After all it's not the easiest task to identify the correct drive from a list of 13 /mnt/sdX entries within a Linux mini environment ...

B.t.w.: As 'Scrub' in the Linux world usually means shredding all data on that particular drive, the denominator is somehow misleading. I think the windows equivalent would be something like chkdsk. Thus maybe 'CheckDisk' would be a less misleading title for that Windows process.

**Comment by maharmstone** [comment]
Closing old issues
