### ISSUE TITLE
After saving document with Notepad++, it says "This file has been modified by another program"

### ISSUE THREAD

**Issue by derkan** [maharmstone/btrfs#83]
I'm using` Windows 10(v1709)` and `btrfs v1.0.1`. 
*Problem:* 
1- I save document at `Notepad++` to a file on `btrfs`.
2- A few seconds later Notepad warns with "_This file has been modified by another program_" and asks me to reload document.
No other program is using this document. It also happens for newly created files.

I've tried VNote and same problem happened(which do not have an option to *silently reload* on change and goes to head of document after loading annoyingly)
Regards

**Comment by maharmstone** [comment]
Thanks. It looks like the lazy writer is triggering a notification for change of file size, even when it stays the same. I'll get it fixed.

**Comment by maharmstone** [comment]
This is fixed by 66dc7f26a41538ff6d43393372bddb3dbf616368.
