### ISSUE TITLE
Partitionless volume isn't mounted

### ISSUE THREAD

**Issue by Milek7** [maharmstone/btrfs#84]
Partitionless volume `ab4a9126-c451-44c9-9391-1bcf7c04df22` (on 3TB HDD) have it's registry entry but isn't mounted. (other volume stored on GPT partition and partitionless disk mounts properly (it frequently corrupts filesystem when in read-write, but that is other issue))
[btrfs.log.zip](https://github.com/maharmstone/btrfs/files/1754402/btrfs.log.zip)

**Comment by maharmstone** [comment]
This should be fixed by https://github.com/maharmstone/btrfs/commit/514b224db8e6a4e801a7f5d8f0c75ba2e28867c9
