### ISSUE TITLE
btrfs.sys

### ISSUE THREAD

**Issue by jkjkrules** [maharmstone/btrfs#85]
I keep getting an error on install

"the file file btrfs.sys on btrfs device installation disk is needed"

I don't see one in the download

**Comment by luksi1** [comment]
I'm hitting this too. I tried using pnputil, as suggested in #70, and I'm getting the same error. Is this a documentation issue? Or a bug?

**Comment by a-n-u-18** [comment]
> 
> 
> I'm hitting this too. I tried using pnputil, as suggested in #70, and I'm getting the same error. Is this a documentation issue? Or a bug?

Same issue!!

**Comment by Zero3K** [comment]
Its in the x86/x64 sub-directories.

**Comment by maharmstone** [comment]
Closing old issues
