### ISSUE TITLE
Windos on Ubuntu

### ISSUE THREAD

**Issue by heixiaobai** [maharmstone/btrfs#86]
Hello, excuse me, why I can not detect the file in / mnt / e / on my Windows on ubuntu, but I seem to have seen WinBtrfs support this

**Comment by NatoBoram** [comment]
Can you provide some screenshots?

![explorer_2018-07-15_18-34-34](https://user-images.githubusercontent.com/10495562/42739079-c7a451cc-885d-11e8-9321-4bf3a93fd7c2.png)

**Comment by heixiaobai** [comment]
> Can you provide some screenshots?
> 
> ![explorer_2018-07-15_18-34-34](https://user-images.githubusercontent.com/10495562/42739079-c7a451cc-885d-11e8-9321-4bf3a93fd7c2.png)

Oh sorry...
I didn't see your response in time.
After applying the latest update, everything is normal, thanks
