### ISSUE TITLE
write.c: Clang-Cl reports 1 "-Wsometimes-uninitialized"

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#91]
Build [ReactOS](https://www.reactos.org/) with Clang-Cl:
{{
c:\reactos-cov\drivers\filesystems\btrfs\write.c(542,13) :  warning: variable 'factor' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
    else if (type == BLOCK_FLAG_RAID6)
             ^~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\write.c(545,22) :  note: uninitialized use occurs here
    if (stripe_size * factor > max_chunk_size)
                      ^~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\write.c(542,9) :  note: remove the 'if' if its condition is always true
    else if (type == BLOCK_FLAG_RAID6)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\write.c(367,78) :  note: initialize the variable 'factor' to silence this warning
    UINT64 max_stripe_size, max_chunk_size, stripe_size, stripe_length, factor;
                                                                              ^
                                                                               = 0
1 warning generated.
}}

**Comment by maharmstone** [comment]
Please do not file code analysis reports unless you are certain there is a bug. There is no bug here - factor is initialized by the if-block.

**Comment by SergeGautherie** [comment]
> factor is initialized by the if-block.

I assumed it could be.
Then, `else if (type == BLOCK_FLAG_RAID6)` "should" be `else // if (type == BLOCK_FLAG_RAID6)`, isn't it?
Or, this warning should be disabled...

**Comment by ale5000-git** [comment]
I think would be more future proof:
```
else if (type == BLOCK_FLAG_RAID6)
  ...
else
  ERR("Unhandled case\n");
  Status = STATUS_INSUFFICIENT_RESOURCES;
  goto end;
```

**Comment by SergeGautherie** [comment]
> more future proof

Sure, I simply gave a minimal example.
