### ISSUE TITLE
btrfs.c. Clang-Cl reports 22 "-Wcast-calling-convention"

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#92]
Build [ReactOS](https://www.reactos.org/) with Clang-Cl:
{{
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5500,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_CREATE]                   = (PDRIVER_DISPATCH)drv_create;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1363,9) :  note: consider defining 'drv_create' with the 'stdcall' calling convention
NTSTATUS drv_create(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5501,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_CLOSE]                    = (PDRIVER_DISPATCH)drv_close;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(467,16) :  note: consider defining 'drv_close' with the 'stdcall' calling convention
static NTSTATUS drv_close(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5502,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_READ]                     = (PDRIVER_DISPATCH)drv_read;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1415,9) :  note: consider defining 'drv_read' with the 'stdcall' calling convention
NTSTATUS drv_read(PDEVICE_OBJECT DeviceObject, PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5503,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_WRITE]                    = (PDRIVER_DISPATCH)drv_write;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1285,9) :  note: consider defining 'drv_write' with the 'stdcall' calling convention
NTSTATUS drv_write(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5504,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_QUERY_INFORMATION]        = (PDRIVER_DISPATCH)drv_query_information;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1337,9) :  note: consider defining 'drv_query_information' with the 'stdcall' calling convention
NTSTATUS drv_query_information(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5505,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SET_INFORMATION]          = (PDRIVER_DISPATCH)drv_set_information;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1333,9) :  note: consider defining 'drv_set_information' with the 'stdcall' calling convention
NTSTATUS drv_set_information(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5506,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_QUERY_EA]                 = (PDRIVER_DISPATCH)drv_query_ea;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1341,9) :  note: consider defining 'drv_query_ea' with the 'stdcall' calling convention
NTSTATUS drv_query_ea(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5507,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SET_EA]                   = (PDRIVER_DISPATCH)drv_set_ea;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1345,9) :  note: consider defining 'drv_set_ea' with the 'stdcall' calling convention
NTSTATUS drv_set_ea(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5508,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_FLUSH_BUFFERS]            = (PDRIVER_DISPATCH)drv_flush_buffers;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(516,16) :  note: consider defining 'drv_flush_buffers' with the 'stdcall' calling convention
static NTSTATUS drv_flush_buffers(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5509,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_QUERY_VOLUME_INFORMATION] = (PDRIVER_DISPATCH)drv_query_volume_information;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(711,16) :  note: consider defining 'drv_query_volume_information' with the 'stdcall' calling convention
static NTSTATUS drv_query_volume_information(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5510,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SET_VOLUME_INFORMATION]   = (PDRIVER_DISPATCH)drv_set_volume_information;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(1150,16) :  note: consider defining 'drv_set_volume_information' with the 'stdcall' calling convention
static NTSTATUS drv_set_volume_information(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5511,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_DIRECTORY_CONTROL]        = (PDRIVER_DISPATCH)drv_directory_control;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1307,9) :  note: consider defining 'drv_directory_control' with the 'stdcall' calling convention
NTSTATUS drv_directory_control(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5512,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_FILE_SYSTEM_CONTROL]      = (PDRIVER_DISPATCH)drv_file_system_control;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(4757,16) :  note: consider defining 'drv_file_system_control' with the 'stdcall' calling convention
static NTSTATUS drv_file_system_control(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5513,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL]           = (PDRIVER_DISPATCH)drv_device_control;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1495,9) :  note: consider defining 'drv_device_control' with the 'stdcall' calling convention
NTSTATUS drv_device_control(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5514,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SHUTDOWN]                 = (PDRIVER_DISPATCH)drv_shutdown;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(4877,16) :  note: consider defining 'drv_shutdown' with the 'stdcall' calling convention
static NTSTATUS drv_shutdown(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5515,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_LOCK_CONTROL]             = (PDRIVER_DISPATCH)drv_lock_control;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(4838,16) :  note: consider defining 'drv_lock_control' with the 'stdcall' calling convention
static NTSTATUS drv_lock_control(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5516,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_CLEANUP]                  = (PDRIVER_DISPATCH)drv_cleanup;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(2132,16) :  note: consider defining 'drv_cleanup' with the 'stdcall' calling convention
static NTSTATUS drv_cleanup(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5517,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_QUERY_SECURITY]           = (PDRIVER_DISPATCH)drv_query_security;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1315,9) :  note: consider defining 'drv_query_security' with the 'stdcall' calling convention
NTSTATUS drv_query_security(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5518,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SET_SECURITY]             = (PDRIVER_DISPATCH)drv_set_security;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1319,9) :  note: consider defining 'drv_set_security' with the 'stdcall' calling convention
NTSTATUS drv_set_security(IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp);
         ^
         WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5519,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_POWER]                    = (PDRIVER_DISPATCH)drv_power;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(4930,16) :  note: consider defining 'drv_power' with the 'stdcall' calling convention
static NTSTATUS drv_power(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5520,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_SYSTEM_CONTROL]           = (PDRIVER_DISPATCH)drv_system_control;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(4971,16) :  note: consider defining 'drv_system_control' with the 'stdcall' calling convention
static NTSTATUS drv_system_control(_In_ PDEVICE_OBJECT DeviceObject, _In_ PIRP Irp) {
                ^
                WINAPI 
c:\reactos-cov\drivers\filesystems\btrfs\btrfs.c(5521,67) :  warning: cast between incompatible calling conventions 'cdecl' and 'stdcall'; calls through this pointer may abort at runtime [-Wcast-calling-convention]
    DriverObject->MajorFunction[IRP_MJ_PNP]                      = (PDRIVER_DISPATCH)drv_pnp;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
c:\reactos-cov\drivers\filesystems\btrfs/btrfs_drv.h(1430,9) :  note: consider defining 'drv_pnp' with the 'stdcall' calling convention
NTSTATUS drv_pnp(PDEVICE_OBJECT DeviceObject, PIRP Irp);
         ^
         WINAPI 
22 warnings generated.
}}

**Comment by maharmstone** [comment]
This is invalid - the calling convention is set in the compiler flags. Do you really think it would run if it wasn't?
