### ISSUE TITLE
It seems unable to mount the RAID0 disk array created using mkfs.btrfs -d raid0 /dev/sdb /dev/sdc

### ISSUE THREAD

**Issue by daiaji** [maharmstone/btrfs#95]
But this RAID0 disk array is available under opensuse.

**Comment by Atemu** [comment]
Could you run `btrfs inspect-internal dump-super /dev/sdX` (sdX is one of the devices of the RAID0) and post the `incompat_flags` section?

**Comment by maharmstone** [comment]
Closing old issues
