### ISSUE TITLE
Balancing to create RAID1 throws CRC error

### ISSUE THREAD

**Issue by Nachtschatten** [maharmstone/btrfs#98]
Greetings!

I'm happy to see you've taken the task to bring BTRFS to Windows. Awesome! I also really like that the driver is signed so I don't need to put my system in test mode.

So I'm trying to configure two SSDs drives as a RAID1.
As I don't have much experience with BTRFS I'm probably doing something wrong, because instead of resulting in a working RAID1 the balancing fails with a CRC error.
Here's the steps I took (and with which I can reproduce the error):

1. In Windows' drive manager, create simple volumes on both SSDs and format with NTFS.
2. In a PowerShell with elevated privileges, use mkbtrfs to format the drives. E.g. "mkbtrfs I: Data1" and "mkbtrfs J: Data2".
At this point, I have two separate drives that I can see in Windows Explorer. Right click -> Properties shows a "Btrfs" tab. The drive letters have been reassigned automatically.

![devices properties after format](https://user-images.githubusercontent.com/717899/42056167-b94b4cf8-7b19-11e8-8944-955d740c43eb.png)

3. In the properties window of my first drive (Data1 in this case), switch to the Btrfs tab.
4. Click "Devices...", "Add device...", confirm elevation prompt.
5. Because the devices overview listed "ID 1, Disk 1, partition 2", I select Disk 2, partition 2, click "OK" and confirm "Are you sure that you want to add this device? It already appears to contain a filesystem (Btrfs)." with "Yes".

![adding second device](https://user-images.githubusercontent.com/717899/42056190-d13a8e1e-7b19-11e8-933f-064427c79af7.png)

At this point, the partition has been added and is listed as "ID 2, Disk 2, partition 2".

6. Closing the "Devices" window with "OK", I click "Balance..."
7. I check all three boxes for Data, Metadata and System, and I set the same options for all. As I understand, all options except "Convert" and "Soft" concern filtering, which I don't want to do. So I just check "Convert" and set it to "RAID1".
8. I click "Start balance" and confirm the elevation prompt.

![balance options](https://user-images.githubusercontent.com/717899/42056213-df9835ba-7b19-11e8-9e99-b3a6e83c6926.png)

At this point, the balance fails with a CRC error. To be precise, error c000003f.

![error after balance](https://user-images.githubusercontent.com/717899/42056229-f3886798-7b19-11e8-9158-0289a1359b3e.png)

The BTRFS volume is then write-protected. It can't be attempted to be balanced again ("The medium is write-protected" error popup). In Windows' drive manager, the devices still show up as RAW and error free.

![drives after balance](https://user-images.githubusercontent.com/717899/42056237-fa07b5a6-7b19-11e8-93c9-1eb5e088e438.png)

After a reboot, they don't - they show up with their size, but without any other information.

![drives after balance after reboot](https://user-images.githubusercontent.com/717899/42056260-0de239b6-7b1a-11e8-92ea-392b6abce4f4.png)

I have a couple of questions about this:
* Is this the right way to create a RAID1? If not, what is the right way?
* I find the balance dialog non-descriptive, so I suggest to replace it with a wizard (or something else with more clarity, of course). Would that be possible?
* What has gone wrong, and can the code be hardened so that it doesn't (apparently) eat my drives? In other words: Something has gone wrong way too easily.
* Do you need more information?

Kind regards,
Nachtschatten

**Comment by maharmstone** [comment]
Hi Nachtschatten,

Yes, you're doing everything right there. I suspect what's happening is that Windows is writing to the old volume of the second disk, when you've already added it to the filesystem of the first. You don't need to format the second disk as Btrfs, as this is taken care off when you add it as a device.

Can you try zeroing the partitions and trying again?

Thanks

Mark

**Comment by Nachtschatten** [comment]
Hi Mark,

thanks for your reply. I feel newbish, because I don't understand what you're asking for. Can you give me more detailed steps? I tried various things (using MiniTool Partition Wizard to wipe the partitions, rebooting before balancing, etc) but I keep getting the error.

Kind regards,
Nachtschatten

**Comment by Atemu** [comment]
He wants you to remove the partition from your BTRFS, clear **all** data present on the partition by overwriting it with zeroes and then try to add the partition again without formatting it as BTRFS before.  

I don't know how to do it on Windows or that proprietary partitioning tool but on Linux you'd do this: 

Remove the device:

    btrfs device remove 2 /path/you/mounted/the/btrfs/to/

Overwrite the partition with zeroes:

    dd if=/dev/zero of=/dev/disk/by-id/$yourdisk-part$yourpartition status=progress

`$yourdisk` is the disk's ID (double press TAB after you enter `/dev/disk/by-id/` for a list of drives) and `$yourpartition` is the partition number (most likely 2 in your case).

**Comment by Nachtschatten** [comment]
@Atemu thanks, but is there a way without Linux? I don't have that. I'm not trying to use BTRFS to share data between two OSes. To me it's a replacement for ReFS and NTFS on my data drives.

**Comment by Atemu** [comment]
There must be but I don't know of any and it's probably not nearly as simple as getting a live Linux USB and executing a few commands (well, for me at least :p), so this is the only way I could help with.

Under normal circumstances this shouldn't be necessary at all,  it's just for debugging purposes.

**Comment by Nachtschatten** [comment]
Thank you a lot for your help. To be honest, I am too lazy to put Linux on a USB stick and execute these steps. And, well, looking at the other open issues I also stopped trusting BTRFS. I worry it's going to eat my personal files at some point.

So in the meantime, I turned these disks into a ReFS array. Should this issue stay open? While it's solved _for me_, the actual cause may still apply to other users.

**Comment by happyme531** [comment]
Ran into the same issue today after balancing a simple btrfs partition with lzo compession without checking any checkbox in the balance option.

**Comment by happyme531** [comment]
It shows CRC error, become write-only, after reboot show up with their size, but without any other information. Exact error happened on a simple btrfs partition on a single drive. Plz let other know the balance operation is dangerous(in this driver)

**Comment by yretenai** [comment]
I ran into this problem a few weeks ago with a single btrfs partition. After rebooting the drive showed up with only partition information but no files present on the drive. Formatting the drive again to NTFS resulted in an immediate blue screen. The drive had to be formatted several times for it to be usable again.

**Comment by happyme531** [comment]
After breaking the partition, I have tried a lot of ways to recover, but nothing works:

- btrfs rescue super-recover: All supers are valid.
- btrfs rescue chunk-recover: ERROR: duplicate entry in cache start 73618423808 size 1073741824
- btrfs check: 
   ```
   checksum verify failed on 4929302528 wanted 0x000000000 found 0xb6bde3e4
   checksum verify failed on 4929302528 wanted 0x000000000 found 0xb6bde3e4
   bad tree block 4929302528 , bytenr mismatch, want=4929302528, have=0
   ERROR: cannot read chunk root
   ERROR: cannot open file system
   ```
- btrfs-find-root:
   
![图片](https://user-images.githubusercontent.com/20812356/143815210-9ced9705-7304-4805-83bb-43c14a7d7d8a.png)
- btrfs rescue zero-log:
   
![图片](https://user-images.githubusercontent.com/20812356/143815278-0a0440cf-263e-469b-8f11-05f6a4757126.png)

- btrfs inspect-internal dump-super:
 
![图片](https://user-images.githubusercontent.com/20812356/143815425-e8830341-5124-4d00-98d9-cc868b232b38.png)
![图片](https://user-images.githubusercontent.com/20812356/143815495-94e2deb5-1b84-4eeb-97d8-9fa217b0c298.png)
![图片](https://user-images.githubusercontent.com/20812356/143815540-fdfad629-a525-4dbd-8d36-a0eeb5e452d7.png)
