### ISSUE TITLE
autorun.inf ignored on btrfs formatted disks

### ISSUE THREAD

**Issue by niemandag** [maharmstone/btrfs#99]
I use the autorun.inf files on my disks to customize the icons and get longer volume names.
But they don't seem to get recognized, and windows uses the default icon and the partition name instead of the longer one.

All of my Drives have gotten the same treatment, Pikachu is NTFS, HDD is BTRFS, Schiggy is exFAT and Digda is Fat32.
![hdds](https://user-images.githubusercontent.com/15233497/42109616-8a6ce8e0-7bde-11e8-923c-b1d08fabe92c.PNG)

**Comment by maharmstone** [comment]
Oh, you're right - I'll have a look. Thanks for reporting this.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/825bd546247b5b5d16598c1217c73a1f3388e235.
